### ISSUE TITLE
Please provide an option to delete all icons in the database

### ISSUE THREAD

**Issue by stefanobartoletti** [keepassxreboot/keepassxc#10026]
As the title says, please provide an option to delete all icons in the database.

Currently, only two options are present, `delete selected icons` and `delete unused icons`, but both these options are not really helping to really cleanup.

Having to select all icons by hand and delete them one by one is really tedious and I think that an option to wipe them all at once would be handy.

Thanks :)

**Comment by JohnLGalt** [comment]
If you select all the icons then `Delete selected icon(s)` works perfectly fine.

Trick to select all icons at once is to click a single icon and use CTRL + A (Windows, and the corresponding keystroke combination in other OSs) to select all.

I do not see the point of a button, but I do see a pitfall associated with a button - someone, somewhere, is going to accidentally click the button, lose their icons, and then go ballistic on why this option even exists in the first place.

Since the above method works, and is less accident-prone, I think it is best to stick with it.

**Comment by stefanobartoletti** [comment]
Thanks, I didn't notice that it was possible to select all icons at once with the key combination.

I'm closing this as it is basically solved.
