### ISSUE TITLE
[GNOME][Wayland][Flatpak] The clipboard is not cleared if the application window is not focused

### ISSUE THREAD

**Issue by popov895** [keepassxreboot/keepassxc#10048]
## Overview

On GNOME under Wayland, the Flatpak version of KeePassXC doesn't clear the clipboard after timeout if the application window is not focused. Actually the clipboard is cleared, but somehow the password appears again in the clipboard as plain text (`x-kde-passwordManagerHint` mimetype not specified).

## Steps to Reproduce

1. Login to Wayland session on GNOME (tested on GNOME 42 and GNOME 45)
2. Open the Flatpak version of the KeePassXC (tested on version 2.7.6)
3. Copy password (`Ctrl+C` on selected entry or `Copy password` in popup menu)
4. Switch to another application so that the KeePassXC application window loses focus
5. Wait for the clipboard clear timeout to complete
6. Check the contents of the clipboard (paste it into a text editor)

## Expected Behavior

The clipboard is empty.

## Actual Behavior

The clipboard still contains the copied data.

## Context

There's no such issue on GNOME/X11, KDE/X11 and KDE/Wayland, so it looks like a bug in GNOME. I decided to file a bug report here because I think it will be easier for you to figure out what exactly the problem is.

KeePassXC: 2.7.6 Flatpak
Operating System: Linux
Desktop Env: GNOME
Windowing System: Wayland

**Comment by droidmonkey** [comment]
#4498 file a bug with gnome, please. We simply use the qt api to clear the clipboard. It then handles the hard part of doing that on every type of system configuration. Wayland gnome has (I think) the opinion that only the focused app should be allowed to modify the clipboard.

**Comment by pythonneur** [comment]
Has there been any movement on this? I'm still experiencing the bug using Debian 12/Wayland/GNOME. In #[4498](https://github.com/keepassxreboot/keepassxc/issues/4498) I see jakedane's post with source code with a workaround, but I'm no developer, just a simple user. In any case, has a bug report been filed with GNOME? After searching for this issue, this is where I ended up but I don't know where the trail goes from here.

**Comment by lostfictions** [comment]
I definitely feel like I've only started noticing this as of KeePassXC 2.7.6 -- is there any possibility there's been a regression? I've been on Gnome on Wayland this whole time. (EDIT: seems like [`Clipboard.cpp`](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Clipboard.cpp) hasn't changed since the [last fix related to these issues](https://github.com/keepassxreboot/keepassxc/pull/9148) three years ago, so probably not.)

Maybe it's also possible that there's a new difference in behaviour due to a recent change in the `org.kde.Platform` runtime?

**Comment by droidmonkey** [comment]
This only occurs on Gnome + Wayland, regardless of install method. It may be a qt + gnome + wayland issue, but certainly not a KeePassXC specific issue. We do have a potential work around which is calling wl-copy command line tool as a detached process.

**Comment by du291** [comment]
This bug happens when KeePassXC is *forced* to run on gnome/wayland session instead of X11.

There must be some known Qt5 incompatibilities, because Qt has by default an aversion to run on gnome/wayland.

When KeePassXC is run from command line, it will say:

> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

You can force use of wayland using `QT_QPA_PLATFORM=wayland` and then it will run on wayland, but the clipboard clearing bug will occur.

So while this is probably a bug between Qt, gnome and wayland, I don't think it will get fixed in Qt5. I have noticed that Qt6 apps are more willing to run on wayland (e.g. kdenlive). So maybe when KeePassXC is upgraded to support the newer Qt6 library ( see https://github.com/keepassxreboot/keepassxc/issues/7774 ), this issue would be fixed as well.

**Comment by droidmonkey** [comment]
Install `wl-clipboard`

**Comment by du291** [comment]
OK, I was wondering how installing a command line application `wl-clipboard` would fix an issue between Qt and Wayland. So it appears that KeePassXC code already tries to detect Wayland and runs the command-line app `wl-copy` to clear the clipboard:

https://github.com/keepassxreboot/keepassxc/blob/5736c6379c8b5178b2945982ee42a763335ac0ea/src/gui/Clipboard.cpp#L110

Unfortunately, whether the app is installed or not, or whether its execution succeeded or not, is not checked by KeePassXC. Maybe it would bring more usability (and visibility into this issue) if there was such a check? Then KeePassXC could display a warning such as “unable to run wl-copy, the password in your clipboard was likely not cleared”. I feel that people only discover this issue by accident, thinking their clipboard is clear when it's really not.

**Comment by droidmonkey** [comment]
Since you don't have keepassxc focused when this issue occurs, you might not see a message we show. I'm hoping this just gets fixed with qt6, but haven't tested it.

**Comment by du291** [comment]
> Since you don't have keepassxc focused when this issue occurs, you might not see a message we show. I'm hoping this just gets fixed with qt6, but haven't tested it.

This dialog seems to grab attention by forcing focus on the keepass window. Maybe same technique can be used to alert on the fact that wl-clipboard is not present or failed?

https://github.com/keepassxreboot/keepassxc/blob/092879bceeb78dfbbf0931be99a95cff2fe7fd66/src/gui/DatabaseWidget.cpp#L2060
