### ISSUE TITLE
[Feature] VSCode Integration

### ISSUE THREAD

**Issue by Thundercraft5** [keepassxreboot/keepassxc#10082]
## Summary
Many developers will often store credentials, secrets, and other sensitive information on a `.env` in plaintext file for development. This allows them to quickly access these values when developing, but they are easily vulnerable to getting stolen at rest.

A KeePassXC extension for VSCode would eliminate this issue, in addition to to requiring consent from the user before releasing any secrets to the development environment.

## Examples
I work as a freelance developer, and I want to ensure that I have a very high standard of security for my clients. 

If for whatever reason my device became compromised, I could ensure that my wide range of access keys would remain safe in the `.kdbx` database in such a scenario.

## Context
- I started using KeePassXC about 3 months ago, and I quite quickly decided it was the best password manager around for Windows. I like how I can store my secrets like TOTP, SSH, online account passwords and other sensitive information quite securely and easily. The only issue I found is that it doesn't provide management of developer secrets.
- [1Password for VSCode](https://github.com/1Password/op-vscode) - I could have gone with this extension, but I don't want to use a cloud service for my secrets management.
- I use windows, so I cannot use a Secrets Service.
- Secret References (#10081) could be used in the proposed extension

**Comment by droidmonkey** [comment]
Unfortunately that is far outside the scope of our application. Anyone is free to develop said extension, probably leveraging the browser protocol. However we do not have the developer time nor ability to maintain said extension.

**Comment by dkebler** [comment]
For those searching and ending up here with the same security issue I can get autotype to work but you have to slow it down to 200ms and  use {ENTER} instead of {TAB} in the autotype sequence.   Also the window title changes depending on the workspace so no way to make it associate for any vscode window :(.   So it's not as nice as some integrated solution but better than copy paste.

Better seems to not use https but ssh for push/pull and then you can use an ssh-agent which integrates well with XC.  Guess I need to try to set that up myself as I already use ssh-agent for ssh logins.
