### ISSUE TITLE
Merging always marks the database as dirty

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxc#1010]
No matter if changes were made to the destination database, merging always marks it as dirty (modified).

## Expected Behavior
The database is marked as changed only if the merge operation resulted in a change.

## Current Behavior
The database is marked as changed for every merge operation.

## Steps to Reproduce (for bugs)

1. Duplicate a database
2. Merge the 2 duplicated databases
3. The destination database is marked as modified even though no changes were made.

**Comment by louib** [comment]
I feel like this should be pretty easy, now that `merger.merge()` returns true if the database was modified during the merge operation!

**Comment by AlexJoss** [comment]
Seems to be resolved on the latest build. Tested with the gui and cli, and the target database is not marked as modified. No failed tests in either testmerge or testmodified, but I was thinking that since the cli passes a message when the database is not modified after a merge operation, maybe the gui should as well.
