### ISSUE TITLE
Provide ability to autotype the password history.

### ISSUE THREAD

**Issue by pbulteel** [keepassxreboot/keepassxc#10184]
## Summary

#7297 Is requesting adding history to the password generator. 
That would be useful (particularly for password change scenarios) where you can use the password history. I avoid the issues discussed in that issue by saving the password after generating it (for existing entries) and then using it. However, it means that I have first to copy the existing password and paste it in the "current password" field, then generate a new password, accept it, and then autotype the new password. This works but is a bit convoluted. Being able to reference or get to the history of the entry would permit an autotype sequence that includes the previous password used.

## Examples
For password change where current password and new password entries are required
Autotype entry {PASSWORD -1}{TAB}{PASSWORD}{TAB}{PASSWORD}{ENTER}   
Autotype entry {OLDPASSWORD}{TAB}{PASSWORD}{TAB}{PASSWORD}{ENTER}
For password change where you enter your current password and then go to a different screen for a new password.
Autotype entry {OLDPASSWORD}{ENTER}{DELAY 5}{PASSWORD}{TAB}{PASSWORD}{ENTER}

## Context
Password changes mean that you're required to generate a new password after you've entered the current password.

**Comment by droidmonkey** [comment]
This isn't a very good solution because you would have to build an autotype sequence for every entry just to use it. I recommend adopting this sequence before we actually implement the password change tool:

- Open website to password change 
- Use global Auto-Type shortcut, choose entry, press Ctrl+2 to type current password
- Open entry for editing and change password, save changes
- Repeat global Auto-Type process to type in the new password 

#6323
