### ISSUE TITLE
Unable to open Database. No Root Group

### ISSUE THREAD

**Issue by VonBishere** [keepassxreboot/keepassxc#10314]
Hello i,ve bin using Keepassxc for a bit now , but this morning i plugged the usb stick into another pc and saved some new entry ,s in Keepassxc , only to greeted later on when i wanted to use it again with  " Unable to open Database. No Root Group "

this is the second time it happened , a while back aswell , i reckon it,s corrupted ?

i was hoping i could get some support here , i did made a backup , but it,s older , andt that one opens up just fine , but it,s older , i,m losing quite a bit 

i,m a novice user a step by step instruction of a possible sollution would be fantastic , are there possible sollutions to this ?

running the latest version of keepassxc on a linux distro

kind regards

**Comment by droidmonkey** [comment]
> plugged the usb stick

You corrupted your database by unplugging your USB stick without removing the device and completing data write. Unfortunately there is absolutely nothing we can do about this. DO NOT USE A USB STICK for your database.

**Comment by VonBishere** [comment]
Oki , thanks for the reply and feedback ofcourse , i thought this program was ment to be highly mobile, i used an older version of keepass for years on a usb stick , nothing happened , i did,t removed it before saving ,i always check carefully before removing it

i did try the cli tool with different arguments : export and such just now , no joy

Ah wel , i,l look for something else that works, chears mate

**Comment by r4gus** [comment]
@VonBishere totally late to the party but for everyone encountering a "No root group" error, it's worth trying to open the database using KeePass (e.g. keepass2) and then just saving it again. On Debian/Ubuntu it can be installed via `apt install keepass2` (see [KeePass Downloads](https://keepass.info/download.html)).

In the case above, it is very unlikely that the issue was caused by a corrupted DB, as the result of a corrupted data write. In such a case it is far more likely that KeePassXC would complain about a missing empty block or not being able to decrypt the db.
