### ISSUE TITLE
KeePassXC doesn't remember last opened database on Windows

### ISSUE THREAD

**Issue by EntityinArray** [keepassxreboot/keepassxc#10351]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeepassXC on Windows doesn't remember last opened database upon starting the app, making you select the database manually.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC and open your database
2. Go to Tools -> Settings -> General and make sure "Load previously open databases on startup" is checked
3. Quit KeePassXC and launch it again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC loads your last opened database and prompts for password

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC doesn't load last opened database and shows the welcome screen

## Context
[NOTE]: # ( Give us any additional information you may have. )
This issue only occurs on Windows, Linux works great

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro 22H2 19045.4046

**Comment by JeanPluzo** [comment]
Hi,
you might want to check some folder permissions. I've installed KPXC in several machines with different users, and every time they open KPXC the database is remembered. I wouldn't file this as a bug since I can confirm it's working as it should in many use cases.
Have you tried reinstalling KPXC?
Have you checked folder permissions?
Perhaps one of the installed extensions is causing problems?
We also use Win10 in different versions.
Regards,
J.

**Comment by EntityinArray** [comment]
Reinstall helped, thank you
