### ISSUE TITLE
Custom Browser option Missing in Windows for Browser Extension

### ISSUE THREAD

**Issue by nuenuewei** [keepassxreboot/keepassxc#10473]
## Summary
Four years ago, #4148 added support for dealing with custom browsers. But _only for mac and linux_.

## Examples
Just add it to windows also.

## Context
Currently windows users have to make registry edits or use symlinks to accomplish this, which are clunky workarounds that many users can't/won't/shouldn't try to do. Symbolic links also require CLI or third party tools. The kind of person who shouldn't be screwing with that needs tools like this **more** than someone who can

**Comment by droidmonkey** [comment]
We decided not to do this because _you still need to make registry edits_. The end user still needs to know where the registry entry needs to go to tell KeePassXC to make it. Custom browsers are less of an issue on Windows since most alt browsers look in the correct spot of the registry for their base browser.
