### ISSUE TITLE
v.2.7.7 Yubikey No-Prompt/Timeout Bug

### ISSUE THREAD

**Issue by 3knight** [keepassxreboot/keepassxc#10485]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The blue banner prompt occasionally does not appear when using Yubikey after initial unlock. Will display the spinning wheel of death until a timeout (red banner appears). Yubikey does still work despite there being no blue banner prompt.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock database that uses Yubikey
2. Wait for database to auto lock
3. Click green "Unlock Database" button
4. Use fingerprint to unlock database
5. No blue "press Yubikey to unlock" prompt, spinning death wheel appears, eventually times out with red banner

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Once you provide your fingerprint to unlock, a blue banner should pop up along the top of the window prompting you to press your Yubikey to unlock

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No blue banner appears, starts to buffer with spinning wheel and eventually times out

## Context
[NOTE]: # ( Give us any additional information you may have. )
Was not an issue prior to recent update

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by aussiefella74** [comment]
Have been experiencing this on mothe M1 and M2 macs since I updated to 2.7.7. If you wait until the timeout occurs and try again, the blue banner asking for yubikey appears correctly the second time you attempt to unlock your database. Alternatively you can just touch the key when it flashes after entering password/fingerprint even though the prompt banner has not appeared. Database will unlock normally for me first try  in this situation. Glad to see I'm not the only one experiencing this little bug.

**Comment by droidmonkey** [comment]
This appears to be just a ui bug with the banner. Should be easy to fix.

**Comment by droidmonkey** [comment]
I cannot replicate this anymore after doing other changes, this is fixed for 2.7.8
