### ISSUE TITLE
Start minimized first asks to unlock the DB

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#105]
## Expected Behavior

When the "Hide window to system tray on App Start" is enabled, KeePassXC should start in the Tray no matter if it's locked or unlocked

## Current Behavior

When the "Hide window to system tray on App Start" is enabled, KeePassXC first ask to unlock the DB and then minimize to Tray.

## Possible Solution

Always start minimized when the "Hide window to system tray on App Start" is enabled or add an option to "Don't unlock DB on Minimized AppStart"

## Steps to Reproduce (for bugs)

1. Enable "Hide window to system tray on App Start"
2. Close KeePassXC
3. Open KeePassXC

## Your Environment

* KeePassXR version/commit used: 065de97801479faf63bdda461aea5a8829da4a7e
* Qt version (e.g. Qt 5.3): 5.7
* Compiler (e.g. Clang++3.6.0): G++ 5.4.0
* Operating System and version: xUbuntu16.04
* Desktop Environment: XFCE 4.12

**Comment by Manko10** [comment]
Assigning myself since this has annoyed me a lot as well. Will fix it ASAP.

**Comment by meisanerd** [comment]
I would just like to add a note that I prefer it the way it currently works, as it is pointless for me to open up the app without having the database unlocked.  For any implementation change, I would recommend having an option that allows someone to keep the current behavior, while still allowing for the direct to tray on start.

**Comment by Manko10** [comment]
I don't see why you would want that behavior. There is really no reason to have a permanently unlocked password database and I don't know if I want to encourage users to have a permanently unlocked password database running in the background. For any other use case, the unlock dialog at startup is rather annoying and it's very confusing when you enter the password and KeePassXC just minimizes itself to the tray.

If you have an issue with auto-type not working with a locked DB, this was reported before in #101 and has already been fixed in the current develop branch.

**Comment by meisanerd** [comment]
I tend to only open up the app when I need to access the database, and have it set to automatically lock after 10 minutes, so it doesn't stay permanently unlocked.

My usual flow is to open up my web browser, start KeepassX, then log into all of the sites I use for work for the day.  The database spends most of the day locked.

This is also the way that Keepass on Windows works (although they have a separate dialog to ask for the password, rather than the main window).

**Comment by TheZ3ro** [comment]
Note that you will still be able to use KeePassXC with your normal flow by disabling the "Hide window to system tray on App Start", open KeePassXC and using #99 to Minimize the Window after you have unlocked the database

**Comment by Manko10** [comment]
Yes. You can either configure KeePassXC to not start minimized at all, log into all of your services and then minimize or let it minimize automatically and then use ChromelPass or AutoType which will then ask you for your password.

So I don't see how how fixing this issue will interfere with your workflow. This issue is about KeePassX not starting minimized (although it is configured to start minimized) and then minimizing itself once you enter the password. If I understood you correctly, this even interferes with your workflow since you would to manually restore the KeePassXC window every time after entering the password.

**Comment by meisanerd** [comment]
From what I read in #99, I would have to manually minimize to tray after I enter in the password.

Right now, it works perfectly with the workflow.  I open the app when I need to get the passwords, it asks me to unlock the database, then minimizes to the tray, out of my way.  All of the passwords I enter are used through the ChromeIPass plugin, so I don't ever have to see the KeepassX window again, which is done within that 10 minute window before the database auto-locks itself (Keepass on Windows is slightly better in that it can auto-lock after X minutes of computer inactivity, but the current KeepassX auto-lock works find for my workflow).

All I am suggesting is that an option be added that allows me to keep the current behavior.

**Comment by Manko10** [comment]
That is an issue addressed in #28. When that issue is resolved, the unlock dialog shows up automatically when you use ChromelPass and the DB is locked. No need to have KeePassXC show its unlock dialog after startup.

**Comment by anatoli26** [comment]
Just tested the 19a9608, it works as expected now, though there's a slight appearance of the window before it disappears (always talking about Ubuntu 16.04). I know it could be quite tricky to handle the window states on X, and this is really a small detail, but.. is there any way to truly start the app minimized (i.e. window-less) as opposed to start it with a normal window and then, at the beginning of the initialization, minimize it?

If there's a simple solution maybe it should be implemented. If it's something complex, then for me it's ok how it works now.

Same small detail happens when minimize-to-tray is enabled. First the app is minimized to taskbar, then the minimized state is detected and the app window is hidden (you can notice that on the taskbar icon).
