### ISSUE TITLE
Add an autoexec feature

### ISSUE THREAD

**Issue by alterratz** [keepassxreboot/keepassxc#1052]
Add a folder AutoExec which contains scripts which will be executed when the database is opened
This is very handy when you want to automount a decrypted folder when keepass is opened ....
The implementation couns use the url ar program name (including command line options) and pipe the contents of the notes to the standard input of the application.

I have already implemented this feature for me but there is a option missing that AutoEexc can be disabled (specially for database files from untrusted sources since it could harm your computer, "rm -rf /" comes into mind) ..... And of course it should be disabled for unknown (= files not in history) databases for this reason...
However, I am using it and I am happy like a young puppy with it.

usage example:

url: ```/bin/bash -```

notes: 
```#! /bin/bash
if ! mount | grep -q -e /home/bernhard/.dec
then
    echo "this is of course my real password" | /usr/bin/encfs -S /home/bernhard/.enc/ /home/bernhard/.dec/
fi
```

**Comment by alterratz** [comment]
However, I think at the moment my solution is not ready for general use due to a lack of restricting the exec function to known datrabases, but maybe someone will find it useful:
https://github.com/alterratz/keepassxc/tree/feature/autoexec

**Comment by phoerious** [comment]
This sounds really dangerous to me. I'm not sure if I want to trigger arbitrary script execution that way.
This should rather be implemented in the context of a plugin system.

**Comment by alterratz** [comment]
Well it might sound dangerous because it is (at least if you do not know what you are doing). This is why it should be disabled by default and only be allowed for known and trusted files. But anyway, if you have some feature where you can execute code, there will always be a risk if you start wildly opening unknown files and enabling Macros (i.e. office, acrobat, ....). So consider the changes in my git tree as an case study.
On the other hand it is very powerful and convenient (like in my use case automatically unlocking a decrypted partition)

**Comment by affinityv** [comment]
I know this isn't autoexec, but I prefer to open databases manually via a URL with related data stored in an entry, better still if it is the fuller URL overrides that are provided by KP2

https://keepass.info/help/base/autourl.html

With a URL override setup, I can create custom methods that relate to data fields and operate on the URL field of an entry.

For instance with just "aaaa://" in the URL field

Can invoke a cmd (for the aaaa URL) as follows:
cmd://"{APPDIR}\KeePass.exe" "{DB_DIR}\{S:DB_NAME}" -pw-enc:"{PASSWORD_ENC}" -keyfile:{S:KEY_FILE}

This will run KP2 (on Winblows), with some built-in placeholders being used and using data from text entries (additional string attributes for DB_NAME and KEY_FILE).  There is also a method by KP2 that encrypts a password so that it can, supposedly, be passed securely when opening the database.  I'm not so sure that the password is really sent securely, but it might be -- it does rely on the user's Window login credentials, so I believe that helps.

There are these related built-in URL overrides in KP2 as:
cmd://"{APPDIR}\KeePass.exe" "{BASE:RMVSCM}" -pw-enc:"{PASSWORD_ENC}"
cmd://mono "{APPDIR}\KeePass.exe" "{BASE:RMVSCM}" -pw-enc:"{PASSWORD_ENC}"

The built-in entries are not editable, so that is why I create my own.  Note that KP2 has some extra placeholders including APPDIR and DB_DIR, which I use.

You can do things like the following in the URL field of an entry in KeepassXC as well, but the password isn't sent safely.

cmd:///home/andrewm/bbbb.sh "{PASSWORD}"

That will (when you invoke the URL with CTRL-U), run the shell script /home/andrewm/bbbb.sh with the quoted password as the parameter for the script.  Multi-word passwords become "$1" in the bash script.

For the KP2 overrides to work I had to have only a single instance of KP2 (by settings), which causes opening of new databases to become tabs in the first running instance of KP2.  If KPXC has single instance set, it won't open another database from the command line; it can only be opened via the file menu.

So, I think some tweaking of the code and use of URL overrides might have some merit for exploration.

**Comment by pquerner** [comment]
With URL Overrides I was able to open a slave database with password and additional key file (if wanted) (on Windows), however I dont have the URL override anylonger. 
Is this something KeepassXC considers adding (URL Override I mean) ?

**Comment by droidmonkey** [comment]
I have no interest in delivering this feature, it adds to the attack surface and is way outside our scope.
