### ISSUE TITLE
Add an option to accept Monero (XMR) donations

### ISSUE THREAD

**Issue by TheFuzzStone** [keepassxreboot/keepassxc#10535]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Add [Monero (XMR)](https://www.getmonero.org/) wallet address (better subaddress) to the website: https://keepassxc.org/donate/

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

GrapheneOS has a positive experience with Monero (XMR), see here: https://twitter.com/GrapheneOS/status/1684663777273233408

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

When you add an XMR wallet to the site, tag me with "@" and I'll send the first donation of 50 USD.

**Comment by droidmonkey** [comment]
I prefer donations in a currency that can pay the bills.

**Comment by TheFuzzStone** [comment]
@droidmonkey, how many bills have you paid with Solana?...

Never mind, though.

**Comment by its-me-ct** [comment]
I like Keepass because it allows me to keep my most important data private, and for that I'd like to support you too.

Unfortunately none of your donation options are private, and Monero is the most popular choice in that regard. Unlike bitcoin and Ethereum it's also cheap to send (typically about $0.01), so you get to keep a larger share, especially of smaller donations. If your current exchange does not support Monero natively, you can use trocador.app for a quick and easy exchange to BTC, ETH or SOL, no signup needed.

I respect you opinion either way, but should you change your mind, I'd like to offer an additional 50 USD worth of XMR.

**Comment by serejandmyself** [comment]
> I prefer donations in a currency that can pay the bills.

tell this to the people in ussr or any other non existent state nation. the comment is so terribly far from understanding what crypto stands for, that it will make ya famous

**Comment by detherminal** [comment]
Why should we use decentralized and private cryptocurrency when a completely centralized (Solana reruns the chain via Discord lol) and transparent cryptocurrency honeypot exists, right?

**Comment by 200ug** [comment]
> I prefer donations in a currency that can pay the bills.

People living in some of the more authoritarian nations in the world might prefer keeping their donations private even if you don't see the benefit in that. Besides that XMR is actually [quite widely accepted](https://monerica.com/) even outside DNMs and such.

**Comment by droidmonkey** [comment]
> People living in some of the more authoritarian nations in the world might prefer keeping their donations private even if you don't see the benefit in that

> tell this to the people in ussr or any other non existent state nation. 

I don't want their money. Spend it on your family and maybe escaping from that situation.

> the comment is so terribly far from understanding what crypto stands for, that it will make ya famous

No one cares. It might come as a surprise, but we don't care about cryptocurrency. We only offer a couple donation options for the more popular coins. The only one that matters is Bitcoin. I think I've received about $50 in ETH + SOL in 3 years. 

Consider how you folks respond to someone who doesn't agree with your world view. Pile on, spit out strawman about repressive nations, etc. How about just stop asking because we already told you no about 10 times.

**Comment by nmateo** [comment]
I agree with this guy, if he doesn't want your xmr, just stop asking him to take it, it's that simple.
Also "Bitcoin is the only one that matter" sums up his opinion lol, even tho i dont agree, can't force the guy to accept xmr

**Comment by droidmonkey** [comment]
> Bitcoin is the only one that matter

Just to be clear, this was only referring to total donation amounts received.

**Comment by its-me-ct** [comment]
Understood. I was only describing the aspects I value, you don't have to agree. @me if you change your mind. Take care.

**Comment by SyntheticBird45** [comment]
Would have been happy to give some of my neros. KeepassXC is great.

**Comment by rafael-xmr** [comment]
> I prefer donations in a currency that can pay the bills.

>> Bitcoin is the only one that matter
>
> Just to be clear, this was only referring to total donation amounts received.

You could just try it out as it costs nothing to leave a static address people can donate to, with peace of mind of not having to trust third parties or being exposed to chain analysis companies, and see how well it performs and if there are any actual hurdles to "pay the bills", as it doesn't seem there is anything to lose for someone that already accepts Solana and just leaves the address there even after 3 years of not making over $50

**Comment by Final-Phoenix** [comment]
> > People living in some of the more authoritarian nations in the world might prefer keeping their donations private even if you don't see the benefit in that
> 
> > tell this to the people in ussr or any other non existent state nation.
> 
> I don't want their money. Spend it on your family and maybe escaping from that situation.
> 
> > the comment is so terribly far from understanding what crypto stands for, that it will make ya famous
> 
> No one cares. It might come as a surprise, but we don't care about cryptocurrency. We only offer a couple donation options for the more popular coins. The only one that matters is Bitcoin. I think I've received about $50 in ETH + SOL in 3 years.
> 
> Consider how you folks respond to someone who doesn't agree with your world view. Pile on, spit out strawman about repressive nations, etc. How about just stop asking because we already told you no about 10 times.

trocador.app
orangefren.com

It takes two seconds to swap to whatever crypto your heart desires. You'll lose more money if we all individually swap to BTC, ETH, or SOL first instead of us pooling XMR donations directly to you and you make a single swap every once in awhile.

It's so weird you don't want free money from users who appreciate your software and are trying to give back to you but ok. If you don't want those XMR donations I'll take them: 

8C3GcmbizWAMkNfMsSoTpt2TBtgLRPYF3JgvuZPxxM267BTveZjrqXkW2bv64Dx4ktQi4FzmKGoNQNasAb7VP6FuEG9xA8T
