### ISSUE TITLE
In Google Chrome, a website can return data by universal match URL

### ISSUE THREAD

**Issue by Cang-Cat** [keepassxreboot/keepassxc#10559]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
In Google Chrome, a website can return data by universal match URL

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
For example: at www.test.com, I created an account and password and saved it to the database. After some time, the domain name of the website changed to www.test.org, so I could not match the domain name of com registered by KeePassXC-Browser

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Some websites often change their domain names, which leads to frequent changes to the data in KeepassXC. Hopefully, we can match it with https://www.test.*

**Comment by varjolintu** [comment]
That kind of scenario is not really recommended because it will allow matching with every domain that has that as a subdomain. A proper solution would be to just change the entry URL, or add another to Additional URL's list.

Anyway, wildcards are covered in this change: https://github.com/keepassxreboot/keepassxc/pull/9835

**Comment by droidmonkey** [comment]
This is a phisher's dream
