### ISSUE TITLE
Logging required - When was the database unlocked and when was which key copied

### ISSUE THREAD

**Issue by HeartOfGermany** [keepassxreboot/keepassxc#10582]
## Summary
Currently neither KeepassXC nor KeepassXC Browser does log important actions.

## Examples
```
12.04.2024 - 06:20 - Unlocked database <database name>
12.04.2024 - 06:21 - Copied Password of <entry name> <database name>
12.04.2024 - 06:21 - Automatically logged in via Browser on <url name> <entry name> <database name>
```

## Context
It sometimes is utterly important to know, when access has happened. And to know, when the database got accessed can be an important feature for a company. So can someone please add this feature? I am totally confused, why this is not already a feature, as logging often is part of the development process anyways. Would like it be accessible for the user.

From what I understand I would think that is required in the EU anyways, as all data protection/security relevant things need to be logged anyways.

**Comment by droidmonkey** [comment]
This is not present _by design_. If you need logging then this isn't the program for you. 

KeePassXC, and pretty much all other variants, are personal password management applications. You are welcome to use them in whatever setting you like, but we are absolutely not an enterprise solution.

**Comment by HeartOfGermany** [comment]
Yeah exactly. Pretty much every other variant is a personal application. What widespread enterprise solution even exists? Why would this be by design? I do not see the benefit of rejecting to just add an option in the... options. If you are not motivated to do so fine, but limiting kinda obvious features "by design"? Jeeez... What is the phylosophy of this product?

**Comment by droidmonkey** [comment]
Our philosophy is privacy and minimal footprint. There are plenty of enterprise password management solutions that enable auditing of your employees. KeePassXC is not one of them and will not be one of them. There is a big difference between personal password management and enterprise password (credentials) management.

**Comment by HeartOfGermany** [comment]
No, I do not want to audit "my employees", I am employee and sometimes would benefit from knowing, when I logged in to a certain page. I do not think, that even the user should not be allowed to log his own actions, if he wants to do so. Just saying... And as an employee I cannot enforce an enterprise solution just to get a log.

**Comment by JohnLGalt** [comment]
I suspect if we were to put it to a vote amongst all the users out there, it would end up being an extremely niche request.

I mean, I have used KeePass, and now KPXC for the last few years, collectively for well over 20 years. I currently have 74 groups that contain a total of 791 entries, The actual database I'm currently using was created 28 May 2013, and contains 692 **unique** passwords, with 0 expired entries as of right now.

Even in plain text, that is a lot of logging, *and* a privacy concern, unless it is inaccessible without some sort of additional protection/ encryption, and I use KPXC every single day to log in to a wide variety of sites on a variety of devices.

I may not use all 700 of them, but it is safe to say I use close to 100 per day on any given day, as I don't like having my PWs stored anywhere else for reuse.

Let's say that this is a very liberal assessment, and be more conservative. Let's say it is only 50 items per day. That is still 18250 per year. if there was logging going on for the entire time this database has been in existence, that would be well over 180000 log entries. So that means there needs to also then be a mechanism to prune the logs, either by age, or by quantity, to something else, and some people will want it done by age, with variable age requirements, and some will want it by quantity, also with variable requirements, and then there is the matter of how it will be stored, because some people like me use this same database across a multitude of devices, and my database is already over 1 MB in size, and how do you account for when a password is used for entry into not a website, but an application, where you just manually cope and paste the login info into the application, or service? 

It's not just a matter of "this item was accessed at this time", let's log it.

**Comment by HeartOfGermany** [comment]
Well, such an option should not be enabled by default in my opinion. But why would I not have the option to decide this for myself? This setting could also be stored within the password database, so not even the company can access it just to show a strange possibility.

And the copy into an application would just log "<timestamp>: <entry name> password copied". Typically the entry is only for the 1 application, so it is obvious, what the usecase was.

This log could even be stored in the same password database, or another database file with the same password and encryption method, if privacy is a concern. I understand it is very niche, but it would not require the reinvention of the wheel - at least I would seek for an implementation that just adds this almost exclusevly based on existing code.

Super stupid approach would be enough: If a password gets copied, a fuction pastes it to the clipboard. There is a function called "log(timestamp(), database, entry, initiator)" and it can be pasted anywhere, where a password is fetched.

initiator would mean: Browser plugin || copy&paste || entry edited

To enable the log, without exposing the setting to the system, you could allow an optional password entry like: "save_log_enabled" and set the password to "enabled" to enable the logging. More like a hidden feature. Of course a separate dialog could be created with the name "save_log_enabled" detected, but that is just to much hazzle in my opinion.

And the log function could be something like (this is javascript style but it does not matter for the logic):

```
function log(time, db, ent, ini)
{
   if(read_keepass_entry(db, get_current_password(), "save_log_enabled").password == "enabled")
   {
      new_keepass_entry(db+"_log", get_current_password(), time + ": password " + ent + " of database " + db + " was accessed.");
      return false;
   }
}
```

Just an idea. I do not know, how it actually is implemented at the time, to save an entry, but if it is similar to this, that would be a fine solution and not force people to accept the companies surveillance.

And reviewing the log would be just, to open the database with the _log on the end of the name and see the entries. That would require almost no additional code.

**Comment by michaelk83** [comment]
If you are looking for website login history, you can just search your browser history. E.g. in Firefox you can go to Library -> History -> Manage History, enable the Most Recent Visit column, and then search for the website name.

You could probably install a 3rd party app or setup your OS to log when you use which app outside of the browser.

**Comment by HeartOfGermany** [comment]
The History does not work, as it saves the last access. If I access it today it overwrites the entry from yesterday. That was my issue, I had.

The OS or any App could not be set up, as I am user of a companys domain. I would prefer this in the official app, which would be rolled out eventually. I have no power to get this feature to work in any meaningful way. I could create a userscript for every company page I log into to fetch a webserver of mine to save a log entry, but the effort is quite large for a single user to benefit and I am 100% certain, that logging data related to the company externally is absolutely getting me to jail if one figures it out.

To explain: I forgot to stamp my "Comming" time on the one day and I would be able to figure out, when I came to work from such a log to fix it. I had to book the latest possible time to ensure I do not cheat on my company. This is time of my life wasted and not getting paid for. A history would have helped me. Since I already logged in everywhere, the history entries where all overwritten to the current day. That is not helping me at all.

**Comment by michaelk83** [comment]
Try maybe your phone's location history. This all sounds very very niche, and unlikely to be implemented.

**Comment by droidmonkey** [comment]
You can see when you logged into your computer through Windows Event Viewer:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/4db88706-ee01-4c69-971a-fa16c0e7a52b)

just search for your username and it'll hop to the points where you "logged on" just find the earliest one for the day.
