### ISSUE TITLE
Version 2.7.6 on MacOS version 11.7.10 ask to upgrade to 2.7.8 but 2.7.8 is not compatible

### ISSUE THREAD

**Issue by jonatanmv** [keepassxreboot/keepassxc#10754]
## Overview
Using app version 2.7.6 on MacOS 11.7.10
When launching the application it reports a newer version (2.7.8) and remains the user to upgrade from the website.

## Steps to Reproduce
1. Open the app
2. Read the upgrade warning
3. Access to the link and upgrade

## Expected Behavior
The upgrade reminder should only appear for compatible versions

## Actual Behavior
App remains about and upgrade to a non compatible version

## Context
Operating System:: MacOS 11.7.20
KeePassXC version: 2.7.6

Thanks in advance !

**Comment by phoerious** [comment]
We cannot know ahead of time what OS version will still be compatible when we release a version and we cannot change it afterwards. Just disable the update check if you don't plan on upgrading your OS (which you should, since macOS 11 is EOL and will not receive security updates). Technically, KeePassXC should still able to run on 11, but no guarantees.

**Comment by jonatanmv** [comment]
Yes, I understand.
Hope KeePassXC should still able to run on 11 as OS upgrade is not an option for laptops some years old (but still functional).

Regards !!
