### ISSUE TITLE
Problem while verifying signatures (DIGEST file)

### ISSUE THREAD

**Issue by Nakayuna** [keepassxreboot/keepassxc#1085]
Hi,

After downloading KeePassXC files, I tried to verify its integrity by checking its hash digest.
Command ran : gpg -v --verify /KeePassXC-2.2.1.dmg.sig /KeePassXC-2.2.1.dmg.DIGEST

## Expected Behavior
gpg: GOOD signature from « KeePassXC Release <release@keepassxc.org> » [unknown]

## Current Behavior (translated from french)
gpg: Signature made Mon  2 oct 2017 06:27:06 PM CEST
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: using subkey B7A66F03B59076A8 instead of primary key CFB4C2166397D0D2
gpg: using PGP trust model
gpg: WRONG signature from « KeePassXC Release <release@keepassxc.org> » [unknown]

## Context
Trying to verify the integrity of KeePassXC 2.2.1 files (downloaded a few hours ago) by checking its hash digest.
I first tried to run the following command:
shasum -a 256 -c /KeePassXC-2.2.1.dmg.DIGEST

but it said "KeePassXC-2.2.1.dmg: FAILED open or read". After reading https://www.qubes-os.org/security/verifying-signatures/, I ran the following command:
gpg -v --verify /KeePassXC-2.2.1.dmg.sig /KeePassXC-2.2.1.dmg.DIGEST

Operating system: macOS 10.13

What should I do? I'm a complete newbie here... Many thanks in advance.

**Comment by sts10** [comment]
No expert here either, but I've got some guesses. 

Unless you downloaded your dmg, sig, and DIGEST files all to your HOME (`/`) directory, your handling the file locations wrong. 

My guess is that you downloaded those three files to your `Downloads` directory. If all three files are there, try the following. (And if they're not there, you can move then there or re-download all three files and try the following)

## GPG Verification 
`gpg --verify ~/Downloads/KeePassXC-2.2.1.dmg.sig`

You should see something like 

```
gpg: assuming signed data in '/Users/samschlinkert/Downloads/KeePassXC-2.2.1.dmg'
gpg: Signature made Mon Oct  2 12:27:06 2017 EDT
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

If you're still getting an error, there's a chance you have `gpg` version 1.x rather than 2.x. To check your version, you can run `gpg --version`. You can also see if you have `gpg` version 2 installed under `gpg2`. If running `gpg2 --verison` shows a version of `gpg` over 2.0, try `gpg2 --verify ~/Downloads/KeePassXC-2.2.1.dmg.sig`



## SHASUM DIGEST thing verification

I'm less sure here, but this worked for me on macOS 10.10. 

To do this part of the verification, it seems that you have to navigate to the `Downloads` directory, then run the command. So to move to `Downloads` directory by running: 

`cd ~/Downloads`

And then run:

`shasum -a 256 -c KeePassXC-2.2.1.dmg.DIGEST`

You should get: `KeePassXC-2.2.1.dmg: OK`

**Comment by droidmonkey** [comment]
From the looks of it you are trying to verify the signature of the digest file instead of the executable.

**Comment by sts10** [comment]
Yeah, more succinctly, what @droidmonkey said.

**Comment by phoerious** [comment]
Yes. You need to verify the binary, not the digest file.

**Comment by Nakayuna** [comment]
The files were on Desktop. I moved them to my home directory as suggested and it worked, many thanks!

Can I delete the .sig and .DIGEST files now? It was just for verifying right?

**Comment by phoerious** [comment]
Yes.
