### ISSUE TITLE
Keyboard Associations

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [keepassxreboot/keepassxc#10904]
I would like two options to specify optional keyboard shortcuts and associations that mimics the behavior of vanilla KeePass:

1. Map a single key or key combination such that when you're in the top-level context of the app, it minimizes/closes the app. I typically use the Esc key. I like the behavior where if you're in a sub-context it brings you out of it, but at the top-level nothing happens and I just want to minimize/close the app by maniacally tapping the Esc key.
2. Allow for a system-wide custom assignment to open the keepassxc interface. On vanilla KeePass I had mapped Ctrl+Alt+- (which is the - sign on the numpad) and I miss being able to use it :(.  Often times there's unexpected behavior with a site I'm logging into and I need to open the app and browse to the entry. Currently I have to use my mouse and open it through the system tray. It gets aggravating.

**Comment by droidmonkey** [comment]
Your first request is not going to be implemented because ESC is used for many other things like canceling search, canceling edits, etc. To minimize use Ctrl + M, to minimize to tray us Ctrl + Shift + M.

Your second request is captured here: #1858 

Since you seem to have just migrated from KeePass2, you should read our user manual and look into our much more robust auto-type dialog that eliminates a lot of the need to bounce back and forth into the application.

https://keepassxc.org/docs/KeePassXC_UserGuide

https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type
