### ISSUE TITLE
Database entries are not loaded after update to 2.7.9

### ISSUE THREAD

**Issue by mgieseki** [keepassxreboot/keepassxc#10927]
When opening my database file with version 2.7.9, it doesn't seem to load the entries because KeepassXC only shows an empty window. After reinstalling 2.7.8, everything works correctly again.
I'm on Windows 11 23H2 (22631.3737). 
Am I missing anything here or is this a known issue?

![grafik](https://github.com/keepassxreboot/keepassxc/assets/3620467/6322c476-015c-4739-9282-326768ac2bf8)

**Comment by GabryB-06** [comment]
Hi, I'm having (I belive) the same issue , I can see my passwords that are stored in the database's root directory but I can't see the folders list and browse it. The only way I've found to see the directories is to close the database and reopen it.
I'm on Windows 11 23H2 (22631.3737) and using [KeePassXC-2.7.9-Win64.msi](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.9/KeePassXC-2.7.9-Win64.msi)
![Immagine 2024-06-20 100242 2](https://github.com/keepassxreboot/keepassxc/assets/122260835/129bbcdc-75a7-45dc-bfe3-34efe503add6)

**Comment by droidmonkey** [comment]
Looks like your group and preview panel got hidden. We fixed a couple bugs with them that may be manifesting because of a bad config file entry. Easily fixed by dragging from the far left (you should see your cursor change).

I assume you don't have any entries in your root group.

**Comment by mgieseki** [comment]
That's it. Yes, you're right, there are no entries in the root folder. Thank you for the fast help and sorry for the noise.

**Comment by talistech** [comment]
I had the same issue, thank your for the question and solution provided here! :)

**Comment by SinnySupernova** [comment]
> Looks like your group and preview panel got hidden. We fixed a couple bugs with them that may be manifesting because of a bad config file entry. Easily fixed by dragging from the far left (you should see your cursor change).
> 
> I assume you don't have any entries in your root group.

Dragged it and it's showing now. 

I didn't have a previous version installed, so this definitely happened within the context of v2.7.9

**Comment by BlackAlpha700** [comment]
I have the same issue and could fix it by dragging from the left. After a restart of KeepassXC everything is fine and works as expected.

But interesting thing by the way, before I've dragged from the left: If I had disabled the systray symbol in the settings, the group and preview panel are shown as expected. Enabling the symbol again had "hidden" the two panels again. I could reproduce this behaviour unter Win10 and Win11.

**Comment by ghost** [comment]
The issue isn't fixed in 2.7.9, so I'm not sure why this is closed. Same issue as OP here and it was driving me nuts. Something in the update is setting the X position to the side panel to 0, and the user needs to manually slide it over to fix the bug.

A workaround is to close the database manually and reopen it, however, after a restart, the issue will return until the user fixes the position himself.

**Comment by CodeCubeNeo** [comment]
Why not set the minimal length of the side bar, so people dont wast time lookinga at an empty screen and finding their way here? I also think this should be reopened

**Comment by droidmonkey** [comment]
Welcome, we close issues when we fix them, not when we release a fix. The fix is in 2.7.10 upcoming release. Thanks.

**Comment by LinuxOnTheDesktop** [comment]
Just now, after KeePassXC refused to open a few times - and this after I had to forcibly reboot the machine because the machine would not resume from sleep - the database appeared blank. Moving the slider - the one that reveals the groups - revealed nothing. _I found that my database reappeared when I changed the theme setting from dark to (I think it was) light; subsequently setting the theme back to dark did not make the database entries invisible._

Linux Mint 21.1 Cinnamon (based on Ubuntu 24.04)
KeePassXC 2.7.10

Perhaps I should mention this within one of the reports linked above, or open a new report. If so, then I or you (dear maintainer) can move the report.

**Comment by droidmonkey** [comment]
Sounds 100% like not our code, especially if you are running classic theme

**Comment by LinuxOnTheDesktop** [comment]
Before I had the problem I was not running the KPXC classic theme but rather the dark theme. Just now I tried the classic theme and it was largly illegible. I tried the 'automatic' theme setting too; it gave me a light theme when the rest of my system is dark.
