### ISSUE TITLE
2.7.9.msi 64bit does not start with Win11 after update from 2.7.8

### ISSUE THREAD

**Issue by it32890** [keepassxreboot/keepassxc#10968]
## Overview
[TIP]:  After install 2.7.9 over 2.7.8 in Win11 the KPXC does not start
[NOTE]: I reinstalled the 2.7.8 over 2.7.9 and all work fine.

## Steps to Reproduce
1. install KeePassXC-2.7.9-Win64.msi  ==> KPXC does not start
2. repair  with  KeePassXC-2.7.9-Win64.msi ==> KPXC does not start
3. remove  with KeePassXC-2.7.9-Win64.msi ==> OK remove KPXC
4. install KeePassXC-2.7.8-Win64.msi  ==>  All work fine

## Expected Behavior
KeePassXC-2.7.9 work fine after step 1

## Actual Behavior
KeePassXC-2.7.9 does not work after step 1

## Context
Windows 11 pro

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9
Revision: Last

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro
Desktop Env: version 23H2

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925#issuecomment-2179741873

**Comment by it32890** [comment]
thanks doidmonkey,  after installation of  https://aka.ms/vs/17/release/vc_redist.x64.exe now 2.7.9 start without problems.

**Comment by Martin2p** [comment]
Got also problem with version 2.7.9. , first it was working with vc_redist.x64.exe ... but now the programm doesnt start again ->back to 2.7.8

**Comment by Iiridayn** [comment]
Just upgraded from windows 10 to 11, and keepassxc (2.7.9) wouldn't start. Downgraded to 2.7.8 and it starts fine.

**Comment by droidmonkey** [comment]
Update your vsredist.

**Comment by Iiridayn** [comment]
> Update your vsredist.

Chocolatey reports that my system is completely up-to-date, with the exception of keepassxc. Is there an updated dependency as of 2.7.9 I should report to the chocolatey package maintainer? From what I can tell there are dozens of vsredist versions. Which should I update, and how? I've not installed a windows app outside of chocolatey/steam/windows store in a very long time since windows is at best a tertiary computing platform for me (primarily MS office controlled via synergy from my desktop, note taking in vim, and some occasional browsing - other than MS office most everything I use is cross-platform). My apologies for my weak windows system administrator abilities.

**Comment by droidmonkey** [comment]
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

This is linked and discussed above.

**Comment by Iiridayn** [comment]
When I downloaded and ran the installer linked, it said it was already installed. I chose to repair the installation and reboot, after which the upgrade to keepass 2.7.9 worked - thank you. Perhaps the windows upgrade broke some associations.

**Comment by brad-richards** [comment]
Setting up a completely new Win-11 computer. KeepassXC 2.7.9 does not start. Version 2.7.8 works fine.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
