### ISSUE TITLE
MacOS Sonoma 14.6 SSH Agent key confirmation doesn't work

### ISSUE THREAD

**Issue by krisavi** [keepassxreboot/keepassxc#11134]
## Overview
On macOS Sonoma 14.6 (OpenSSH version 9.7p1) it seems key confirmation doesn't reach to KeepassXC (acts like in #1627)

## Steps to Reproduce
1. Set up SSH Agent in Keepass
2. MacOS upgrade to Sonoma 14.6 (OpenSSH_9.7p1)
3. use SSH to log in
4. (Bonus) Try to log into another machine if previous machine was jumphost

## Expected Behavior
Able to log in 

## Actual Behavior
`sign_and_send_pubkey: signing failed: agent refused operation` message

## Context
Turning off key confirmation or using `ssh-agent` and adding keys there works fine

KeePassXC - Version 2.7.7
Revision: 68e2dd8
Same issue on Version 2.7.9

Operating System: macOS 14.6

**Comment by krisavi** [comment]
https://github.com/theseal/ssh-askpass/issues/54#issuecomment-2264396356 Might be extra context here

**Comment by droidmonkey** [comment]
Confirmation is not done by keepassxc, we just set a flag when loading the key into ssh-agent. You'll either need a newer version of ssh-agent or figure out your current setup but this isn't a keepassxc problem.

**Comment by krisavi** [comment]
MacOS has changed OpenSSH. KeepassXC sets flag that might be changed now. As far as I know MacOS uses custom version of OpenSSH, where -c is not key confirmation, but is "keychain" usage. That might have changed from Sonoma 14.5 where OpenSSH 9.6p1 was used versus Sonoma 14.6, where OpenSSH 9.7p1 is used. Other thing that have changed is that you cannot seem to set SSH_ASKPASS as environment variable like it was used to be. I believe that environment variable is critical for KeepassXC to direct key confirmation to correct place for confirmation.

I believe your answer that it is due to newer version that comes with newer version of macOS out of the box is way too rushed. There hasn't been any analysis done on your side from the information that has come out from ssh-askpass guys who are facing exact same problem. 

I think you should at least then put up notice that it does not work any more with OpenSSH packaged with macOS and direct people to using Homebrew.

**Comment by krisavi** [comment]
> Confirmation is not done by keepassxc, we just set a flag when loading the key into ssh-agent. You'll either need a newer version of ssh-agent or figure out your current setup but this isn't a keepassxc problem.

Just for information, it worked on older version of OpenSSH before and OpenSSH version doesn't matter. Homebrew ships OpenSSH_9.8p1, OpenSSL 3.3.1 4 Jun 2024 and that doesn't work either. Where do I get any newer one?

KeepassXC agent worked with Homebrew 9.8p1 and macOs own shipped 9.6p1 in Sonoma 14.5, but doesn't in 14.6.

As I mentioned in previous post, OpenSSH version is not even the main issue here. It is that SSH_ASKPASS environment variable is something that needs to be set and KeepassXC is unable to set it in Sonoma 14.6.

**Comment by droidmonkey** [comment]
> It is that SSH_ASKPASS environment variable is something that needs to be set and KeepassXC is unable to set it in Sonoma 14.6.

We don't set that environment variable, that would be on your side through the system environment variables or your profile (im not a macos expert). We also don't call ssh-agent from the command line so -c doesnt apply here. A bug would need to be filed with macos if their version of openssh is broken.

**Comment by droidmonkey** [comment]
Just do this: https://github.com/theseal/ssh-askpass/issues/54#issuecomment-2268376357

**Comment by micolous** [comment]
For what it's worth, I agree with @droidmonkey's assessment... this isn't KeepassXC's bug to solve. 😄 

All KeepassXC seems to do is optionally [request the running `ssh-agent` to request confirmation before being able to use a key](https://github.com/keepassxreboot/keepassxc/blob/e48ef80e9c81a16ab971ca0e40e0ab4cfb39defb/src/sshagent/SSHAgent.cpp#L298-L300). It's up to `ssh-agent` to pick an `ssh-askpass` implementation.

[`ssh-agent` doesn't actually check whether it *could* ask confirmation when loading a key](https://github.com/apple-oss-distributions/OpenSSH/blob/9b6202341ee10b42e7391229ad5c0f2eb8aea8af/openssh/ssh-agent.c#L1299-L1306) - it just sets a flag, and as long as you didn't set it _twice_, there's no error. [KeepassXC checks the result](https://github.com/keepassxreboot/keepassxc/blob/e48ef80e9c81a16ab971ca0e40e0ab4cfb39defb/src/sshagent/SSHAgent.cpp#L313-L323), and even suggests the agent not supporting confirmation as a possible reason for rejection if requested.

If `ssh-agent` actually checked that it *could* ask for confirmation when loading a key, then KeepassXC's check would be effective.

It's only when `ssh-agent` actually tries to use that confirmation-required key that it can fail; as it does on Sonoma 14.6 and 14.6.1 unless you've [applied the workaround I suggested](https://github.com/theseal/ssh-askpass/issues/54#issuecomment-2268376357).

Upgrading or using Homebrew's version of OpenSSH won't help anything, because this was all caused by a `launchd` change, and Apple's `ssh-agent` config is what matters. I'd actually recommend *uninstalling* Homebrew OpenSSH and sticking to Apple's version, because it can cause all sorts of strange issues.

> As far as I know MacOS uses custom version of OpenSSH, where -c is not key confirmation, but is "keychain" usage

Apple's `ssh-add` has always supported `-c` just like other platforms. You're probably thinking of [`-K`, which was replaced with `--apple-use-keychain`](https://docs.github.com/en/authentication/troubleshooting-ssh/error-ssh-add-illegal-option----apple-use-keychain), because `-K` is used in upstream OpenSSH for loading FIDO2 resident keys.
