### ISSUE TITLE
Unreadable small text on 4K screen after leaving overnight - How to reproduce and workaround

### ISSUE THREAD

**Issue by Growlertiger** [keepassxreboot/keepassxc#11203]
## Overview
On a computer with a 4K screen the program normally correctly displays the text the correct size.
However I found that sometimes the screen changes to have very tiny text. You have to close the progam and open it again.
After much experimentation I found how to reproduce the problem quickly.

## Steps to Reproduce (quickly, without waiting all night)
1. In Windows settings, make the screen go to sleep after 1 minute.
2. In KeePassXC settings for security:
- Lock databases after inactivity of: 90 sec
- Lock databases after minimising the window: untick
3. Minimise KeePassXC.
4. Wait 2 minutes without touching the computer. (After 1 minute the screen goes black. 30 seconds later the minimised window locks the database.)
5. Wake up the computer.
6. Restore the KeeePassXC window.

## Expected Behavior
You can read the text.

## Actual Behavior
Tiny text.

## WORKAROUND
Go to the properties of the shortcut.
Compatibility tab
Press Change high DPI settings button
Program DPI: tick
Override high DPI scaling factor: tick
Scaling performed by: System (Enhanced)
Press OK.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro, up to date.

**Comment by droidmonkey** [comment]
This isn't a problem with KeepassXC, it would be a qt issue if anything. Recommend trying some of the environment variables qt affords to control this: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

**Comment by Growlertiger** [comment]
Surely it could be a bug in KeePassXC as it is only when your code closes the database that the DPI setting is lost.
If it is a problem with qt then it is still a bug that appears to a user when someone uses KeePassXC, so knowing about this bug and its workaround would be helpful to others who encounter it, and as more people get 4K displays this will increase.
If I am to investigate QT environment variables it would help if you said what DPI settings you have used with QT?
Also I don't understand why you flagged my report as non reproducible when it is reproducible.

**Comment by droidmonkey** [comment]
I use a 4K screen on Windows 11 (both 16:10 and 16:9 ratios) with 1.5 scaling without any issues what so ever. You are the only one reporting this type of issue. Without reproduction steps there is nothing we can do to attempt to resolve the situation that you are experiencing. The fact that this is resolved by using the alternative DPI settings means there is some configuration wrong on your end that is causing KeePassXC to not be scaled appropriately. This is why I recommend investigating the Qt environment variables which can force a specific scale factor.

**Comment by JohnLGalt** [comment]
> Surely it could be a bug in KeePassXC as it is only when your code closes the database that the DPI setting is lost. If it is a problem with qt then it is still a bug that appears to a user when someone uses KeePassXC, so knowing about this bug and its workaround would be helpful to others who encounter it, and as more people get 4K displays this will increase. If I am to investigate QT environment variables it would help if you said what DPI settings you have used with QT? Also I don't understand why you flagged my report as non reproducible when it is reproducible.

I have to agree with DM about the issue being QT-based, having used KPXC for a long while, and encountering a couple other QT-based apps (like Free Download Manager) that exhibit the exact same behavior in the same manner - wake from Sleep mode in Windows 11 renders the text miniscule.

As for something being wrong, though, @droidmonkey, I have to interject that, rather than something **set** incorrectly, I'd point to more of an incompatibility between Windows 11 and QT-based apps , specifically when waking from Sleep mode. It's gotten so bad that I actually don't allow my PC OS to sleep, rather just power down the monitors into standby states, to prevent issue like this.

I did a lot of testing with those QT-specific DPI settings, and no combination of settings could ever fix this one aspect - and the fact that it happened randomly (yet consistently) forced me to change the way I operate my PC. Being a desktop connected to a beefy (and managed) UPS, I'm not too worried about power outages, so I can afford to go this route - but others simply cannot.

**Comment by droidmonkey** [comment]
Hopefully these issues go away when we move to Qt 6 in 2.8.0
