### ISSUE TITLE
Horizontal scrollbar not visible in groups

### ISSUE THREAD

**Issue by leohoman** [keepassxreboot/keepassxc#11300]
## Overview
KeepassXC doesn't show horizontal scrollbar when group name(s) don't fit to group area.
![keepassxc_scrollbar_bug](https://github.com/user-attachments/assets/47b17d0d-d0b7-44f3-9350-2c04ef223fe9)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a group with long enough name that doesn't fit to group area

## Expected Behavior
KeepassXC should show horizontal scrollbar when group names don't fit to group listing area.

## Actual Behavior
The group area doesn't show horizontal scrollbar and group names are partially hidden (unless you widen the group area enough).

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Operating System: Windows & Linux

**Comment by droidmonkey** [comment]
There is a horizontal scroll bar but it only shows when the panel is minimized significantly. That is because Text Elision is default turned on (...) and a little bug in Qt that doesn't resize the column automatically.

I have turned it off here and will add this to 2.7.10, thank you for the report!

![image](https://github.com/user-attachments/assets/5b463306-3b2e-489b-bf00-2f6abb1d2b2e)
