### ISSUE TITLE
Autotype putting data into wrong application

### ISSUE THREAD

**Issue by HoppyH** [keepassxreboot/keepassxc#11394]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Running multiple (2) monitors, auto type is putting data into wrong application.
This is my first bug report and I am not sure if it's KeepassXC, Plasma or Xwin.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. On primary monitor, open a file in Libreoffice Calc - On secondary monitor open Firefox - on primary monitor open KeepassXC
2. On secondary monitor click in username entry box to place cursor there.
3. On primary monitor right click on the proper entry in KeepassXC, select Perform Auto-Type and select any of the offered choices.
4. The selected username and/or password and/or both will be entered in the Open Libreoffice document.

## Expected Behavior
The data provided by KeepassXC should go into the entry box where the cursor has been placed.

## Actual Behavior
The data provided by KeepassXC is placed in the document on the same monitor as KeepassXC

## Context
I have been using KeepassXC for some time now, and this behavior has just appeared with the latest update from pacman.  I am using the Oxygen halo on my windows to tell which is the current window.  

I have been using the described process for some time now, and it has always worked.

I did notice that if I change the location/monitor of the applications, it works.  In other words, KeepassXC has to be on the same monitor as the application I want it to access even though the halo tells me which is the default window.  This is new to me.

Hope this helps!

[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
> this behavior has just appeared with the latest update from pacman

Woudnt be us then. It's likely a change in how window ordering is handled by KDE. If you want definitive window choice, use the global autotype shortcut. Using entry level autotype relies on the window manager to select the "last used window" properly. 

There may be a KDE option that sets preferred window choice behavior, not sure.

**Comment by Wohntrends-Shop-Strunz** [comment]
Doesn't that just mean KeepassXC is using the wrong "last application" system call? Because using a traditional ALT+TAB results still in the same expected behaviour as before. So there expected behaviour still exists and still is the default action for that keybinding. In case it helps, the shortcut in the export is labled "Walk Through Windows".

**Comment by droidmonkey** [comment]
We don't call "last application" thst doesn't exist. We minimize which brings the next window to the front.

**Comment by Wohntrends-Shop-Strunz** [comment]
So _System Settings > Workspace Appearance and Behavior > Window Behavior > Focus > Multiscreen Behavior_ conflicts with your expected behaviour when minimising. So at least you should check for the flag, since it does potentially write secrets into unintended windows which I consider a possible security issue (when setting is active and multiple screens available). Not sure how that would ideally be implemented, in doubt maybe some warning in the auto type setting window?

**Comment by droidmonkey** [comment]
Use global Auto-Type if you want guaranteed window affinity
