### ISSUE TITLE
Prrogram does not close

### ISSUE THREAD

**Issue by azalea4va** [keepassxreboot/keepassxc#11448]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
On some occasions, the program will not minimize after clicking on the "Close" button.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start program and enter database password
2. Click on Close" button.
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Window minimizes

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Window does not minimize

## Context
[NOTE]: # ( Give us any additional information you may have. )
On Linux Mint (version 22), I autostart KeepassXC on login.  The program is configured with both "Minimize window after unlocking database" and "Minimize instead of closing the app" checked.  But about 50% of the time, the KeepassXC does not minimize after enter the password and unlocking the database.  It also does not minimize after clicking on the window's Close button or clicking on "Close Database" in the Database menu.  It will terminate if the "Quit" option in the database menu.

This erroneous behavior is not consistent.  I have not noticed a pattern as to when it fails to work correctly.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
I have never seen this behavior before. Without additional information, it is impossible to debug, reproduce, and fix. You will need to look through or provide information from X11 or Cinnamon logs. You are also running an outdated version, we are on 2.7.9, but I doubt that would change this situation. 

If solid information can be provided that shows this issue is actually with KeePassXC, then I'll reopen.
