### ISSUE TITLE
Authy TOTP codes don't work.

### ISSUE THREAD

**Issue by Kingdud** [keepassxreboot/keepassxc#11583]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

I am migrating from Windows to Linux. On Windows, I used WinAuth. I made a backup of my data in plaintext, including my secrets. When I import those secrets, and their settings, into KeepassXC, the TOTP codes don't work. I'm, frankly, baffled at what the problem might be. I saw you say "it's either time or the secret". Do you know that winauth encodes its secret in base32 with some sort of salt? I extracted the secret, originally, from the authy desktop app. Though I can't use that anymore.

Specifically what I coped out of my winauth backup was the bit after otpauth://totp/token:token?secret=*copied this*&digits=7&issuer=token&icon=WinAuth&period=10

Things I've tried:
1. I've ensured the clocks on my windows PC, linux PC, phone, and time.is are all in sync, and they are to the second. 
2. Copying the raw TOTP string out of winauth and pasting it into KeepassXC (didn't work)
3. Trying different time steps (20/30 seconds) -- no effect.
4. Writing down the digits from both keepassxc and authy for > 2 minutes to look for overlapping codes; none ever did.
5. Changing generation algorithms from SHA1->256->512
6. Trying to run winauth in wine.

Am I nuts? Am I missing something obvious? Is this some sort of regression? Why does winauth work and keepassxc doesn't?

### Steps to Reproduce

1. Configure TOTP in Keepassxc (Custom settings, paste in secret, 10 second time step, 7 digits)
2. Try to use TOTP code, fail.

### KeePassXC Debug Information

```Text

```

### Operating System

Linux

### Linux Desktop Environment

KDE

### Linux Windowing System

None

**Comment by droidmonkey** [comment]
Unfortunately, there really isn't much we can tell you about this. It is possible that winauth is storing the secret in a format other than Base32, you'll have to use a converter to see if that is true. You said you synced your system time, but it sounded like you did that manually. We absolutely recommend using a time sync service instead. Closing since this isn't a KeePassXC code issue at this time.

`digits=7&issuer=token&icon=WinAuth&period=10`

This indicates your TOTP is 7 digits long and 10 seconds period, you should adjust your settings to match that. 

You can also just create an `otp` advanced attribute and paste the `otpauth://` url directly as-is into that as the value.
