### ISSUE TITLE
Attachments of KeePass not shown in KeePassXC and vice versa

### ISSUE THREAD

**Issue by BsNoSi** [keepassxreboot/keepassxc#11592]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Opening a database created with KeePass (2.5.7.1 → current), its attachments are not displayed (and not accessible) with KeePassXC (2.7.9 → current).

Adding an attachment with KeePassXC and opening the database in KeePass, they are not shown there and vice versa.

Attachments are not lost, but they can only be displayed and accessed with the application that has added them.

Both show only attachments added on their own, which means that database format is incompatible.

### Steps to Reproduce

1. Open KeyDatabase with KeePass (or KeePassXC).
2. Add an attachment to any key.
3. Open key with KeyPassXC (or Keepass)
4. Navigate key and try to access attachment.

### Expected Versus Actual Behavior

Any attachment, regardless which application added it to the database should show up in all applications that use "keepass database format".
Not sure, if it is correct, but I'd say, that KeePass is the leading product for the format, which should be supported by KeePassXC.

### KeePassXC Debug Information

```Text

```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

**Comment by droidmonkey** [comment]
I cannot replicate this. I did note that KeePass 2.57.1 does NOT auto-reload the database when the file is changed, that appears to be a new bug on their end. We do not auto-reload the database if the editing window is open for an entry, that is a known issue and being addressed in the next release.

Otherwise, there is no incompatibility in the formats, tested and worked as expected.
