### ISSUE TITLE
multiple key slots (multiple master passwords)

### ISSUE THREAD

**Issue by adrelanos** [keepassxreboot/keepassxc#1180]
## Expected Behavior

change master password -> advanced -> add another keyslot

Similar to luks, where one can have up to 8 key slots. (Different passwords unlock the master key.)

## Current Behavior

Currently one can have only one master password.

## Context
This would be useful to set up a one password plus yubikey and another password as backup in case the yubikey breaks either due to lost hardware or software bugs.

**Comment by TheZ3ro** [comment]
We already discussed this in #1160 and in #892

**Comment by phoerious** [comment]
See https://keepassxc.org/docs#faq-yubikey-broken-yubikey

**Comment by RootLUG** [comment]
Is it possible to dump something like a "plaintext master key header" that could be used to recover the database?
In case of yubikey I unfortunately doesn't have the HMAC secret and generating a new one isn't an option because it would reset auth on other places where I use it.

If I understand correctly, keepassxc is using all components combined together to create some form of "master key" that is then used for DB decryption. Would it be possible to provide an option to dump this combined master key that could be stored in a secure location (that's up to user how to do it) and allow recovery from it?
