### ISSUE TITLE
Need icon for merge database action

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#122]
## Expected Behavior

Icons should be added for better usability and recognition of actions.

## Current Behavior

No icons are present.

**Comment by wolframroesler** [comment]
With Material Design icons (cf. #475/#4066) we have a plethora to chose from. How about this one:

![Screenshot from 2019-12-27 16-53-13](https://user-images.githubusercontent.com/25565229/71523459-771abd00-28c9-11ea-837c-ca8903a364c6.png)

https://materialdesignicons.com/icon/database-refresh

**Comment by droidmonkey** [comment]
That is more like sync. Is there one with just an incoming arrow? We can use that for the upcoming synchronize feature.

**Comment by wolframroesler** [comment]
You're right, the Auryn arrows are very similar to what Nextcloud displays while syncing.

How about this one:

![Screenshot from 2019-12-27 22-09-40](https://user-images.githubusercontent.com/25565229/71532848-b7903000-28f5-11ea-8d7f-752e0da95b0f.png)

https://materialdesignicons.com/icon/database-import

Alas, nothing with two databases exists yet, but giving the existing icons, creating a new one shouldn't be too difficult for someone familiar with Inkscape (I'm not).

**Comment by droidmonkey** [comment]
That one is nice

**Comment by wolframroesler** [comment]
Too generic IMHO. We have "open database" and "new database" already, "merge databases" should graphically connect with them.

Anyway, make your choice, I'll add it to #4066 and configure "Database -> Merge from database" to use it.

**Comment by droidmonkey** [comment]
Agree, lets use the one you proposed

**Comment by wolframroesler** [comment]
Done, pushed to #4066.

![dbmerge](https://user-images.githubusercontent.com/25565229/71549529-37ce9800-29bf-11ea-9722-00ef1c76bbf0.png)

**Comment by droidmonkey** [comment]
These are very nice!

**Comment by wolframroesler** [comment]
Glad you like them @droidmonkey.

While I was at it, I added another bunch of missing menu icons ("OpenURL" in "Entry", "Sort A-Z/Z-A" in "Group", and almost all in "Help"). Pushed to #4066. We now have icons for all menu items that don't open, or are in, a sub-menu.

![entries](https://user-images.githubusercontent.com/25565229/71549995-31441e80-29c7-11ea-94eb-30ff10e0e150.png)

![groups](https://user-images.githubusercontent.com/25565229/71549996-31441e80-29c7-11ea-8d08-20c067c221ad.png)

![tools](https://user-images.githubusercontent.com/25565229/71550016-6cdee880-29c7-11ea-9918-017d49be194e.png)

![help](https://user-images.githubusercontent.com/25565229/71549997-31441e80-29c7-11ea-8780-803fc187ea5f.png)

**Comment by phoerious** [comment]
Can we find adequate replacements for the entry and group icons as well? That used to be the blocker in my previous attempts at doing this. They are extremely low-resolution and its an enormous amount of work to find alternatives.

BTW with this change we should finally enable pixmap scaling on all platforms.

**Comment by wolframroesler** [comment]
@phoerious That would be great. The default icons for groups/entries (`share/icons/database` in the source code) are ancient, hideous, unintellegible, and 16x16 only, and really should be redesigned. I see some possible issues however:

First, users consider these icons part of their database, and it could be off-putting for them if a new KeePassXC release suddenly made everything look different. Not all of our users are IT experts who are tolerant about such changes.

Second, our redesign could mess up people's use of the icons because the redesign would be based on the "semantic" meaning of the icons, but people may have used them "literally" based on their current graphical appearance. For example, there's the C33_Run.png icon that's supposed to resemble a start flag, however I'm using it for games because it also happens to resemble a chess board. C59_Package_Development.png looks like a hammer and C34_Configure.png looks like a wrench; what would break if we changed them into something completely different, e. g. a box and cogwheel?

Third, people use different KeePass clients across platforms (e. g. KeePassXC on macOS and Strongbox on iOS) and may expect icons to look identical (or at least similar enough be be recognizable) on all of them.

AFAIK all of these clients are open source and under active development, and I suppose their maintainers are as annoyed by the icons as we are. Maybe we can try and find a solution together with the others, so at least we maintain some consistency across clients.

Finally, custom icons (e. g. downloaded favicons) don't look too nice next to icons that follow other styles like Material Design. Have a look at this screenshot of KeePassium, a KeePass client for iOS that already uses redesigned default icons:

<img width="320" alt="2019-12-29 12-08-33-1" src="https://user-images.githubusercontent.com/25565229/71556296-f1b51b00-2a36-11ea-890d-6a3d47f9bb10.png">

It's not too bad in this case because this database consistently uses default icons for groups and favicons for entries, but it looks totally messy if they are used in a mix.

For these reasons, I think that redesigning the default icons should go into an issue of its own where we can discuss the solution in detail. IMHO it's independent of the ongoing redesign of the application icons (#475, #4066, #122) which is entirely a question of our own UI design.

If you agree, I'll create a new issue for the default icon redesign and jot down some ideas there.

**Comment by wolframroesler** [comment]
@phoerious 

> BTW with this change we should finally enable pixmap scaling on all platforms.

For clarification, does "this change" refer to the existing one (SVG instead of PNG for the application icons as of #475/#4066) or the one you proposed (redesigning the default group/entry icons)?

Also, could you elaborate on how to enable pixmap scaling?

**Comment by droidmonkey** [comment]
We already did that scaling fix in the pr

**Comment by phoerious** [comment]
KeePass2Android also uses material icons instead of Nuvola. I for myself completely stopped using these icons for entries (except the generic key icon for if there is no favicon) and I am extremely annoyed by the fact that there are so many. We could easily downscale to let's say a handful and 90% of our users would probably still be fine.

**Comment by droidmonkey** [comment]
Let's make a new issue for this because it does need to be addressed, ideally in 2.6.0

**Comment by phoerious** [comment]
In the worst case, we need to pull a higher-res copy of Nuvola, but I am all for replacing it with something that actually looks good.

**Comment by wolframroesler** [comment]
After some rework, here's what the "merge database" icon and the others in the Database menu currently look like (cf. #475/#4066 ):

![Screenshot from 2020-01-10 22 48 04](https://user-images.githubusercontent.com/25565229/72188794-7f134a80-33fb-11ea-9719-9a1ca72a7477.png)

**Comment by droidmonkey** [comment]
I like that a lot

**Comment by wolframroesler** [comment]
Since #4066 has been merged, I think this issue can be closed.
