### ISSUE TITLE
Windows font: Can't distinguish "1" (one) and "l" (lower-case L)

### ISSUE THREAD

**Issue by ruslo** [keepassxreboot/keepassxc#1226]
There is absolutely no visual difference between `1` and `l` on Windows.

## Expected Behavior

**KeePassXC** on Linux screenshot:
![linux](https://user-images.githubusercontent.com/4346993/33235507-90fd77c6-d24a-11e7-8c53-72d937a49976.png)

**KeePassX** on Windows:
![windows-old](https://user-images.githubusercontent.com/4346993/33235514-bcb3bb78-d24a-11e7-8c2e-16a916de3fd5.png)

## Current Behavior

**KeePassXC** on Windows:
![windows-new](https://user-images.githubusercontent.com/4346993/33235549-4648138e-d24b-11e7-8d56-07c1ff6910a8.png)

## Possible Solution

Probably change default font?

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
That's a problem of the shitty default monospace font Windows provides. Other platforms have less problems with that. Using a proportional front, however, is not a solution, since that would produce even more hard-to-distinguish characters. Using another monospace font if one is installed could be a solution.

**Comment by phoerious** [comment]
Fix has been merged into 2.2.3.
