### ISSUE TITLE
The input method intercepts auto-input

### ISSUE THREAD

**Issue by amitbha** [keepassxreboot/keepassxc#1237]
When the chinese input method is active, the automatic input function does not work normal.
The password auto entered will be displayed as chinese characters.

## Expected Behavior
The automatic input function works as excepted.

## Current Behavior
Can't auto input when the chinese input method is active

## Possible Solution
inactive the input method before auto-input

## Debug Info
KeePassXC - 2.2.2
Operating system: Ubuntu 17.10
Input software：ibus
CPU architecture: x64
Kernel: 4.13.0

**Comment by frostasm** [comment]
Related issues #324 #474 #596

**Comment by peremen** [comment]
While from the user's point of view they are the same, but technically this bug is different from the related issues. On Linux input methods are separate from the xkb layouts, which are the main cause of mentioned bugs here. To resolve this bug, just interacting with xkb is not enough afaik, and KeePassXC needs to call the input method itself. Here we need to take specific approach for every IMs.
