### ISSUE TITLE
Add more color neutral icon set for KDE Plasma 5

### ISSUE THREAD

**Issue by shmerl** [keepassxreboot/keepassxc#1291]
KDE Plasma 5 prefers color neutral icons (almost monochrome style), with color added only for some specific attention emphasis. It would be nice for keepassxc to have an option to use such icons for better KDE integration.

For instance, when the DB is locked, it shouldn't use red color in the notification area (system tray) icon, since in KDE that usually indicates that user should pay special attention to the notification area, which isn't the case here.

**Comment by shmerl** [comment]
Looks like it can be related to #756 and #475.

**Comment by phoerious** [comment]
Are you only referring to the tray icon? The in-app icons are original Breeze icons if the Breeze theme is installed.

**Comment by shmerl** [comment]
Yes, I refer to the notification area icon (system tray). However, the toolbar icons are a bit inconsistent color wise as well. Here how it looks to me:
![toolbar](https://user-images.githubusercontent.com/310927/34055251-5eaf0c4c-e19c-11e7-8f74-5329fa3c7948.png)

**Comment by shmerl** [comment]
In the notification area, it looks like this:

Unlocked:
![tray1](https://user-images.githubusercontent.com/310927/34055324-a67209a8-e19c-11e7-871e-bc592a5059a8.png)

Locked:
![tray2](https://user-images.githubusercontent.com/310927/34055333-b02a2098-e19c-11e7-8812-4a90b2c1acce.png)

**Comment by ArchangeGabriel** [comment]
That’s because some are not part of Breeze. There is also issues with HiDPI support.
![capture du 2017-12-15 19-37-28](https://user-images.githubusercontent.com/490531/34055425-6a674832-e1cf-11e7-8e63-efdbe282a7c6.png)

**Comment by franksouza183** [comment]
I did not tested, but I believe it's because this:

`[m_ui->actionEntryNew->setIcon(filePath()->icon("actions", "entry-new", false));](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/MainWindow.cpp#LC269)`

See some previous lines for some action that has its icon working icon theme: `m_ui->actionDatabaseNew->setIcon(filePath()->icon("actions", "document-new"));`

The `false` param is probably "disallowing" fetch the icon from icon theme.

**Comment by ArchangeGabriel** [comment]
@franksouza183 Yes, this is what #756 is about (and it is also expected to solve #548).

**Comment by franksouza183** [comment]
Oh, sorry, I didn't see that. Thanks

**Comment by noahadvs** [comment]
I'm adding more KeepassXC compatible icons to the KDE Breeze icon theme. I'll let you guys know when I'm finished so you can close this issue.

**Comment by phoerious** [comment]
Cool. I have been working on a new icon theme as well, but haven't got very far. Perhaps we can just make Breeze our new default if we can fill in the missing icons. I especially dislike the die for the password generator. It's not clear what it means and the Breeze icon does not even look like a die at smaller resolutions.

**Comment by noahadvs** [comment]
> Cool. I have been working on a new icon theme as well, but haven't got very far.

I'd like to see what you've got if you don't mind. If you want to make your own changes to breeze-icons, I'd love to help you out. Or I could include them in my own commit if that's alright with you.

> Perhaps we can just make Breeze our new default if we can fill in the missing icons.

That could work fine. I could make additional icons you might want to achieve a consistent looking icon style. With the current version of Breeze, you get a mix of color and monochrome icons in the sidebar preference categories.

![screenshot_20190221_030608](https://user-images.githubusercontent.com/3580471/53153192-a5cb5700-3585-11e9-8c01-f389cdf5e9e3.png)


> I especially dislike the die for the password generator. It's not clear what it means and the Breeze icon does not even look like a die at smaller resolutions.

Funny thing, I actually made a monochrome pair of dice for the password generator so that Breeze wouldn't be too different from the official icons for KeepassXC. I kind of agree, but I don't have better ideas right now.

**Comment by phoerious** [comment]
I played around with a completely different icon set and it wasn't monochrome, although I think that's the way to go, particularly with dark themes.

I think coloured icons for the sidebar are okay as long as they are consistently coloured. The toolbar icons should be monochrome, I think. We also "misuse" certain standard icon names, because a more or less suitable icon exists on some Linux distributions. If we have a proper icon for that, we can also give it a proper name and not be surprised what certain platforms make of it. For instance, the lock icon is `document-encrypt` which really should be something like `lock` to avoid someone making it an icon that has a document but no lock.

**Comment by noahadvs** [comment]
If you are going to use Breeze icons for KeepassXC, I should contribute the icons directly to KeepassXC, right? Of course, any that are appropriate for Breeze icons should also go upstream.

**Comment by phoerious** [comment]
Yes.

**Comment by noahadvs** [comment]
If you use monochrome icons, is there a way for KeepassXC to change the color of the icons based on the user's theme? In KDE Plasma, Breeze icons are able to change their colors based on the user's color scheme in Qt applications. I do not know if other desktop environments are able to do something similar. If they can't, then users of other DEs who use dark themes could end up with difficult to read icons.

**Comment by phoerious** [comment]
I don't think there is a good way to do that, but we can try to make it work somehow.

**Comment by noahadvs** [comment]
> I don't think there is a good way to do that, but we can try to make it work somehow.

I think there is, because KDE applications can do that as well, but it involves adding a bunch of KDE Frameworks dependencies and you might not want that.

**Comment by phoerious** [comment]
We do not depend on Kf5 and do not plan to. KColorScheme is not a plain Qt feature.

**Comment by noahadvs** [comment]
You're probably going to have to add some way to manually switch between light and dark themes within KeepassXC then. I can add a set of light and dark monochrome icons. This is still significantly more complicated than just using color icons for everything like you do now, except that Breeze icons are easier to make than Oxygen icons.
