### ISSUE TITLE
Refactor key file generation to produce random byte stream instead of XML

### ISSUE THREAD

**Issue by Bleuzen** [keepassxreboot/keepassxc#1325]
Hi,
I created a key file within KeePassXC to better protect my database. But this keyfile is only 162 B big, so really small.
Now we live in a time where we have more than enough space. The free space should not be the problem.

So can you make the key files, let's say for example, about 10 times as long as they are now? Would this be ok or is there a reason to keep them so small these days?
(Maybe performance when opening databases?)

**Comment by phoerious** [comment]
162 completely random bytes should be plenty. That's 2^1296 possible combinations (we can assume, the universe consists of about 10^82 atoms btw). There is no point in creating longer key files. Especially not since the contents of the file will be hashed to a 256bit hash anyway (yes, that's 32 byte!) and then transformed together with other credentials to produce a 256bit AES key.

**Comment by Bleuzen** [comment]
Ok, thanks for the reply. But I'm still not done, sorry ...

Now I opened the key file in a text editor and found out that inside the key file is a lot xml metadata. I guess this is not used to encrypt. The key itself is only 45 bytes long and is bas64 encoded. If we decode it, it is a 16 chars long password.

I'm not sure if this is really enough these days. Yes, I know, it's hashed, but still. Should we use a only 16 chars password to encrypt a whole password database?
If we use a key file and a password, this may be ok. But maybe there are also users that only use a keyfile? For them, the key could be longer.

Well, I know, maybe I'm a bit paranoid, I'm sorry.
Anyway, this was just an idea to improve this software. But you are the developer, you have to decide ;)

**Comment by phoerious** [comment]
It''s not a 16 character password, it's 16 totally random bytes, but I agree, that's not too much (65k combinations can easily bruteforced offline). To be honest, this whole key file generation part is legacy code and I for myself have never used this function. I don't know why it contains XML code at all. I guess there used to be a long forgotten reason for it.
The keyfile isn't parsed in any way. It's just treated as a byte stream, so you can easily create your own massive 2048 Byte key file like this:

    dd if=/dev/urandom of=keyfile.key bs=2048 count=1

I'll reopen this as a reminder to refactor the key file generation code.

**Comment by phoerious** [comment]
Oh, I see the reason. It's to be compatible with KeePass2 key files (or key file generation). KeePassXC tries to load an XML file in KeePass2 format and if that fails, it uses the file verbatim as a byte stream (which is IMHO the preferred option). I tested key file generation with KeePass2 and it produces the same format and the same key length. KeePass2 puts a lot of effort into letting the user produce enough entropy by bothering them to move their mouse inside for a minute inside a field, but then uses all that entropy only to generate a shitty 16-byte random string.

KeePass2 seems to be able to read both formats as well: XML and binary. It also seems to be okay to use a longer string in XML format, but since there is no point in wrapping our precious random bytes in XML, I would suggest we just generate a random byte stream.

**Comment by droidmonkey** [comment]
Concur with this, we should not offer to generate the xml version. The code needs to be properly annotated with comments to identify the "legacy support" portions.

**Comment by TheZ3ro** [comment]
> But maybe there are also users that only use a keyfile?

Just a note: Please, don't use only keyfile to encrypt your database

**Comment by phoerious** [comment]
I'll prepare a patch later this evening.

**Comment by phoerious** [comment]
I submitted a patch for review, which now generates a 128-byte binary file instead of an XML file.
