### ISSUE TITLE
Access and modify libsecret keyrings from KPXC interface

### ISSUE THREAD

**Issue by david-libremone** [keepassxreboot/keepassxc#1402]
**User story:** I am a GNU/Linux user with a desktop keyring. I want to access my keyring with KPXC so that I have a single interface for all my passwords/secrets.

## Possible Solution

* GNU/Linux keyrings are accessible with libsecret
* Make KPXC-libsecret interface
* This doesn't account for other secrets often managed by the desktop, SSH keys, GPG keys, etc

**Comment by intika** [comment]
>  Make KPXC-libsecret interface

Is not this already the case ? KPXC can replace gnome keyring so other then kwallet you can use keepassxc as a central locations for all passwords

**Comment by droidmonkey** [comment]
Yes this is true, closing this request

**Comment by michaelk83** [comment]
FYI, the intention of this request was for KeePassXC to act as a *client* for *other* Secret Service providers, similar to Seahorse (use case 1 from https://github.com/keepassxreboot/keepassxc/issues/440#issuecomment-357657695), so it's not actually implemented. What was implemented is for KeePassXC to act as a *"server"* of Secret Service (use case 2).

The user story was poorly phrased. It should be something like: "I want to use the KeePassXC interface to view and manage passwords that are stored in a 3rd party Secret Service keyring." Though I don't know if there's any interest to implement this.

**Comment by michaelk83** [comment]
I can think of a couple reasons to implement such client behavior in KeePassXC:

1. It would allow users the freedom of choice to use any of the other Secret Service providers, while still being able to manage all of their passwords through the same GUI. Other than Gnome keyring and KWallet, there is currently at least [mdellweg/pass_secret_service](https://github.com/mdellweg/pass_secret_service) for the `pass` backend, and [mvdan/bitw](https://github.com/mvdan/bitw) for BitWarden (though granted, the only mature provider at the moment, other than KeePassXC, is Gnome keyring). There may be more Secret Service providers in the future.

    Currently, I think the only GUI for 3rd party Secret Service keyrings is Seahorse, which is a Gnome application. So this can be especially useful for KDE users, who may prefer to avoid Seahorse.

2. The 2nd reason is this would provide a vector for users to migrate their Secret Service passwords from the 3rd party keyring into KeePassXC: enable the client side integration &rarr; use the KeePassXC GUI to copy the passwords from the 3rd party keyring to a `.kdbx` database &rarr; disable the client side integration, and enable server side integration using the copied passwords.

    As a bonus, using the KeePassXC GUI to manage 3rd party Secret Service passwords may encourage such users to perform that migration, and switch fully to KeePassXC.

However, I realize that there's little to no benefit to KeePassXC itself, so it's probably not worth the effort.

**Comment by droidmonkey** [comment]
Acting as a client is definitely not worth the effort. You can export your credentials and import them using CSV if you want to migrate.

**Comment by RJVB** [comment]
> However, I realize that there's little to no benefit to KeePassXC itself, so it's probably not worth the effort.

An import feature (aka plugin) can be a life-saving benefit for _users_, and thus to the program that provides it. If excursions through CSV can be avoided that is always better, in my experience.

Disclaimer: I have minimal experience with the Gnome KeyRing and the kind of information it can store, but certain of its equivalents allow to store much more than username+password credentials. Such stores can become treasure troves of secure information over time, the kind you don't want to have to "just recreate" when migrating to a different platform. KPXC being cross-platform and among the most versatile in terms of what the kind of information it can store securily, platform-specific importers do definitely have a place in its code (since importer plugin hooks are not provided).

**Comment by michaelk83** [comment]
Pretty much anything that is accessed through the Secret Service API is automatically generated by the client apps (with some input from the user). But I agree that it'd be easier to migrate such data using a tool, rather than recreating it.

**Comment by RJVB** [comment]
>But I agree that it'd be easier to migrate such data using a tool, rather than recreating it.

A quick test of https://github.com/mnagel/gnome-keyring-dumper confirms that: there are a number of entries even in my tiny store that must be quite annoying to recreate (who likes typing long wifi passwords for instance!)

That dumper works fine and as I thought you just have to enter the passwords for the collections/stores you have defined (no memory how I've ended up with a 2nd one; it seems I must have tried to set up a secure note store like I have in one of my Mac keychains). Pity that it doesn't generate a format that can be imported into KPXC, but I suppose that it shouldn't be too hard to modify it to that effect.

**Comment by michaelk83** [comment]
You'd need to make sure to duplicate all the attributes correctly. AFAICT, that dumper only prints out the username and password, and ignores everything else. You can take a look at some entries in your exposed group to see what they look like in KeePassXC, and create your own test entries with [`secret-tool`](https://manpages.ubuntu.com/manpages/focal/man1/secret-tool.1.html).

But since you can't run KPXC Secret Service and Gnome keyring daemon at the same time, you'll have to export a format that KPXC can import, and which can express all of the necessary parts of the data. KPXC has also a CLI, but unfortunately it doesn't support adding attributes yet (#9212). There is also the interface used by the browser extension. I'm not sure what that one can do.

**Comment by michaelk83** [comment]
Generally speaking, if you want to try writing an exporter tool in python, you have two options that I know of: either [SecretStorage](https://github.com/mitya57/secretstorage), or the python bindings for [libsecret](https://developer-old.gnome.org/libsecret/0.18/). The dumper you linked to seems to be using the former.
