### ISSUE TITLE
Allow ALT as the accelerator key

### ISSUE THREAD

**Issue by geertj** [keepassxreboot/keepassxc#1432]
Trying to keep my sanity as a dual Linux/Mac user.

Mac uses Command as the standard accelerator key, while Linux  uses Ctrl. It would be nice if a different accelerator key could be used. In my case, I'd map it to Alt on Linux, because Alt is at the same place on my keyboard as the Command key on my Mac. My muscle memory would appreciate this.

So, with this configuration option, Alt-C would copy a password, for example.

I know that it's possible to map the physical Alt key to the Ctrl key code using XKB on Linux. But this is a system wide setting, and means that Ctrl-C now becomes Atl-C everywhere, which again makes for different behaviour on Mac vs Linux.

**Comment by phoerious** [comment]
I don't think we can or want to fix this. Remapping the Ctrl key is responsibility of your operating system, not an individual application. It's way too complicated for us to do that, because we would need to add additional logic everywhere we use key modifiers and we'd also need to remap default accelerator keys defined by the widget toolkit.

**Comment by geertj** [comment]
@phoerious fair enough, it may be too complicated. However let me add some context that what I'm trying to achieve isn't possible at the OS level. Neither Mac OS or Linux allow you to remap accelerator keys on a per-application basis. And I can't map it globally, as in my terminal I still want CTRL to have its original location and behavior (e.g. CTRL-C emits an interrupt character).

It's not uncommon that applications allow you to customize hotkeys, or at least select a different accelerator key. GNOME Terminal allows the former, while Firefox allows the latter (via ui.key.accelKey).

**Comment by phoerious** [comment]
Still pretty much wontfix. It's not responsibility of the application to remap modifier keys, unless there is a very good reason for it. I also don't see how that would improve usability. All it does is create confusion, because modifier keys work differently from the rest of the desktop. Non-Mac keyboards simply have one modifier key less. You may like it or not, but that's how it's always been.
