### ISSUE TITLE
Use libssh for public key handling

### ISSUE THREAD

**Issue by cryptomilk** [keepassxreboot/keepassxc#1471]
Why don't you use https://libssh.org for handling public keys?

http://api.libssh.org/master/group__libssh__pki.html

**Comment by phoerious** [comment]
We do not need any real SSH stuff. All we need is some code to read the key files. Adding a full SSH library only for that seems to be a bit excessive. We were thinking about OpenSSH, because it brings crypto primitives and we could replace libgcrypt, but it's licensing is incompatible with the GPL.

**Comment by cryptomilk** [comment]
Well you implement PKI to handle ssh keys. That's what libssh offers. It is a small library doing that for you :-)

**Comment by phoerious** [comment]
It's really not that small. It's 3MB of source code vs. our 100kB.

**Comment by hifi** [comment]
It would be interesting to have these in libssh so that it would help remove a lot of code and also provide new functionality:

- Agent client, it's a hard requirement
- New feature: Agent server so we could embed an agent without writing one
  - Server especially useful on Windows so you don't need Pageant
- Full support for all mainstream private key types and encryption
  - New feature: PuTTY keys
- Loading new OpenSSH keys without decrypting them
  - We currently support this and show the fingerprint and public portion without decrypting
  - Maybe not *that* important but it would be nice to not lose functionality

These were just the first things that I thought of if replacing the existing code. It would clean up all the KDF code that I had to pull from OpenSSH and the simplistic ASN.1 parser that barely reads RSA and DSA keys and naturally the OpenSSH key parser.

Also, libssh is not self contained and depends on OpenSSL for crypto. That would mean it would pull in yet another crypto library indirectly. It would be less of an issue if KeePassXC used OpenSSL but it doesn't. Currently the implementation that is in does not depend on any new dependency and compared to the amount of code (~600 according to cloc for key management) it's not that bad.

As of now, I see it missing too much of the required functionality to replace enough of the existing code and not having anything new on top of what we already have to have enough value.

**Comment by TheZ3ro** [comment]
I agree that we should use a third party library for OpenSSH key. 
Less crypto-related code to maintain ourselves (very prone to errors) and use a well-tested library instead.

But sadly libssh isn't included in msys2 repository. On windows this can be a little trouble.
Maybe we can take a look at (libssh2)[https://github.com/Alexpux/MSYS2-packages/tree/master/libssh2]?

**Comment by phoerious** [comment]
libssh is in the msys repository.

But we don't really have any crypto code (except bcrypt kdf, which was copied from OpenBSD). The needed crypto primitives are implemented by libgcrypt. We only implement the file format and agent code.

libssh2 is even less suited for put purposes, as it only supports very few key formats.

**Comment by cryptomilk** [comment]
- libssh is a ssh-agent client if you do ssh-publickey auth, there was no need to provide and API for other things till now.
- If possible you should use ssh-agent from OpenSSH and not implement your own. The ssh-agent of OpenSSH is very small, it just implements a small feature set and normally no features are added (there are exceptions if the code is very simple). You don't want to have a security issue in an agent. So the advice is don't implement it on your own. Use the one from OpenSSH.

**Comment by phoerious** [comment]
We don't implement a custom agent. We only implement the protocol to feed keys into the agent.

**Comment by yan12125** [comment]
I have no preference about libssh or no libssh. I just want to share some technical details.

> On windows this can be a little trouble. Maybe we can take a look at libssh2?

A major issue is that libssh2 does not support ED25519 keys (for now): https://github.com/libssh2/libssh2/issues/39

> Also, libssh is not self contained and depends on OpenSSL for crypto

libssh can use either openssl, libgcrypt or mbedTLS as a backend. For example, the [Arch Linux package](https://www.archlinux.org/packages/extra/x86_64/libssh/) uses libgcrypt.

**Comment by yan12125** [comment]
Hmm, looks like libssh does not implement SSH_AGENTC_ADD_IDENTITY. As hifi said:

> Agent client, it's a hard requirement

libssh is not applicable for keepassxc.

**Comment by hifi** [comment]
> libssh can use either openssl, libgcrypt or mbedTLS as a backend. For example, the Arch Linux package uses libgcrypt.

Well that helps a little if it had all the other features KeePassXC would need.
