### ISSUE TITLE
Beta UI issues

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#1510]
This is a small collection of minor UI bugs in the 2.3 beta version that need solving before the final release.

- Restrict maximum length of preview panel header
- Reduce unnecessary white space on the preview panel (and perhaps automatically resize to minimum?)
- "Entry successfully updated" often gets discarded instantly
- Paper clip not shown on all systems (#1505)

## Debug Info

KeePassXC - Version 2.3.0-snapshot
Build Type: Snapshot
Revision: 10bd73c

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-31-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by closingin** [comment]
Some issues I found too :

* In the "General" settings, if there is a scrollbar on the "Basic Settings" tab, the same one with the same height will also be visible on the "Auto-Type" tab, even if not needed. I assume the same behavior occurs for other settings.
* (minor bug) On the "Legacy Browser Integration" settings, an x scrollbar appears instead of correctly resizing the "Length" input of the "Password Generator" tab

**Comment by droidmonkey** [comment]
I have a fix for the paperclip

**Comment by phoerious** [comment]
@closingin The first one needs a bit of extra coding for handling size policies. By default, the QTabWidget has the size of the biggest child.

The second issue only occurs on the last few pixels and we generally do not fix anything for KeePassHTTP anymore if it's not a major (security) issue.

I don't think it's really worth putting effort into either issue.
