### ISSUE TITLE
Minimize Window at Application Startup

### ISSUE THREAD

**Issue by stef204** [keepassxreboot/keepassxc#155]
## Expected Behavior

When starting up, the initial login window should popup so one can enter the password to unlock the database; and once one hits <enter> window should minimize to tray (for those users checking the "Minimize Window at Application Startup" box. 

_Its predecessor, keepassx-http USED to behave as such, before it was merged into keepassxc._

## Current Behavior

Currently, the app just minimizes to tray with database locked, upon startup.  It does not seem useful to have the app start this way as one then has to go to systray, maximize window, enter password, and minimize window to tray again.  Just too many gestures, clicks, etc.

I would suggest integrating the minimize code base from keepassx-http which behaved "properly"--according to me anyway.  Possibly other users have a different opinion.
## Steps to Reproduce (for bugs)

1. Check box "Minimize Window at Application Startup".
2. Exit App.
3. Launch App.
4. Window minimizes to tray without giving user a chance to unlock database first.

## Your Environment

* KeePassXR version/commit used: 
* Qt version (e.g. Qt 5.3):  5.7
* Compiler (e.g. Clang++3.6.0): 3.7.1
* Operating System and version:  Linux 4.8+

**Comment by TheZ3ro** [comment]
There are various version of keepassx-http, can you point out witch integrates this feature? Thanks

**Comment by stef204** [comment]
I inadvertently deleted the directory which contained the version I was using, including the compiled binary (which I had uninstalled to try this version.)

However, I think it was this one:
[https://github.com/Ivan0xFF/keepassx](url)

**Comment by phoerious** [comment]
I'm sorry, but this looks like a WONTFIX for me. The behavior you want is a bug in older versions of KeePassX and several forks based on KeePassX. It was described in #105 and fixed a while ago in KeePassXC. "Minimize on Startup" means "Minimize on Startup". What you want contradicts with what that option is supposed to do.

When you want to unlock your database after starting the app, simply disable that option. Also if you want to insert a password somewhere you can always use autotype which asks you to unlock anyways, no matter if the application is minimized or not.

**Comment by stef204** [comment]
@phoerious 
With respect, the behavior is not a bug at all--but a feature.
Let me try the Auto-Type way you described.  It might just do the job for me.  Will post back.

**Comment by phoerious** [comment]
It is a bug. When I want KeePassXC to start minimized, I expect it do start minimized. The fact that it didn't do that annoyed the crap out of me. Even more annoying was that even though it didn't minimize itself right away, it did so every time once I unlocked it, because then I actually wanted to select an entry in the database, but the window was just gone.

I generally don't see why you would want to unlock your database only to minimize the window right after. Either you want to start the program without getting in your way (then it also shouldn't ask you to unlock) or you want to unlock right away, but then you probably also want to select a password, in which case it wouldn't make any sense to automatically minimize the window after unlocking.

And as I said, autotype also works when the database is locked. To enter a password, simply hit the autotype shortcut, an unlock dialog comes up and then your password is entered. No way to restore the window first.

**Comment by stef204** [comment]
@TheZ3ro 
I finally found the version which included the code you mentioned in your comment above:

[https://github.com/keepassxreboot/keepassxc#commit=cbb1269](url)

So I am sure you guys are familiar with it.

With respect, this is a much better/more useful behavior:  user launches application, it opens and lets user unlock db, and minimizes to tray.  All automagically (except for password input obviously.) 

Again, with respect to whomever has a different opinion, this is a feature, not a bug and did not need to be fixed.  It is a useful feature, reducing number of keystrokes, interaction, etc.  It should at least be configurable (although I do realize there are many more urgent features which need attention.)

**Comment by phoerious** [comment]
Sorry, but I still don't see how your behavior would be useful or couldn't be achieved using autotype (you can use it simply to unlock even if you don't have a window selected which matches an autotype rule).Future versions will also support more command line options which may also be interesting for you (see #99).The old behavior was removed because it didn't do what the feature suggested and was therefore a bug. What you want can basically be achieved using autotype, but the reverse isn't true. So sorry, but this has somehow turned into a political question now and we will not retore the old behavior.

**Comment by stef204** [comment]
Understood.  I think that generally these types of issues are best resolved by surveying a significant enough sample of users.  Probably not feasible in this case; and certainly not a priority.  I'll either go back to version I posted above for now, or think about creating my own patch to substitute the relevant part of the code (not sure how much work would be involved). Thanks for replying, in any event.

**Comment by TheZ3ro** [comment]
> With respect, this is a much better/more useful behavior: user launches application, it opens and lets user unlock db, and minimizes to tray. All automagically (except for password input obviously.)

I think you leave your minimized database unlocked. (note that this is not very secure)

Your workflow is a very edgy and particular one.

What's the problem with:
- Opening KeePassXC
- Unlocking the db
- Manually minimize the window

Anyway if more users will require this feature back *maybe* we can consider to add an option in the settings

**Comment by stef204** [comment]
@TheZ3ro 
I use the Lock Database after Inactivity of "x" feature, so db gets locked periodically.
Understood re. the optional feature if requested by enough users.
Let's close this. Thanks.
