### ISSUE TITLE
avast! blocks keepassxc when cybercapture is on

### ISSUE THREAD

**Issue by Jon-guy30** [keepassxreboot/keepassxc#1550]
Hi all. Avast lately has been a bit bit more sensitive. I tried to upgrade to keepassxc 2.3.0 from 2.2.4 and avast blocks it. I've always been able to install previous versions without doing anything special, but now cybercapture decides to "nope, can't do this, sorry!" and then access is denied. I can't continue the install process even if I choose "I trust this file" in the pop-up. What can I do to fix this? I can probably temporarily turn off cybercapture setting, but I really think this should be fixed. This is probably an avast thing and avast should fix it, but I'm letting you know anyway.

![avast blocks keepassxc](https://user-images.githubusercontent.com/10241225/36779495-163ea45c-1c68-11e8-99a9-033235b5f2af.PNG)

![more details](https://user-images.githubusercontent.com/10241225/36779503-1f321e18-1c68-11e8-9d8b-90e3c25162ee.PNG)

![what gives](https://user-images.githubusercontent.com/10241225/36779507-22f6f226-1c68-11e8-837c-dc29db1047f0.PNG)

Rough translation of the error: Could not access the current device, path or file. You probably don't have the right privileges to access the object.

I'm using Windows 8.1 with latest updates.

EDIT: My bad. I had a setting turned on in cybercapture to always block files. I changed it to "allow me to decide". Now I know why it was blocked. But when I ran the file it scanned it. Probably still thinks it's malware or something. I've never had this happen before. But avast still shouldn't block legit files even if block by default is chosen.

**Comment by phoerious** [comment]
Congratulations, you just experienced a live demonstration of the uselessness of anti virus software.
We used to have these problems with Symantec in the early days of KeePassXC and always had to submit our installer for whitelisting. We stopped doing that after a while, because it's a pain in the ass and the problem seemed to have gone away.

We also started signing our installer with an expensive certificate we acquired from Comodo, . That esn't guarantee that an installer doesn't contain malware, but at least verifies it's integrity and provides publisher information, which should provide a certain level of trust.

The fact that Avast seems to think our new release is malware nonetheless, is something we really can't do anything about, at all. It's very common for anti virus software to flag self-extracting installers. Probably more common than to detect actual malware.

**Comment by Jon-guy30** [comment]
Thanks for the comment. So it's been a problem before, huh. Thankfully I managed to resolve it, this thread could be useful to someone else having the same problem. There was another file I had avast thought was malware, but it didn't block it. But this one avast completely blocked. Probably because it's a brand new file, I don't know.

I understand why you don't want to submit files anymore, too many AVs now have a "cloud blacklist" feature, and sometimes with many false positives.

**Comment by phoerious** [comment]
Funnily, VirusTotal reports no complaint by Avast: https://www.virustotal.com/#/file/8daa0c73b362d1c9824031bc92a74591881a5f89f51a542563d500bc7f6071a0/detection

**Comment by droidmonkey** [comment]
ROFL! "We are currently questioning the file, and it's beginning to crack"

**Comment by phoerious** [comment]
I resisted the temptation to comment on that...

**Comment by Jon-guy30** [comment]
So I got the message from them just a moment ago. Hopefully now it won't alert others who are going to install keepassxc on their computers and block access to it. 

![xd](https://user-images.githubusercontent.com/10241225/36786751-708ce0d8-1c7f-11e8-8f9d-20e9229e2b67.PNG)

It's all good now.

**Comment by phoerious** [comment]
"We can protect you...."

No further questions, your honor.
