### ISSUE TITLE
Werror CMakeLists flag blocks compilation

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#1558]
GCC 8 is not able to finish compilation when `-Werror` flag is present in CMakeLists.txt
[build log of Fedora 28 compilation](https://kojipkgs.fedoraproject.org//work/tasks/7048/25367048/build.log)
[Full logs list](https://koji.fedoraproject.org/koji/taskinfo?taskID=25367048)

Note: compilation has been runned with flags
```
    -DWITH_TESTS=OFF \
    -DWITH_XC_HTTP=ON \
    -DWITH_XC_AUTOTYPE=ON \
    -DWITH_XC_YUBIKEY=ON \
    -DCMAKE_BUILD_TYPE=Release
```

**Comment by TheZ3ro** [comment]
Note: If you are planning to enable all the XC feature please use `-DWITH_XC_ALL=ON` instead of single switch.

`WITH_XC_ALL` includes:
* Auto-Type `WITH_XC_AUTOTYPE` "Automatic password typing"
* Networking `WITH_XC_NETWORKING` "Compile KeePassXC with network access code (e.g. for downloading website icons)"
* KeePassXC-Browser `WITH_XC_BROWSER` "Browser integration with KeePassXC-Browser"
* KeePassHTTP `WITH_XC_HTTP` "Browser integration compatible with ChromeIPass and PassIFox (deprecated, implies Networking)"
* SSHAgent `WITH_XC_SSHAGENT` "SSH agent integration compatible with KeeAgent"
* YubiKey `WITH_XC_YUBIKEY` "YubiKey HMAC-SHA1 challenge-response"
