### ISSUE TITLE
Provide Better Documentation for Steam OTP Use

### ISSUE THREAD

**Issue by JoshuaPettus** [keepassxreboot/keepassxc#1615]
I fully expect that this is user error but I can't seem to find any documentation on how to get this working in KeePassXC though I see the option in the Setup otp menu.
  I followed the directions 
here ->  https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication
 to get the secret key for the the steam authenticator using the desktop authenticator.  The value the guide suggests fails in keypass, and  I have tried every value I could think, including the oath token.  None of them produce a code that lines up with the Desktop Authenticator.  Is there some other trick to this I'm missing?

Thank-you!

**Comment by C0rn3j** [comment]
Same issue here. Tried to copy shared_secret from WinAuth (which easily shows it) but no dice.

Running Arch Linux - 
```
[0] % pacman -Q keepassxc
keepassxc 2.3.0-1
```

**Comment by Generator** [comment]
I've obtained the [secret key from Steam Android app](https://github.com/victor-rds/KeeTrayTOTP/blob/master/README.md#obtaining-totp-secret-from-a-rooted-android-phone-by-darkdaskin), and it's working without issues.  

There's [steamguard-cli](https://github.com/dyc3/steamguard-cli) an alternative to Windows Steam Desktop Authenticator and mobile app.

**Comment by C0rn3j** [comment]
>otpauth:\/\/totp\/Steam:[your Steam login]?secret=[TOTP secret]&issuer=Steam

Ok so I wasn't actually copying the TOTP secret, it now works, thanks a lot.

**Comment by JoshuaPettus** [comment]
This may not be a bug, but it's poorly documented.  I copied the "TOTP secret" from
    otpauth://totp/Steam:[your Steam login]?secret=[TOTP secret]&issuer=Steam

It generates codes, but they are not what, nor in sync with what Steam Authenticator is  Please don't close.

**Comment by C0rn3j** [comment]
>nor in sync with what Steam Authenticator

Is your system clock across the two devices the same?

Also I do agree it's poorly documented. Could also have some kind of check that the TOTP secret is valid in the first place. *shrug*

**Comment by JoshuaPettus** [comment]
That's it!  I knew it was something stupid I was missing.

**Comment by OLLI-S** [comment]
I am very new to KeePassXC (I am using KeePass and tested Bitwarden, but I want to switch to KeePassXC because here I can keep all my data).

For Bitwarden I asked if Setam OTP is possible in Bitwarden (https://community.bitwarden.com/t/question-about-steam-totp-codes/3513).

In that topic they wrote an answer how this is possible:
https://community.bitwarden.com/t/question-about-steam-totp-codes/3513/10

Maybe this helps you creating a documentation.

**Comment by OLLI-S** [comment]
I tested the **Steam Desktop Authenticator (SDA)** (that is needed to get the Steam OTP).

When you have already set up the Steam App to generate the OTP for you (like I did), then the SDA tells you that you already have an existing Authenticator and that you have to remove the current Authenticator and set up a new one (set up the SDA as Authenticator).

So the **Steam Desktop Authenticator** is **not an alternative** to the Steam App, it **replaces the Steam App** (authentication via the Steam app will no longer work). So you can only login via the SDA and KeePassXC (after you extracted the Authenticator Key from the SDA).

You have to trust the SDA completely because it will be your only way to login into Steam.
**So it is very important to set up recovery codes for the Authenticator** so you can remove it in case the SDA is no longer working!

**Comment by nift4** [comment]
Hi! I have an rooted Droid and copied my secret into KeePassXC (of course I selected Steam TOTP) but the codes are different, the expiration times are the same though. What is my problem? (If you need more infos, say it :) )

KeePassXC 2.5.3 on Win10 Pro, Steam App 2.3.11 on LineageOS 17.1 (that's Android 10)
