### ISSUE TITLE
File locking feature is problematic

### ISSUE THREAD

**Issue by milankni** [keepassxreboot/keepassxc#169]
When I shutdown computer (Arch Linux, Mate) without exiting KeePassXC manually, the .db-name.lock file remains in the folder and blocks KeePassXC from opening the db file next login (it is automatically started on logon). Even when confirming "yes, open the file anyway", the original lock file remains in the folder and the user has to delete it manually (in terminal, since it is a "hidden" file, which are usually not displayed in the file managers by default).

## Expected Behavior
KeePassXC should avoid using lock file on db.

## Current Behavior
On force close, the lock file remains stale. It does not get deleted even on forced re-opening by user.

## Possible Solution
Instead, it should read the db before save and merge any changes. (The same way as Keepass2Android does it.) It would also resolve a problem of file syncing in the background (e.g. via Dropbox) with other clients/systems.

## Your Environment
* KeePassXC version/commit used: 2.0.3
* Operating System and version: Archlinux.

**Comment by phoerious** [comment]
Having two instances of KeePassXC running which both write to the same file is generally unsafe and may lead to corruption.

More to your point: a stale lock file should not cause any problems since it will get deleted if the process who wrote that lock file doesn't exist anymore. It should therefore never block KeePassXC from reopening a database after a fresh login. If you are really having problems with stale lock files, though, please try out the most recent KeePassXC version from the develop branch and make sure you are also using a recent Qt version (preferably 5.7). I just verified that stale lock files get silently replaced when reopening the database.

However, I agree that lock files should be removed when KeePassXC receives a SIGINT to prevent cluttering the file system with hidden lock files.

**Comment by phoerious** [comment]
Since there hasn't been any response from you, I assume that your issue was resolved and I will close this. If you are still encountering issues, please start a fresh issue report.
