### ISSUE TITLE
Allow building the cli without linking Qt5::Widgets

### ISSUE THREAD

**Issue by darix** [keepassxreboot/keepassxc#1714]
Currently the cli also links the gui library. For installing it on a server to have a nice way to access your DB from a remote host via ssh, it would be nice to have it install without all the gui libraries.

removing Qt5::Widgets from the cli CMakeLists.txt is not enough as some core headers reference Qt classes only reachable via the GUI parts. (QColor e.g.)

**Comment by louib** [comment]
The reason why the CLI needs to be compiled with the widgets I believe is because the `core/` modules require so. So I think the real issue here is to be able to compile the `core/` modules without `Qt5::Widgets`. I guess this would be a requirement if we ever want to publish a `libkdbxc` library. @droidmonkey Is this still something you're considering?

**Comment by phoerious** [comment]
Yes, we're still considering that.

**Comment by droidmonkey** [comment]
I need to pick that back up, but want to implement some other features first.
