### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1737]
As a security feature, I'd would be nice to do some fuzzing of your code in order to find potential vulnerabilities.

See also: https://fuzzing-project.org/

You may:
* do parts in your unit tests.
* use some hard core server, always running, just for fuzzing
* [apply at Google's OSS-Fuzz](https://github.com/google/oss-fuzz) (don't know if KeePassXC would, however, count as a "widely-used open source project")

**Comment by yan12125** [comment]
If a project is more popular than [libchewing](https://github.com/chewing/libchewing), it's fine to apply for OSS-Fuzz, and KeePassXC definitely satisfies the condition :)

(You can see what projects have applied here: https://bugs.chromium.org/p/oss-fuzz/issues/list)

**Comment by rugk** [comment]
@droidmonkey closed, because?

**Comment by droidmonkey** [comment]
Fuzzing is done offline, not as part of unit testing. At least we won't do that. If you want to fuzz the app you are welcome to do it. We don't have plans to ever automate or formally support fuzzing.

**Comment by rugk** [comment]
What about:
> apply at Google's OSS-Fuzz 

? Just let Google do the work and continously fuzz. Fuzzing takes processing power, so if this is always done, it's better than if you do it "offline" from time to time.

**Comment by droidmonkey** [comment]
It is not as easy as just submitting an application. You need to plumb the fuzzing input throughout the application. For a GUI app that is incredibly challenging, especially since you have workflow to consider. It *could* be possible to incorporate into our GUI tests, but that would require basically rewriting those tests to use the fuzz data.

At this time there is no bandwidth for these activities. Fuzzing the CLI would be rather trivial and I recommend exploring that if you like.

**Comment by droidmonkey** [comment]
We implemented this for the CLI, no further effort will be made on this front.

**Comment by rugk** [comment]
> We implemented this for the CLI

Great, is there any more detail about the implementation? I.e. no commit or so is linked here, so I am a little curious what/how exactly you implemented it?
