### ISSUE TITLE
Every Chrome launch creates new additional keepassxc-proxy

### ISSUE THREAD

**Issue by dreamlayers** [keepassxreboot/keepassxc#1765]
Every time I launch Chrome, an additional keepassxc-proxy appears in Task Manager. So far I have 8 of them running. Each one also has its own conhost.exe and cmd.exe.

## Expected Behavior
Either the old keepassxc-proxy should quit when I quit Chrome, or it should be reused next time I run Chrome.

## Current Behavior
Each launch of Chrome creates a new keepassxc-proxy process. This is in Windows 7 32 bit with Chrome 65.0.3325.181 (Official Build) (32-bit), KeePassXC 2.3.1 and KeePassXC-Browser 1.0.1

## Possible Solution
Probably best to reuse the old keepassxc-proxy process.

## Steps to Reproduce (for bugs)
1. Run Task Manager
2. Run KeepassXC
3. Run Chrome with KeePassXC-Browser installed and enabled
4. Quit Chrome
5. Run Chrome again
6. Observe in Task Manager how there are multiple keepassxc-proxy processes
7. Repeat steps 5 and 6 if you want to see more processes

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: i386
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Launching a new proxy for each chrome instance is by design, its what keepa native messaging secure. However, they should be killed when the browser closes. I suspect they may be left alive due to the chrome tasktray feature.

**Comment by varjolintu** [comment]
They should be killed yes. Multiple open processes does no harm though.

**Comment by varjolintu** [comment]
One more thing: using the old process is not possible. Native messaging always launches a new process on browser startup.

**Comment by aadrian** [comment]
> Multiple open processes does no harm though.

It does though:
 - their number keeps growing until consume the entire memory
 - they do not appear in the process tree as child of the browser process that "started" them, but in the root (but not as a service), so it's not obvious why a new one would be needed.
 - many audit/security/monitoring software already marks it automatically as problematic after a few of these "zombie" processes.
 - KeepassXC was already put on blacklists because of this behavior in some companies :( .

**Comment by varjolintu** [comment]
I have seen this kind of behaviour before. For some reason Chrome doesn't kill the native messaging processes like Firefox does and they keep running in the background. Haven't solved this one yet. One thing that could be done is that every proxy process will be terminated when KeePassXC launches.

**Comment by droidmonkey** [comment]
This sounds more like a chrome bug than a KeePassXC bug. We don't spawn or control the process...

What is your evidence for the claim of "KeepassXC was already put on blacklists because of this behavior in some companies"

**Comment by seanlynch** [comment]
Not sure if this is an instance of the same problem, but Chrome started behaving very strangely for me today, in particular being extremely slow and crashing, and menus for some of my extensions wouldn't come up. Meanwhile, had created 2000+ instances of keepassxc-proxy, which causes the rest of my system to bog down. I definitely did not launch it 2000 times.

**Comment by rask** [comment]
I had hundreds of `keepassxc-proxy` processes running just now. I have Chromium and I've opened around 15 tabs. I had to kill the proxies as my 16GB Windows 7 PC already shut itself down because it ran out of memory once before today.

This is an issue and will prevent me from using the browser integration unless fixed.

**Comment by phoerious** [comment]
I have a few, but hundreds sounds very excessive.
As a workaround you may turn off proxy support in the settings and let Chrome manage your KeePassXC instance directly.

**Comment by seanlynch** [comment]
For the moment I've just removed the extension from Chrome. I use Chrome
just for work-related stuff, and we have Bitium, so I can just use that to
manage most of my work passwords and keep my personal passwords in
KeePassXC.

The problem is reliably reproducible, incidentally; approximately two
processes are getting created per second.

On Thu, May 10, 2018 at 12:55 PM, Janek Bevendorff <notifications@github.com

**Comment by phoerious** [comment]
I tested it and the problem is caused by auto reload and the fact that Chrome on Windows doesn't properly shut down the proxy. You can avoid it by making sure that KeePassXC is always running in the background. As soon as you stop KeePassXC, the browser will start trying to reconnect and spawn processes which are not cleaned up properly.

**Comment by DuncanFairley** [comment]
Freshly booted PC, I had maybe 2 or 3 Chrome tabs open, my PC gets super sluggish all of a sudden. I open task manager and see this:
![screenshot 2018-05-10 19 16 17](https://user-images.githubusercontent.com/1350420/39903464-2b6dafd2-5488-11e8-85ba-8cfefe4dda1c.png)

Keepassxc 2.3.3

**Comment by droidmonkey** [comment]
We are working to fix this. As a workaround, leave KeePassXC running or disable the browser extension in Chrome.

**Comment by sheavner** [comment]
@droidmonkey 

Is there a work around or manual edit possible aside from disabling it?   I found I had 326 of them running and 327 conhost.exe tasks.   I only had 4 or so tabs open and maybe only for 10 minutes.   My machine has been crashing a lot lately, I believe all these running keepassxc-proxy instances are consuming too many resources.

I unchecked the "use proxy application between KPXC and browser extension" and now i see it trying to spawn multiple KPXC instances.   Though mostly it stops after one, but I had 5 at one point when I viewed the task bar.

[tasks.txt](https://github.com/keepassxreboot/keepassxc/files/1994009/tasks.txt)

**Comment by varjolintu** [comment]
@sheavner Until we have a new release available the only thing you can do is to keep KeePassXC open in the background when proxy is enabled.

**Comment by phoerious** [comment]
We reverted the autoreconnect feature and uploaded a fixed version to the store.

**Comment by NibblyPig** [comment]
Logged into my computer today to find some warnings about lack of memory, and found exactly as in the first screenshot, over 100 copies of keepass-xc.exe running. Using Microsoft Edge, using the plugin. Running keepass 2.6.4 and plugin 1.7.6

I realise I'm 1 version out of date so I will update it now, but this bug isn't listed on the fix list.

I generally open keepass-xc when my PC boots and never close it, except occasionally by accident because of the annoying behaviour that X closes it whereas most applications that have background functionality minimise when X is pressed so I'm accustomed to that. But my uptime is 1 day and 10 hours so there's no way I've opened 100 copies of whatever it is that triggers the bug.

**Comment by varjolintu** [comment]
@NibblyPig This might be related to the issue where waking up from sleep doesn't connect to the extension. It may be that the proxy if left in the background in that kind of situation and doesn't exits like it should.
