### ISSUE TITLE
Display version in error message "Unsupported KeePass database version"

### ISSUE THREAD

**Issue by PostalBlab** [keepassxreboot/keepassxc#1781]
## Expected Behavior
`Unable to open the database.
Detected database version (1.2.3) is newer and not supported`

## Current Behavior
I accidently downgraded KeePassXC from 2.3.0 to 2.2.3 without noticing it. Then i tried to open my Database and got the message
`Unable to open the database.
Unsupported KeePass database version.`

Would it be possible to display the database version to make it easier to spot the problem? I thought the database was broken and started to mount my backups.

## Steps to Reproduce (for bugs)
1. Open 2.3 database in 2.2
2. ???
3. Panic for a second

## Debug Info

KeePassXC - 2.2.4

Operating system: Gentoo

**Comment by mkrsn** [comment]
Same problem here. Would be nice not to die because of an heart attack :)

**Comment by droidmonkey** [comment]
Uh just upgrade your KeePassXC to the new version again. The database version itself is completely irrelevant to end users. It does not correlate with anything you have seen in KeePass(X)(C)

**Comment by maathieu** [comment]
I'd like to repoen this case since this is also a documentation issue. The documentation on KeepassXC's website does not mention that we need to install latest version or that there is a downwards compatibility problem between 2.x versions. This may be a problem to some users such as ones on Debian who can't control which version they install and have a slightly out-of-date version.
