### ISSUE TITLE
Max time in OTP

### ISSUE THREAD

**Issue by Niarff** [keepassxreboot/keepassxc#1785]
Hi,

Can you allow more than 60 seconds in the configure pane of TOTP ?

It's not a bug, it's a feature.

**Comment by Generator** [comment]
Don't think so, TOTP (Time-based One-Time Password) need to be in sync with server, bot need have the same interval, otherwise the token will miss match  

> the clocks of the user's device and the server need to be roughly synchronized
Both the server and the client compute the token, then the server checks if the token supplied by the client matches the locally generated token. 

https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm

**Comment by weslly** [comment]
In addition to what @Generator said, TOTP servers usually have a delay window to avoid problems with desync.

**Comment by Niarff** [comment]
But if the server use a period of 90s and KeepassXC 60s, the otp will change too often, no ?

**Comment by droidmonkey** [comment]
What server is using 90 seconds? This seems like its outside the standard.
