### ISSUE TITLE
Add SSH key to agent from entry list

### ISSUE THREAD

**Issue by hdiogosilva** [keepassxreboot/keepassxc#1815]
Similarly to how you can copy a username/password/url or auto-type from the entry list (without opening the actual entry), if you have the SSH agent integration active you should be able to quickly add a key to the agent via de GUI (toolbar icon) or with key combo.

## Expected Behavior
Clicking and icon on the toolbar or pressing a key combination should add the selected entry's SSH key to the SSH agent.

## Current Behavior
To add a key (not set to auto add) to the agent after the db is unlocked:
1. Open the entry
2. Select the SSH Agent Tab
3. Click to add the key to agent

Enabled extensions:
- SSH Agent

**Comment by hifi** [comment]
Some kind of fast shortcut is definitely needed when you have a lot of keys but don't have them all automatically loading.

Thinking about the UI, would it be a single button that changes state based on if the key has been sent to the agent or not? I was also thinking of some sort of separate list that has only SSH keys with action buttons. Like a completely separate window or something you could open.

**Comment by hifi** [comment]
Some progress has been made: toolbar icon, context menu and shortcut. They only add to agent but they will honor any settings set in the entry edit (lifetime, confirm and remove on lock). The branch is still very much in development.

@phoerious challenged the toolbar already has enough buttons but the button is only visible if SSH Agent is enabled. Let us discuss here.

![image](https://user-images.githubusercontent.com/106598/39876267-64f9bbea-547b-11e8-8380-fcf472cf6a8f.png)

(I thought I had submitted this comment before but apparently not)

**Comment by hifi** [comment]
Set milestone for 2.4.0 as a reasonable target to finish up the refactor and context menu entry.

**Comment by droidmonkey** [comment]
@hifi still looking to implement this?

**Comment by hifi** [comment]
If I find the time. It should not end up being a 2.4.0 blocker, though.

**Comment by outdooracorn** [comment]
I like the idea of being able to see all the keys or all the entries that have keys. If tags (#508) were implemented I could tag all my entries with ssh-keys and then search on that tag.

Would also be good to select all or multiple keys (or entries with keys) to add/remove them to/from the ssh-agent.

Let me know if you want me to create a separate issue for any of these ideas.

**Comment by hifi** [comment]
@outdooracorn Please do create any issues you see fit and we'll tag them appropriately. We don't close feature requests / wishes unless they are against the project goals.

**Comment by drawks** [comment]
I just started using the ssh agent integration and was immediately disappointed that the "add to agent" "remove from agent" buttons are buried so deep in the UI. Having an add/remove dual state button present in the tool bar/context menu would be rad. Even better IMHO would be if the ssh-agent integration presented the agent state as a group in the UI, I've honestly never browsed the codebase to see how difficult that sort of feature would be to implement, but anything would be better than the current multiple clicks dance it takes to interact with the agent integration if you don't want everything loading/unloading along with keepassxc lock/unlock


P.S. It took me a while to find this issue because searching for "ssh agent" in the issues brings up every ticket that has "SSH Agent" listed as an enabled extension, perhaps the issue template for this project should account for that better somehow

**Comment by droidmonkey** [comment]
Use the label "plugin: SSH Agent"

![image](https://user-images.githubusercontent.com/2809491/54711256-e932ca00-4b1f-11e9-929d-205a0e67e63e.png)

**Comment by outdooracorn** [comment]
> @outdooracorn Please do create any issues you see fit and we'll tag them appropriately. We don't close feature requests / wishes unless they are against the project goals.

Thanks. I ask because your [comment on the 8th April](https://github.com/keepassxreboot/keepassxc/issues/1815#issuecomment-379525763) is similar to part of my suggestions so wondered if my comment was a continuation of this issue or separate issues. I'll go and create a separate issues for them - I guess you can always mark them as a duplicate if you want to track it under another issue.

**Comment by scruloose** [comment]
The ability to add an ssh key to my agent from the right-click menu without having to open the database entry is a feature I would love to see, as I use Keepass to manage a fair number of ssh keys.

As for the point raised by @phoerious about too much clutter in the toolbar, I don't feel strongly about it one way or the other (especially if the icon is only visible when an entry with an ssh key is highlighted).  I do have a related suggestion, though:  The "General" pane that appears in the bottom of the main window when an entry is highlighted seems like it would be an ideal place to have buttons to add key to agent and remove key from agent, and ideally also an indication of whether the key is currently loaded in the agent. (In addition to a toolbar icon? Instead of a toolbar icon? \*shrug\*.

I have also opened a somewhat related issue #3571 which, if implemented, would make me *much* less concerned about the number of clicks it takes to manually add a key to my ssh-agent.

**Comment by hifi** [comment]
Once/if https://github.com/keepassxreboot/keepassxc/pull/3833 is merged I will have a PR that will add agent add/removal to _Entry_ menu, right click context menu and possibly to the entry preview panel.

Sorry for taking well over a year, family stuff. Will definitely get in 2.6.0.
