### ISSUE TITLE
Entering the password in auto-type with keyboard results in an error

### ISSUE THREAD

**Issue by MisterY** [keepassxreboot/keepassxc#1856]
## Expected Behavior
Entering a password into a web site, for example, should behave the same whether the entry in the list at the auto-type window was selected by keyboard or by mouse.

## Current Behavior
If an entry is selected via keyboard and Enter is pressed, most sites return an error with invalid login.
If the same entry is selected via mouse, the login proceeds correctly.

## Possible Solution
Not sure. I guess this is a bug but requires a further confirmation.

## Steps to Reproduce (for bugs)
1. Get to a web site that requires log-in
2. Press the auto-type hotkey combination
3. Select an entry with keyboard (up/down) and press Enter

## Context
Not moving a hand from keyboard to select an entry should work equally well.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by MisterY** [comment]
OK, this does not happen on every site but I did notice it a few times so far. Will pay more attention and provide additional details when it happens.

**Comment by droidmonkey** [comment]
It's probably because the site is doing some stupid JavaScript trickery when you submit the form that the autotyping is not triggering.

**Comment by mrnagydavid** [comment]
I have the same problem, e.g. with github, too. No such problem with the original KeePass or the Mac port of it.

**Comment by droidmonkey** [comment]
I cannot reproduce this, even on the degiro.nl website. When I click the eye icon, the full password has been entered by autotype, no issues.

**Comment by MisterY** [comment]
Yes, I guess it's been working for some time now, for whatever reason. :)

**Comment by cedricvanrompay** [comment]
I am having a somehow similar problem, don't know if it is the same or not.
The solution from @droidmonkey [[1][]] does not fix it for me.

# Steps to reproduce (for me)

- find a form you know does not have "fancy JS". I use this one because it tells you what you just typed: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_password
- use auto-type (either by clicking on autotype button in KeePassXC or by typing Ctrl-V)
- I used it with the following dummy entry: `test@username.fr : testpassword`
- the form tells me it received: `email=test@username.fr&pwd=testpass`, that is it only received the beginning of the password
- same thing happens with other, non-dummy passwords.
- same thing happens if I increase "auto-type typing delay" to 40 ms and also if if follow @droidmonkey suggestion to set the custom auto-type sequence to `{USERNAME}{TAB}{DELAY=100}{PASSWORD}{ENTER}`

# Debug Info
KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-34-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

[1]:  https://github.com/keepassxreboot/keepassxc/issues/1856#issuecomment-423982327

**Comment by droidmonkey** [comment]
Lol look closely.... 

``` <input type="password" name="pwd" maxlength="8">```

**Comment by cedricvanrompay** [comment]
Damnit.

Okay, then now it seems to work. I used to have "incorrect password" problems frequently on websites so I stopped using the "auto-type feature", but I will start using it again and come back to you if it comes back.

Sorry for doing such a bad job at bug reporting :'-(
