### ISSUE TITLE
Don't start autotype until modifier keys are released

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1915]
## Expected Behavior

When "Always ask before performing Auto-Type" is disabled, delay starting the autotype sequence until the CTRL/ALT/SHIFT keys are fully released.

## Current Behavior

Autotype has a fixed delay, that is user configurable in 2.3.2

## Possible Solution

Add blocking AsyncTask in place of the current Tools::Wait call at https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L223

**Comment by orzechow** [comment]
It would also make sense, to pause autotyping, if any of the modifier keys is pressed again.

Sometimes I forget how "long" the autotyping needs and start using the keyboard again (switching desktops etc.). That is usually a big surprise with all these hidden shortcuts triggered by me pressing e.g. `CTRL` and autotype firing all kind of characters to that :sweat_smile: 

Most often my autotype is `{username}{enter}{delay 100}{password}{enter}`, because I work a lot in terminals on Linux (Mint 19.2, based on Ubuntu 18.04).
