### ISSUE TITLE
On Mac, Win & Lin with 2.3.1 and Chrome 66.0.3359.139 DB unlock is never requested

### ISSUE THREAD

**Issue by mircsicz** [keepassxreboot/keepassxc#1916]
I'm on MacOS 10.12.6 and on Win10 18.03 and on Ubuntu 16.04 with latest Chrome and KeepassXC and I've the checkbox in Browser-Integration set. But I never get a request, instead I see this on a regular basis:

[Screenshot](http://www.imgpaste.net/image/kdDox)

**Comment by droidmonkey** [comment]
On all platforms? Did you check the chrome checkbox as well?

**Comment by mircsicz** [comment]
Yes on all three major platform's and yes the chrome check box is set...

**Comment by droidmonkey** [comment]
Probably related to this issue https://github.com/keepassxreboot/keepassxc-browser/issues/102

**Comment by mircsicz** [comment]
I've upgraded the homebrew and the ppa install. On MacOS the window is brought to foreground to unlock the DB in 18.04 this doesn't happen using budgie...

Windows test follow's later

**Comment by r3wald** [comment]
@mircsicz Are you using google-chrome-unstable? I did and since KeePassXC only establishes a connection to google-chrome (see https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900) this was not working.
I copied ~/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json to ~/.config/google-chrome-unstable/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json and now it's working like a charm.

**Comment by droidmonkey** [comment]
@mircsicz is this still an issue?

**Comment by mircsicz** [comment]
I'm using the stable release and no it currently works as expected...

Best 
Mirco 

Von meinem iPhone gesendet
