### ISSUE TITLE
KeePassXC 2.3.2 on Windows10 does not work.

### ISSUE THREAD

**Issue by extrajoker** [keepassxreboot/keepassxc#1921]
KeePassXC-2.3.2-Win32.exe
KeePassXC-2.3.2-Win32.msi
KeePassXC-2.3.2-Win64.exe
KeePassXC-2.3.2-Win64.msi
All did not work.

I reinstalled KeePassXC-2.3.1-Win64.exe. It worke.

**Comment by masoo** [comment]
I work KeePassXC-2.3.2-Win64.exe on Windows 10.

**Comment by Tanarri** [comment]
KeePassXC 2.3.2 on Windows 7 (64bit) doesn't work. When I start it crashes imediatelly.

KeePassXC 2.3.2 Portable starts on my system.
When I go to Preferences - Browser Integration and activate is (German: KeePassXC-Browser-Integration aktivieren) then it crashes also

I think its a problem with the browser integration. Because the portable app doesn't have activated the browser integration, the programm starts - but my installed version crash on start, because it the browser integration is activated in my system.

Workaround: If I delete the "keepassxc.ini" in "C:\Users\<username>\AppData\Local\keepassxc" then also my installed version starts.

In my firefox the addon "KeePassXC Browser" 2.3.1 is installed - no update to 2.3.2 is available until now.

Hope this helps

**Comment by macau23** [comment]
Disable browser integration and it will launch. Issue #1922
