### ISSUE TITLE
Compilation warning on 2.3.3

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc#1932]
## Expected Behavior
No warning should appear during compilation

## Current Behavior
```
In file included from /usr/include/qt/QtGui/qtguiglobal.h:43,
                 from /usr/include/qt/QtWidgets/qtwidgetsglobal.h:43,
                 from /usr/include/qt/QtWidgets/qapplication.h:43,
                 from /usr/include/qt/QtWidgets/QApplication:1,
                 from /build/keepassxc/src/keepassxc-2.3.3/src/gui/Application.h:23,
                 from /build/keepassxc/src/keepassxc-2.3.3/src/gui/Application.cpp:20:
/build/keepassxc/src/keepassxc-2.3.3/src/gui/Application.cpp: In static member function ‘static void Application::handleUnixSignal(int)’:
/build/keepassxc/src/keepassxc-2.3.3/src/gui/Application.cpp:240:29: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
             Q_UNUSED(::write(unixSignalSocket[0], &buf, sizeof(buf)));
                      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/keepassxc/src/keepassxc-2.3.3/src/gui/Application.cpp: In member function ‘void Application::quitBySignal()’:
/build/keepassxc/src/keepassxc-2.3.3/src/gui/Application.cpp:252:20: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     Q_UNUSED(::read(unixSignalSocket[1], &buf, sizeof(buf)));
              ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Steps to Reproduce (for bugs)
1. Compile 2.3.3 (with gcc 8.1.0)

## Context
Compiling 2.3.3 for Arch Linux package.

**Comment by droidmonkey** [comment]
What? That is exactly what the Q_UNUSED macro is for! Looks like a new "feature" in GCC 8.1

**Comment by phoerious** [comment]
Can we create a new tag "absurdly superfluous nuisances"?

**Comment by ArchangeGabriel** [comment]
@droidmonkey Hum indeed, I should have read the warning content… Yeah, likely a new GCC 8 “feature” (they are other that are worse, actually resulting in errors). I’m not sure if this is a Qt or GCC bug here, any opinion?

**Comment by ArchangeGabriel** [comment]
This was in Release mode actually, though I should have changed to None per our new Arch Linux policy.

But indeed this would be an issue when trying to build in Debug mode.

**Comment by ArchangeGabriel** [comment]
Interestingly they were no warning when building with None or Debug mode, only with Release.

**Comment by wizeman** [comment]
FYI, I ran into this exactly this issue with keepassxc 2.6.4 when building in debug mode (which means the build failed).

**Comment by droidmonkey** [comment]
This isn't something we will fix and hasn't been a problem with any of the various build systems I've used and our CI system uses.

**Comment by wizeman** [comment]
Which build systems are you referring to? I'm building keepassxc using cmake, which is what keepassxc requires as far as I understand.

BTW, I'm guessing that there is a strong likelihood that these warnings are somehow (and surprisingly) non-deterministic, because nixpkgs uses exactly the same build environment as I do (which is sandboxed and only contains the dependencies necessary for the build) but they aren't running into this issue on their build servers. Nixpkgs goes to great lengths to make builds deterministic but there are still some sources of non-determinism when building (depending on how the build machine is configured, for example... in my case: much higher parallelism than normal, having the build machine under very high load which can make certain build steps slower, etc).

Also, someone said above that they only ran into this issue in release mode but not under debug mode, which may also be evidence of non-determinism. So there's a non-negligible probability that someone will encounter this bug in the future again.

Anyway, I understand if you don't want to fix this issue, because it's not common and is just a harmless compilation warning/error, so it's really not a big deal :smile:

**Comment by droidmonkey** [comment]
This is a compiler issue, not cmake. So gcc or clang. In this case a specific version of gcc seems to trigger the problem more often (or exclusively) than others.

**Comment by wizeman** [comment]
This doesn't seem to be a compiler issue, at least not according to the gcc devs.

The `Q_UNUSED` macro comes from QT (specifically, `qtbase`), which seems to be defined as follows:
```
$ rg "define Q_UNUSED"
src/corelib/global/qglobal.h
117:#define Q_UNUSED(x) (void)x;
```

So `Q_UNUSED(x)` is just casting `x` to `void`.

According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425, the gcc devs specifically decided that casting to void would not suppress this warning (caused by the `warn_unused_result` attribute). Specifically, they say:

> GCC originally added this attribute and made the decision then that void would not suppress the attribute.
>
> There are even tests in the GCC testsuite testing that.

(...)

> I think the request came from Uli that it isn't that easy to suppress it, at least initially the warning was meant for cases where it would be a major security problem to ignore the return value.

In this case, looking at the code, I think there shouldn't be a security issue, so if you are interested in fixing this warning, I think a solution could be to define your own 'unused' macro, e.g. like this:

```C
#define KEEPASS_UNUSED(x) do { if ((x)) {} } while(0)
```

... which should properly ignore the result and suppress the warning in both gcc and clang (according to my simple test and to the gcc testsuite, apparently).

**Comment by droidmonkey** [comment]
Nice reference thread, the real issue is the c compiler versus c++ compiler. They have different behaviors!

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c29

Another poster showed that is is sufficient, use a negation on the return value:
```
(void) !func()
```

**Comment by wizeman** [comment]
> the real issue is the c compiler versus c++ compiler. They have different behaviors!

I don't think so... according to the thread and to my tests, this issue exists both when compiling C and when compiling C++. Anyway, that's not really the point of this issue.

> BTW, that bug report is entirely related to compiler behavior.

Yes, but it's gcc's intended behavior, it's not a bug (according to the gcc devs).

They specifically wanted the `warn_unused_result` attribute to not be suppressed with a void cast.
Which means that they actually wanted macros such as `Q_UNUSED()` to not suppress the "return value unused" warning when the `warn_unused_result` attribute is added to a function (in this case, glibc's `read()` and `write()` functions).

Note that `Q_UNUSED` does indeed suppress this warning for normal functions. It's only functions specially marked with the `warn_unused_result` attribute that bypass the intended behavior of the `Q_UNUSED` macro (on purpose!).

So the compiler is behaving as intended: it's emitting a warning because ignoring the return value of functions such as `read()` and `write()` almost always indicate that the code is buggy.

That said, in this specific case, it seems to be OK to ignore the return value (at least, according to my brief analysis), which is why `keepassxc` should probably implement a workaround.

It doesn't seem like gcc is going to change this behavior, so I don't think ignoring this issue and treating it as being "some weird gcc problem" is going to solve these warnings...

Anyway, I spent too much time on this already, I don't think I will comment on this further. Thanks!

**Comment by michaelk83** [comment]
If the intention of `Q_UNUSED()` is specifically to suppress this warning, then that makes it a Qt bug. But if they fix it, it just becomes an arms race between Qt and GCC, at least until they can agree on some specific cases and behaviors where this warning *can* be suppressed safely. Then, since it's the compiler's job to identify safe vs unsafe cases, ideally, GCC should define a separate switch (or fix the existing one) to suppress these warnings only in the safe cases.

@wizeman , if you want this fixed in KPXC, I suggest submitting a PR. Following the naming convention of other compiler constants in KPXC, the fixed macro can be defined as `XC_UNUSED() (void) !x`.

**Comment by droidmonkey** [comment]
We don't need a new macro just add the negation in the macro call like I showed above

**Comment by michaelk83** [comment]
I figured, if it's used in a lot of places, better use a macro. But it's not my call, of course.
