### ISSUE TITLE
Add case option to passphrase generation

### ISSUE THREAD

**Issue by shaneknysh** [keepassxreboot/keepassxc#1933]
## Expected Behavior
Allow for case selection for passphrase generation. 
option group or dropdown
(x) lower case (default)
( ) Title Case
( ) UPPER CASE

## Current Behavior
The current use reads the words from the word list as is - new behavior would read the word from the word list and set the case before adding it to the generated passphrase.

Operating system: Windows 10, latest creators update
CPU architecture: x64
Kernel:  ntoskrnl

Enabled extensions:
- KeyPassXC-Browser

**Comment by jlemonde** [comment]
**I just opened GitHub to make the same request.** I'd really enjoy to have following options in the pass phrase generator:
- Choose if lowercase only or including some Titlecase or UPPERCASE words (some websites require the presence of uppercase letters)
- Include a few numbers as words (some websites require the presence of numbers)
- Add a few punctuation signs (,.!?()'-:;$)

The reason why I don't want to use the general password generator but a passphrase generator instead is that it is easier to type by hand. I come frequently into the situation where I have to log into a service on a computer which is not mine and on which I can't install anything (that means that I can't open any KeePass database nor add a plugin to my browser). In those cases, I check my passphrase and type it by hand. It turns out that things like "_scarce-78-Property-embassy-pony-Bondless-decorator-LAPEL-bankroll-!!_" (entropy = 209) are ways easier to type by hand than the generated "_t9E$vV9-Wi!pAtK%.`~m3#PnBNb_" (entropy = 153) or even  "_JJ3m52FcuPM6qJWMWFn8fQdiGBd_" (entropy = 140) and have a better entropy.

**Comment by shaneknysh** [comment]
Working on it ;)

**Comment by affinityv** [comment]
For diceware passwords.... camelcase and remove spaces would seem to be the most useful.  Other simple adjustments can be done manually as needed (like adding numerals and/or special characters).  Some sites require passwords to be a maximum size as well, to fix that I often do a sub-selection of each word, ie a number of characters per word instead of the whole words.
