### ISSUE TITLE
Improve search by selected group interface because right now it is not intuitive.

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassxc#1949]
The current search by group function is not intuitive and it is not logical and does not follow industry standards that people expect. Let me describe the various UI elements currently:

1. Group filters left column - this filters everything by group
3. Search box - this is where people search and it has a few sub-UI elements
       A) Search box right click to search by selected group
       B) Search box close button to cancel search

**Currently** when someone searches they type in the search box. Any group filter they added in the left column remains and it becomes ignored. Thus, unintuitively, the **group filters are now broken**. In order to fix the broken group filters, a user needs to right click the search icon and click "search in group".

None of that really makes sense. Why would someone need to click two times to repair the group filters that the search already just broke? You can see how the UI does not make any sense.

To simplify this and make it logical and follow industry standards the group filters should never be broken. **Group filters should always work as expected and not work one way under one circumstance and work entirely different in another circumstance**

To do this, I recommend the following action:

1) Remove the convoluted "search in group" action that is not discoverable and breaks the program UI

2) Automatically de-select any group filters when searching so that nothing is broken. This makes the default behavior of search apply "globally" and keeps the group filters side bar logical

3) Upon clicking a group filter while the search is active it will narrow the search to that specific group. Thus being intuitive, following industry standard, being discoverable, etc.

4) Just like now, someone presses the search cancellation button to end search mode or they can empty the search box.

**Comment by droidmonkey** [comment]
I'll agree that the "search in groups" setting is undiscoverable, but I am not changing the default setting. There is no industry standard for searching. Global search is preferred far more than group level searching. If you don't like that, change the setting to group search. That setting persists between application launches.

**Comment by t4777sd** [comment]
I did not propose that global search should not be default. I proposed that the UI should follow standards. In the recommendations you can see that I proposed a way to make it follow standards and be global:

1. When searching, any filtering previously done by groups is automatically de-selected

2. If a user subsequently clicks a group in the left hand column, then the search is filtered by said group.

As to whether what I propose is a standard or not: You can utilize any software product that has both filters and search. From ecommerce websites like ebay or amazon to desktop software applications such as thunderbird. There is not a single one that let's a user select a filter (such as category), then when a search is done perform a global search while **still keeping the filter active but ignored** then continue to show said active but ignored filter and continue to ignore it despite user-action (very confusing). Only to then re-enable the visible but ignored filters if they right click and further click on a button.

When nearly 100% of all search implementations follow the UI I described and keepassxc is the lone wolf that has an entirely different user experience, then I think it might be a good idea to analyze what keepassxc is doing and see if it is actually beneficial.

**Comment by droidmonkey** [comment]
After re reading your original points I see what you were getting at. Outlook 2016 search is pretty wonky if you've never had the pleasure.

**Comment by tomhundt** [comment]
Good points about group selection being equivalent to filtering.

I would add the following considerations:
1. It's not immediately apparent how to de-select a group in the groups panel (left side), probably because you can't: Instead, you select the "root" group (name of database file), e.g., (on mine) by hitting Home.  (This is good, because it doesn't break the filtering metaphor.)
2. Selecting a group on the left displays only its contents on the right; it does not display the groups it contains on the right (unlike file manager software like Finder/Windows Explorer).  
So, does the "filter" limit the context to what's displayed on the right (the entries in that group), or, does it limit it to those entries _plus_ those in all the groups contained in the selected group?  (Aside: I wouldn't mind if it _did_ display the contained groups on the right...)
3. It isn't possible to select more than one group at a time, on the left.  So, this is a limitation on doing "filtering" in this way.
4. Apparently groups themselves (names/notes) are not included in searches at all (but used to be?  See #3482).

**Comment by droidmonkey** [comment]
2.6.0 adds the ability to search by groups using the `group:<text>` selector.
