### ISSUE TITLE
Master key Yubikey can be changed by saving with a new Yubikey

### ISSUE THREAD

**Issue by zonfromron** [keepassxreboot/keepassxc#1985]
I have two yubikeys, just to check if everything was working correctly, I tried logging in with the other yubikey. Of course it doesn't work. Great. 

However, once logged in with yubikey A, and then switching the yubikey to another, making a change which saves the db (and requires a press of the yubikey), the new yubikey B is accepted and is the one that now has to be used for logging in. The old yubikey A, with which the database was initially set up, won't work any longer. 

I know this is an edge case, as there probably isn't a single person in the world who would have problems with this, but I thought I'd report it anyway.

**Comment by droidmonkey** [comment]
Yes this is certainly not desired behavior since you could inadvertently change to a different yubikey without even knowing. You should only be able to "reprogram" a new yubikey for the db in the "Change Master Password" dialog.

**Comment by phoerious** [comment]
We cannot detect which YubiKey is plugged in. Sure, we could check for a serial number or so, but this has two major problems:

- we'd need to save it in plain text in the KDBX header, which leaks information about how to decrypt the database
- you couldn't use a backup key anymore that wasn't formerly registered

Assuming, we do not save any additional information about the key, the only way we could ensure to only save with the same key is to send two challenges: one with the old transform seed to check if the response is the same, and another one with the new transform seed. That, however, would cost a lot of time and you would need to touch it twice if you programmed it to require user input.

**Comment by seatedscribe** [comment]
Hello,
I'd like to chime in to see if I am missing something. Is it not true that
saving with another YK could potentially open a security issue? I mean, a
thief with a YK could potentially copy my database if I forget to close
laptop lid or lock the screen? Yes, if there is physical access you are
already screwed, but this makes things easier and, in my opinion, the
benefits are not balanced by the risk.
Am I right? Sorry to bother, I am curious :)

**Comment by phoerious** [comment]
I would consider it an unlikely threat scenario. Switching the YubiKey while the DB is locked, wouldn't work, because you'd notice when you can't open the DB, so it needs to be unlocked already.

Here's what's needed for this attack: You need to leave your workstation with both your database unlocked AND your YubiKey still plugged in (why would you do either of that?!) and then an attacker needs to switch YubiKeys without anyone noticing. I'd be surprised if anyone tried that instead of just keeping the original key and unlocking your database with that. Also with an attacker having physical access to the machine with an unlocked database on it, a switched YubiKey should be the least of your concerns.

**Comment by zonfromron** [comment]
I don't think the yubikey needs to remain plugged in by the target for this attack to work. However, yes it's highly unlikely. I only reported it because there might be some other repercussions / attack vectors that I don't know about.

**Comment by phoerious** [comment]
The YubiKey needs to be plugged in while the database is open, otherwise you cannot save it. And it also needs to remain plugged in while you are away, otherwise an attacker couldn't steal it.

**Comment by phoerious** [comment]
Not sure what you mean. Yes, you can unplug it after decryption, but you cannot save without it. And you do need to steal the Yubikey when you want to do anything with it. If you don't have to, it means that you have unnoticed access to the PC while the user is present. In that case the attacker can access the database anyway, unless maybe he has remote access to another unprivileged user account on the same machine which can talk to USB devices and reprogram the key. But it's also totally possible that the user doesn't change anything in the database and the attacker just locks both the user and himself out of the database forever. Also timing such an attack needs some sort of side channel, such as shoulder surfing.

**Comment by githubnww** [comment]
I use multiple Yubikeys, and after several frustrating events before I found this ticket, I now close my database entirely when swapping keys.  Things can get tricky when you have to update the database and use the "wrong" key at the same time.  You can't plug both keys in because KeepassXC may choose the wrong one when saving.  My point is that this is much more than a minor security problem.  I thought I had some weird synchronization problem that was corrupting my database.  It took me a while to figure out enough to even find this ticket.  I'm a Mac user, in case that's pertinent.

The Yubikey serial number check seems ideal, or at least the best that can be done for this scenario.  Does that really represent a security leak, and is that leak serious enough to discount using to fix this problem?

**Comment by droidmonkey** [comment]
The serial number doesn't correlate in any way to the secrets on the Yubikey.

**Comment by Sbgodin** [comment]
Maybe a sanity check could be performed by trying to reopen the database. The correct key would return the correct response.

It may also be possible to store a challenge-response in memory upon opening the file. Before saving, the challenge-response would be checked before using the key to encrypt the database.

**Comment by phoerious** [comment]
Closing this, since I doubt anybody will work on this.
