### ISSUE TITLE
Please remove auto-type macro warnings, or create toggle to suppress them.

### ISSUE THREAD

**Issue by ccady** [keepassxreboot/keepassxc#2017]
## Expected Behavior

I expect KeepassXC not to second-guess my auto-type macros.  

## Current Behavior

I have an auto-type macro which says "{DELAY=100}{PASSWORD}".  When I try to run the macro, I get a confirmation box which says "This Auto-Type command contains very slow key presses. Do you really want to proceed?"

## Possible Solution

I would prefer that KeepassXC not bother me when I execute a macro.  If you really want to keep this behaviour, then I suggest adding a configuration value to let you turn this behaviour off.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

Instead of simply being able to run an auto-type macro, I have to confirm that I want to run it.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.16.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
I agree a 100 ms delay shouldn't yet trigger that warning. If you want to work around that, 99 ms is below the threshold.

**Comment by hfr-hfr** [comment]
I agree. If at all, there could be a warning right after entering a huge delay in settings. But not while performing auto-type since it removes focus. Even after hitting accept on the warning, the autotype doesn't work anymore because the desired window is now out of focus. (this and the locked database issue are two very annoying autotype bugs for mac users)

**Comment by TheZ3ro** [comment]
This feature was broken by design, I already expected this some time ago (https://github.com/keepassxreboot/keepassxc/pull/552#issuecomment-299910387, https://github.com/keepassxreboot/keepassxc/pull/217#issuecomment-275346013) 

Anyway I'm planning to replace that with a syntax checker directly when typing the sequence.
At this time I'm a little busy but I will do this asap

**Comment by alvarogmj** [comment]
Running 2.3.4 on MacOS El Capitan, saw this warning today for the first time, but with a DELAY=10000.

Since the issue was opened with a much lower delay, I assume in later versions the threshold for the warning was changed to avoid affecting more users. Came here to report it, after reading the comments I realize it is a known problem. There should (must, I dare say) be a checkbox to disable this, as this effectively reduces the flexibility of Auto-Type, my sequence is unusable because the AutoType starts when the focus is in the KeePassXC window.

In my case, I need to login to a bank which asks for user/pin, and then does a page reload (with a quick verification via a "security image") before requesting the actual password. I was able to get Auto-Type to work by reducing the DELAY, but I share the sentiment that the application should not assume the sequence is wrong considering which kind of software we are talking about.

Looking forward for that syntax checker :)
