### ISSUE TITLE
KeepassXC looks really bad on MacOS Mojave with dark theme

### ISSUE THREAD

**Issue by tkolo** [keepassxreboot/keepassxc#2083]
I've installed macOS mojave beta to test the dark theme, unfortunately keepass doesn't seem to fully apply the theming, resulting in a very bad look. Attached a screenshot presenting the issue

<img width="805" alt="screenshot 2018-07-01 at 22 42 38" src="https://user-images.githubusercontent.com/3638714/42138632-db3b2a36-7d80-11e8-88e2-5e6a57767a88.png">

## Debug Info

KeePassXC - 2.3.3

Operating system: macOS Mojave 10.14 Beta (18A314k)
CPU architecture: x86_64
Kernel: Darwin Kernel Version 18.0.0

**Comment by droidmonkey** [comment]
This might be a Qt problem

**Comment by phoerious** [comment]
I think we will have to increase our minimum supported macOS version further or provide various builds for older versions in the future. Maintaining backwards-compatible macOS builds seems to be impossible.

**Comment by DemonWav** [comment]
[Weak linking is apparently how you're supposed to do it.](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html) I think that means if you set the deployment SDK version to the older version, but set the target SDK version to 10.14 it'll enable the proper dark theme support while still supporting older versions of macOS. I don't have any experience developing in this area though, so that's just a guess.

**Comment by droidmonkey** [comment]
The next release will be built with 5.12

**Comment by LnxGnome** [comment]
2.4.0 still looks pretty bad with Dark Theme.  Is there a way to disable it for just KeePassXC?
Unselected tabs when you have more than one DB open are still black on dark gray.
URLs in the Preview pane are dark blue on dark gray.
The black group background is too stark against the group names/icons.
![Screen Shot 2019-03-28 at 10 46 31 PM](https://user-images.githubusercontent.com/5316950/55206006-6eb31b80-51ab-11e9-9e73-fb9eea55a0fd.png)

**Comment by droidmonkey** [comment]
These are all Qt bugs. I've already reported the tab coloring and it's been fixed in the next qt release.

**Comment by droidmonkey** [comment]
Closing this issue as the remaining problems are not ours to fix at this point.
