### ISSUE TITLE
Support for Non-legacy encryption-modes

### ISSUE THREAD

**Issue by Florianjw** [keepassxreboot/keepassxc#2162]
## Expected Behavior

The encryption modes used are all properly authenticated ones, like OCB, GCM or at least contain a proper MAC, like ChaCha20+Poly1305

## Current Behavior

From what I can tell, CBC is used for block-ciphers.

## Possible Solution

Add support for something more modern like OCB (the patent-issues it had in the past are no longer applicable and it certainly is one of the nicest AEAD-modes out there) or GCM (well, established, though several issues in detail for example key-extraction after nounce-reuse). After that keep an eye on the CAESAR-competition.

## Context

There really is no reason to use unauthenticated cipher-modes today. In the best case-scenario, doing so won't offer real benefits, but it can easily make other issues worth or in the worst case create full vulnerabilities. 

There is little point in providing 256-bit keys, if your modes suck.

**Comment by phoerious** [comment]
This is mainly a compatibility issue. We have to support what KeePass supports, so that is CBC. However, contrary to your statement, our encryption is authenticated. KDBX 3.1 uses mac-then-encrypt (yes, that is a bit flaky, but for an offline password manager not immediately dangerous), but KDBX 4.0 uses proper encrypt-then-mac using HMAC-SHA256.

**Comment by Florianjw** [comment]
Okay, that turns it somewhat less bad, but it would still be wise to provide clearer documentation of these things (see also #2161). I've just seen terrible choices hidden under the “We use AES, therefore it is secure!”-carpet a few times too often.

That being said: You may want to support what Keepass[x] supports, but is there any issue with supporting more that?

**Comment by phoerious** [comment]
It is documented in the KeePass docs (I agree that they are not very good, though). We only re-implemented them.

We also support more than KeePass already. Twofish is only supported by by KeePassXC. But using different modes would require providing another "Algorithm option", so suddenly we have two "AES" options and two "Twofish" options. And then someone comes and wants another mode and four options turn into six etc. This becomes confusing really quickly and I don't really see the benefit of it. If you really dislike CBC that much, I'd suggest you use ChaCha20 instead.

**Comment by sebast889** [comment]
@phoerious 

Is it true KeepassXC's implementation of ChaCha20 is not authenticated at all? This means it is vulnerable to bit flipping, potential nonce reuse and other attacks. This reduces security of the encrypted database which looks to only be for the sake of compatibility. I see no reason not to use ChaCha-Poly1305 even if it breaks compatibility or if not possible then please introduce a new option for ChaCha20-Poly1305 because it is important for the overall security of users databases who want to use ChaCha20. Does KeepassXC protect against the above attacks when using ChaCha20?

**Comment by phoerious** [comment]
Our cipher texts are authenticated block-wise using HMAC-SHA256.

**Comment by sebast889** [comment]
@phoerious Thanks for the information. Is it safe to assume HMAC-SHA256 way of authenticating ChaCha20 in KeepassXC is secure against bit flipping and other attacks common against unauthenticated ciphers?

**Comment by droidmonkey** [comment]
The very way bit flipping is prevented (or at least detected) is the use of MAC. So yes, using a side-channel HMAC-SHA256 on the block is a way to detect a bit flipping attack. The advantage that Poly1305 gives is that the MAC is embedded into the cyber stream, not separate. This is only really necessary when transmitting over an untrusted channel (such as the internet) which is why it is favored for TLS by Google. Since we do all operations in RAM, this would provide marginal, if not no, extra security.

**Comment by phoerious** [comment]
Also the most important reason for using MACs is the prevention of oracle attacks and message forgery. Both are not a real problem for offline databases.
