### ISSUE TITLE
On the use of '/' in the titles of the entries...

### ISSUE THREAD

**Issue by liar666** [keepassxreboot/keepassxc#2225]
When I try to insert an entry which title contains a "/", I get an error:
```
user$ title=https://www.academia.edu/
user$ keepassxc-cli add "$KEEPASS_DB" "/$title" <<EOF
$KEEPASS_PASS
EOF
Insert password to unlock test.kdbx: 
Could not create entry with path /https://www.academia.edu/.
```

I can understand why ('/' is the path separator).

But when I try to protect the path sep, it does not work:
```
user$ title=https:\/\/www.academia.edu\/
user$ keepassxc-cli add "$KEEPASS_DB" "/$title" <<EOF
$KEEPASS_PASS
EOF
Insert password to unlock test.kdbx: 
Could not create entry with path /https:\/\/www.academia.edu\/.
```

Of course, it works if I replace the "/" char by another one.

However, I don't understand why using the GUI for the creation makes everything works seamlessly for the CLI:
```
user$ keepassxc-cli ls "$KEEPASS_DB" "/"
Insert password to unlock /home/guillaume/test.kdbx: 
http://www.test.com/test/test2
```
```
user$ keepassxc-cli show "$KEEPASS_DB" "/http://www.test.com/test/test2"
Insert password to unlock /home/guillaume/test.kdbx: 
Title: http://www.test.com/test/test2
UserName: 
Password: 
URL: 
Notes: 
```

So my question / feature request is: is there a means to protect '/' when calling the add command of the CLI?

**Comment by vi-n** [comment]
I have been looking into fixing this. It's harder than it looks. In your example, the $title being passed to keepassxc-cli add is stil `https://www.academia.edu/` because the shell will eat the \/ into /. 

You could make it work by double escaping the backslash, making it title=https:\\/\\/www.academia.edu\\/. 

Than you can make it work. If that's acceptable I can send a pull request.

Another option would be to specify the group seperately...
