### ISSUE TITLE
Feature: Using DuckDuckGo for favicons

### ISSUE THREAD

**Issue by nfitzen** [keepassxreboot/keepassxc#2258]
I see that in the settings one can use [Google] for downloading site favicons in case there's no favicon.ico. Can you also add [DuckDuckGo]'s favicon service to this? The format for the image is `https://icons.duckduckgo.com/ip3/www.example.com.ico`

For example, [Google]'s icon is here: https://icons.duckduckgo.com/ip3/www.google.com.ico

Thank you for reading.

[google]: //www.google.com/
[duckduckgo]: //duckduckgo.com/

**Comment by TheZ3ro** [comment]
seems a very good alternative to the google service

**Comment by RealOrangeOne** [comment]
With some testing, it also looks like the DuckDuckGo API parses the HTML `meta` tag rather than naively looking for `/favicon.ico`, which is really nice! Should drastically increase the hit-rate of icons

**Comment by kneitinger** [comment]
I'd like to work on this issue this week, if nobody else has plans to.

Also, to clarify, although @nfitzen originally said "also add", should we consider simply replacing Google with DuckDuckGo?

**Comment by kneitinger** [comment]
I've implemented this, as well as a fix for #2265, but this will be my first PR for this repo, and I have a couple of questions before opening it.

1. I've changed the messages `Hint: You can enable Google as a fallback under Tools>Settings>Security` and `Use Google as fallback for downloading website icons` to reference DuckDuckGo; how do I deal with translations?  Edit only `share/translations/keepassx_en_US.ts`?
2. When I run `make format` from my build dir, it modifies ~110 other files, should I skip this step, and only run `clang format` against my files?

Thanks!

**Comment by droidmonkey** [comment]
Good deal, for (1) don't worry about translations, that is handled by Transifex separately from GitHub. For (2) don't run format at all, we will take care of formatting if necessary.

**Comment by gilluc** [comment]
thank you.
i added : width="32" height="32"

**Comment by qs-arno** [comment]
I see that this issue is closed, but just in case anybody's still paying attention, I randomly ran across a third option for a favicon service while I was trying to remember DuckDuckGo's URI for it; you can also use Yandex.  It has a really cool feature that you might find useful when mass-retrieving favicons, in that you can specify more than one domain and it'll return a single PNG "sprite sheet" with all the favicons at once.

For example, a regular request like this will return a 16x16 PNG with Google's favicon:

```sh
curl -o google-favicon.png "https://favicon.yandex.net/favicon/google.com/"
```

However, this will return a single 16x48 PNG "sprite sheet" with all three favicons (I just checked with a deliberately-bogus name, and if a domain doesn't exist it still puts a 16x16 spacer in its place, so you can rely on the positioning of each requested favicon image even if one or more is "missing"):

```sh
curl -o alphabet-favicons.png "https://favicon.yandex.net/favicon/abc.xyz/google.com/youtube.com/"
```

I found this information here: https://blog.jim-nielsen.com/2021/displaying-favicons-for-any-domain/

On the minus side, it looks like Yandex is -- or soon will be -- tightly intertwined with the Russian government.  This may not really have any practical impact on a straightforward service like favicon retrieval, but it may sting from a morality/ethics standpoint so I figure with the current climate it's worth pointing out: https://techannouncer.com/yandexs-bold-move-leaving-russia-amid-censorship-challenges/
