### ISSUE TITLE
Discussion: Information about database key files

### ISSUE THREAD

**Issue by HanaO00** [keepassxreboot/keepassxc#2272]
Hello, I have some questions about keepassXC :

I do not know why, I wanted to change my .key file because I got a notification telling me it was an old format, and it broke the database, someone would know why ?

I did another one, but I was wondering, with keepass I had generated a .key file with the mouse, there it is done without that part ?

Is the database file compatible with older versions?

I used to connect my usb key, open keepass and disconnect the usb key, but here I have a message that tells me that the data could not be written on the usb key, is it okay to break the database? Because I do not write anything I open just keepass

**Comment by thatmatt24** [comment]
I'm having the same issue. 
It was working right before I had to reinstall xcode for something else, don't see how that could be related but it was from one minute to the next. 
Also updated to mojave, so that could be the issue as well. 

Seems that its reading the .key file for the "Key File" as a Keynote file, again not sure if this has anything to do with it either. But those are the steps to reproduce my errors - xcode and mojave updates.

**Comment by phoerious** [comment]
Just use a new file with random contents. You can create one from the master key dialogue.

The main reason fir deprecating these key files is actually not the lower entropy, the main reason is that the old-style key files do nothing but wrap a fixed 32-bit random string in various formats such as XML or plain hex ASCII armour, whereas the sensible way would be to just have a file containing these raw 32 bit of data without the need for content detection. The file is hashed again, so the security aspect comes into play when you consider that the 32 bit of source data may not map into the full 32-bit target space, effectively reducing the entropy a little by unwanted collisions. Having a fixed 32-bit secret is also not useful in case we want to use another hashing function in the future, which creates longer hashes.

**Comment by bodograumann** [comment]
I am trying to understand what you’re saying, @phoerious.
One major difference to the old format is that now the generated key file is not human readable anymore. I had backed up my previous key file on a piece of paper. Probably, because it was suggested by keepassx and it made sense, that this would be a much more durable backup.
This is not possible anymore with the new generated key file. So which way is *sensible* depends on your point of view.

I also don’t quite understand: don’t you still have to do content detection, if you want to support the old-style key files? Or maybe you always just ran a hash function over the key file?

**Comment by phoerious** [comment]
You can still use a key file with ASCII contents if you like.

**Comment by bodograumann** [comment]
As much is clear. I just didn’t completely  understand why that is not the default anymore.
If my key file is pure ASCII, will I still get the warning regarding the legacy key file format?

**Comment by droidmonkey** [comment]
No, that format is very specific and is explicitly detected.
