### ISSUE TITLE
Autotype popup with _NET_WM_STATE_ABOVE

### ISSUE THREAD

**Issue by foosinn** [keepassxreboot/keepassxc#2300]
## Expected Behavior

The popup window should have `_NET_WM_STATE_ABOVE` as _NET_WM_STATE.

## Current Behavior

Currently following options are set: `_NET_WM_STATE_ABOVE` and  `_NET_WM_STATE_STAYS_ON_TOP`

## Steps to Reproduce (for bugs)

Install i3 window manager and open the browser in fullscreen. Press the autotype keybinding.
The window is not visible until you leave fullscreen mode.

## Context

I3 Issue: i3/i3#3411

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.6-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by akobel** [comment]
On a closely related note, it'd be great if the popup window could be distinguished from the main window by, e.g., WM_CLASS.
Use case: I map keepassxc to some dedicated default workspace on startup; i3 supports this via regex matching of WM_CLASS. But I would like the popups to open on the *currently* active workspace rather than the dedicated space (which I'd like to only visit when making changes to the entries). AFAICS, this is not possible right now since both popup and main window have the same class entry, so I can only redirect all or nothing?

(Please ignore if I'm asking for something inappropriate, e.g. if the WM_CLASS should be identical. I'm neither an expert concerning the ICCCM spec nor w.r.t. i3's matching facilities, which IIUC only cover a subset of the ICCCM-prescribed window properties. E.g., WM_TRANSIENT_FOR seems somewhat apt, but I can't seem to use it for matching in i3, nor does a rule of the type _NET_WM_STATE ~= _NET_WM_STATE_MODAL seem to be available.)
