### ISSUE TITLE
Use keepassxc.ini from same directory if present.

### ISSUE THREAD

**Issue by fcore117** [keepassxreboot/keepassxc#231]
Please add ability to read and use keepassxc.ini if present in same directory as KeePassXC.exe. Perhaps in future add ability to portable Linux versions too.

**Comment by phoerious** [comment]
Any reason why you can't simply copy it over?

**Comment by droidmonkey** [comment]
This is a great idea to easily enable a portable version

**Comment by jean-sh** [comment]
I'm a beginner when it comes to contributing to open source projects but I think I can work on this issue.

Can someone detail a little bit what needs to be done so that I know I'm doing the right thing?

Is it just making it so the keepassxc.ini file gets created in the same directory as the keepassxc binary and use it if it already exists?

**Comment by phoerious** [comment]
I would make it an option. "Save configuration to installation directory" or something.
If you need further assistance, I think it's better you hop on IRC #keepassxc-dev.

**Comment by TheZ3ro** [comment]
I think the best is adding an option like "Make KeePasXC configuration portable" or something like that. 
The default behavior should be loading the correct ini from configuration file and the portable should be an option

**Comment by droidmonkey** [comment]
I dunno, I like the idea of looking first in the same directory and then going from there. It eliminates the need for a question or additional option while keeping the original behavior.

**Comment by TheZ3ro** [comment]
I think the average user on most platform wants/needs an installed KeePassXC. The portable is more a Windows optional thing

**Comment by droidmonkey** [comment]
Right, so if it is installed there won't be an ini file in the install directory.

**Comment by phoerious** [comment]
I'm not sure if I like that. It's a little too technical. And then we are getting reports by users who just open the ZIP file, double click the EXE, click OK to extract everything to a temporary location, close the app and then wonder why their config is gone.

**Comment by fcore117** [comment]
I use portable apps on Linux too much as possible, i hate when settings are put on userprofie. I have usb3 fast drive and absolutely everything runs from there(ext4 for Linux and NTFS Win)

**Comment by TheZ3ro** [comment]
@fcore117 that is your workflow, but it doesn't mean it the right or the average workflow.

I also agree with @phoerious on the "hidden" feature, users won't really know where those config come from unless reading the manual.

Anyway currently KeePassXC will create the file in the config path if it doesn't exists, filling it with default values. So the config file will be created on the first use.

We can't really do this without an user specified option.
We detect if the non-portable file exists and the if the portable file exists.
If they both don't exist which one should be created? If we create the portable one KeePassXC will always load as portable, and vice-versa. Also if we release KeePassXC with the config file (portable or not) it will always load that file because it exists.
The only solution in the described behavior is letting the user create the config file where he want but this will be easily replaced by an option in KeePassXC

**Comment by fcore117** [comment]
Yes it might be option based too where you choose make KeePassXC portable and .ini is moved to own directory.

**Comment by jean-sh** [comment]
What about an option that defaults according to what version is run?
Check both locations: if the file already exists, use that one. If not, check the version: if installed version: default to the separate config directory; if portable version: default to the same directory as the executable.
That way it is handled transparently but the option is available for users to select the directory manually.

**Comment by fcore117** [comment]
With every release it becomes better and better, now i have used it weeks and works great. Deleted old bloat and slow keepass. 

I am great user of usb3x raid drives and constant keepassxc re-configuring is quite a pain, i hope devs will find very best solution for portability that works on Linux and on Win.

**Comment by highend** [comment]
Any news on this? I would even take a command line option like
```
keepassxc.exe --ini=".\keepassxc.ini"
```
Where you can either use a relative (to the folder where keepassxc.exe lives in) or a fixed path...

**Comment by qezzo** [comment]
Since there are no news on this feature in the last few months, the download page for windows should be changed. It say portable, but it is not. At least the name is misleading.
https://keepassxc.org/download#windows

**Comment by droidmonkey** [comment]
I am going to implement this for 2.2.0, likely today.

**Comment by fcore117** [comment]
Wonderful news, no more losing options when reinstalling Win/Linux and can keep setting well on my portable usb raid drive.
