### ISSUE TITLE
keePassXC-Browser not working on Firefox with 2.3.4

### ISSUE THREAD

**Issue by Etuldan** [keepassxreboot/keepassxc#2398]
With the new 2.3.4 release of KeePassXC, the browser extension isn't working on my Firefox.
Base is connected (according to extension), but Field Detection return nothing.

## Expected Behavior
In 2.3.4, when visiting a website with login form, when clicking on a field, a KeePassXC-Browser list should appear.

## Current Behavior
Login suggestion list doesn't show up.

## Steps to Reproduce (for bugs)
Install 2.3.3. Setup at least a keepass entry with the URL set. Visit the URL in Firefox. KeePassXC-Browser should either ask authorisation for this website (if not set before), or display a list of logins when html field is selected. URL of one of my entry is `google.com`, and I tried to visit `https://mail.google.com` in Firefox.
Update to 2.3.4. List doesn't show up.

## Context
I reverted to 2.3.3, and it's working.
Tried in 2.3.4 to "Disconnect browsers" and "Cleanup authorisations". Both Firefox and KeePassXC 2.3.4 have been fully shutdown.

## Debug Info
KeePassXC - Version 2.3.3
Révision : 0a155d8

Bibliothèques :
- Qt 5.10.1
- libgcrypt 1.8.2

Système d’exploitation : Windows 7 SP 1 (6.1)
Architecture processeur : x86_64
Noyau : winnt 6.1.7601

Extensions activées :
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This will be fixed in 2.4. See #2253

**Comment by drrobotic** [comment]
i had the same issue, but now even with 2.3.3 the website detection is not working anymore. i created new keepass files, i removed public keys and reconnected the databases, its just not detecting the website and its credentials. (saving new credentials works)
its not working for months now, i hope 2.4 will fix this. perhaps you should consider to create hotfix releases because browser integration is keepassxc main feature.
