### ISSUE TITLE
Autotype picks the wrong window in multi-monitor setup [MacOS] 

### ISSUE THREAD

**Issue by dovecode** [keepassxreboot/keepassxc#2401]
## Expected Behavior
When pressing the global hotkey for autotype, the user name and password should be entered into the application window that the user had focus on.

## Current Behavior
KeepassXC sometimes picks the wrong window of the application. This seems to happen when there are multiple windows of the same application (e.g. browser windows) open on different monitors.

## Possible Solution
No idea. This is probably related to MacOS "alternative" window switching behavior.

## Steps to Reproduce (for bugs)

1. Configure multi-monitor setup
2. Open an application that support multiple windows (e.g. Firefox)
3. Place a window on every monitor
4. Press the global autotype hotkey
(step 4 might be tried in different windows on different monitors -- I have yet to find a pattern)

## Context
This ends up with passwords in URLs, submitted in forms, etc. The information leakage is pretty bad!

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Auto-Type needs some fixes in general. Unlocking from Auto-Type when there is another database open also focuses back the KeePassXC window.

**Comment by jazzschmidt** [comment]
In my case, when using Auto-Type via hotkey, the main window is focused instead of the Auto-Type list. This happens for applications, that have or had multiple windows even on the same desktop. Moving the main window to that desktop Auto-Type works most of the time.

**Comment by droidmonkey** [comment]
Adding this to my Auto-Type overhaul for 2.7.0

**Comment by Pointy** [comment]
Still happening for me with 2.7.0. I have two Safari windows open, one on the same monitor as KeePassXC (where I want the auto-type to take effect), and one on a different monitor. Performing autotype in this situation seems to always, or almost always, type into the Safari window in the other (not primary) monitor. I've got my Mission Control set up such that the primary monitor (the one where I want the action to work) has a few (like 4 or 5) desktops, and the other monitor has 1 or 2.

I'm on a basically brand new MacBook, fully updated.

**Comment by mrkeuz** [comment]
Faced with quite same issue on Linux. 

When database LOCKED and you try Auto-Type from global shortcut - dialog appears on latest position (i.e. on other screen). Very uncomfortable.

Need another issue for this?

Env:
KeePassXC 2.7.1 (snap)
Ubuntu 20.04 (x11, gnome)

**Comment by pietryna** [comment]
@droidmonkey I'm facing the same issue for MacOS 15.2 and KeePassXC 2.7.9. 
When I have two windows of app (e.g. Firefox) autotype chooses main one (the first one that has been opened) not the one I'm focusing on, which has been popped out from "original window" with tab drag&drop.

Also there are certain windows (currently pickchars part of www.ing.pl login page and MacOS native OpenVPN password typing window) where global autotype shortcut does not invoke autotype menu. Not sure if there's issue for this.

**Comment by droidmonkey** [comment]
We are not going to chase down individual instances of window focus problems. It wastes a lot of time trying to setup the exact replication scenario. Your best bet is to just not have that scenario in the first place or figure out a better way to replicate it easily or fall back to copy/paste if all else fails.

**Comment by pietryna** [comment]
I'd really like to copy&paste if I could but those idiots are still using masked password instead of 2FA.

In general issue with choosing incorrect window is 100% reproducible in any scenario when you have like 2 windows of firefox on this MacOS. I just barely use autotype for browser due to nice plugin support. But plugin does not support pickchars that's why ING is the only place I have to use autotype for browser.

**Just open multitab FF window on MacOS, drag and drop one of the tabs to open second window, open there any login page of your liking and invoke global autotype there. Credentials would be typed in "original" window. This case works for any page, and is 100% reproducible.**

ING problem is more specific, that some windows (like mentioned MacOS OpenVPN app when you try to connect to VPN) just forbids to invoke autotype menu with global autotype shortcut. ING pickchars login is problematic, as you have to have valid account name to reach that part of login. OpenVPN would require some VPN connection asking for password.
But this issue is not that problematic. You can invoke global autotype menu at any other space, look for entry, change scope to the valid place you want to type and then hit "type sequence". This is minor to moderate problem.

But the original one, with incorrect scope is in my opinio quite severe. I've exposed parts of my cretentials (thanks to masked password, only few chars) over messenger because it happend to be on top scope of "original FF window".
Problem does not occur on Windows/Linux. Those systems seem to have different way of managing windows of apps which allow to open multiple instances. MacOS must group it somehow.

**Comment by droidmonkey** [comment]
@pietryna I cannot replicate this problem at all on macos. Two browser windows open, the auto-type always chooses the right one to bring to front. Make sure you don't have any third party tools installed that are trying to "control" which windows are brought to front.

**Comment by Pointy** [comment]
> [@pietryna](https://github.com/pietryna) I cannot replicate this problem at all on macos. Two browser windows open, the auto-type always chooses the right one to bring to front. Make sure you don't have any third party tools installed that are trying to "control" which windows are brought to front.

This is amazing, because reproducing the behavior is *absolutely trivial* on MacOS. Not being able to return to the proper window is the normal behavior on MacOS with this application. On occasion it does work, but generally in a situation with multiple monitors and multiple desktop/workspaces per window, it basically **never** works.

**Comment by droidmonkey** [comment]
A video would do wonders here

**Comment by Pointy** [comment]
I think this is a MacOS problem honestly, I seriously doubt that it's possible to overcome.

**Comment by pietryna** [comment]
@droidmonkey @Pointy Like, few days forward and it works... it looks that window is chosen correctly.
However as for Firefox, within "task manager" I have only one instance of app while, for e.g. for CLion I have 4 instances (3 projects and gateway). So it might be also related to the way FF "registers itself" in the system.

One chage is that I've installed 3rd party "dock" utility as MacOS native one is pointless to use in multi screen environment. It's more like older windows (whole mirrored to every screen). But each window has it's own tile, while MacOS dock is more like tile per app and then, from the list you can choose window.
However I really doubt, such UI application should make any difference.

**Comment by HanSyt** [comment]
I noticed this behaviour too on Linux. Setup: same computer, KDE Debian 12, working fine. Debian 13 (Trixie) autoype only uses the current screen. So I drag KeepassXC to the screen where I want to autotype and it works.
I guessed it has something to do with the focus following the mouse cursor. (different KDE 5 to 6).

After this I went to Window Behaviour in Setting, unselected Separate screen focus and that solved it.

![Image](https://github.com/user-attachments/assets/35c50209-cc5a-48b1-9005-6383a0183418)
