### ISSUE TITLE
Why is keepassxc HUGE?

### ISSUE THREAD

**Issue by pepa65** [keepassxreboot/keepassxc#241]
Not a bug as such, or even a feature request, more a question.
When I install keepassx from the repo in Ubuntu (16.04), the whole package is less than half a megabyte. But when I install keepassxc, the (snap) package is 75 megabyte. So I haven't tried it yet.

**Comment by phoerious** [comment]
The reason is that the AppImage and Snap Package need to ship all required dependencies (including Qt). When you install debs from the repository, the package is compiled for your specific system and therefore uses the libraries which are already installed on your system. You can try these (unofficial) DEBs if you want: https://github.com/magkopian/keepassxc-debian/releases

**Comment by pepa65** [comment]
Thanks for the link to the .debs. 1.5 megabyte is more reasonable.
(Unfortunately keepassxc suffers from the same lack of configurability as keepassx 2.)

**Comment by phoerious** [comment]
KeePass2 has far too many configuration options and KeePassX has too few. This release is still mostly based on KeePassX with a bunch of additional feature. The more features we add in future versions, the more configuration options we will probably get.

**Comment by TheZ3ro** [comment]
I think we can close this
