### ISSUE TITLE
Provide clear direction on database unlock dialog

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2445]
## Expected Behavior

New users will understand the different options on the unlock dialog, the meaning of the checkboxes, and the definition of "key file".

## Current Behavior

User confusion, especially surrounding the checkboxes and key files.

A picture is worth a thousand words:
![unlock_dialog](https://user-images.githubusercontent.com/2809491/47876106-d036b000-ddee-11e8-9a64-898c66ebac3f.png)

**Comment by notand** [comment]
Related request: Improve error message for database unlock dialog
### Current Behavior
If the user checks the "Key File" Checkbox in a case in which there is no key file (and if they enter some inappropriate file in the "Key File" field), the following error message is displayed: "Unable to open the database. Wrong key or database file is corrupt."
### Expected Behavior
Not exactly sure. Something like "Wrong key or database file is corrupt or Key File method falsely selected." Or: If the software can actually identify that the entered key file is not really a key file, throw an extra error message dedicated just to this specific error.

**Comment by notand** [comment]
Do key files have a specific format or are otherwise identifiable by the program? If yes, modify the Key File Browsing functionality.
### Expected behavior
In the Key File field, the user can only select a file of an appropriate format. Particularly, the user cannot select a .kdbx file.

**Comment by phoerious** [comment]
A key file can be anything.

**Comment by macau23** [comment]
"Wrong key or database file is corrupt" is scary.

**Comment by droidmonkey** [comment]
Fixed by #3287
