### ISSUE TITLE
Detect window-specific autotype sequence when performing CTRL+SHIFT+V

### ISSUE THREAD

**Issue by ShosMeister** [keepassxreboot/keepassxc#2490]
## Expected Behavior
Browser login should use main auto-type setting of {TAB} and ssh/putty session should use window specific auto-type of {ENTER}

## Current Behavior
Selected custom window association and checked to use a different auto-type sequence. Main sequence has a {TAB} and the custom has an {ENTER} between the username and password. On linux, this does not appear to work as when the autotype is selected with the window active matching the title, it still uses the {TAB}.

Could be that I missed something in the setup but seems pretty simple. Have not the easy ability to try on another platform at this time.

## Context
What I have is an entry that has both a web interface and the ability to SSH in via command line or something like putty. The main is setup to auto-type {TAB} between the username and password while putty/SSH needs to have {ENTER}. When opening the putty session, the window title is defined specifically to match XC's expectation - was selected in the pulldown upon creation of window association - yet the auto-type still does not use {ENTER}.

## Debug Info
KeePassXC - 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.5 LTS
CPU architecture: ESXi 6.0 and later (VM version 11) x86_64
Kernel: Linux 4.4.0-138-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration
- SSH Agent
- YubiKey

**Comment by kneitinger** [comment]
I'm having a little bit of trouble replicating this behavior. I have a github entry that only use for logging into the browser since I use ssh to clone/push/etc, so I edited it and tried to clone a private repo through the cli with https instead of ssh to get a login prompt:

Steps:
- I typed `git clone https://github.com/kneitinger/A_PRIVATE_REPO.git` into my terminal and hit enter.
- When that command was waiting for my input, I went to keepass and created an association to that window (verbatim), using the drop down menu.
- I set the autotype sequence for that association to `{USERNAME}{ENTER}{PASSWORD}{ENTER}` and saved the entry
- I disabled all of the autotype match broadening options
![2018-11-18_20-53-34_autotype-match-broadening](https://user-images.githubusercontent.com/5200550/48687089-3e5fce80-eb74-11e8-92b7-477950d5bb44.png)
- Returned to terminal and pressed global autotype shortcut. Presented with only my window association's sequence
![2018-11-18_20-55-28_correct-sequence](https://user-images.githubusercontent.com/5200550/48687119-7109c700-eb74-11e8-9300-faeb29413a0d.png)
- Selected that sequence:
```
Cloning into 'A_PRIVATE_REPO'...
Username for 'https://github.com': kneitinger
Password for 'https://kneitinger@github.com': 

# Note that the password line is displayed and it has my username (which is
# whatever is typed on the previous line) populated.
# If I use the default `{USERNAME}{TAB}{PASSWORD}{ENTER}` sequence I see:

Username for 'https://github.com': kneitinger	sUp3rSecuR3p@55w0rd
Password for 'https://kneitinger	sUp3rSecuR3p@55w0rd@github.com':
```
- Repeated process with "Always ask before performing Auto-Type" and same results
- Re-enabled the match broadening settings, and was presented with the choice of both github sequences (even with ask disabled, because of match ambiguity), but never had the tab sequence type on its own.

Were you steps different?  Can you copy the window title that is stored in keepass, and also the output of `xprop` on the window you're trying to target (edit out anything that may be sensitive :slightly_smiling_face:)?  If you're unfamiliar with `xprop`, you type it in, hit enter, and then click on the window you want to see the properties of (in this case the terminal with the login).

Thanks in advance!

---

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.16-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by forty8bits** [comment]
I think part of the issue here is that KeePassXC seems to get the prioritisation of autocomplete sequences wrong. I expect intuitively that if I've set a custom sequence for a specific window title, that it should take priority over others when autocompleting into that window, but it doesn't; when I attempt to autocomplete using the global shortcut, I'm prompted with both options, but the first option is the generic default autocomplete sequence, so I have to manually select the correct one below it (clunky). This is made even worse when using the CTRL-V shortcut on a highlighted entry from the KeePassXC window itself, as this doesn't seem to prompt at all and just defaults to the generic sequence.

**Comment by droidmonkey** [comment]
We will not be implementing this due to the new Auto-Type selection dialog being far more robust.
