### ISSUE TITLE
IOS and Android app using flutter

### ISSUE THREAD

**Issue by kishaningithub** [keepassxreboot/keepassxc#2545]
As [flutter](https://flutter.io/) has reached its [1.0](https://developers.googleblog.com/2018/12/flutter-10-googles-portable-ui-toolkit.html) stage. Do you have plans to make an official ios and android app using the same?

I am thinking of creating a library to read and write kdbx files in dart and then create ios and android apps using the [flutter framework](https://flutter.io/) on top of it. What do you think ?

**Comment by droidmonkey** [comment]
We have no plans to produce a mobile app. We are discussing the possibility of creating a "libkdbx" from our core code, but that would be in C++ using Qt.

**Comment by kishaningithub** [comment]
When there is an official [browser extension](https://github.com/keepassxreboot/keepassxc-browser) why not a hybrid native app ? I personally feel this is the only missing link affecting the widespread adoption of keeppassxc.

**Comment by vnagendra** [comment]
@droidmonkey - what is the status of this? https://github.com/keepassxreboot/keepassxc-specs. Maybe the core team isn't currently planning to develop App - no worries, I am sure someone in the community would be interested.. Just trying to figure out what it would take (I am interested) 

I can see an MVP being 

1. Support for Cloud Files (kdb files on iCloud or similar for Android)
2. Support for TouchId (some kind of biometric Id, even though I am saying TouchId)
3. Decent UI/UX, to see/search/copy

I am purposely not including generation as that would require hopping into C++ land, which IMO Flutter isn't all that great with. 

@kishaningithub - I'd be interested in collaborating...

**Comment by droidmonkey** [comment]
This would take a separate team (one with mobile experience and the toolchains and testing gear necessary) to adopt the product. It would only be truly "ground breaking" if you are running the libkdbx in native code to gain a tremendous speed boost over Java/Kotlin/Dart/C#. If an MVP is developed with bindings to a minimal libkdbx we could adopt that into our GitHub organization and let a team loose on it.

**Comment by phoerious** [comment]
I will have some time over the holidays I think (hope). :-)

**Comment by vnagendra** [comment]
@droidmonkey - Thanks. Just to make sure I understood your references correctly 

> that is currently being worked on by @phoerious

*that* here refers to 

> a minimal libkdbx

and *not*  the MVP? 

I am not entirely convinced that a speed boost *should be* the goal here. I am not saying that's not important, having a unified c++ (or whatever) code is good from a security standpoint - less things to go wrong, whether it's the implementation or the underlying libraries that support crypto. 

While I don't profess a lot of experience in the Dart or Kotlin crypto toolkits - the idea of all the "front ends" (like Apps, MacOs or whatever) having their own crypto implementation - isn't appealing. 

However if we were to go down this path with Flutter + libkdbx (which is where the thread started) -- we will need to wait for this - https://github.com/flutter/flutter/issues/7053

**Comment by phoerious** [comment]
I think that referred to the keepassxc-specs repository.

**Comment by vnagendra** [comment]
hahaha. Perfect. I wasn't even close :)

**Comment by droidmonkey** [comment]
They really 1.0'd flutter without native code bindings?

**Comment by droidmonkey** [comment]
What does FFI stand for, I never seen that acronym before. By "native" I am referring to code compiled down to machine language (i.e., not interpreted or byte code).

**Comment by vnagendra** [comment]
FFI == Foreign function interface

Basically in the Flutter world you can "talk to" a native *thing* -- the thing typically is a `ViewController` or `Activity`. This happens over what is called *Channels*. 

So in the Android world it's a little wonky -- but let's take the example of an iOS App. The Swift code (or Objective C) is generally compiled to binary. In the Android world - it's an APK, which is in byte code. 

Typically in a mobile App, especially in a cross-platform thing like Flutter -- when developers want to talk to *native* -- they are talking about a ViewController, Activity or somesuch. If you are coming from a C world though - you'll be thinking C libraries of some sort. In Java land this is JNI (I believe) -- I try to stay away from Java land, so my acronyms may be tiny bit off. In Swift this is just an external lib (either statically or dynamically linked) *in* your App (added as part of building the App). 

Flutter currently supports calling a ViewController, Activity etc., You could in theory currently just go *through* Java code to C++ land. This requires a lot of ceremony and magic incantations. 

The issue (on Flutter that I linked to) is talking about *directly* without ceremony calling C++ code (or some other object library). That is *not currently supported*. 

When that is supported, we can figure out a plan for supporting the C++ code provided by KeepassXC rather than writing our own code to do the crypto parts. I am happy to pitch in and help out.

**Comment by droidmonkey** [comment]
Cool thanks for the explanation. I have a good amount of Android app experience using Java and then Kotlin. I don't want to learn Dart just yet so I am holding off on Flutter atm.

**Comment by droidmonkey** [comment]
So I took the dive into Flutter (and Dart) and actually enjoyed it. Very easy to use. I absolutely hate the endless closures and indentations though.

**Comment by andreadelfante** [comment]
Hi, is there any news about using flutter for a cross-platform mobile keepassxc version?

**Comment by droidmonkey** [comment]
Not going to happen anytime soon. There are plenty of great Android apps and one actively developed iOS app that is fully compatible.

**Comment by vnagendra** [comment]
Well it couldn’t have happened until now anyway. Finally looks like Dart 2.5 now supports FFI - so any projects that may want to do this can finally start. It was also released today (it appears)

**Comment by SVilgelm** [comment]
> one actively developed iOS app that is fully compatible.

@droidmonkey Could you tell a name of that app? I found only strongbox.

**Comment by droidmonkey** [comment]
Strongbox is the recommendation.

**Comment by SVilgelm** [comment]
> Strongbox is the recommendation.

Thanks

**Comment by keepassium** [comment]
> Strongbox is the recommendation.

@droidmonkey, I might regret asking this in public, but is there a reason why KeePassXC's endorsement omits KeePassium?

**Comment by droidmonkey** [comment]
Maturity mainly, tbh

**Comment by keepassium** [comment]
> Maturity mainly, tbh

Fair enough, thanks for the response.

**Comment by OLLI-S** [comment]
What is annoying in KeePass and KeePassXC is that there are no **official** mobile apps.
I am forced to use apps from 3rd party developers (like KeePass2Android) that look and behave different than KeePass/KeePassXC and that have slightly other features than KeePass/KeePassXC.
This is the main argument why some of my colleagues use Bitwarden, LastPass, or 1Password.

I fear that this is too much work for this project and that this idea gets rejected.
But I suggest it anyways, because it is important for a good usability.

**Comment by OLLI-S** [comment]
@droidmonkey How much money must be donated for this feature request?
If you **really** think about creating an Android app, then I would donate 50 Dollar for this.
But I will make my donation later, when you plan to start with this feature!

**Comment by droidmonkey** [comment]
This feature request would cost about $15,000 if you want to be realistic. :smile:

**Comment by OLLI-S** [comment]
> This feature request would cost about $15,000 (minimum) if you want to be realistic. 😄

😱 SHOCK

**Comment by ArminWeb** [comment]
I also want to have an Android app

**Comment by OLLI-S** [comment]
@phoerious suggested in a chat that maybe a cooperation with Keepass2Android (we use the Keepass2Android app with a KeePassXC rebrandung).
This sounds reasonable and avoids an implementation of an app that is already existing.
So I posted his idea here.

**Comment by phoerious** [comment]
Careful, before we spread rumors here. That is what I see as the most probable path something like this would happen. It does not mean in any way that the KP2A maintainer is on board with this, nor have we even asked him.

**Comment by OLLI-S** [comment]
@phoerious Sorry if my posting was misunderstood (or mot written correctly).
I should have written that a cooperation might be an idea.

**Comment by phoerious** [comment]
It's alright. I just don't want somebody to read this, take it as a fact, and write a blog article about it or so. This is a rather large project after all.

**Comment by phoerious** [comment]
We do not have any immediate plans or capacity for developing separate mobile apps at the moment. The development of a simple mobile UI for a libkdbx may become simpler in the future, though: #5717
