### ISSUE TITLE
Add Yubikey Challenge-Request as 2FA

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#26]
All the details in this PR https://github.com/keepassx/keepassx/pull/52
Maybe @kylemanna can help

**Comment by droidmonkey** [comment]
Is YubiKey popular? I would much rather add something like Google Authenticator 2FA.

**Comment by TheZ3ro** [comment]
Yubikey also works as OTP (TOTP as GoogleAuthenticator).
It Would be nice to select between 2FA method (OTP or Challenge-Response) to support both

**Comment by stmllr** [comment]
yubikey supports challenge/response, so 2fa would even work offline in opposite to Google Authenticator.

**Comment by TheZ3ro** [comment]
Google Authenticator works also offline because it's [Time-based OTP](https://en.m.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm) (after the first sync online).
[Here](https://www.serverstack.com/blog/2013/02/21/implementing-totp-authentication-into-your-infrastructure/) a guide to implement TOTP with GAuthenticator (maybe can help), but this will take some time to develop.

**Comment by kylemanna** [comment]
re: @TheZ3ro @stmllr 

The YubiKey challenge response works completely offline.  Google Authenticator and all TOTP mechanisms don't make any sense as they don't enhance the crypto key.  They are usually used by a remote "trusted" third party (i.e. Google, Lastpass, etc) to control access to actual encrypted payload.

My implementation of the YubiKey challenge-response optionally adds strength to standalone key files and static passwords by hashing all the combinations together to generate a stronger key.  This process occurs completely offline with just the YubiKey, supporting host libraries and KeePassX with this pull request.

**Comment by kylemanna** [comment]
To restate this: 

TOTP controls access to the encrypted payload in the case of services like lastpass.

Challenge-Response makes the encrypted payload key stronger. If done right, challenge-reponse would force someone to attack the crypto cipher instead of brute forcing or guessing passwords that in standalone implementations are the basis for the key.

**Comment by TheZ3ro** [comment]
Can you rebase your PR on the KeePassX Reboot code? (On the develop branch, or in a feature/* branch) Thanks :+1:

**Comment by kylemanna** [comment]
Honestly, I don't have the time in the near term.  The most time consuming part is verifying that all the edge cases (that I can remember) work so that people don't lose their databases due to something silly like corruption since it does manipulate the way the crypto key is derived.  Let's revisit it sometime down the road.

**Comment by TheZ3ro** [comment]
I will try to rebase your changes, If I need help I will ask you 😅

**Comment by TheZ3ro** [comment]
I will try to rebase your changes, If I need help I will ask you 😅

**Comment by droidmonkey** [comment]
@kylemanna great explanation and that makes perfect sense, thank you!

**Comment by Thynix** [comment]
@TheZ3ro Have you been able to rebase? Can I help?

**Comment by Thynix** [comment]
My bad, I now see that #127 is that rebased version.
