### ISSUE TITLE
Auto-Type key modifiers not implemented

### ISSUE THREAD

**Issue by dotancohen** [keepassxreboot/keepassxc#2603]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
The string `%d` in the Autocomplete field should send `Alt-D` to the application.

## Current Behavior
The string `%d` in the Autocomplete field is sending `d` to the application.

## Steps to Reproduce
1. Replace the Autocomplete field for a website with `%d`.
2. Invoke autocompletion.
3. I expect the URL field to be focused, but instead a literal `d` was sent to the page.

## Context
Using Firefox 64.0 on Ubuntu Linux 18.10 with KDE 5 and KeepassXC 2.3.1 with no extensions.

**Comment by droidmonkey** [comment]
I am not in favor of that syntax at all. Bare words should never be interpreted as special actions. If anything it should be reversed... {%d} should execute ALT+D.

**Comment by mara004** [comment]
Possibly, a note that key modifiers don't work should be added somwhere in the documentation until they are implemented? Currently, the docs states by mistake that all keys mentioned on the KeePass website would be supported ([Quote](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences): "A complete list of supported actions and placeholders can be found at [KeePass Auto-Type Action Codes](https://keepass.info/help/base/autotype.html#autoseq) and KeePass Placeholders.")

I do agree with @dotancohen that KeePassXC should use the same notation as KeePass for this functionality (regardless of whether we personally like the syntax), so that people switching from KeePass can easily copy/paste their autotype sequences and do not have to learn two different notations. It would also make documentation easier if autotype was implemented in exactly the same way as in KeePass, then we could keep refering to KeePass.

**Comment by droidmonkey** [comment]
I'm just going to implement it
