### ISSUE TITLE
Support macOS keychain 

### ISSUE THREAD

**Issue by greuff** [keepassxreboot/keepassxc#2619]
It would be such a quality-of-life improvement if KeepassXC could remember the password in the logged in user's keychain.

**Comment by droidmonkey** [comment]
Please provide some use cases for this. Are you referring to using the keychain to unlock the KeePassXC database?

**Comment by greuff** [comment]
Sorry for not being verbose enough before. You're correct. Basically I'd like the same mechanism like with SSH for example. My SSH keys have passwords so that even when an attacker is somehow able to copy them, they're useless for him. But I don't have to type in that password every time I want to use them, because it is stored in the session's keychain. I think GnuPG can do the same.

**Comment by droidmonkey** [comment]
Yes this is very similar to #1403

**Comment by greuff** [comment]
I don't really get how this would solve my problem.

**Comment by candoz** [comment]
Any news on this? I'd really appreciate not having to insert two passwords at every startup.

**Comment by droidmonkey** [comment]
There are no plans to incorporate this within the next release.

**Comment by droidmonkey** [comment]
This will be implemented with the further improvement of Quick Unlock (this is a duplicate request).

**Comment by kvaps** [comment]
@droidmonkey could you provide id of the original issue or PR to track?

**Comment by droidmonkey** [comment]
Search for quick unlock

**Comment by kvaps** [comment]
guess this one https://github.com/keepassxreboot/keepassxc/issues/488
thanks

**Comment by habibalamin** [comment]
@droidmonkey the Quick Unlock doesn't seem to have anything to do with saving the KeePassXC DB master password to the macOS keychain. I'd like for KeePassXC to automatically search the macOS keychain anytime it needs to be unlocked; at login (autolaunch), on lid open, I don't care, I just want it unlocked.

Essentially, I want it to work like the macOS keychain, which automatically unlocks itself on login (when possible); it can do this since, by default, its password is the same as the user's login password.

If KeePassXC saves its master password in the keychain, it can automatically unlock itself, too.

My use case for this is that I use a certain app that has KeePassXC integration, but not Keychain integration. I store a single password in KeePassXC, just so that this app can autofill the password from the KeePassXC DB, but I don't want to have to manually unlock the KeePassXC DB, ever, just like I don't have to do that with my iCloud Keychain or Login keychain.

To be clear, I don't even want KeePassXC to ask for my fingerprint when it unlocks itself.

**Comment by droidmonkey** [comment]
Then why use keepassxc in the first place? Your requirements are not in alignment with our program

**Comment by habibalamin** [comment]
I use a certain app that has KeePassXC integration, but not Keychain integration. I store a single password in KeePassXC, just so that this app can autofill the password from the KeePassXC DB.
