### ISSUE TITLE
Plugin for KeePass 2 to use KeePassXC Browser

### ISSUE THREAD

**Issue by Skrelpoid** [keepassxreboot/keepassxc#2631]
It would be very cool if you could make a plugin for KeePass 2 so your new KeePassXC Browser extension works with the original KeePass. Since you already did this in the past with KeePass Http I think it is reasonable to do the same thing for your new browser integration.

## Expected Behavior
The plugin should to the user work the same as KeePass http but should use the method (named pipes I believe) that works with KeePass Xc Browser

## Current Behavior
Currently there's only the KeePass http plugin as for KeePass 2, which is deprecated

## Debug Info

Libraries:
- LIBS

Operating system: Windows
CPU architecture: x64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by yan12125** [comment]
I guess this is worth a look - https://github.com/smorks/keepassnatmsg

**Comment by droidmonkey** [comment]
I thought I saw that before, excellent!

**Comment by Skrelpoid** [comment]
Sadly KeePassNatMsg doesn't work that well. (see https://github.com/smorks/keepassnatmsg/issues/25)
The biggest problem for me is that saving the connection doesn't work. After closing KeePass and reopening it, KeePassXC-Browser doesnt recognize the connection anymore and I have to reconnect
![natmsg](https://user-images.githubusercontent.com/22478595/51593541-af17c400-1ef2-11e9-9b21-40024d809ce4.png)
The update notice is also kind of annoying.
Maybe someone here can fork the plugin and make a compatible version with the browser extension

**Comment by Skrelpoid** [comment]
It seems the new version of NatMsg works well. So a new "official" plugin is probably not needed

**Comment by auwsom** [comment]
It would be very useful to use plugins, such as this to sync to a cloud db file. Especially now that LastPass for mobile is $40/year.
https://sourceforge.net/projects/kp-googlesync/

**Comment by droidmonkey** [comment]
Tusk is no longer maintained and should be considered extremely high risk. We offer by far the most secure browser integration on the market.

**Comment by auwsom** [comment]
Thanks @droidmonkey, for the information. As I said, this is just for low importance accounts and signins, but good to know.

Re batteries included.. then could you include a method to sync a cloud file on Linux without having to install a heavyweight full sync app like GDrive? I guess this is where the plugins still shine. Stale, but at least they exist. 

Im sure theres some short snippet to sync a db file on a cron job, after setting up authentication. Probably semi-trivial, but also possibly semi-trivial for KPXC to suggest such a procedure or build in a simple sync option, which would then benefit many more people than just myself. 

Then again, there is still no remove duplicates function in KPXC, I think provided by the stock KP application, so I guess I wont hold my breath and go with the 'stale' plugin and 'unmaintained' extension. Thanks for your quick reply though..

**Comment by droidmonkey** [comment]
This isn't the issue to discuss this on, but there are so many great options to handle cloud file syncing on all operating systems. Why would we invest the time to integrate it into KeePassXC above other more important features that do not have alternatives?

https://github.com/gdrive-org/gdrive/blob/master/README.md

**Comment by auwsom** [comment]
Thanks again, also good to know, and its only 7mbs. You might want to provide a link to that in KPXC as one of the primary ways to sync. I know it may seem obvious, but the regular plugins are the first goto for many simply by convention. It is also nice to have a dedicated function and auth, so that if people can use a different G accounts (I think this GDrive only allows one, another reason why I dont use it, along with providing an open window right to my files if someone steals my laptop). At least a plugin is modestly obscured long enough for me to change all my account passwords. (And its not running in the background doing god knows what else for Google).

Also, are you saying 'remove duplicates' function has an alternative? What is more important than porting over the stock functionality? Don't get me wrong, I really appreciate the maintenance of these critical utilities, but the Keepass2Android app will sync with many clouds, so I just dont know why that is a difficulty here if this is the most maintained KP manager.

On a related note, like Tusk, KPXC doesnt seem like it will auto-ask and save passwords. Is that correct? So I have to save with Google, export and then import in KP, then sync to the android app. Its all a big pain. I realize its free compared with LastPass, but its not like this hasnt been done a hundred times before. (granted I realize recognizing *every* password field is a challenge, but simple ones should be easy). Thoughts?

**Comment by droidmonkey** [comment]
Our extension does ask you if you want to save new accounts / passwords when it recognizes them.

**Comment by auwsom** [comment]
Okay, that is good to know. I may use it for that purpose. 

re gdrive, I dont like having to install more things, because it one more thing I have to reinstall when reinstalling the OS, especially if they arent listed in an ubuntu repo, however after working on this what should be a simple problem for *hours* trying every solution I will list link to below for future searchers, I am giving in to this idea. Kubuntu has a kio-gdrive client, and according to where my search ended on a KeeAnywhere GitHub repo, it can be used, with caveats, to sync with GDrive (https://github.com/Kyrodan/KeeAnywhere/issues/18#issuecomment-599293246). There is also a solution using the dll from KeeAnywhere and Mono with KP portable 2.43, which is the in following issue comment in that link.

Unfortunately, though gdrive-org solutions is nice being precompiled and small, it fails in Ubuntu with error after opening the Google authentication link "Sign in with Google temporarily disabled for this app..This app has not been verified yet by Google in order to use Google Sign In.".

**Comment by auwsom** [comment]
Here is a discussion of KeePass with plugins on Ubuntu and either browser integration in general and that is more current: "KeePass and Ubuntu 20.04 Setup (with Chrome, Firefox)?" https://askubuntu.com/questions/1228389/keepass-and-ubuntu-20-04-setup-with-chrome-firefox
