### ISSUE TITLE
Use password *or* key file

### ISSUE THREAD

**Issue by aerique** [keepassxreboot/keepassxc#2662]
## Summary

As far as I know in KeePassXC it is only possible to use a password **and** a key file (like it was in the original KeePass).  So if you've configured both you'd need to enter both to open the database.

I would like to be able to have both a (long and strong) password configured and a key file for convenience.  So when either the password **or** the key file is entered the database is unlocked.

## Desired Behavior

When a password *or* key file is present the database should unlock.  So we're not using both together for extra security but we're using the key file as convenience.

## Possible Solution

I suspect it is not possible to unlock with a password or key file due to the encryption of the database, but I've been using KeePass and its descendants for years now and I've got hundreds of entries and the DB file is only 195 KB.

Perhaps it is possible to append two DB's together and save them.  One that can be unlocked with the password and one that can be unlocked with the key file.

## Context

As said: it's convenience.  I'm pretty strict with closing the DB when I've used it and entering the password gets tedious.  I also want to switch to a stronger password which would make it even more tedious.  So I'd like to be able to use a smartcard with PIN to provide the key file.

**Comment by gamesguru** [comment]
[LUKS](https://github.com/mbroz/cryptsetup) supports up to 10 keys per partition.

**Comment by droidmonkey** [comment]
That is great for LUKS but that is not how the kdbx standard was designed. We would break compatibility with KeePass and all other derivatives if we did what LUKS does. For the curious, LUKS encrypts a shared (constant) master key in each key slot using the user provided password (after a key transform). The master key being constant is the tricky part, if the master key changes (as it does in KeePass) on every save then you would need to enter ALL possible credentials to re-encrypt the master key in the various key slots.

**Comment by aerique** [comment]
Thanks for the elaborate explanation, that makes it a little easier to swallow :-)

**Comment by ValeCrafter** [comment]
It is kind of possible.
If you just write your password inside of a txt file and use that as key file it will work. At least it did for me on Windows 10. 
I understand that this brings a lot of security issues, but it is something to consider. The biggest problem is that you now basically have all your password exposed as if they were just written in a txt file. 
So only use this method with caution!

**Comment by droidmonkey** [comment]
Or spend $20 on a yubikey which will be far far more secure and requires no password if you choose not to use one.

**Comment by Freeedim** [comment]
To do this, I have been using dummy databases with an AutoOpen group pointing to the real one. For example:
- Real database with a very strong password
- "Dummy" database, only protected by a key file if you will (a Yubikey in my case), with a unique group "AutoOpen", containing a unique entry pointing to the real database with that strong password, and possibly with the "IfDevice" limitation that the auto-open operation only occurs on my laptop (see the [docs](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening "KeePassXC AutoOpen") for the AutoOpen usage).

### Result:
**On my laptop**, I only need to open the Dummy (with my YubiKey, but it could be with your key file), and it automatically opens the real database too.

On other devices, including  for people with whom I share the real database over the cloud, it remains the regular database with a strong password.

Of course, I realise it might not fit other use cases, for example based on CLI, scripting etc. especially since it opens 2 databases at once...

### Last note:

I have recently been considering adding yet another "Dummy 2" database pointing to the real database, for recovery purpose in case I lose/break my YubiKey and forget my strong password. "Dummy 2" would then be secured by a recovery secret, like an extremely long passphrase that I keep on a note in a drawer at home, or a key file that I keep offline in external drives, or a bought music/movie/eBook file (you can re-buy/re-download it if you lose or alter it) that I would keep among many other ones.
