### ISSUE TITLE
Bring main window to front when reopening database from browser extension

### ISSUE THREAD

**Issue by lazycrypt** [keepassxreboot/keepassxc#2668]
I am not sure if I'm missing an option, if the application is not behaving as it should or if this should be made into a feature request.

When pressing the Reopen database button in the KeePassXC browser extension the main window opens however it is not brought to the front/top but is instead still hiden behind the browser window. So I still have to manually get to the main window to unlock the database which kind of defeats the point of having the button in the browser extension.

This is happening on Windows 10, I have not tested it out on a Linux yet.

**Comment by lazycrypt** [comment]
Just tried it on Arch Linux (KDE) and it seems to bring the main window to the front (and then hide it) just fine. Is there an option to have this same behaviour in Windows?

**Comment by Vilx2** [comment]
Windows is trickier because it's picky about who can bring windows to the front. An application can't just bring itself to the front when it wants to - that would open the door to way too much abuse. In fact, that's just what happened years ago and is the reason why this restriction is in place. The "proper" way would be for the browser extension to get the "window handle" (aka "hwnd") from the KeePassXC main window and then bring it forward. But I don't know if it can call low-level APIs like that.

There are a few other times when an application is allowed to grab focus, but I don't think any of them are usable here unless you want to get hacky.

**Comment by droidmonkey** [comment]
This is implemented in 2.4.0
