### ISSUE TITLE
Search results without Backups

### ISSUE THREAD

**Issue by tulsmith** [keepassxreboot/keepassxc#2687]
Please consider a toggle which would allow display of search results without Backups. This could be an option in Settings or a button on the search results page.

**Comment by droidmonkey** [comment]
What do you mean by backups?

**Comment by markalston** [comment]
They meant the old password entries which are automatically stored in the group "Backup" when you change the password.  These old entries show up at the top of the search results because "Backup" is usually alphabetically before any of your actual groups.  This makes the search results fairly worthless if you have been using keepassxc for a long time.  

On some searches I have to page down the results many pages before getting to an actual current password result.
