### ISSUE TITLE
Allow keyboard shortcut customization in settings

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#2689]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I use a different clipboard manager that is configured to Cmd+Shift+V - which clashes with the autotype binding in KP-beta (v 2.4.0-beta1).

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
The autotype binding should be configurable for the installation of KP.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
I would like to use the key bindings like in the previous general release (2.3.4)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Different clipboard manager that is already configured for the same keyboard shortcut.

**Comment by droidmonkey** [comment]
This should really be expanded to allow for custom keyboard shortcuts for select actions in the application

**Comment by vraravam** [comment]
sorry - yes, that is more reasonable as a feature. would it be possible to prioritize it and get this working anytime soon?

**Comment by droidmonkey** [comment]
We can tee it up for 2.5.0

**Comment by vraravam** [comment]
I will cope with the mouse-click way of initiating auto-type till then. As I said, I am very keen on contributing by being a beta tester (I am a developer - but dont know C++, so, can't contribute via code) - so any interim beta releases, I can help test.

**Comment by reagle** [comment]
2.4.0 changed some of the shortcuts (requiring shift to open the URL or auto-type). Why was this changed, could we change it back with this enhancement?

**Comment by droidmonkey** [comment]
The change was for consistency. Data copying is now always CTRL+[key] and performing an action is always CTRL+SHIFT+[key]. You'll get used to it :wink:.

**Comment by vraravam** [comment]
but, shouldn't that choice be with the user? I kindly request you to reconsider and give this as a user-manageable option.

**Comment by droidmonkey** [comment]
Yes of course, in due time. That takes a lot of effort

**Comment by afontenot** [comment]
Coming over here from https://github.com/keepassxreboot/keepassxc/issues/4062 which was closed. This is a severe usability issue for me because of the terrible default which puts "copy password" and "make all my passwords visible" a single modifier key apart. 

I'm either going to have to quit using Keepassxc or compile it myself to fix this. I certainly couldn't recommend it to anyone else with such a major usability issue.

**Comment by remyvrs** [comment]
I have the same issue as previously stated by most of the of the other guys ...
Even though I can wait to have the feature implemented (custom modifiable keyboards shortcuts) I was thinking to share my workaround: instead of choosing the "perform auto-type" (by using the mouse) I took the time and configured the feature "Auto-type"> "Window Association".
The main selling point is that you can assign the "Global Auto-Type Shortcut" in the application's settings.

I thought that this might help someone ...

**Comment by tobalr** [comment]
Very interested in this feature as the CTRL + SHIFT + V  shortcut collides with the default shortcut for pasting in standard linux terminals.

**Comment by droidmonkey** [comment]
Why would that collision matter? Ctrl+Shift+V only works when KPXC has focus.

**Comment by remyvrs** [comment]
> Why would that collision matter? Ctrl+Shift+V only works when KPXC has focus.

actually the conflict I guess is that, while being inside the KPXC app, Ctrl+Shift+V is also preconfigured for some clipboard manager's actions.

**Comment by superlevure** [comment]
Hi ! 

Any news on that feature ? 
I would love to re-bind <ctrl> + W to closing the window instead of closing the database

Thanks for the great software !

**Comment by suckiden** [comment]
Hi,
I started using KeePassXC yesterday, but I was using original KeePass for many years already. The main reason I switched to KPXC is because of the browser integration and the slightly more modern UI.
Unfortunately I'm really missing the original KeePass options for custom shortcuts, as already mentioned by other users.
In order to be able to open/focus KeePassXC with a shortcut and using the ESC key to minimize the application I had to install AutoHotkey and write a custom script.
Now I ran into the same issues as mentioned. I'm not able to set a custom shortcut for auto-type and the pre-configured Ctrl+Shift+V is not an option for me as I'm using a clipboard manager (phraseExpress) which in fact does conflict even when KPXC is in focus.

Therefore I would really appreciate if the KPXC would offer a way to be able to customize the shortcuts. Remember, there is no right/wrong or more logical way of using shortcuts, just personal preference that's why the user should be able to set them.

Thanks though for the otherwise great software!

**Comment by chisou** [comment]
Just here to support this.
For me CTRL-SHIFT-V collides with a system wide 'unformatted paste' from a clipboard manager. That I don't want to change because it makes just so much sense to me.

**A note, though**: People who want to change these shortcuts are probably power users. So - it doesn't have to be in an UI. Configuration via the .ini file would suffice for some time.

**Comment by ritaelyn** [comment]
I decided to check out KeepassXC being a long time windows user of Keepass 2.X. I'm deciding to stick with keepass 2.X over not being able to rebind ctrl-shift-v (auto type) and crtl-shift-u (go to url) to just ctrl-v and ctrl-u. It's very disappointing and it's quite frankly a bad user experience. 

I highly suggest that all keybindings are editable and furthermore the windows build defaults to the same defaults as keepass 2.X.

**Comment by Kemeros** [comment]
![image](https://user-images.githubusercontent.com/15658976/140381807-8dd53d1d-6800-4ced-8d2d-42f6e20073fa.png)

@droidmonkey 
I guess this means we're not getting this very requested feature soon? :(

**Comment by Gumnos** [comment]
[as requested on Twitter](https://twitter.com/KeePassXC/status/1471520304421871617), shortcut-customization would also allow me to use control+{some key other than u} to copy the URL to the clipboard.

Currently if I `control+f` to Find an item, type "visa", it finds the item. However, with focus still in the find-box, hitting `control+u` clears the find-text instead of copying the URL to the clipboard. Hitting `enter` opens the detail of the entry rather than selecting it in the row below. I currently have to remember to hit the down-arrow (changing focus from the Find box, down to the list of matches), and then `control+u` behaves as expected, copying the URL to the clipboard.

FWIW, this happens on FreeBSD 13.0 (with `fluxbox` as my window-manager), but I had similar issues on Debian (also with `fluxbox`) and OpenBSD (with `cwm` as my WM)

**Comment by kadarmarton** [comment]
My thoughts:
- all kinds of keyboard shortcuts (like edit entry, etc) are a help, but Auto-Type shortcuts are by far the most important, as you use them much more often than anything else.
- an entry can have any number of additional attributes - this is already cool and is a must. But what they should be usable for, is any number of Auto-Type sequence that references them. For example some apps at work need my domain user, others my email address, with the same password. If accessing them without a VPN, an OTP is asked as well, when inside the company network, it is not.
- simplest example: working with git in both the terminal and a browser. The terminal wants Enter between username and password (or omit username altogether as it is set in git config), a browser frontend usually wants a Tab. And it is not the window title that should decide, but you, by selecting the appropriate keyboard shortcut. Controlling / identifying terminal and browser window titles with console and web apps running in them is not a reliable method.
- So in my opinion the current "Entries" / "Perform Auto-Type sequence" menu should be extendable by the user, who should be able to assign each a keyboard shortcut of his/her liking.

**Comment by ptar** [comment]
I came here to suggest Ctrl-Alt-C for Toggle Passwords Hidden instead of Ctrl-Shift-C (which collides with copy in Linux and is just to close to Ctrl-C in any system). Ctrl-Alt instead of Ctrl-Shift might fix some other problematic shortcuts like Ctrl-Shift-V. Ctrl-Alt can alternatively be typed as AltGr, which might be useful, too.

A well defined set of default shortcuts would be great, but customizable shortcuts would improve the usability even further.

BTW: Thanks a lot for 2.7.0!

**Comment by ReveStobinson** [comment]
This is the one thing I liked more about the vanilla KeePass 2.x. The shortcuts made more sense and had fewer collisions and near misses with other KeePass shortcuts and OS keys. My biggest gripe is the show/hide passwords feature. In KeePass 2, you could toggle it from within the database with `Ctrl` + `H`. And KeePassXC actually _does_ use `Ctrl` + `H ` to show/hide the master password when unlocking a database, but when you have it open, it reserves that for the ssh agent features which I never use.

Keeping the easy-to-hit shortcuts on the more popular features would be a start, but I think customization should definitely be the ultimate goal.

**Comment by isumix** [comment]
Hello! I would very much appreciate to be able to configure the keyboard shortcuts for autotyping: login, password, OTP, separately. Maybe defaults like: `CTRL+SHIFT+U` for username, `CTRL+SHIFT+P` for password...

Templating is not enough any more. As these days login forms are getting less user friendly with separate screens for login and password, and in the other app on the single form, and in the third app separated by some other controls. 

It would be beneficial to just remember the shortcuts once and autotype whatever is required.

**Comment by droidmonkey** [comment]
@isumix use CTRL+1 to CTRL+3 in the global auto type selection dialog.

**Comment by isumix** [comment]
@droidmonkey can you elaborate please? I didn't find where this dialog or any mention about this shortcuts in the docs. Obviously this key combination do nothing in my setup - KeePassXC 2.7.4, KDE, Debian.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type

See figure 70

**Comment by isumix** [comment]
Oh, I wasn't even aware of this functionality. Usually, I do everything from the main window. Thank you!

**Comment by kasumiru** [comment]
How can I remap the copy TOTP keyboard shortcut from Ctrl+T to Ctrl+X, for example? Also, remapping Ctrl+W for minimize (not for current discard db) is very necessary. Also hotkey for open from system tray.

**Comment by droidmonkey** [comment]
Coming in 2.8.0

**Comment by Mayurifag** [comment]
Oh, that was several year issue! Just realized I wanted to change several settings like close db -> close window and remove quit shortcut and was lurking to find a way to do that. I hope this settings will be saved in db itself (or might be a setting for that) and things will work across systems :)

Thanks for development!
