### ISSUE TITLE
YubiKey must press button twice in New Database Wizard

### ISSUE THREAD

**Issue by onlykey** [keepassxreboot/keepassxc#2704]
You have to press the Yubikey button twice when creating a database in Linux/Mac. Users may have thought that they just didn't press hard enough to trigger the Yubikey and so they press again but two presses are required to proceed. This only happens when creating a new database.

I tested this out on the last release, there was no issue there because it looks like the create a new database wizard is different. The issue can be reproduced on the beta release 2.4

**Comment by phoerious** [comment]
I assume you are referring to clicking the "Next" button on the encryption settings page and then once more to when we are actually saving the database, I assume?
That is because we need to transform the key once to determine good encryption settings and then we do it again when we actually save the database. There isn't much we can do here, except maybe reusing the previously transformed key. I already got rid of a third transformation a while ago (which was there due to me being a lazy or wary programmer who doesn't want to keep states around for too long).
I will see what I can do to fix this, but generally, we do not recommend activating button presses for HMAC-SHA1 on your YubiKey. It's just not how this mode is meant to be used.

**Comment by phoerious** [comment]
I correct myself: we still had three transformations. I submitted a fix which eliminates one of these. The other two are still necessary and we cannot really get rid of them. The first is to determine the KDF settings, the second one is the actual key transformation when the database is saved to disk. I eliminated one transformation in between that occurred after setting the master key.

**Comment by onlykey** [comment]
@phoerious I tested it out on 2.4.0 beta 2 and the issue has been resolved. Only one press is required to create a database now. Thanks!
