### ISSUE TITLE
Lock database on suspend/hibernate only (not on screen lock)

### ISSUE THREAD

**Issue by orzechow** [keepassxreboot/keepassxc#2753]
## Summary

I need an option to lock the database automatically on suspend/hibernate without locking on screen/session lock.

## Desired Behavior
In #2014 we ask to at least lock the database after system wakeup.

But a safer solution would be to lock the database right when/before suspend (but I don't want the lock on screen lock).

## Context

At work I need my passwords multiple times per hour, while I lock my screen very frequently (for meetings, nature’s call, …). 
I prefer to have to unlock the database max. 2-3 times per day.

So automatic database locking on screen lock is not an option for me.
Thus I use the inactivity timeout to lock the database.

But as I suspend my system session at the end of a workday, the database is often still unlocked on the next morning. This should not be the case. In fact it should already be locked before the system has been suspended.

## Debug info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.6.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18
CPU architecture: x86_64
Kernel: linux 4.4.0-138-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Locking on screen lock is already incredibly difficult, because there is no well-defined signal for it that works across platforms, not even across Linux desktop environments. Locking on suspend is even more difficult, because if there is a lock signal on a platform, it is not consistently sent before the PC goes into suspend mode (with the result that sometimes you wake up your PC and KeePassXC is still unlocked). This is kind of an inherent problem, because standby and hibernate are supposed to be entirely transparent to the system. Memory contents are simply preserved or dumped to disk from where they are later restored. No interruption of any process occurs. We can try to find ways to make it work more reliably, but it's damn difficult at least.

**Comment by orzechow** [comment]
Thanks for considering! If it's so challenging, I'd be glad if at least #2014 will be solved :)

**Comment by droidmonkey** [comment]
We won't implement this distinction since it is not consistent across platforms and with Quick Unlock capability the (time) cost of unlocking the database will be greatly reduced.
