### ISSUE TITLE
Support extra Places from KIO in KDialog

### ISSUE THREAD

**Issue by marco-parillo** [keepassxreboot/keepassxc#2796]
## SUMMARY

The full list of places seems unavailable in keepassxc that appears to use kdialog for the file menu when installed in a KDE environment

## STEPS TO REPRODUCE
1. Go to an app (I used keepassxc) and File Open (from Open Existing Database)
2. Right Click in the Places column
3. Add Entry
4. Reboot

## OBSERVED RESULT

The new entry is visible in Dolphin and Kate, but not Falkon or Keepassxc.

## Desired Behavior

All file dialogs should look the same.

## SOFTWARE/OS VERSIONS

Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.1
Kernel Version: 4.19.29-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7 CPU M 620 @ 2.67GHz
Memory: 3.6 GiB of RAM

## Possible Solution
Is it possible that keepassxc explicitly requests to only consider local files (file:// protocol). All other entries are thus hidden. Could there be a KIO support plugin for keepassxc, even through I not sure if this also affects the file dialog filtering.

## Context

I currently backup my database to dropbox, but I would like to consider my GDrive instead. Plasma offers kio-gdrive as a way of making that drive look almost local.

**Comment by marco-parillo** [comment]
Kate with places.
![KateWithPlaces](https://user-images.githubusercontent.com/32338352/54495954-d0c47480-48bf-11e9-87ed-4f11399f433b.png)

**Comment by marco-parillo** [comment]
Keepassxc without Places
![KeepassxcWithoutPlaces](https://user-images.githubusercontent.com/32338352/54495966-05d0c700-48c0-11e9-9158-9217fdee41c1.png)

**Comment by droidmonkey** [comment]
Please post debug information from kpxc.

**Comment by droidmonkey** [comment]
This is very likely a Qt "bug" that we cannot control. Please see my previous comment under gnome: https://github.com/keepassxreboot/keepassxc/issues/2469#issuecomment-437708523

**Comment by marco-parillo** [comment]
> Please post debug information from kpxc.

Would you please point to how I could do that? I might be too much of a newbie to do anything more than follow step-by-step directions.

**Comment by droidmonkey** [comment]
Help -> About -> Debug Info (tab) -> Copy/Paste into GitHub

**Comment by marco-parillo** [comment]
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.29-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by vetko** [comment]
@droidmonkey:
May I ask why this issue was closed?

It is still not working unfortunately.
And it's not only about the missing "Extra Places" in the KDE Open File dialog, but KeePassXC cannot handle network shares in KDE at all, even if the full path is pasted manually in the dialog.
For example, a path served by KIO Gdrive looks like this:
`gdrive:/myDriveAccount/Passwords/pass.kdbx`

To me it seems that KeePassXC doesn't support KIO (remotes) at all. See for more info: https://github.com/KDE/kio

So the following suggested solution cannot work, because KIO is not actually mounting the remote in a filesystem directory:
> You will just have to navigate to the mounted location starting from Root.

Is there any chance that KeePassXC gets KIO support? 
Currently this rules out all KDE users to have a simple-to-use syncing possibility. (Yes, I know there are other solutions like `rclone` and `syncthing` but all of them require more advanced knowledge to set up.)

**Comment by phoerious** [comment]
We do not control KDialog. That issue is with KDE, which should expose those as normal places.
