### ISSUE TITLE
Own diceware, multi files, home instead of share

### ISSUE THREAD

**Issue by Utini2000** [keepassxreboot/keepassxc#2854]
## Summary
Currently you can use the stock diceware list from KeePassXC or put your own list in the /usr/share/keepassxc/ folder.

## Desired Behavior
I would prefer to put my own created list inside my /home/ folder (e.g. .config/keepassxc/) instead of making it "widely available" in the share folder.
Also I would prefer to use multiple files at the same time (e.g. different languages) so my password will consist of words from different languages instead of being just one language.  

I think the changes shouldn't be too hard to make but would greatly improve a passwords security?  
In case someone wants to create password that aren't meant to be remember in your head, one could create a diceware password that consists of several different languages, numbers and symbols. It would probably be secure enough for the next 10 years of technology to come :)

**Comment by droidmonkey** [comment]
If you don't intend on remembering the pass phrase, just create a password with random values. That is more secure. I doubt we will open up the wordlist in this manner, this isn't a feature many people would use or is necessary.

**Comment by Utini2000** [comment]
A random combination of letters/numbers/symbols is more secure than a diceware with 6 words of different langauages?

I thoght diceware was more secure because it offered more possible combinations? :o

**Comment by droidmonkey** [comment]
Absolutely not. Diceware picks from a set of fixed words that are typically lowercase letters separated by a space. A 15 character password with numbers/upper/lower/symbols has FAR more entropy than a 10 word passphrase.

**Comment by Utini2000** [comment]
Well then I wonder bother using diceware for passwords thats I save with KeePassXC.

To me it seemed like e.g. when using letters and numbers, I am limited to a total of 36 different options (26 letters and (0-9) 10 numbers).
How ever, when using words I would have way more options because I am not limited to 26 letters and 10 numbers but to e.g. 30.000 words of a single language.  
I would then randomly pick 8192 words out of that language and then create my diceware from those words. Meaning in total I had more possibilities than just with numbers + letters.
Ofcourse I would include upper/lower case as well as numbers & symbols in my Diceware.

E.g. Word_word-w0rd&Word5Word.10Word

**Comment by droidmonkey** [comment]
As long as you keep your set large, then yes that is rather secure. Plus an attacker needs to know your set and that you are actually using diceware to properly attack it. Either way, you can use whatever method you want, but a 20 character random password or 7+ word diceware passphrase are more than sufficient

**Comment by SebiderSushi** [comment]
The key advantage of a diceware passphrase over a password consisting of randomly chosen characters is memorization. A 7 word passphrase gives you a lot more entropy than 7 characters, and about as much entropy as 15 characters (with a list of 8'000 words as opposed to a character set of A-Z, a-z, 0-9 and 10 special characters). The idea behind a passphrase is that most humans are better at memorizing 7 words than 15 random characters without any sense to them.
Also, to get away from a computer random number genrator, if you are going the true "diceware" way and generate your passphrace by rolling actual dice and looking up words in an off-line wordlist, then rolling the dice for 7 words might be easier than rolling them for 15 characters.

However, if you don't need to memorize your passcode and if it's generated by your computer anyway then you don't need a passphrase and a password is more suited to pack the most entropy into the least characters than a passphrase.
Imagine a website that only allows 32 characters as your passphrase. Let's say the words on your wordlist are, on average, 5 characters long. That means you can cram in 6, maybe 7-9 short words into those 32 characters. Given your example, is assume you'll throw in a delimiter after each word, each consisting of 1-3 charaters either 0-9 or one of 9 other special characters. This should result in 20^3 combinations for the delimiter. Given that every word is followed by a delimiter, it's as if you would compile a new list, with all word-delimiter possibilities included and use this one as a regular passphrase wordlist. In that case, it will have `8000*20^3` entries.
This yields from `log2((8000*20^3)^6) = 155.6` to `log2(8000*20^3)^9) = 233.4` bits of entropy, whereas with the former set of characters A-Z, a-z, 0-9 plus 10 special characters you get constant `log2((26+26+10+10)^32) = 197.4`bits of entropy - which is totally enough for almost all purposes.
You'd have to cram at least 8 words with delimiters into those 32 characters to get more entropy than with the password (and it would be 207.5 bits). Also, the 32 character limit rules out many combinations because they are longer and this adds to knowledge an attacker might have about your passcode.
So, for some website, just use a password and save it in your Password Manager, maybe max out its length as allowed by that site.
For cryptography, don't save it anywhere, generate it safely, maybe even without touching a computer, otherwise you might just get a special passphrase generator with advanced features for that.
In the end, i don't see the purpose of a password manager anywhere near the purpose of a diceware passphrase or a totally secure passcode and agree that this is possibly out of scope here.

Also, remember that password entropy is not the only and final measure on passcode safety and pretty much just a worst case scenario measure for:
My attacker knows how i generated my password and is trying out possible combinations. How many tries will they likely need to guess my password?
Whereas `Expected number of guesses (to have a 50% chance of guessing the passcode) = 2^(entropy in bits - 1)`. Note that this will always be `number of possible passcodes / 2`, which in the end turns passcode entopy into a complicated way of saying: How many combinations does my attacker need to guess in order to have a 50% chance of having guessed my password. Which is answered with: Half of the possible combinations that can result when generating my password.
And whereas "my attacker knows..." means, they know your set of symbols (wordlist or characterset) and might also know how much of these are in your passcode.


For Information see
https://generatepasswords.org/passphrases-vs-passwords/
https://generatepasswords.org/how-to-calculate-entropy/

**Comment by tylert** [comment]
Having the ability to specify the location of the wordlists in the keepassxc.ini file would be valuable while running Keepassxc inside a Docker container without having to rebuild it (e.g.:  https://github.com/westonsteimel/docker-keepassxc).

**Comment by shaneknysh** [comment]
I use symlinks to "add" my desired wordlist to KeePassXC while not having to copy them into the shared folder.

**Comment by metal450** [comment]
Likewise, it seems there's no way to add a wordlist when running the appimage version (without extracting & rebuilding the appimage yourself).  +1 request for being able to put it in your home folder.

**Comment by droidmonkey** [comment]
#989
