### ISSUE TITLE
KeepassXC deletes database file after unsafe save on different file system

### ISSUE THREAD

**Issue by jankatins** [keepassxreboot/keepassxc#2888]
## Expected Behavior
I want my datafiles save on a google drive for business (Drive File Stream) folder.

## Current Behavior
I've my keepass file on a google drive for business virtual drive (Drive File Stream) in my mac (updated to latest version). When I started with keepassxc 2.4 this morning, it told me that it needed to move my browser settings into the database settings (i clicked yes). Afterwards I got an error message that it couldn't save the file ("Writing the database failed, cross device link"). Afterwards my keepass file was gone.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Add a pre keepass 2.4 (with browser settings) file to a google drive for business folder
2. open it, click yes to the browser migration question
3. observe: the file is gone

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
Did you actually reproduce this or only experienced it once? The migration of settings has nothing to do with file saving.

Do you have save file saves disabled?

**Comment by phoerious** [comment]
That looks to me like you do not have safe saves enabled and somehow your database was on a different file system than your temporary savefile.

**Comment by jankatins** [comment]
I have "Savely save databases files (may be incompatible with dropbox...)" **off**. Before, in 2.3.x, the backup file was directly next to the active keepass file (I've "backup database file before saving" and "automatically save after every change" on).

I can reproduce it with the re-downloaded file from the drive website (so restoring was possible). tried it three times now.

**Comment by droidmonkey** [comment]
Does the same thing happen if you just edit an entry and save?

**Comment by jankatins** [comment]
Yes: I opened the file, clicked no to browser setting migration, added a new entry, named it 'try', clicked ok (Which closed the "Edit entry" dialog) and then got the error message ("Writing the database failed, cross device link") and the file was gone. The funny thing is, it doesn't even say it needs to be saved after this error: the save menu is greyed out and command+s doesn't do anything. Only when I do another change, I get the error again.

**Comment by droidmonkey** [comment]
Does your database have the standard kdbx extension? And no backup file is being created?

Just need to tease out a couple more details to narrow the scope.

**Comment by moobyfr** [comment]
I have the same problem when upgraded to 2.4.0, macOS 10.14.3
I don't use google drive (but seafile, something like dropbox)
On save, message "Writing the database failed, cross device link" and the file was gone, no backup file. the file was named MDB.kdbx

**Comment by droidmonkey** [comment]
I just did this and could not replicate the behavior.

**Comment by SunTsu** [comment]
Same happened to me - I was storing the database file on a VeraCrypt drive. Now it's gone. I have plenty of disk space, I have the correct permissions, it was working with 2.3.x. 2.4 deleted it. There are no backups although "Backup database file before saving" is enabled. And yes, I got the same "cross device link" error as well.

**Comment by droidmonkey** [comment]
@moobyfr is your $HOME mounted on a different file system? Perhaps an encrypted volume?

The cross-device link error occurs when trying to rename a file from one file system to another.

I think the issue here is that, on Linux only, we copy the temp file to it's final destination before renaming. We should be doing the same on MacOS as well. I do consider this a Qt bug because Qt should smartly copy the file first if trying to rename across file systems.

Responsible code block:

https://github.com/keepassxreboot/keepassxc/blob/d7660dad3774ee5192e3ce1728cb4945b1e834dc/src/core/Database.cpp#L243-L256

**For now, I absolutely recommend enabling safe saves to get around this issue.**

**Comment by droidmonkey** [comment]
Yes, the behavior of Qt is at fault here. Their documentation states rename will try to copy the file first if simple rename fails.

https://doc.qt.io/qt-5/qfile.html#rename

I will file a Qt bug report if one doesn't already exist.

**Comment by droidmonkey** [comment]
Oh wow, this is unfortunate. It looks like QTemporaryFile::rename(...) has a different, undocumented, implementation than QFile::rename(...).

https://bugreports.qt.io/browse/QTBUG-71782

Ridiculous! I will fix this issue at once.

**Comment by SunTsu** [comment]
Thanks for fixing it! But could somebody please add a warning to the release notes? If you don't have a recent copy of your database this is a fatal problem and people need to be aware.

**Comment by droidmonkey** [comment]
I updated release notes and sent a tweet.

**Comment by moobyfr** [comment]
my ``$HOME`` is stored on another disk (classical mount). ``TMPDIR`` is set to ``/var/folders/....`` which isn't on the same disk.

**Comment by jankatins** [comment]
Another thing (apart from #2889) could be that after not being able to safe, it still greys out the "File > save" menu entry, leaving you with no indicator that a (automatic) save was not happening (the error goes away after a few seconds, so if you press ok and switch away from the window, you might miss that). This might be related to the fact that I have 'automatic saving after any changes' on.

**Comment by droidmonkey** [comment]
That is automatic save, the toolbar button will always be disabled

**Comment by jankatins** [comment]
I get that, I just think this is not what you get trained for in other apps: usually save is only greyed out, if the latest state is saved to the disk. In this case it is not, but still the "Database -> Save database" entry is greyed out.

**Comment by droidmonkey** [comment]
This is a good point, and that is certainly a bug

**Comment by phoerious** [comment]
We should remove the save button if autosave is on. It makes no sense to have it. Only confuses users.

**Comment by jankatins** [comment]
The problem is more that there is no indicator that your changed data needs a save if you have autosave on, but anything goes wrong during the save. I usually view a greyed out save button as "everything is saved', so I expected that the greyed icon/menu entry is because the save happened, not because the autosave setting is on.

**Comment by phoerious** [comment]
That's a totally different problem and should not happen at all.

**Comment by stysedo** [comment]
> I updated release notes and sent a tweet.

Might be worth adding the warning info to the downloads page of the main keepassxc.org page at https://keepassxc.org/download/#mac

**Comment by droidmonkey** [comment]
We'll be releasing the fix this week. Going to let it ride for now.

**Comment by beks6** [comment]
Hanging in here, just for completeness.
We are using our Database through SMB, everyone is already on KeePassXC 2.4 and when answering the Browser Integration question with Yes on opening the database, KeePassXC deletes the database.

**Comment by droidmonkey** [comment]
I'd like to stress that if you have safe saves enabled this bug is nullified.

**Comment by beks6** [comment]
no, safe save is not active, since it says (may be not compatible with dropbox etc.)

**Comment by beks6** [comment]
ok, is there something we have to pay attention because of "may be incompatible with Dropbox etc."?

**Comment by droidmonkey** [comment]
Actually no because the macOS distribution is using Qt 5.12 which doesn't have the bug that caused us to make an unsafe save in the first place.

**Comment by SunTsu** [comment]
Then there might be another issue, because I use Mac and I fell prey to a vanishing database. And this user reports the same problem using MacOS: https://github.com/keepassxreboot/keepassxc/issues/2888#issuecomment-481240035

**Comment by droidmonkey** [comment]
There is not another issue. The code path that leads to databases vanishing was only activated when save safes were disabled. Just enable save safes and you won't have any issues:

![image](https://user-images.githubusercontent.com/2809491/55877691-b735e600-5b68-11e9-9615-3ffd719a711d.png)

**Comment by SunTsu** [comment]
Yes, understood, that's what I've been doing the last 14 days. I just wondering if there might be another issue because you've said that the MacOS distribution doesn't have the bug in the first place. Well, if it doesn't have the bug - why did it happen to me? But maybe I just misunderstood what you were saying.

**Comment by droidmonkey** [comment]
That is not what I meant, sorry. The bug that forced us to create unsafe saves in the first place was in the QSaveFile class. It did not properly hold a lock on the file while it was performing its function which allowed DropBox, Drive, etc to acquire a lock while attempting to sync the file. With Qt 5.11+, this bug in QSaveFile no longer exists (allegedly) so you can use save safes again without causing file locking issues.

**Comment by Yquas** [comment]
Hello there!
It seems to me that this issue somehow still exists, but in a weird way. And combined with Android.
What I experienced:
1. I open a database in KeePassXC (2.6.4-1) that I have on my Android phone, which is connected to my (Manjaro Arch) Linux PC via USB.
2. I make a new entry or import an entry from another database (the two things I already tried with this bug) into this 'Android-phone-only' database. But now KeePassXC tells me "Writing the database failed: Input/output error". But the new entries still show up.
But here comes the catch: The database on the phone is deleted now! (also not a hidden file)
3. I try close the database, it asks me if I want to save changes, I click save. But then the following pops up:
"KeePassXC has failed to save the database multiple times. This Is likely caused by file sync services holding a lock on the save file. 
Disable safe saves and try again?"
I always clicked cancel here because disabling safe saving doesn't sound right and safe. Then I tried to close the database, but the same error with disabling safe saves comes again. Inbetween the tried closing and the safe saves popup, the database reappears on the phone, but as a zero byte file and with some characters appended something like this: [databasename].kdbx.WZKmeeu
When the safe saves popup appears, the file is gone.
And when I discard the changes, the file is also gone.
This sadly happened to a real database of mine and I lost some new entries I hadn't backupped yet, but luckily I can get all of those lost passwords back.
I tried disabling the safe saves when testing this bug with a new database (for science!) and the database reappeared, healthy.
But now the weird thing is: This bug only happens when safe saving is enabled. In the discussion of this issue it was the other way around. It only happened with safe saving disabled...

For now I won't try to edit my phone entries directly but first copy them to the PC, that fixes it. And: BACKUPS!
But this surely is a bug, right? Thanks for reading.

**Comment by droidmonkey** [comment]
What you describe sounds like an error with file storage through the USB connection in general and not specifically a keepassxc problem. We don't encourage use of keepassxc in this manner on an external device.

**Comment by Yquas** [comment]
@droidmonkey Ok, I understand that. Some people aldo told me that Android MTP isn't good for duch things. Thanks.

**Comment by johanjaimes** [comment]
This just happened to me. KeePassXC deleted my dkbx file after failing to save changes to an existing file. This is the first time I've seen software deleting a file after failing to save the changes! 
I decided to move from Windows 11 to Linux Mint, my kdbx file is on Google Drive. I've been using KeePassXC with no issues to read the contents of the kdbx file but the day I needed to update an existing entry, KeePassXC decided to delete the file after failing to save the changes. 
Fortunately Google Drive has a tool to "Recover a deleted file in Google Drive".

**Comment by droidmonkey** [comment]
Since you are likely using gvfs-fuse built in with gnome, then you need ro disable safe saves and use direct write method. Its a known issue with that interface, not on our side but on the gvfs side. Any program that uses atomic file saving will fail miserably because of how they set that up.
