### ISSUE TITLE
Clear-text passwords shown in overview

### ISSUE THREAD

**Issue by simolus3** [keepassxreboot/keepassxc#2954]
## Expected Behavior
I would expect the password column to hide the password, just like the details panel.

## Current Behavior
After upgrading to 2.4.0, passwords are shown in clear text:
![grafik](https://user-images.githubusercontent.com/5738860/55667526-ae3dcf80-585d-11e9-9f22-303f2116511e.png)

## Context
I have
- "Hide passwords in the entry preview panel" turned on

Was there some setting introduced to allow this behavior that I might have accidentally turned on? I couldn't find one.

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.0.5-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Right click the header of the entries list and choose "hide passwords". Or press CTRL+SHIFT+C.

**Comment by nniesen** [comment]
It might be helpful, and reduce bug reports for this, if the settings text was:
`Hide passwords in the entry preview panel. Use CTRL+SHIFT+C to toggle visibility in password column.`
Showing the hotkey on the column context menu or a hotkeys settings panel would also help.
Also, CTRL+H would be more intuitive for those coming from stock KeePass.

**Comment by droidmonkey** [comment]
The default setting is to hide the passwords in the entry view. The showing of passwords was actually broken in 2.3.x so people had it enabled without knowing it. I think the settings are clearly worded, I adjusted the wording for 2.4.0. This is more about going from broken state to working and not realizing the column visibility was turned on all along.

**Comment by tvannahl** [comment]
Just had a shock because of this and was about to file a bug regarding this because I haven't found an option regarding this.

There is a very specific reason about why I hit Ctrl+Shift+C, approximately after 2.4.0 the "Open URL" changed to Ctrl+Shift+U and my workflow:

 1. Ctrl+F <searchword>
 2. Ctrl+U
 3. Alt+Tab
 4. Ctrl+B
[…]

doesn't work reliably anymore. The username or password isn't always copied without using the mouse… probably during this it happend and I didn't even realize.
