### ISSUE TITLE
Is there a way to get CTRL+V autotype back?

### ISSUE THREAD

**Issue by rpgdev** [keepassxreboot/keepassxc#3051]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I loved this shortcut and made a whole lot of sense but I see that you guys changed it just because a couple of people complained. Is there a way to get it back?

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Hitting ctrl+v should execute autotype.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Right now ctrl+shift+v produces the expected behavior. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. press ctrl+v on an entry
2. nothing happens

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
On 2.3.4 hitting ctrl+v on an entry performs autotype as expected but for some reason on 2.4.0 and 2.4.1 the behavior changed. 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.11.3
Debugging mode is disabled.

Operating system: Fedora 29 (Twenty Nine)
CPU architecture: x86_64
Kernel: linux 5.0.7-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
It's not just a "couple of people complaining". We removed it after careful deliberation, since it is dangerous (we ourselves even keep fat-fingering that shortcut every now and then) and it does NOT make a lot of sense. Ctrl+V is paste, not "minimise window and start typing where ever that has left you". I do acknowledge that people got used to it and are upset about changes, but there is really no reason why you couldn't get used to Ctrl+Shift+V instead.

There is no way you can change it back and we do not have any plans to bring it back.

**Comment by rpgdev** [comment]
> There is no way you can change it back and we do not have any plans to bring it back.

That's what I thought but for the sake of the argument:

>it does NOT make a lot of sense.

Yes it does, if it didn't you wouldn't have selected it as the shortcut for autotype in the first place. Autotype "pastes" your credentials where you need them. In the context of this application ctrl+v for this functionality made sense.

>I do acknowledge that people got used to it and are upset about changes, but there is really no reason why you couldn't get used to Ctrl+Shift+V instead.

It's not the same to type ctrl+something than ctrl+SHIFT+something. At least you could've selected another, two key combination.

**Comment by droidmonkey** [comment]
We did not select this shortcut to begin with, it was in the original application that we forked from.

**Comment by phoerious** [comment]
Ctrl+V ON KeePassXC is to paste something INTO KeePassXC. This is a conflicting shortcut.

**Comment by rpgdev** [comment]
> Ctrl+V ON KeePassXC is to paste something INTO KeePassXC. This is a conflicting shortcut.

I understand that but that has always been the case and yet you still chose ctrl+v as the autotype shortcut and the reason you did it was because it made sense. You changed your mind, and I accept this, but the shortcut still makes sense.

**Comment by phoerious** [comment]
We did not and we did not change our mind. We left it as is and now we changed it.

**Comment by wolframroesler** [comment]
How about making hotkeys configurable, thus finishing the discussion once and forever? (I also strongly want ctrl-V back BTW, because I found it both convenient and intuitive, and because I have to twist my wrist in in uncomfortable way to type shift-ctrl-V which makes using it just that little bit unpleasant.)

**Comment by seguri** [comment]
@wolframroesler indeed. I don't know why, instead of just replacing the shortcut, they didn't make it configurable with their new beloved default value ctrl-shift-v.
I'm still using 2.3.3 to have that shortcut.

**Comment by TomyLobo** [comment]
I might be late to the party but I only just upgraded to a more recent version of KeePassXC.
I'm currently using KeePassXC on my own machine and KeePass2 on shared users on various machines which are not my own.
So since KeePassXC changed the shortcut without a way to change it back, I'm now stuck with having different shortcuts for autotyping, depending on where I am.
This is not a great situation and I can't just "move on" to the new way, since I still have to use the old way half the time!

**Comment by droidmonkey** [comment]
Well, you'll be happy to know I'm putting the finishing touches on this PR: https://github.com/keepassxreboot/keepassxc/pull/9643

**Comment by jojsport** [comment]
How does KeePass autotype work properly, when also ctrl-v pasting in to its dialog works, but KeePassXC does not have it?

Not all people have fat fingers, c'mon and bring it back finally, cause its annoyoing and time wasting without it.
