### ISSUE TITLE
[UX] Confusing UX for search bar for users coming from main keepass project

### ISSUE THREAD

**Issue by clarjon1** [keepassxreboot/keepassxc#3058]
## Expected Behavior
As a user coming from the original Keepass project, I have been trained for years that I need to hit Enter/Return when performing a search, which then executes the search

## Current Behavior
With 2.4.1, hitting enter while the search field has focus opens the editing interface for the top result in the list. I personally find this to be an anti-pattern, as the results list didn't have focus, just the search box.

## Possible Solution
If searchbox has focus, enter does not activate entry editing interface

## Steps to Reproduce
1. Type in search field in top right of interface
2. Hit enter to trigger search as is expected in previous project and is standard UX/UI behaviour in many projects
3. Be greeted by editing interface for top result instead of expected list of results.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Operating system: Windows 10, Arch Linux
CPU architecture: x86_64, x86_64
Kernel: winnt 10.0.17134, linux 5.0.7-zen1-1-zen

**Comment by droidmonkey** [comment]
This behavior is consistent with allowing Ctrl+c to copy the top entry's password. Unfortunately we will not be changing this behavior since many more people rely on this functionality for their workflow. We have another issue discussing the ux of the search bar.

On a side note, having to press enter to start a search is an anti-pattern in my opinion. Especially for locally available data. I can understand for network or file operations to wait for the user to be finished (limit data transfer).
