### ISSUE TITLE
Auto-Type not working in Microsoft Remote Desktop on macOS

### ISSUE THREAD

**Issue by jgallias** [keepassxreboot/keepassxc#3080]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-Type will type into the actively selected text field of the in-focus window

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Auto-Type will only type the 'a' character for the length of the password
{ENTER} key still being properly sent.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Unknown

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Using Microsoft Remote Desktop on macOS, connect to a Desktop that requires the password to be entered every time you connect
2. You can correctly Auto-Type into any macOS window that appears before the connection
3. A Full Windows Login Screen should then appear inside the RDP connection
4. Attempt to Auto-Type using Command+V inside KeePassXC or Global Auto-Type shortcut
5. You can Auto-Type into any field after login and it will still produce the error

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
All of my RDP connections at work requires the password to be entered every time you connect, even if you save the credentials.
You cannot copy/paste into this screen.
Auto-Type will appear to work but only types the letter 'a' for the length of the password.
I'm using a custom Auto-Type sequence for the Password field only: {PASSWORD}{ENTER}
However, the default Auto-Type sequence has the same issue: both the username and password will be the correct length but only the letter 'a'

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Microsoft Remote Desktop Version 10.2.12 (1590) for macOS

**Comment by jgallias** [comment]
Seems like a duplicate and/or related to the issues with Auto-Type into Virtual Machines:
#2876 
#1833 
I'm seeing the same behavior in VMware Fusion.

I'm guessing the same fix would work for Microsoft Remote Desktop?
Feels like the same/related issues.

**Comment by droidmonkey** [comment]
Yes this is a duplicate, was going to write that.

**Comment by roco72** [comment]
I found out that if you have the keyboard mode set to "scancode" this issue exists only. When you switch to "Unicode" it works as intended.

**Comment by jdix531** [comment]
@roco72 can you elaborate how to change this? I am on ubuntu facing a similar issue (connecting to VMWare Horizon remote desktop session) and would like to see if I can work around it immediately.

**Comment by roco72** [comment]
I am sorry, I wasn't very clear. The issue is not in KeepassXC, it is how the receiving application is handling input. The setting I referred to is actually in Microsoft Remote Desktop for MacOS. It is located in the menu of an open RDP session under "Connections"->"Keyboard Mode". There you have two choices, either scancode or Unicode. When Scancode is set, it types a's, when unicode is set, it works as intended. Issue that I am having is that when set to Unicode, a web-based vSphere console inside this RDP session does not handle my actual typing any more, characters do not appear in the console (and yes, it has the focus). Only keys as return, tab seem to work, but I can not type anything else.
So it is a MS Windows RDP for mac setting, not a keepassxc setting. You can also use the keyboard shortcuts ctrl+command+K for activating scancode mode, or ctrl+command+U for activating Unicode mode.

**Comment by danpritts** [comment]
The bug still exists on my mac. Adding this to prime the search engine pump for "windows app", which is microsoft's new name for their "Remote Desktop Client" for MacOS.

a brief search did not show any gui-exposed settings to shift from unicode to scancode mode, but the ctl-cmd-k and ctl-cmd-u shortcuts still work.
