### ISSUE TITLE
Support PKCS#11 Software Emulation to allow certificate based authentication

### ISSUE THREAD

**Issue by riedel** [keepassxreboot/keepassxc#3111]
It would be great if additionally to the autotype and native messaging PKCS#11 would be supported to manage credentials and security keys.

## Summary
PKCS#11 is a standard to provide access to certificates similar to the ssh agent. It is commonly used as an interface to hardware security modules (#255 addresses this issue), but can be also used to access software implementations see (https://github.com/risacher/p11-capi).

## Desired Behaviour
Applications having PKCS#11 support could natively use KeePass as a password/certificate backend: https://en.wikipedia.org/wiki/List_of_applications_using_PKCS_11 

This would solve also #1683 (and #280) in a slightly different (standard) way. Keepass could be registered as key provider for the application.

## Possible Solution
There are some implementations out there that sketch how this can work. However, they are not trivial to use. Eg. https://github.com/kinnalru/soft-pkcs11 (generic) or https://github.com/risacher/p11-capi (bridge to windows certificate store)

## Context
As  PKCS#11 is a standard (rather than other interfaces which require plugins on the client side) this would offer a proven interface to many applications. One downside is that is usually not used for password exchange which is I guess the primary use of keepass. To make it worse typically passwords support with PKCS#11 as I understand it works mostly by storing encrypted versions of the passwords in the application itself, which is actually not a desired behaviour when using keepass. I still wanted to open this issue to explore the design space in this direction and collect feedback.

**Comment by gartfr** [comment]
+1
I'm just waiting for this feature for years now...
I just can't imagine a software like keepassx which is not able to deal with pkcs11 natively.
It opens to the best security practices with the use of HSM.

**Comment by droidmonkey** [comment]
KeePass[XC] is not a certificate store. The exception being SSH Agent which serves certificates to existing key servers. All operating systems offer PKCS#11 certificate storage and retrieval. I do not think there is much to gain in adding this functionality to KeePassXC.

**Comment by MrJudge77** [comment]
right now i've been using https://github.com/risacher/p11-capi to load the keys into the ssh-agent. It's been working great. However, I would ditch it and use keepassxc if it can do the same thing.

**Comment by flippipe** [comment]
If KeePassXC become a certificate store with PKCS#11 emulation, it would be a cross platform certificate store and not OS specific. Besides could be used in [other purposes}(https://en.wikipedia.org/wiki/List_of_applications_using_PKCS_11): Email, Browser, VPN, SSH and [PAM](https://opensc.github.io/pam_pkcs11/doc/pam_pkcs11.html)

**Comment by LecrisUT** [comment]
I think the only feature that needs to be implemented is installation from keepass database to browser, system, etc.

For example in my usecase: I have a smallstep CA setup to create short-lived client certificates. Those softwares are good at managing that part. However I want to use that certificate on remote machines as well and transport them securely via a keepass database. But due to the sort life-time it is unfeasible without an automated deployment, ideally when database is unlocked

**Comment by ar-daniel** [comment]
I thought Keepassxc already had this feature and installed to use it for this purpose only. Not knowing how to implement got landed here. It will be great to have this feature. Thanks.

**Comment by droidmonkey** [comment]
Curious, what led you to believe this was already a feature?

**Comment by ar-daniel** [comment]
I was in process of setting client certificate for mutual authentication for TLS and am looking for OS native way for storing client certificate at a single place and make it to be available for applications (Firefox, chromium, curl etc ) to use it automatically when accessing a relevant site requiring the client certificate. 
I saw Keychain access in mac has this feature and expected the feature would be present in this open source alternative. (though not looking for hardware based tokens, but digital client certificate and private key store)

**Comment by droidmonkey** [comment]
Duplicate of #255

**Comment by scabala** [comment]
Hello @droidmonkey 

First of all, I would like to say that I really like KeePassXC and it's been a great improvement to my secure, digital life.

I comment on this long closed issue because I think it might **not** be a duplicate of #255. Please forgive if I'm mistaken - I'll try to explain why I thinks so.

First of all, to avoid further confusion, I'll use terms of PKCS#11 user and PKCS#11 provier.
 - PKCS#11 user - program that loads a PKCS#11 compatible shared library and iterracts with PKCS#11 provider to perform cryptographic operations without exposing private key material
- PKCS#11 provider - program that performs cryptographic operations with private key material and allows users to use cryptography without exposing it.

In #255, as I understand, there's interest to make KeePassXC a PKCS#11 *user*  in order to encrypt and decrypt KeePassXC database with private key that is stored somewhere else - possibly on hardware security key.

In this issue, as I understand, there's desire to make KeePassXC PKCS#11 *provider* by implementing a PKCS#11 shared library that can be loaded by PKCS#11 user programs. This could be potentially done by (ab)using KeePassXC browser integration.

Making KeePassXC a PKCS#11 provider would require to generate private keys, perform cryptographic operations *by KeePassXC*, store certificates and somehow expose interface to let PKCS#11 shared library communicate with KeePassXC.

One might say "just implement it outside of KeePassXC" - this is technically correct, i.e. by using browser integration or SecretService implementation. However, it would make KeePassXC only private key and certificate *store* and require to perform all cryptographic operations *outside* of KeePassXC. And from security point of view, it is sub optimal solution.

In contrary to SSH, there's no single entity and protocol to implement some kind of agent for TLS - at least I have not found one and I searched quite long. The only standard I saw is actually PKCS#11 which works by loading shared library with C interface. I personally do not like that approach - I prefer what SSH agent does - but that's the reality we live in.

I have not understood well KeePassXC codebase but with recent introduction of passkeys, I think that KeePassXC already *do* perform some kind of cryptographic operations by itself. Maybe know it would be possible to extend it to support PKCS#11 provider usecase?

**Comment by droidmonkey** [comment]
Its not necessarily a duplicate, but we aren't going to implement this as a feature.

**Comment by scabala** [comment]
Understood, thank you for clarification
