### ISSUE TITLE
Ugly system tray icon

### ISSUE THREAD

**Issue by Gurran** [keepassxreboot/keepassxc#3145]
#### This is a very  minor gripe!
I think the quit icon (used in the system tray) is a bit to big and ugly. 
[image](https://imgur.com/a/Qbk10tw)

## Possible Solution
Remove icon. I think is looks cleaner without it.

Update Icon to a nicer one.

**Comment by wolframroesler** [comment]
In the current version (2.4.2) a new item was added to the tray menu (see attachment). We now have three menu items, two with an icon and one without.

![trayicon](https://user-images.githubusercontent.com/25565229/58746647-bf234f80-8460-11e9-81ff-3382d01f39b5.png)

May I suggest to add to the possible solutions: "Add icon for Toggle Window so that every menu item has an icon"?

Anyway, my preferred solution would be to remove the other two icons (and I wouldn't object if they were removed from the regular menu items also), but someone will have to make a design decision about that.
