### ISSUE TITLE
UI freeze while DB is computing master key

### ISSUE THREAD

**Issue by instagendleg** [keepassxreboot/keepassxc#3187]
## Expected Behavior

The software should show a writing indicator. The UI should not be impacted by the key computing.

## Current Behavior

When I write a new version if the database, there is a freeze of the UI. My system told me that the app does not respond and ask me to kill it.

## Possible Solution

- Create a thread to separate all the key computation from the UX
- While the thread has an active task, show up to the user a loading indicator

## Steps to Reproduce

1. Create a database with Argon2 and high security key
2. Apply a change on the DB
3. Save

## Context

- DB saving

## Debug Info

KeePassXC - Version 2.4.1
Revision: 7bafe65
Distribution: Flatpak

Qt 5.12.3
Debugging mode is disabled.

Operating system: Linux 5.0.17-300.fc30.x86_64
CPU architecture: x86_64
Kernel: linux 5.0.17-300.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is not writing to disk delay, it is your computer computing the master key. Did you set your argon2 settings too high?

**Comment by klemy** [comment]
@droidmonkey thanks for replying! I understand better now. Indeed, my Argon2 takes ~10sec to compute.

So I propose to rename this issue to "UI lags & freeze while key computing"

**Comment by droidmonkey** [comment]
It is indeed a problem that the UI freezes. Its a little challenging to fix that right now, but it should be addressed.

**Comment by phoerious** [comment]
I don't think it's really "freezing". Iirc, we are just disabling it to prevent user input while key transformation is underway.

**Comment by droidmonkey** [comment]
This was before we implemented the current behavior which is why I closed it

**Comment by phoerious** [comment]
Ah, oh. I only saw it pop up in my notifications. 😁

**Comment by YZgitter** [comment]
This is still problematic. On Windows, when the key security change takes a long time, you get a "Not Responding" message, which invites you to hit the close button that terminates the app (even if it's set to close to tray). It completes fine if you just leave it, though. The behavior is similar on Linux (KDE) and on macOS you get the beach ball. 

<img width="1016" height="643" alt="Image" src="https://github.com/user-attachments/assets/210eb255-eeca-48b0-a63a-6aaaf522f2c7" />

On database decryption it's not as bad, since there's no "Not Responding" message and you can close the window to tray. But it still looks somewhat frozen.
It would be nice if there was an animated graphical indication that it's actually doing something and working as intended ("Loading", "Saving").

I get that very long encryption/decryption times aren't a _typical_ use case, but they're a valid choice in some situations.

**Comment by droidmonkey** [comment]
Holy cow 200 rounds of argon2 is A LOT. Use the 1 second benchmark like we offer...

> but they're a valid choice in some situations.

Disagree, after 1 second you are 100% just wasting human time (and compute time) for no added protection.

**Comment by YZgitter** [comment]
> after 1 second you are 100% just wasting human time (and compute time) for no added protection.

That's true if you're using a _good_ password and/or key file (which is the recommended typical use!). But there are situations where using a weak password is necessary (for "human" reasons I won't get into). Waiting longer is also not an issue if the database is accessed rarely.

Anyway, I don't think this is urgent, but the UI does look broken there, at least after the change in the Database Settings. Preventing the "Not Responding" behavior and making it work the same as when opening/saving the database in the main window would be an improvement.
And the Database Settings saving process actually happens even if "Automatically save after every change" is unchecked, which looks like a bug.
