### ISSUE TITLE
Auto-Type window matching seems broken on Windows

### ISSUE THREAD

**Issue by Yellow-jack** [keepassxreboot/keepassxc#3295]
## Expected Behavior
[NOTE]: # In version KeePassXC-2.4.2-Win64 in auto type that all my title matches would work.  Unlike version 2.4.1 There were no suggestions of what keepass was looking for.

## Current Behavior
[NOTE]: #  KeePassXC-2.4.1 All my auto type titles will  match.  It will also let me know what to enter to match what v2.4.1 was looking for.

I am just a user that loves your program.

**Comment by droidmonkey** [comment]
I find this hard to believe because we did not touch the code for window title matching between 2.4.1 and 2.4.2. We did change AutoType so that it stored the window title after pressing the global keyboard shortcut instead of trying to resolve it after the fact when KeePassXC had focus. This was to fix a macOS issue. I have used AutoType on Windows 10 numerous times since that change and it works flawlessly for me.

I am going to need more information to address your observations. What is your window title matching scheme? Are you using a keyboard shortcut that could be masked by other programs?
