### ISSUE TITLE
Not latest version available on AppCenter in Elementary OS

### ISSUE THREAD

**Issue by ImaCrea** [keepassxreboot/keepassxc#3299]
Hi dear community of Keepass, I'm discovering your tool and I'd love to use it. A bit of context : I'm relatively new to Linux world. I'm on Elementary OS Juno 5.

## Expected Behavior
I'm trying to install KeepassXC. I go to the AppCenter of my OS and I expect to see the latest version available and ready to install.

## Current Behavior
The version available in the appcenter is 2.3.1

It's hard to know if the problems come from your side of Elementary's side so I thought I start with you since you're at the core and I guess it's pretty important for you to know that it's not the latest version that's showing in Elementary's AppCenter. Which means people who installed it that way may use an old version also, which might be worrying in term of security.

Hope it helps, cheers :)

**Comment by phoerious** [comment]
I guess Elementary gets its packages from Ubuntu, which has an old version in the repositories. It is quite likely that those repos will not update to 2.4 for existing Ubuntu versions, so you'd have to wait for a new Ubuntu release for this.

We do not maintain those packages. If you want the latest version, you can install our Snap oder AppImage release.

**Comment by ImaCrea** [comment]
Thank you very much for your help.

**Comment by wolframroesler** [comment]
Small update, I'm on the latest version of elementary OS (5.1 "Hera", built on Ubuntu 18.04.3 LTS) and AppCenter still has nothing better than KeePassXC 2.3.1. That's a shame because elementary is targeted towards non-technical users who shy away from using the terminal and instead rely on point-and-click installations. These people traditionally have little understanding of the intricacies of IT security and tend to use weak passwords or use passwords more than once; they really need a simple-to-use password manager easily available. 2.3.1 is more than 1.5 years old.

Seems like elementary has decided to natively support Flatpack instead of Snap for their app center. Is there any chance you could make a Flatpack distribution of KeePassXC available in addition to AppImage and Snap?
