### ISSUE TITLE
Read-only database can be modified, and prevents closing application without Save as...

### ISSUE THREAD

**Issue by chrisspelberg** [keepassxreboot/keepassxc#341]
## Expected Behavior
A database that is opened read-only should disable all edit options OR when it is modified, when closing the database the program should provide an option to discard the changes and not save the database.

## Current Behavior
A read-only database can be modified. When quitting the program or closing the database it asks to save the database. There is no option to not save or revert the changes.

## Possible Solution
Add an option to discard the changes and not save the database on close.

## Steps to Reproduce (for bugs)
1. Open a database
2. Open it for the second time => read-only
3. Modify some password
4. Close the databases. It wil ask to save the read-only database.

## Context
I accidentally opened the same database twice, and modified a password in the read-only copy.

## Your Environment
* KeePassXC 2.1.2 / b9279f73fa58d75e1ec88f734f3c77c0f015a348
* Qt version: 5.8.0
* Compiler: N/A
* Operating System and version: Windows 7 Enterprise SP 1

**Comment by droidmonkey** [comment]
Agree with this.

**Comment by jpyllman** [comment]
Should it not be like you will not be allowed to modify a read-only? With that I mean it should clearly show it is read-only. And then when you try to edit it will tell you it is read only. The only problem I see with this is that if read-only is only because the lock file was there when you open. But goes away during the time you have it open it should not be read only. Think this should be worked on together with thoughts about lock files.

**Comment by droidmonkey** [comment]
That leaves the potential of overriding changes that you've made in the previous the open file.

**Comment by liv-kuka** [comment]
Seems like issue is resolved already, along with changes for #1113. Can someone check it?
