### ISSUE TITLE
Connection to KeePassXC Browser Extension unsuccessful [ERR]: "Key exchange unsuccessful"

### ISSUE THREAD

**Issue by dolorosus** [keepassxreboot/keepassxc#3438]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

Connection to KeePassXC Browser Extension unsuccessful
Errormessage "Key exchange unsuccessful"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Establishing a connection to the http plugin

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Errormessage "Key exchange unsuccessful"

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. start browser
2. try to connect to KeepassXC
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: REVISION

Libraries:
- LIBS

Operating system: Windows 10
CPU architecture: x64

Enabled extensions:
KeePassXC Browser Extension unsuccessful.

Just for the records: for me browser integration is a "conditio sine qua non". After more than one houer of fiddeling around  with KeepassXC I decided to switch back to Keepass.

**Comment by varjolintu** [comment]
There's no support for HTTP plugin (meaning KeePassHTTP) anymore. Please see https://keepassxc.org/docs/keepassxc-browser-migration/ for basic instructions.

**Comment by dolorosus** [comment]
Sorry I wasn't precise. 
Shurely I used KeePassXC-Browser as browser addin. The connection worked some time, but then it was broken (Error as mentinond above).

So I decided to start over and deleted the database connection (KeePassXC-Browser->setting->connected Databases).

No way to reconnect every try gives the errror above...

This evening I will build a testenvironment and try to reproduce the situation.

**Comment by Chmood** [comment]
I also have the same "Key exchange unsuccessful" error on my Linux machine (Ubuntu Mate 19.04, fresh install) running KeePassXC v2.3.4 (rev. 6fe821c) from apt repo on Brave browser.

Strangely, it works fine on Chrome, despite having a warning saying that I'm not using the last version (v2.3.4 too).

Both browser are `Chrome/Chromium 76.0.3809.100` based, and both of them use KeePassXC-Browser plugin v1.4.7.
Also, Chrome plugin do detect the right KeePassXC version (in the plugin options panel), but Brave don't and only says "unknown".

So I tried to update KeePassXC to last version 2.4.3 rev. 5d6ef0c (using AppImage release instead of Ubuntu apt package), that causes both browser to throw the "Key exchange unsuccessful" error. And now both fail to detect KeePassXC version, too.

I will try to boot on my previous Ubuntu install to check which versions I had, that were working fine back then.

**Comment by varjolintu** [comment]
@Chmood Please check that you have the option "Update native messaging manifest files at startup" enabled from Browser Integration -> Advanced.

**Comment by Chmood** [comment]
Thanks for the tip @varjolintu, I enabled this option and now Chrome integration is working again.
Brave browser still shows the error message, though.

I also tried to install it on Firefox, and all went fine. So I assume this bug is somehow related to which browser I use.

**Comment by varjolintu** [comment]
Does it help if you disable/re-enable the Brave support? If that doesn't help, check the paths from https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide and see if everything is correctly inside the JSON scripts.

**Comment by Chmood** [comment]
This helped a lot @varjolintu, since Brave integration wasn't enabled at all!

On v2.3.4 the Brave checkbox wasn't available yet, so I stupidly assumed that it fell under the Chromium family. Double checking everything made me realize that a dedicated checkbox for Brave appeared in the meanwhile in v2.4.3. And that I was a big fool.

Sorry for this, and many thanks for the helping hand. Keep up the good work :)
