### ISSUE TITLE
Different File Extension

### ISSUE THREAD

**Issue by ghbjklhv1** [keepassxreboot/keepassxc#3486]
## Expected Behavior
I expected it to create 1 .kbdx file.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
What it appears to actually do is somehow create a almost-random file extension file with the same name (e.g maybe file.kdbx.cdx43) as well as the .kdbx file.

Then it seemed to remove user privileges from it and/or delete itself.

__________

I was able to get it to go away after I deleted the origininal database and reboot.
It kept saying file does not exist with `sudo rm -r <filename>

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
The main thing I wanted to discuss is if this is a recurring issue with the system or app.
Or if I need to be worried more about malware or even just a simple mis-type.

## Steps to Reproduce
1. Create Database
2. Save to Desktop
3. Fill database with one entry
4. Notice 
second database
5. `rm -r <filename>`
File doesn't exist
6. Delete original database
7.  reboot

I deleted the file therefore cannot provide more information.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Some random file showed up on my desktop.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - AppImage
Revision: REVISION

Libraries:
- LIBS

Operating system: Trisquel
CPU architecture: AMD64
Kernel: Linux

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
That will be the temporary save file. Saving is a two-stage process involving a temporary file to prevent data loss. Somehow renaming the new  file after deleting the old one failed, perhaps due to some in-between file system or permission issue. I don't think this is a bug, but just a weird coincidence on your system. If this keeps happening, you should check your file system for errors.
