### ISSUE TITLE
Search within notes / Highlight query results

### ISSUE THREAD

**Issue by liar666** [keepassxreboot/keepassxc#3497]
Hi,

Thanks again for the work! Tools are great!

It would be even greater if we could search text within Entry fields, e.g. the "notes" field.
Or, if it is easier to implement, if, when a "search" is performed and a resulting Entry opened, the related matches could be highlighted within the fields that are displayed (e.g. "notes").
Because for the moment, it is impossible to understand why a particular result is displayed, nor find the exact location of the searched text...

Thanks!

**Comment by droidmonkey** [comment]
This is already implemented (search within fields) in 2.4.0. Highlighting the data is way too complicated to implement.

**Comment by rody64** [comment]
If highlighting the data is too complicated would it be possible to search the Notes field when editing an Entry?

Kind Regards

**Comment by liar666** [comment]
Hi all,

For those that would encounter a similar problem, I've written the following script:

```
#!/usr/bin/env bash

if [[ $# != 3 ]]; then
    echo "USAGE: $0 <DB file> <entry name> \"<(grep args: -i -C15) keyword>\""
else
    dbfile=$1
    entryname=$2
    keyword=$3

    read -s -p "Password:" pass # or stty -echo/stty echo / echo -n/printf

    ### Get list of Entries matching "<entryname>"
    entries=$(echo $pass | keepassxc-cli locate $dbfile "$entryname" | tail -n +2)

    ### For all entries => grep "keyword" inside its content
    echo "$entries" | while read entry
    do
        echo $pass | keepassxc-cli show $dbfile "$entry" | grep $keyword
    done
fi
```
It interactively asks for the password of the provided kdbx file, then grep-s for the wanted keywords into the specified entry's content.

EXPLE USAGE: ./script.sh mydb.kdbx OLDENTRY "-C3 --color supersite"

This can be useful for those, like me, that where using another tool for sotring passwds before and that created a single big entry with all the previous login/passwords in the "note" field when they switched to keepass.

**Comment by alwaysfollowthewhiterabbit** [comment]
FYI:
Just worte a KeePass (not KeePassXC) "Notes Search Plugin" (NotesSearchPlugin.dll) for KeePass 2.x (current Version 2.54 https://keepass.info/download.html ) with support from chatGPT 3.5 because my C# programming skills could be quite a bit better ;-)

Usage:

* select or search for an entry
* right-click - select "NotesSearch"
* enter search string
* and start searching - results will be highlighted in red

you can copy everything you found (ctrl-c)
detailed documentation and download of NotesSearchPlugin.dll & sourcecode on my homepage:
https://besch-it.com/keepass-notes-search-plugin-innerhalb-der-kommentare-suchen-search-within-notes-field/

As of today (09/07/2023) the plugin was also published on the official KeePass project website and maintained by Dominik Reichl.
https://keepass.info/plugins.html#notessearch

This plugin is far from perfect, but it does the job.
I´m grateful for any feedback or suggestions. Have fun. :)
