### ISSUE TITLE
Allow for deleting a custom favicon used by multiple entries

### ISSUE THREAD

**Issue by matthewdavis** [keepassxreboot/keepassxc#356]
## Expected Behavior

When attempting to delete a custom favicon the message "Can't delete icon. Still used by $X items" is displayed. Maybe make the '$x items' a link to the found items.

## Context

Reasons for this feature request are as follows
* Because when I clicked download favicon, if one is not found a default icon is used for that site. And because #232 still exists, numerous 'default' icons have populated my custom favicon list. I wasn't aware of the fact they were all using default icons until now and cannot clean them up since the icons have no perceived link to a given site.

* Also I'm OCD and don't like the duplicate icons in there.

## Your Environment

* KeePassXC version/commit used: Version 2.1.2 Revision: 0f1c518592af2758b0f1dbec6d538df01cfbde92
* Qt version (e.g. Qt 5.3): Qt 5.7.1
* Operating System and version: Fedora 25 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.9.11-200.fc25.x86_64

**Comment by droidmonkey** [comment]
A group can also have an icon assigned to it. This might be easier to implement by changing it to a question instead of an error.

"This icon is used by X entries, and will be replaced with the default icon if deleted. Are you sure you want to remove it?"

If you click yes it will take the enumerated entries and replace the icon with the default then delete the custom icon.

Perhaps an even better option would be to allow merging/replacing icons with another.

**Comment by droidmonkey** [comment]
I posted a fix, see if this fits your needs.

**Comment by matthewdavis** [comment]
Just tested it and it worked great.
