### ISSUE TITLE
Firefox connection to KeepassXC works only when Firefox is started first.

### ISSUE THREAD

**Issue by nudgegoonies** [keepassxreboot/keepassxc#3598]
I am using Debian 10, Firefox 60 ESR and KeepassXC 2.4.3. Since my Update from KeepassXC 2.3.4 to 2.4.3 or during the update of the Firefox KeepassXC plugin (or both) i have to start Firefox first.

## Expected Behavior
Start KeypassXC before Firefox and Firefox can successfully connect to KeepassXC.

## Current Behavior
Connection fails with "Key exchange error".

## Possible Solution
Workaround is to Start Firefox before KeypassXC.

## Steps to Reproduce
1. Start KeepassXC
2. Start Firefox
3. Check KeepassXC Icon in Firefox and try to connect.

## Context
Updated KeepassXC and Firefox Plugin within a short time.

## Debug Info
```
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.11.3
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.19.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4
```

**Comment by farid-fari** [comment]
I'm affected by this issue -- I can't confirm it *never* works when Firefox is opened second, but it often has the same issue and restarting keepassxc makes it work.

**Comment by varjolintu** [comment]
I still haven't been able to reproduce this, which makes finding the actual reason very difficult.

**Comment by farid-fari** [comment]
I'm using Arch Linux, and Firefox 69.0.2, which are both different from nudgegoonies so it's probably neither of these.

My debug info is:

    KeePassXC - Version 2.4.3
    Revision: 5d6ef0c

    Qt 5.13.1
    Debugging mode is disabled.

    Operating system: Arch Linux
    CPU architecture: x86_64
    Kernel: linux 5.3.1-arch1-1-ARCH

    Enabled extensions:
        - Auto-Type
        - Browser Integration
        - SSH Agent
        - KeeShare (signed and unsigned sharing)
        - YubiKey

    Cryptographic libraries:
         libgcrypt 1.8.5

Also, I can pretty much confirm that this bug occurs if and only if Firefox is started afters KeepassXC.

**Comment by varjolintu** [comment]
Anyone affected by this, please try https://github.com/keepassxreboot/keepassxc-browser/issues/615#issuecomment-538622196. See https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually for instructions.

**Comment by nudgegoonies** [comment]
I have read the comments from the linked comment on. De-activating and Re-activating works as a workaround.

Because the link from the wiki did not work for me (about:debugging#/runtime/this-firefox) i only opened about:debugging and the KeepassXC 2.4.3 entry shows the following message:
```
Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.
```
This line comes from the latest release, not from the keepassxc-browser_test_build_2.zip file.

Then i quit firefox, started keepassxc (without opening my database), started firefox, went to the debugging poage, loaded the manifest from the keepassxc-browser_test_build_2.zip and it works.

**Comment by nudgegoonies** [comment]
I have read the comments from the linked comment on. I can confirm that de-activating and re-activating works as a workaround too.

Because the link from the wiki did not work for me (about:debugging#/runtime/this-firefox) i only opened about:debugging and the KeepassXC 2.4.3 entry shows the following message:
```
Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.
```

This line comes with the latest release and also from keepassxc-browser_test_build_2.zip file.

Then i quit firefox, quit keepassxc. started keepassxc, started firefox, went to the debugging page, loaded the manifest from the keepassxc-browser_test_build_2.zip and it works. But i suspect that temporary loading a local plugin could be the same effect as de-activating and re-activating. For a real test the keepassxc-browser_test_build_2.zip version must be a permanent plugin to survive a browser-restart.

**Comment by varjolintu** [comment]
That error line is not relevant. It's just one property that only Chromium-based browsers use in the manifest.

And yes, temporary loading doesn't survive a browser restart. I think you'll need to use `web-ext` for that. See https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/

And make sure your are using the `--firefox` parameters to give it the path of your local installation. Otherwise it probably loads a nightly or beta version for the run.

**Comment by derula** [comment]
I appeared to have the same problem (connection to KeepassXC fails due to some key exchange error if Firefox was started after KeepassXC; restarting KeepassXC while Firefox is running fixed it). De-activating and re-activating the extension did not help, however.

I tried the version from https://github.com/keepassxreboot/keepassxc/issues/3598#issuecomment-538776241, but it didn't work at all, not even if KeepassXC was started after. I re-enabled version 2.4.3 of the extension, now it doesn't connect at all anymore, regardless of which order browser and Keepass are started in.

I realized though that if I start the browser after KeepassXC, it seems to _think_ it's connected (green KeepassXC logo rather than gray with an X), but it just doesn't find any passwords when it should. (Not a PEBKAC, it worked earlier on exactly the same page with the same database being loaded etc.).

I'm on Windows 10, Firefox 69.0.2.

It gave me the error "No content script available for this tab.", I googled this and found https://github.com/keepassxreboot/keepassxc-browser/issues/609, which suggested removing all browser connections from database settings. Did that, tried to connect again, got the popup from KeepassXC to name the connection. Now the connection shows up in database settings, but not in the extension options. Clicking "connect" again does nothing. After restarting KeepassXC, the connection shows up in the extension settings, but still isn't working.

Tried running the version from https://github.com/keepassxreboot/keepassxc/issues/3598#issuecomment-538776241 again, still nothing. Back to 2.4.3, nothing, console log:

> Error 7: Message encryption failed. Is KeePassXC running? keepass.js:1061:13
> Failed to connect: Unknown error keepass.js:946:13
> Error: No content script available for this tab. keepass.js:1174:25
> Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 2 keepass.js:1061:13
> Error: No content script available for this tab. keepass.js:1174:25

Restarted KeepassXC again, still nothing, console log:

> Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 2 keepass.js:1061:13

Disable / enable extension, console log:

> Error 7: Message encryption failed. Is KeePassXC running? keepass.js:1061:13
> Server public key: [REDACTED] keepass.js:603:21
> Error 4: Cannot decrypt message 2 keepass.js:1061:13
> Error: No content script available for this tab. keepass.js:1174:25

(Yes, KeepassXC is running. Yes, browser integration is enabled.)

I'm more or less randomly trying out different things, please let me know if you need me to do anything in particular. Sorry if my problem is actually unrelated.

**Comment by nudgegoonies** [comment]
Thank you very much. The new version of the plugin fixes the problem.
