### ISSUE TITLE
Can't open DB because "Invalid credentials" (not true)

### ISSUE THREAD

**Issue by franalbani** [keepassxreboot/keepassxc#3611]
Since a few days ago, I'm unable to open my DB. I tried with a known-to-have-worked back up and I get the same message:

![keepassxc_error](https://user-images.githubusercontent.com/13975308/66516825-5441ef00-eab8-11e9-93d8-8f0ba85ee1e1.png)

I'm 100% sure of using the right password and 99% sure it is not corrupted.

## Expected Behavior
Opening DB as usual...

## Current Behavior
See screenshot

## Context
Using up-to-date Arch Linux. It may have stopped working after a system update, but I'm not sure. I use etckeeper so I can gather more info, if you tell me what to look.

## Debug Info
KeePassXC -  2.4.3-1

Operating system: Arch Linux
CPU architecture: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
Kernel: 5.3.5.arch1-1

**Comment by droidmonkey** [comment]
Make sure all the checkboxes are unchecked except for the password

**Comment by franalbani** [comment]
> Make sure all the checkboxes are unchecked except for the password
Thanks.
I already tried based on other issues. No difference.

**Comment by droidmonkey** [comment]
There is nothing further we can do to assist, unfortunately.

**Comment by droidmonkey** [comment]
Sure you can try using normal keepass

**Comment by franalbani** [comment]
I tried with keepass on mono, and with another keepasxc running in an arch linux docker.

Same problem.

I'm puzzled.

**Comment by droidmonkey** [comment]
Then its probably corrupt

**Comment by franalbani** [comment]
> Then its probably corrupt, where are you storing the database?

It was on my laptop SSD. No known failures.

What puzzles me is that the backup was made before the main copy stopped working.

**Comment by droidmonkey** [comment]
Did you change your keyboard layout?

**Comment by franalbani** [comment]
> Did you change your keyboard layout?

No.

In any case, I checked many times the password was correct, after hitting the eye icon.

**Comment by droidmonkey** [comment]
Did you do ANYTHING to your database before this happened? Changed encryption settings? Changed the password itself? Anything???

**Comment by franalbani** [comment]
> Did you do ANYTHING to your database before this happened? Changed encryption settings? Changed the password itself? Anything???

Nothing.

**Comment by ditrianum** [comment]
I have exactly the same problem. The file is not corrupt. When I restarted Linux I could not open the database anymore. I finally managed to open it by unchecking the database file checkbox. Is this expected behaviour?
![Screenshot_2019-10-13_08-59-03](https://user-images.githubusercontent.com/54737955/66712099-c0ae3e00-ed97-11e9-9af7-eaf31626248a.png)

**Comment by droidmonkey** [comment]
That's not supposed to be the database file at all. That is for a separate non-changing file that gets added to your password to unlock the database. There should be no text in that field.

**Comment by ditrianum** [comment]
Yes, I see it now. I don't know why I mixed that up.

**Comment by phoerious** [comment]
I have seen that quite a few times. We have even received emails about it. Would it make sense the warn users if they are trying to use their database file as a key file? There is no way this is going to work. Even if you actually added the database file as a key file, you wouldn't be able to open it anymore, because that changes the database file and you effectively lost access forever unless you had a backup somewhere. I haven't seen that extreme yet, but if we're already adding safeguards for opening a database, we might as well prohibit saving a database with itself as a key file.

**Comment by franalbani** [comment]
> I'm 100% sure of using the right password and 99% sure it is not corrupted.

Guess what?

I will close this issue and remove myself from the Internet for a while, to meditate on my actions.
