### ISSUE TITLE
Different encryption performances on various Linux distros

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#3657]
Fedora package maintainer here. User claims worse encryption performances on Fedora. I don't know how this can happen. Details at
https://bugzilla.redhat.com/show_bug.cgi?id=1653435

**Comment by phoerious** [comment]
This is most likely a problem with a difference in hardware support for performing AES rounds. Please check the flags libgcrypt was compiled with.

I also strongly recommend not using AES-KDF at all. It's not a good KDF and since AES is so fast, the 1s benchmark outcome fluctuates massively depending on current CPU utilisation. Both the Android and iOS clients we recommend in our FAQ have support for Argon2 and I don't know of any other popular alternative that doesn't, so there is really no reason for sticking with AES-KDF.
