### ISSUE TITLE
KeePassXC wants to record the screen.

### ISSUE THREAD

**Issue by dktcoding** [keepassxreboot/keepassxc#3689]
I updated KeePassXC to 2.5.0 with Homebrew on macOS:

~~~
==> Upgrading 1 outdated package:
keepassxc 2.4.3 -> 2.5.0
==> Upgrading keepassxc
==> Satisfying dependencies
==> Downloading https://github.com/keepassxreboot/keepassxc/releases/download/2.5.0/KeePassXC-2.5.0.d
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/52729242/7624cb0
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'keepassxc'.
==> Backing App 'KeePassXC.app' up to '/usr/local/Caskroom/keepassxc/2.4.3/KeePassXC.app'.
==> Removing App '/Applications/KeePassXC.app'.
==> Unlinking Binary '/usr/local/bin/keepassxc-cli'.
~~~

And when I run it, Catalina shows this warning:

![Screen Shot 2019-10-27 at 17 38 52](https://user-images.githubusercontent.com/709639/67641425-e5023280-f8e0-11e9-9a39-9a2c8b3095fc.png)

Why?

**Comment by elsesiy** [comment]
Please see [here](https://github.com/keepassxreboot/keepassxc/pull/3624) for more details, simply put:
Auto-Type needs to find the window tile for which in MacOS 10.15+ you have to request a special permission.

**Comment by droidmonkey** [comment]
This is what happens when overzealous operating systems decide to word their "privacy" settings with scary sounding names.

**Comment by phoerious** [comment]
We should show a popup first telling the user what we are about to do (with the option to never ask again) and then trigger the permission dialogue. I think that's what we should have done in the first place, since simply triggering this scary-looking dialogue will understandably frighten and confuse users who don't expect it.

**Comment by phoerious** [comment]
I'll reopen this as a UX issue to fix in 2.5.1.

**Comment by keganlance** [comment]
It's totally possible some people are not concerned about the app asking for this permission. Yet it be a good idea to not keep asking for this is the user decides not to grant access and doesn't want to use the Auto-Type feature.

**Comment by tessus** [comment]
Another issue #3731 was closed as a duplicate, even though the message is a compltely different one.

I'm not using auto-type, yet the application prompts every time at start to open system preferences.
If I say 'no', the app is supposed to remember the no and never prompt again. (I can always go to system preferences and give the permission later on...)

Can you plese clarify, if this is really the same issue and if it was fixed by #3624.

**Comment by kitzler-walli** [comment]
It would be great if the application would remember my choice to not give accessibility permission. 
Currently the app asks every time I start it.

**Comment by droidmonkey** [comment]
My idea to get this out the door for 2.5.1 is to move the check for permissions into the global Auto-Type hotkey when it is initially pressed. Also, add a button in the Auto-Type settings that explicitly asks the OS for the permissions. This will prevent it from asking at startup and allow for people to recover from a denial and still use the feature.
