### ISSUE TITLE
Shortcut of the kdbx-database in the windows-taskbar does not open the database. Instead it opens KeepassXC in the welcome-screen.

### ISSUE THREAD

**Issue by rockybeachradio** [keepassxreboot/keepassxc#3716]
Hello,
first I wan ttho say thank you for the great software and your engagement in developing it.
Unfortunatelly I experience a issue and hope you can help.

## Expected Behavior
Add the kdpx-database as shortcut in the windows-taskbar.
When clicking on the shortcut: Keepassxc should start, open the database and ask for its password.

## Current Behavior
Instead Keepass openes in the "welcome screen". Then I have to use the open database button and navigate to the database.

A shortcut to the kdbx-databse works as expected.

## Steps to Reproduce
1. Move the kdbx-file to the taskbar (next to the start-button) and create a shortcut.
2. Click on the kdbx symbol in the taskbar
3. keepassxc starts in the welcome-screen. Should open the database and ask for its password.

## System details
Operation System: Windows10
KeepassXC version: 2.4.x & 2.5.0

## Question
Can that be fixed?
Is there a workarround?

Thanks for helping.
Best.

**Comment by droidmonkey** [comment]
Does double clicking the kdbx file itself (not in taskbar) start KeePassXC with the database loaded?

**Comment by rockybeachradio** [comment]
Yes, normal behavior.
The shortcut on the desktop also works fine.

**Comment by droidmonkey** [comment]
Ok thank you, will debug

**Comment by rockybeachradio** [comment]
Thank you.

**Comment by droidmonkey** [comment]
OK, I see the problem. When you pin a non-executable to the taskbar, Windows 10 actually pins that to the executable jump menu. See these screenshots:

![image](https://user-images.githubusercontent.com/2809491/67821213-94cad200-fa92-11e9-857f-a9e186196aae.png)

![image](https://user-images.githubusercontent.com/2809491/67821237-b0ce7380-fa92-11e9-9998-1a1bde44ef5c.png)

You should just enable the setting "Reopen last used databases" in settings. We cannot fix this since it is Windows 10 behavior.
