### ISSUE TITLE
Uses wrong translation

### ISSUE THREAD

**Issue by teresaejunior** [keepassxreboot/keepassxc#3730]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC should use keepassx_pt_BR.qm:

```sh
GDM_LANG=pt_BR
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
```

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

No matter if language is set to "System default", or set specifically to "Portuguese (Brazil)", `lsof` is listing the generic `/usr/share/keepassxc/translations/keepassx_pt.qm`, which is closest to "Portuguese (Portugal)".

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Versão 2.5.0
Revisão: 1ab8a9f

Qt 5.12.4
Debugging mode is disabled.

Sistema operativo: Ubuntu 19.10
Arquitetura do CPU: x86_64
Kernel: linux 5.3.0-18-generic

Extensões ativas:
- Escrita automática
- Integração com navegador
- Agente SSH
- KeeShare (partilha assinada e não assinada)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by irgendsontyp** [comment]
This is because translator->load() [calls](https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Translator.cpp#L85) QLocale's uiLanguages() method which returns a list of language identifiers ordered by preference.

Quote from https://doc.qt.io/qt-5/qlocale.html#uiLanguages:

> The first item in the list is the most preferred one.

On my system (Arch Linux), the list looks like this:

> ("pt", "pt-BR", "pt-Latn-BR")

Because "pt" is the first item, the translator loads the file keepassx_pt.qm instead of keepassx_pt_BR.qm which it should load.

I couldn't find out how the ordering of the list is decided. Does someone know?

**Comment by droidmonkey** [comment]
Ordered by your operating system preferences, most likely

**Comment by teresaejunior** [comment]
I did a search on /etc, and the only files that seem to affect locales are `/etc/default/locale` and `/etc/locale.gen`, nothing really to see here, it seems:

```
~> cat /etc/default/locale
#  File generated by update-locale
LANG="pt_BR.UTF-8"
LANGUAGE="pt_BR:pt:en"

~> grep -v ^# /etc/locale.gen
en_US.UTF-8 UTF-8
pt_BR.UTF-8 UTF-8
```

**Comment by teresaejunior** [comment]
Actually, LANGUAGE="pt_BR:pt:en" means "prefer pt_BR over pt"...

**Comment by droidmonkey** [comment]
This will have to be debugged

**Comment by irgendsontyp** [comment]
[QLocale::uiLanguages()'s source code](https://github.com/qt/qtbase/blob/2c4b44d7500be72b6eb74c4989e7311b3f924119/src/corelib/text/qlocale.cpp#L4385)

Looking at line 4430 to 4442, if I get the code right, the "minimal" version (which would be "pt" here) is added to the uiLanguages list as the first element (line 4442) without any condition.

A possible solution would be to manually create the locale file's filename by doing something like this:

`QString localeFileName("keepassx_");
localeFileName += language;`

and then calling another overload of QTranslator's load() method:

`if (translator->load(localeFileName, path)) {`

**Comment by droidmonkey** [comment]
That Qt function is a mess. I wouldn't be surprised if there are a ton of bugs in there because it looks like its doing a lot of guessing and manipulation of the list. Recommend a Qt bug report at this time.

**Comment by teresaejunior** [comment]
> This works for me: pt_BR is loaded when choosing Portuguese (Brazil) in the settings.

Weird. For me, both the APT and Snap packages load `keepassx_pt.qm` instead when "Portuguese (Brazil)" is explicitly set.

**Comment by Throne3d** [comment]
I've investigated this behavior a bit more, and it seems that `QTranslator`'s `load(...)` will now load the most general available translation file for a given locale, because that's the first translation file that matches a string in `QLocale`'s `uiLanguages()` return value (i.e. `pt`, or if that doesn't exist, `pt_BR`, or else `pt_Latn_BR`). I'm guessing it didn't do this in the past, since in KeePassXC 2.4.3 we still had `keepassx_pt.ts`, and it didn't break things then.

This only affects Portuguese (Brazil), because we don't have a `keepassx_en.ts` (for English) nor `keepassx_zh.ts` (for Chinese) in the final build – or at least we don't when I built it locally, despite having https://github.com/keepassxreboot/keepassxc/blob/2.4.3/share/translations/keepassx_en.ts in the tree. If we did, and they were different, then English (United States) and Chinese (China) could be affected as well.

A quick and unpleasant fix for this in particular might be to remove the `keepassx_pt.ts` translation file and/or "Portuguese" locale, at the risk of messing with Portuguese speakers outside Brazil and Portugal. I haven't diffed Qt at all here, just looked through some of the source code for how they're doing it now, but it might also be worth inquiring with them about the change in behavior? It seems like the translator really should load using the _most_ specific one it can, first, and fall back to the less specific ones, but I hardly know anything about this whole process.

**Comment by droidmonkey** [comment]
I still believe there is a bug within Qt here. We mitigate part of this bug by compiling our own prioritization, but at the end of the day Qt still chooses the wrong file to load.

**Comment by phoerious** [comment]
Choosing the more general over the more specific one doesn't make any sense. The en case is special, because en is the source file and not an actual locale we ship. But if it were, I would still expect to get en_GB, since that is my locale and en only if I had something like en_NZ, for instance.  I think here it's pretty clear which order makes sense. A bit problematic is only when we do not have a fallback without territory code. In that case, it's difficult to decide which locale is the most fitting one.

**Comment by Throne3d** [comment]
The [QLocale docs](https://doc.qt.io/qt-5/qlocale.html#uiLanguages) state that `uiLanguages` returns the list in preference order '(like "en-Latn-US", "en-US", "en")', except in practice it’s returning the complete reverse of that.

Definitely looks like a Qt bug. :/

**Comment by droidmonkey** [comment]
Closing due to Qt bug that we are not going to work around.
