### ISSUE TITLE
Password Generator: Entropy changes when moving from Password to Passphrase and back.

### ISSUE THREAD

**Issue by ReallyReally17** [keepassxreboot/keepassxc#3785]
In the Password Generator; after entering or regenerating a password, KeePassXC shows a value for Entropy. Then, if I move from Password to Passphrase and back, KeePassXC shows a different value for Entropy... sometimes by a difference of greater than 5 bits of entropy.

This makes me unsure about the real value of entropy. If the calculation of Entropy is not repeatable, then maybe the lowest value out X calculations should be shown.

## Expected Behavior
When moving from Password to Passphrase and back, the value for entropy should NOT change.

## Current Behavior
When moving from Password to Passphrase and back, the value for entropy changes.

## Steps to Reproduce
1. Open Password generator.
2. select the Password tab and note the Entropy.
3. click on the Passphrase tab.
4. click on the Password tab and note the Entropy.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
That is working as intended. For a passphrase we use the word list as alphabet, which changes the calculated entropy.

**Comment by ReallyReally17** [comment]
You are right. I just noticed that when moving from Password to Passphrase and back, the password is regenerate. That is the reason for the different entropy. But does that make sense?

When I regenerate passphrases, the entropy stays the same with the same word count. When I regenerate passwords with "A-Z", "a-z", "0-9", "/*_..." selected, the entropy keeps changing. Does this make sense?

**Comment by phoerious** [comment]
It's not just that the password is being regenerated. Given the same password/-phrase, the entropy would still be different. If your alphabet is characters, then you will have a different entropy for "abc" than if your alphabet is words, in which case "abc" would just be one symbol, not three.

**Comment by SebiderSushi** [comment]
Reading your explanation i am still not convinced that the entropy of a password should change as long as the generator settings stay the same. This came out as quite a lengthy post, so:
#### **TL;DR:**
Isn't entropy a specifically defined measure that does not factor in uncertainty of a given passcode and only statistical attributes that are based on the number of unique symbols that are used to generate it, their probability to be picked and the number of symbols used to construct the passcode?

#### Otherwise: Here's why i think so, please tell my why i'm wrong.

Given [this](https://generatepasswords.org/how-to-calculate-entropy/) explanation of entropy, we can conclude that the entropy changes **only if** the number of possible combinations changes aswell.
This happens if either the set of symbols possibly included in the passcode, the number of symbols totally included in the passcode or the number of rejected combinations changes.

My understanding of the password generator is the following:
- Settings define the set of symbols used for the passcode.
- The generator then chooses one random symbol out of the predefinced set. This step is repeated until the desired number of symbols used for the passcode is matched.
- The set for passphrases is the wordlist. It contains about 7'000 unique symbols, each of which contains one word plus the selected word seperator as a symbol.
- The set for passcodes is created by combining all sets of characters chosen by the user to be included in the password into one conclusive set. Each entry to the set contains one of these characters as a symbol. For example, combinig the sets [a-z] and [0-9] would result in a set with 36 unique symbols.
- **The number of symbols used in a passcode** should **only** change when the user modifies the value of desired words/characters in the passcode. **This requires changing the generator settings.**
- **The numer of unique symbols** should **only** change when **A.** the (hardcoded?) wordlist is updated, or **B.** the user decides to include different characters in his password. **This also requires changing the generator settings.**
- **The number of possible combinations** will decrease, if the option "**Pick characters from every group**" is checked. The number of possible combinations for a passcode generated with these settings is given by (_number of total combinations_) - (_number of combinations that do not include characters from each set_). This decreases entropy but is still a fixed value that does not change between generating passcodes.
If the option is not checked, then every unique symbol should have an equal chance of being chosen for a given position in the passcode. This is what randomness means. If the generated passcode lacks symbols from a specific subset included for generating it, then this should not decrease entropy, as the number of possible combinations remains the same. The resulting passcode is just one of these possible combinations of the symbols from the defined set.

As for patterns, my understanding goes that if your resulting passcode is equal to a pattern or contains one, it is more likely to be guessed by an attacker first trying out likely password combinations or slight modifications of them. This affects the uncertainty (as mentioned [here](https://en.wikipedia.org/wiki/Entropy_(information_theory)#Limitations_of_entropy_in_cryptography)) for the given passphrase, but should not affect the entropy, as it is defined based on the statistical attributes of the _generator_ and makes no statement about uncertainty of a passcode. In terms of passcode strength this matters, but i don't think or know that it has anything to do with entropy itself.

As far as i understand the topic, passcode entropy is a measure of how many attempts an attacker would averagely need to guess a passcode in a brute force attack. This measure also assumes that the attacker knows the set of symbols used to generate the passcode and its maximal length. Otherwise it would also need to factor in guesses of passcodes that contain symbols that were not in the set of symbols used for generating the passcode.
Entropy seems like a very specific measure and not equivalent to passcode strength or security.
If my understanding is correct, then what is implemented in KeePassXC seems like a passcode strength score which is based on entropy, but not the same as entropy.

After all the passcode strength depends largely on how many assumptions an attacker can make about the passcode they want to find out.
The passcode strength also just indicates a probabibility of how likely it is to be found out. It's highly unlikely but still theoretically possible that a specific brute force attack might just guess your passcode on the first try. 
If an attacker knows almost nothing about a passcode then they would only be able to brute-force it, and this is where entropy seems like an applicable measure. As soon as an attacker knows that specific patterns are used more often than others, entropy just fails.
