### ISSUE TITLE
Add Two-Channel Auto-Type Obfuscation (TCATO)

### ISSUE THREAD

**Issue by vlenzer** [keepassxreboot/keepassxc#381]
Hey guys,

what about adding Two-Channel Auto-Type Obfuscation (TCATO) from KeePass in KeePassXC? I think it would be a nice feature.
In case you don't know what it is:

> Instead of simply sending simulated keypresses to the target application (as normal auto-type does), obfuscated auto-type does the following:
> 
> - Backup the current clipboard contents.
> - Intelligently split the text into parts.
> - For each part: check if the clipboard can be used.
> 
> 1.  If yes: Split it into two subparts (character-wise, like two flat intertwining combs). Copy/paste the first part, merge the rest by sending keypresses.
> 2.  If no: Send it normally using simulated keypresses.
> 
> - Restore previous clipboard contents.

The goal should be a safer Auto Type - to make work for keyloggers much harder.

**Comment by TheZ3ro** [comment]
We were talking about it here https://github.com/keepassxreboot/keepassxc/issues/20#issuecomment-252799731

**Comment by phoerious** [comment]
Autotype obfuscation is IMHO absolutely useless. Why would an attacker want to log your autotype passwords when he can simply log your master key each time you unlock your database?

**Comment by vlenzer** [comment]
@phoerious because a pure keylogger then has now every information to log in to a specific website. While the master key is useless without any information about savingpoint or keyfile.

But it seems as it is useless nevertheless as descripted it the linked comment.

**Comment by phoerious** [comment]
When you can install a Keylogger, you can install anything, including a mal ware that abducts your password safe.

**Comment by Throne3d** [comment]
I think the point is possibly that even if you're infected with a keylogger, it might not target any of your password databases whatsoever. You might be at high risk of getting another virus that *does*, of course, but if you get just the one virus in a freak accident and it does not abduct your password safe, only keylogs, this would keep you safe from it. It's about reducing the surface area of attack, since a lot of viruses are targeted only at one thing (i.e. logging keystrokes to find your passwords), as opposed to being a targeted attack on *your* habits.

So while yes, if you can install a keylogger you can also install other malware, that's not to say that investigating ways to reduce the attack area is useless. If you can install a keylogger you can also install an application that sifts through other application's memory for passwords, but that's not really an argument against also protecting KeePassXC's memory area except for how much effort you're willing to put into it.

**Comment by TheZ3ro** [comment]
TCATO works in a way that "Split it into two subparts (character-wise, like two flat intertwining combs). Copy/paste the first part, merge the rest by sending keypresses.".

A keylogger then can copy to the clipboard, listen to KEY_LEFT and KEY_RIGHT and calculate the original password. There are already PoC, not every keylogger can do this.

TCATO is useless against targeted attack, but can keep users safe against very basic keylogger.

**Comment by Throne3d** [comment]
It seems worth considering, then, rather than dismissing out of hand? It's possible we don't want to put the effort into implementing this for the perceived gain, but the gain *might* be worth it.

**Comment by TheZ3ro** [comment]
If someone is willing to work on it, IMHO is in the wishlist

**Comment by jeroen7s** [comment]
i would definitely considder this, especially since keyloggers can easily be run without any admin permissions, on linux with xorg it's litteraly as simple as running "xinput test {keyboardID}", on windows it's also pretty damn easy to make a keylogger

**Comment by phoerious** [comment]
As stated above, TCATO is a big bunch of hogwash. All modern keyloggers come with features such as logging which programs start up and when, make screenshots, copy files etc. If such a program is on your PC, keeping your Auto-Type passwords safe is one of your least concerns. I feel like, it rather creates a deceiving sense of security.

**Comment by zzflux** [comment]
TCATO is only capable of protecting against a basic keylogger, and I think it is possible that it can help (again, only against a basic keylogger) on the Windows version of Keepass2 because of the secure desktop password prompt. I'm pretty sure most Linux systems don't have a working equivalent of this concept, so I can see how TCATO is of limited use here (though still, a pure keylogger would run into the problem of a missing database and/or keyfile).

**Comment by phoerious** [comment]
I don't understand they concept of a "basic" Keylogger. The most basic free Keylogger you can find on Google already records everything with timestamp and screenshot. So even if it doesn't catch the whole password, an attacker will see exactly what the user is doing and can easily adapt to that. That Keylogger is marketed as an "employee monitoring tool", which is fishy but real malicious keyloggers are a lot more advanced than that.

**Comment by droidmonkey** [comment]
I actually recommend closing this issue, I do not foresee us ever implementing this "feature".

**Comment by Michaelsy** [comment]
> I do not foresee us ever implementing this "feature".

That's too bad. I had considered switching from KeePass2 to KeePassXC because I like several points better. But the absence of the TCATO feature is an important reason for me to stay with KeePass2. 

The arguments that IMHO speak for TCATO have already been mentioned in this thread.

Nevertheless I thank you very much for the enthusiasm and effort of this one more FOSS project! :+1:

**Comment by kubycsolutions** [comment]
@phoerious: I understand your objection that you think TCATO lends a false sense of security. However, you haven't indicated that it does any harm, or that it would be hard to implement or maintain. 

What concerns me is that you seem to be saying you're not receptive to discussing whether there's a better solution to the actual concern behind the request. You're rejecting the general issue because you don't like the specific proposal, rather than accepting this as an area worth continuing to look at. That does not give me a warm fuzzy feeling about future support for user requests that may not be exact fits to your current vision for the project.

There may not be a better solution. But I'd be happier if the answer was "I don't think this would achieve what you actually want, but  I'll leave this open so folks can brainstorm alternatives. We support browser plug-ins, for example, which can provide a more protected channel." (You do, right?)

**Comment by phoerious** [comment]
This has been discussed more than enough. It's a nonsensical feature and we are not going to implement it.
