### ISSUE TITLE
Set URL field text suggestion to 'https://example.com'

### ISSUE THREAD

**Issue by matjon** [keepassxreboot/keepassxc#3830]
Hello,
I have been introducing KeePassXC to a non-technical user. She was slightly confused about the field with the name "URL" since she apparently did not know what a URL is.

## Possible Solution
Rename "URL" to "Webpage" and add a note to translators that the translated name should be clear to non-technical users.

## Debug Info
Still present in KeePassXC 2.5.0. We have been using the Polish translation, but the field name is same in English version.

**Comment by varjolintu** [comment]
You can also use URL's like `cmd://C:\Windows\Notepad.exe C:\Test\MyTestFile.txt` (according to the KeePass documentation), so changing the field name to "Webpage" is a bit misleading.

**Comment by droidmonkey** [comment]
That is certainly an advanced usage though

**Comment by matjon** [comment]
@varjolintu This is not discoverable at all and possibly could even cause security problems when working with untrusted databases. Frequently, some passwords are shared among multiple people in an organization (administration credentials for printer devices, for instance). Setting the URL to something funny (e.g. `cmd://reboot`) would not be inconceivable and tracing the joker would not be simple in many cases.

If someone would take the time and read this section of the documentation, this would be "a nice feature". Calling `cmd://C:\Windows\Notepad.exe` a "Webpage address" would be a stretch, but not impossible to imagine.

The field name could also be changed to "Address".

**Comment by droidmonkey** [comment]
"Address" is almost guaranteed to get people to put in their street address :-)

**Comment by varjolintu** [comment]
Or just "Webpage / URL" :)

**Comment by matjon** [comment]
> @varjolintu This is not discoverable at all and possibly could even cause security problems when working with untrusted databases.

I have tested it and KeePassXC asks for confirmation before executing any programs specified in the URL field. So there is no security problem.

Maybe just "Webpage" as it is simpler and shorter.

**Comment by darkwing1** [comment]
Im sorry to say but if a user doesn't (by now) know what a URL is then they shouldnt be using a password manager.  Technical user or not, URL is a universal "word" that everyone today should know.

I am happy seeing it as 'URL' because 'Webpage' is completely misleading as stated above for internal paths, and what about IP addresses, has anyone considered that one?
Besides, the most important thing is that if that user (that doesnt know what URL is) logs onto keepass on a daily basis, surely they will get used to the idea of keepass showing the 3 most basic fields namely: **Username - Password - URL**

Its obvious that URL shows the web address, such as www.twitter.com, clearly the user should get used to this and see it as a web address.
I taught my grandma who is 75 years old where the URL is and she gets it because she uses keepass everyday.
No offense, but this issue is pointless.

**Comment by sunjam** [comment]
A clearer example and compromise might be to display _eg. www.example.com_ within the url field when no url has been added.

**Comment by droidmonkey** [comment]
That is a good compromise!

**Comment by quinncomendant** [comment]
Hard disagree. "Webpage" is a meaningless label (Webpage _what_?). Because of the functionality tied to the `Open URL` command, this field can contain URLs with some non-"webpage" schemes such as:

- `sftp://`
- `ssh://`
- `file://`
- or a custom application URL scheme such as `evernote://`

Thumbs-up on the suggestion for a placeholder value of `https://www.example.com` as a compromise.

TIL KeePassXC is used by non-technical users 😳
