### ISSUE TITLE
Latest versions need OSX 10.12

### ISSUE THREAD

**Issue by kflesch** [keepassxreboot/keepassxc#385]
DMG explains that Version support OSX 10.7.x

## Expected Behavior
should specify which is the base version of OS supported
## Current Behavior
App needs OSX 10.12 latest working version is 2.1.1

**Comment by rockihack** [comment]
Instead of using the environment variable `export MACOSX_DEPLOYMENT_TARGET=10.7` in the release-tool script consider using `CMAKE_OSX_DEPLOYMENT_TARGET` to fix this issue.

https://cmake.org/cmake/help/v3.8/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by phoerious** [comment]
According to the documentation, CMAKE_OSX_DEPLOYMENT_TARGET is initialized with the value of the environment variable. I also checked the generated Makefiles and the -mmacosx-version-min is set correctly.
We had one report like this before, but they fixed it by rebooting their machine. Since then we haven't had any reports about compatibility errors except this one.

**Comment by TheZ3ro** [comment]
I think @kflesch is using the `brew cash` package and that it's outdated (the first commit says 2.1.1)
Try the latest 2.1.3 version on the website, thanks

Also @phoerious we should open an issue on *cash* for updating the KeePassXC package (and remember doing that for every release)

**Comment by kflesch** [comment]
Have redownloaded the latest version and now is fine. Sorry for the inconvenience.

**Comment by TheZ3ro** [comment]
No problem :smile:
