### ISSUE TITLE
`keepassxc-cli clip` with a timeout blocks the terminal

### ISSUE THREAD

**Issue by jjerome00** [keepassxreboot/keepassxc#3855]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
 * I want to get a copy of a password from the terminal (`keepassxc-cli clip`), and have it clear my clipboard after the given timeout
 * The command works, but there is a countdown that blocks any other commands from being run in that terminal session
 * This keeps me from using the password in the terminal during that time

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
1. I want to push my repo to github
2. I run the command `keepassxc-cli clip ... 5`
3. keepassxc copies my requested password to the clipboard
4. I push my repo to github (in the terminal), it asks for my password, I paste it (within 5 seconds)
5. 5 seconds goes by, my clipboard is cleared

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Could this process be run/sent to the background?

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
If I'm running the command from the terminal, then chances are I want to use the password in the terminal

In my particular case, I'm running this in Linux Mint
Keepassxc version 2.3.1

**Comment by droidmonkey** [comment]
Tack an & at the end to send it to the background

**Comment by jjerome00** [comment]
I've tried adding an `&` to the end of the command, but when keepassxc asks for my (db) password, it's shown in clear text.

**Comment by droidmonkey** [comment]
That's curious. @louib any ideas? What's the expected workflow here?

**Comment by louib** [comment]
I guess the password is shown in cleartext because disabling terminal echo only works if the process runs in foreground.

As for the blocking problem, the easiest way that I see would be to use native features from the clipboard managers to clear the password after a timeout, so that we don't have to block the `keepassxc-cli` process. `xclip` does not offer such a feature from what I can see, but we've been asked to support other clipboard managers (see https://github.com/keepassxreboot/keepassxc/issues/3812), which might offer that feature.

@jjerome00 I guess you could do the clearing yourself with a script like:
```bash
clear_clipboard () {
  sleep 5s
  echo "" | xclip -i -selection clipboard
}

keepassxc-cli clip ~/passwords.kdbx $1
clear_clipboard&
```

In which case the best we could do would be to add a `clip --clear` option, which would result in the following script:
```bash
clear_clipboard () {
  sleep 5s
  keepassxc-cli clip --clear
}

keepassxc-cli clip ~/passwords.kdbx $1
clear_clipboard&
```

**Comment by jjerome00** [comment]
This works! I was planning on creating a script for one particular entry anyway. Thanks!

**Comment by krzkrzkrz** [comment]
In keepassxc-cli `2.6.2`, `keepassxc-cli clip --clear` returns with: `Unknown option 'clear'.`

**Comment by droidmonkey** [comment]
That's cause it's not implemented
