### ISSUE TITLE
KeepassXC blocking yubikey static password input (Ubuntu 19.10)

### ISSUE THREAD

**Issue by PeterWq** [keepassxreboot/keepassxc#3884]
Found that when using keepassXC my yubikey static password input could not be used till I remove yubikey out of usb slot and put it back.
When the KeepassXC app is not open the static password is working fine.
The problem is that I'm using yubikey static password as part of my master password

## Expected Behavior
Keepass should not block usage of the yubikey static password

## Current Behavior
As soon I start KeepassXC app and selected the yubikey for challenge-response, the yubikey static-password input is not working till remove the yubikey from the computer and adding it back

## Possible Solution
I suspect the keepassxc is blocking yubikey somehow

## Steps to Reproduce
1. Open keepassXC database that is using yubikey challenge-response and select the yubikey in the hardware key field;
2. in the password field type your password + click the yubikey to input static password (it should be set on the yubikey on slot 1 or 2). THis step could be also be tried just by open any text editor and try to input yubikey static password;
3. the static password input is not working till remove the yubikey from the computer and adding it back;

## Context
Using yubikey challenge-response and static password for your keepassXC database

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.0.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by phoerious** [comment]
The YubiKey not being properly released after use is a known issue. Regardless though, there is no real reason to use both HMAC and a static password for your database.

**Comment by droidmonkey** [comment]
Duplicate issue

**Comment by onlykey** [comment]
@phoerious @droidmonkey Can you guys point me to any more details on how we might properly release Yubikey/OnlyKey? I have been able to reproduce this issue with OnlyKey and Yubikey and have been trying to implement a fix for this in https://github.com/keepassxreboot/keepassxc/blob/develop/src/keys/drivers/YubiKey.cpp and then would do a PR. I do understand that there is no reason to use both HMAC and static password with KeepassXC but the issue is that once KeepassXC binds to the USB device its not releasing it, so lets say you use a static password to log into your Linux box then HMAC with KeepassXC, after launching KeepassXC you could no longer use the static password at all in the Linux OS unless you physically remove the USB device.

Issue details:
- After selecting Yubikey/Onlykey in KeePassXC the USB device is unbinded from Linux more detail here - https://github.com/trustcrypto/OnlyKey-Firmware/issues/98#issuecomment-600894240
So even after you close KeepassXC the static password feature on Yubikey/OnlyKey no longer works.
- Seems to only affect Linux, I suspect USB driver on Mac/Windows shares USB devices differently
- One of our user's came up with a workaround to basically rebind the USB device manually 
https://github.com/trustcrypto/OnlyKey-Firmware/issues/98#issuecomment-608336591
- This workaround is not really an ideal fix so I am looking into ways to basically release the USB device in Yubikey.cpp

So far I have tried using yk_close_key and yk_release to let go of the key but I am getting a segmentation fault error. Any ideas?


bool YubiKey::init()
{
    m_mutex.lock();

    // previously initialized
    if (m_yk != nullptr && m_ykds != nullptr) {

        if (yk_get_status(m_yk, m_ykds)) {
            // Still connected
            m_mutex.unlock();
            return true;
        } else {
            // Initialized but not connected anymore, re-init
            deinit();
        }
    }

    if (!yk_init()) {
        m_mutex.unlock();
        return false;
    }

    // TODO: handle multiple attached hardware devices
    m_onlyKey = false;
    m_yk_void = static_cast<void*>(yk_open_first_key());
#if YKPERS_VERSION_NUMBER >= 0x011400
    // New fuction available in yubikey-personalization version >= 1.20.0 that allows
    // selecting device VID/PID (yk_open_key_vid_pid)
    if (m_yk == nullptr) {
        static const int device_pids[] = {0x60fc}; // OnlyKey PID
        m_yk_void = static_cast<void*>(yk_open_key_vid_pid(0x1d50, device_pids, 1, 0));
        m_onlyKey = true;
    }
#endif
    if (m_yk == nullptr) {
        yk_release();
        m_mutex.unlock();
        return false;
    }

    m_ykds_void = static_cast<void*>(ykds_alloc());
    if (m_ykds == nullptr) {
        yk_close_key(m_yk);
        m_yk_void = nullptr;
        yk_release();
        m_mutex.unlock();
        return false;
    }
    

>      //In Linux, if you do not close the key it is removed from the kernel and no longer works as a keyboard
>      //yk_close_key is different than yk_release
>      //yk_close_key does this:
>      //libusb_attach_kernel_driver(yk, 0);
>      //libusb_close((libusb_device_handle *) yk);
>      //yk_release does this:
>     //libusb_exit(usb_ctx);
>     //libusb_inited = 0;
> 
>     yk_close_key(m_yk);

    m_mutex.unlock();
    return true;
}

**Comment by droidmonkey** [comment]
I am working on making the Yubikey interface more robust right now and support multiple keys. I'll push my branch today.
