### ISSUE TITLE
 Option "Safely save database files" changes the creation date of the keepass file

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#3891]
Hello,

I noticed by default the option: **Safely save database files** activated at KeePassXC.

But before I discovered the cause. I always noticed it when I save my entries to the database after a processing, is the keepass file with a different creation date.

Later I found out that it is due to the option: **Safely save database files**

Please add extend the text in the Basic Settings: **Safely save database files (may be incompatible with Dropbox, etc) - always changes the creation date of the file**

------
KeePaxxXC 2.5.1 (portable) and Windows 8.1

**Comment by phoerious** [comment]
Both options should change the creation date, since we are always creating a new file.
The creation date is pretty irrelevant and hardly something a normal user would be able to understand. I also highly recommend you never turn off that option unless you are indeed experiencing issues with Dropbox.
