### ISSUE TITLE
Sign git tags with the release key

### ISSUE THREAD

**Issue by Keisial** [keepassxreboot/keepassxc#393]
Release tags in the repository should be signed with the KeePassXC Release PGP key.

**Comment by droidmonkey** [comment]
Any particular reason why? I don't see any reason why this is necessary. The release key is meant to enable you to verify built binary distributions as legit. It also is co-signed by three parties (TheZero, phoerious, and myself) and can be revoked at any time as a result by any one of us.

**Comment by Keisial** [comment]
In order to verify the source code as legit if fetched from the repository. Any party performing its own build should be interested on doing so from the proper code.
The tarballs are signed, but verifying the checkout then requires a burdensome download of the same contents in a slightly different format. And still, there are a few files on git but not on the tgz, which are thus not covered by the tarball signature.
(And frankly, it is much nicer to track the upstream git directly than the release tarballs)

**Comment by droidmonkey** [comment]
> In order to verify the source code as legit if fetched from the repository.

Just by pulling from this repository ensures the code you are using is legit. Each of the maintainers commits using their personal PGP and I require 2-factor authentication for registered maintainers. 

We may use the release key in the future, but it is not that big of a deal.

**Comment by TheZ3ro** [comment]
This will be just an extra, releases are already signed by one among me, droidmonkey or phoerious.
Currently the [release tool](https://github.com/keepassxreboot/keepassxc/blob/develop/release-tool#L388) use the default gpg key but it's easy to change that to use the KeePassXC Release key.

The thing is that the key isn't associated with any profile so Github will show an "Unverified" label instead of the current green "Verified" label.
