### ISSUE TITLE
Secret Service Integration not working: "Another secret service is running"

### ISSUE THREAD

**Issue by theCalcaholic** [keepassxreboot/keepassxc#3945]
## Expected Behavior
After enabling the Secret Service integration for a database, KeepassXC exposes it via libsecret.

## Current Behavior
When starting keepassxc from the command line, it will print the message "Another secret service provider is running". When enabling the Secret Service Integration for a database, KeepassXC shows the message:
```
Fdo Secret Service: Failed to register DBus service at org.freedesktop.secrets: another secret service is running
```

## Possible Solution
Maybe this is just a misconception about the feature. Is KeepassXC supposed to act as a Keyring *alongside* the default Keyring (e.g. Seahorse) or is it supposed to replace it? In the latter case, the behavior described above might be expected and I would have to migrate all my credentials from Seahorse to KeepassXC and get rid of the former.

## Steps to Reproduce
![demonstration](https://user-images.githubusercontent.com/6317548/69799842-5aa93900-11d4-11ea-9b12-388f639cd076.gif)
Tested with the snap and appimage versions.

## Context
I am using Ubuntu (Gnome) with Seahorse installed (which it is by default, iirc).

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.3.0-22-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by theCalcaholic** [comment]
It probably makes sense to mention @Aetf :)

**Comment by Aetf** [comment]
I'm here :)

KeePassXC replaces the default one. The default keyring actually has two parts: Seahorse as the frontend, and a keyring daemon as the backend. KeePassXC will replace the backend (the daemon), but works with Seahorse, and other secret service clients.

So yes, you have to stop or remove the keyring daemon (called `gnome-keyring-daemon`), so KeePassXC can register itself as the backend.

**Comment by droidmonkey** [comment]
Can we issue a message on how to disable the existing daemon? Is it possible to detect which one is running?

**Comment by Aetf** [comment]
I agree we need a better message. We can print the command line and PID of the running daemon. But the exact way of disabling the existing one depends on the distro the user is using. Maybe we can provide a link to some documentation to explain it.

**Comment by theCalcaholic** [comment]
Thanks for the explanation. I tried to disable gnome-keyring now. What's a good way to test whether or not the KeepassXC secret service integration is working?

**Comment by Aetf** [comment]
From the output, indeed no secret service is running. Btw, it's on the session bus, and you can get the PID of the service by
```bash
dbus-send --session --print-reply --dest=org.freedesktop.DBus / \
    org.freedesktop.DBus.GetConnectionUnixProcessID \
    string:org.freedesktop.secrets
```

Could you try:

1. quit KeePassXC completely (no tray icons, etc.)
2. verify no process is owning the name using the above command
3. start KeePassXC

**Comment by theCalcaholic** [comment]
Alright.

1. I terminated KeepassXC and verified that it had stopped with:
```sh
$ ps aux | grep -i keepassxc
tknoepp+ 32597  0.0  0.0  21536  1016 pts/0    S+   12:12   0:00 grep --color=auto -i keepassxc
```
2. Ich checked that no process owns the name `org.freedesktop.secrets`
```sh
$ dbus-send --session --print-reply --dest=org.freedesktop.DBus /     org.freedesktop.DBus.GetConnectionUnixProcessID     string:org.freedesktop.secrets
Error org.freedesktop.DBus.Error.NameHasNoOwner: Could not get PID of name 'org.freedesktop.secrets': no such name
```
3. Starting keepassxc (from terminal) now yields the following output:

```sh
$ keepassxc
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Gtk-Message: 12:14:03.432: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:14:03.434: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Another secret service is running
```

**Comment by theCalcaholic** [comment]
I think I'm onto something:

I checked the same steps again with the appimage version of keepassxc (previously I was using the snap version) and it gave me the same error. But when I checked for a running secrets service again, after closing keepass, I realized, that gnome-keyring-daemon had been started again.

After killing the gnome-keyring-daemon again, the AppImage version worked.

My hypothesis is, that the secret service is being requested by snap when I start a snap application and thus preceeds keepassxc in owning the dbus service name

**Comment by theCalcaholic** [comment]
Is there a way to have another secrets provider start by default (when not running and being requested)?

**Comment by Aetf** [comment]
Hmm, it's indeed possible that snap automatically starts a default secret service. I haven't used snap before and don't know how to change which one snap starts though. My guess is that it is defined in a DBus service file.

> KeepassXC seems to cache the secret service PID, btw. When I kill gnome-keyring-daemon after KeepassXC has been started, it will still report that "another secret service is running" if I reenable the secret service integration from the database settings. Otherwise this would have offered a workaround for the snap version.

There's no caching involved. And re-enabling should work. Did you apply the change when you disable the integration?

**Comment by Aetf** [comment]
PR #4128 implements better warning messages that should be helpful in similar situations in the future.

**Comment by theCalcaholic** [comment]
Sorry for the long silence on this topic (I had lost and regained my laptop in the meantime which took precedence over the issue ;) ).

If I kill the secret service (while keepassXC is running, due to the beforementioned characteristic of the snap version):
```sh
> dbus-send --session --print-reply=literal --dest=org.freedesktop.DBus org.freedesktop.DBus.GetConnectionUnixProcessID string:org.freedesktop.secrets
   uint32 10889
> kill "$(!! | xargs | cut -d ' ' -f 2)"
> dbus-send --session --print-reply=literal --dest=org.freedesktop.DBus org.freedesktop.DBus.GetConnectionUnixProcessID string:org.freedesktop.secrets
Error org.freedesktop.DBus.Error.NameHasNoOwner: Could not get PID of name 'org.freedesktop.secrets': no such name
```

the snap version of KeepassXC still reports "Another secret service is running" when I try to enable the SS integration.

**Comment by real-yfprojects** [comment]
Not sure why this was closed as completed since I couldn't find a solution in this thread.

I have the same problem:

## Current Behavior

I uninstalled gnome-keyring using `apt remove gnome-keyring`. Additionally there is no keyring process running on my machine.
```console
> dbus-send --session --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.GetConnectionUnixProcessID string:org.freedesktop.secrets
Error org.freedesktop.DBus.Error.NameHasNoOwner: Could not get PID of name 'org.freedesktop.secrets': no such name
```
I can confirm that there is the interface isn't available in `qdbusviewer`. However KPXC still thinks a service is running:
![grafik](https://user-images.githubusercontent.com/62463991/187453282-648808b2-5138-4444-bff3-7f01c831dab3.png)

The second procedure described in https://github.com/keepassxreboot/keepassxc/issues/6274#issuecomment-810983553 doesn't help.

## Additional Information

KPXC will always show the following two errors.

```console
> keepassxc
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
Qt: Session management error: Could not open network socket
```

## Debug Info
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.4.0-125-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
This isn't our bug... are you using apparmor, firejail, or some other sandboxing? There is also a recent kde wallet bug that is holding the secret service even when disabled.

**Comment by michaelk83** [comment]
This seems to be a Snap-related issue - https://github.com/keepassxreboot/keepassxc/issues/3945#issuecomment-561601196 . I doubt that Ubuntu Core 20 has the latest KDE Framewroks, so that new bug is not likely to be the culprit here.
@real-yfprojects have you checked that the service is not running *while* you get that error message?

**Comment by real-yfprojects** [comment]
> @real-yfprojects have you checked that the service is not running *while* you get that error message?

Yes, I had the task manager open. There was no keyring process. It would be a miracle if there was a gnome-keyring process since it wasn't installed.

**Comment by michaelk83** [comment]
What about other Secret Service providers? Maybe a 2nd instance of KPXC or something. Try checking dbus, not just the task manager.

**Comment by real-yfprojects** [comment]
> Try checking dbus, not just the task manager.

I did. How does KPXC determine that a secret service is already running?

**Comment by michaelk83** [comment]
> How does KPXC determine that a secret service is already running?

https://github.com/keepassxreboot/keepassxc/blob/develop/src/fdosecrets/dbus/DBusMgr.cpp#L359
Roughly speaking, it checks via Qt DBus interface whether the service is registered, and compares the process ID to its own.

**Comment by droidmonkey** [comment]
An unknown process id indicates, at least to me, that the service might be running as root or some other user you don't have permission to see.

**Comment by real-yfprojects** [comment]
I found the following in my system logs:

```
apparmor="DENIED" operation="dbus_bind"  bus="session" name="org.freedesktop.secrets" mask="bind" pid=4255 label="snap.keepassxc.keepassxc"
```

And this is not the only operation of KPXC apparmor denies. Snap automatically installs an apparmor profile for most snap applications. Do you have control over the apparmor profile for KPXC?

**Comment by droidmonkey** [comment]
Use the flatpak or appimage distribution instead

**Comment by real-yfprojects** [comment]
Configuring apparmor is not that hard. I will do it myself if you don't plan to ship a profile with the snap package.

**Comment by droidmonkey** [comment]
Snaps provide their own apparmor profile as part of their build process.... we have already requested the dbus plug that should allow all this to work.... but do whatever you want though.

You should lookup how snaps work. In the meantime you can just switch to the flatpak and it will work immediately.

**Comment by real-yfprojects** [comment]
> we have already requested the dbus plug that should allow all this to work...

AFAIK you only have to request autolinking plugs but you can add plugs the user has to connect manually.

**Comment by vdbhb59** [comment]
Although it has been a long story here, I have been facing this issue in almost every other linux distro. Even after killing, for some weird reason it used to be running. So, instead of pkill, I just used kill *pid* and it worked instantly.
Example
~~~
sudo ps ax | grep keyring
3193 ?        Sl     0:00 /usr/bin/gnome-keyring-daemon --start --components=secrets
33435 ?        Sl     0:00 /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
117231 pts/0    S+     0:00 grep keyring
~~~
I used to pkill 3193, but then I just did kill 3193, and it worked instantly. I did not even have to close KPXC at all. It just showed me option to check the enable, and the secret service error message vanished.
This is the appimage 2.7.4.

**Comment by RJVB** [comment]
> An unknown process id indicates, at least to me, that the service might be running as root or some other user you don't have permission to see.

I'm getting this error currently because for some reason the PID registered in DBus (2346**2** at the moment) doesn't correspond to the PID of the running `gnome-keyring-daemon` (2346**4** at the moment). A bug in that daemon's daemonisation procedure (e.g. registering on the DBus before forking)?

Also, I too was under the impression that KPXC would _complement_ the running service, possibly because of a misconception what `gnome-keyring-daemon` really does leading to questions like "what happens to your already registered credentials when you replace it with KPXC".

And a FWIW: this feature works just fine on Mac provided QtDbus is available, and it would make sense to allow enabling it when building KPXC under/for MacPorts, Brew etc.

**Comment by michaelk83** [comment]
> for some reason the PID registered in DBus (2346**2** at the moment) doesn't correspond to the PID of the running `gnome-keyring-daemon` (2346**4** at the moment).

Possibly because the daemon was started by a parent process, and for whatever reason, the DBus pid got assigned to the parent process? Idk, just a guess.

> Also, I too was under the impression that KPXC would _complement_ the running service, possibly because of a misconception what `gnome-keyring-daemon` really does leading to questions like "what happens to your already registered credentials when you replace it with KPXC".

They are alternative (and unrelated) implementations of the same standard service API, and use separate data stores. If you have data already in Gnome keyring, you'll need either to get the client apps that created that data to recreate it in KeePassXC, or to copy it over using some sort of tool (which currently doesn't exist, AFAIK).

**Comment by RJVB** [comment]
>If you have data already in Gnome keyring, you'll need either to get the client apps that created that data to recreate it in KeePassXC

I'm using a KDE desktop so I really don't have much idea of who stored what in my Gnome keyring...

>or to copy it over using some sort of tool (which currently doesn't exist, AFAIK). 

Sounds like a useful feature for KPXC itself if such a tool doesn't exist! (A bit like my own proposition to develop an import "plugin" for Mac keychain data.)

**Comment by droidmonkey** [comment]
I don't believe one can just scrape all data from the secret service store (gnome keyring). That would represent a huge violation of data security.

**Comment by michaelk83** [comment]
> I don't believe one can just scrape all data from the secret service store.

The data can be enumerated on DBus, but access to it (should be) restricted. An import tool can read it if it knows the credentials to unlock the collection(s). Those are up to the user to provide. However, it was decided to leave such migration or import tools outside of KeePassXC proper. https://github.com/keepassxreboot/keepassxc/issues/1402#issuecomment-1279948116

> I'm using a KDE desktop so I really don't have much idea of who stored what in my Gnome keyring...

You can use `qdbus` to explore the `org.freedesktop.secrets` address space while Gnome keyring daemon is running. Or you can install Seahorse if you prefer a GUI. (I think there was another GUI for Gnome keyring itself. I don't know if they switched to Seahorse or that "native" GUI still exists.)

But generally speaking, if you just shut down Gnome keyring daemon without migrating anything, and let KeePassXC handle the Secret Service API from that point on, whatever client apps had data stored should recreate it on their next login. You'll need to reenter their passwords or whatnot when they ask for them, but after that it should be back to normal.

**Comment by RJVB** [comment]
>I don't believe one can just scrape all data from the secret service store (gnome keyring). That would represent a huge violation of data security.

My impression is that the Gnome keyring gets unlocked when you log in to your session (or when needed afterwards like in my case under KDE) and afterwards the credentials are apparently available without further authentication.

Either way, be it this or KDE's Wallet or the Mac keychain or the browser password store, they're all local secure stores that require access to the local terminal - and once you have that there's very little that remains in term of security (not all of the aforementioned services are set up to require a password for every access by default).

The only way I can see that the GKR can block scraping is by not being searchable, i.e. a black box where clients must know exactly what to ask. And that does not appear to be the case (to that extent) because a simple dbus viewer allows me to see which items I have in ` /org/freedesktop/secrets/collection/login`.

And after typing all that I had the idea of doing a little search which immediately turned up this:
https://github.com/mnagel/gnome-keyring-dumper
