### ISSUE TITLE
password generator - several requests

### ISSUE THREAD

**Issue by vasco65** [keepassxreboot/keepassxc#4027]
## Summary
a) A setting that limits the number of times that a certain character can appear on a generated password.
 b) Add a minimum number of chars from each group.
c) Show more than one password to choose.

## Desired Behavior
a) This setting could be generic, something like just a checkbox saying that a char can occurs only once (that would solve my immediate problem), or be more specific and allow a different number of repetitions for each char group, I'm not sure that this would be much useful.

b) That's simply a way to say that for a certain group you need at least n chars. Something like "each password must have at least 2 numbers and 3 special chars

c) When generating the password, instead of only one, show at least 5 in a drop-down for the user to select the one to accept.

## Context
I must use passwords where each char occurs only once. That's part of the security politics where I work, when using long passwords with special chars, sometimes it is difficult to find the char or chars that are repeated.

**Comment by droidmonkey** [comment]
*sigh* that policy dramatically reduces the search space making passwords far easier to crack.

**Comment by vasco65** [comment]
That is true.
I don't know enough maths to calculate how less secure that makes a password and even if I knew no one would care. From that point of view I'd say that this should not be implemented. :-(

**Comment by bram1253** [comment]
> I don't know enough maths to calculate how less secure that makes a password and even if I knew no one would care. From that point of view I'd say that this should not be implemented. :-(

The math behind it is basically: [amount of possibilities] to the power of [amount of characters].
So if we have a password that exists of only lowercase and upper case letters then you'd have 2 times the alphabet. Which is 52 characters. Let's say we make a password 10 characters long then you'd have 52^10 possibilities. Assuming of course that it's all random, which in most real life scenarios excluding password managers it is not (dictionary attacks). Password managers make this theoretical number of possibilities a reality because you don't have to remember long random strings of characters.

**Comment by droidmonkey** [comment]
Without replacement yields a calculation of: 52*51*50*49*48*...*41. The difference between the two possibilities is 87x10^15

**Comment by SebiderSushi** [comment]
Could it be useful to implement options like these, but in a section dedicated to anti-pattern for password generation. If a user wants to use features in this section, KeePassXC could tell them these options are to be avoided at all costs and that they should reach out to whoever made the ridiculus password rules the're trying to follow right now.

**Comment by droidmonkey** [comment]
We don't support anti patterns

**Comment by drone540** [comment]
Looks like the standard Keepass supports this feature if you do need to use it for password generation: https://keepass.info/help/base/pwgenerator.html#rules

I have definitely seen some sites that required something like 1 special character and 1 number and stuff like that but not more then 1, and the password generator in KeePassXC did not have options for that to help me there, but I kept regenerating until it gave me something I could finally use.

**Comment by droidmonkey** [comment]
You can always do manual substitution to meet ridiculous requirements (that is what I do). We always guarantee a highly random initial password though!

**Comment by SebiderSushi** [comment]
Fromm the keepass.info link sent by @drone540 :
> These options are reducing the security of generated passwords. You should only enable them if you are forced to follow such rules by the website/application, for which you are generating the password.

I was thinking about implementing a similar agenda in KeePassXC: Supporting the user to meet forced requirements while warning them about the consequences and discuraging anti-patterns whenever possible.

Yes, it is bad to support anti-patterns and not implementing an anti-pattern is a very good stategy to enforce that users avoid it - but in my opinion the ridiculous password rules discussed here are a good example of an antipattern where users don't have any choice to begin with and which, under normal curcumstances, hardly any user would choose to use anyway. This is why i favor an implementation that supports users when generating a password for a website, so that they can move on after generating their password once and don't need to fiddle with it every time they change it, while displaying adequate warnings to prevent any misunderstanding or promt users to nag the ones imposing the rules. The user can't simply choose to use a better password - the one imposing the rules is ultimately responsible for imposing an anti-pattern.

This could even be beneficial to security: If a user is given the ability to set password rules for a service once and then be able to generate them easily, instead of fiddling with the rules everytime, they might more easily be tempted to change their password regularly.

Also, the statement
> We don't support anti patterns
does not stand very true as long as password generator options like "Exclude look-alike characters" and "Pick characters from every group exist". Especially looking at the latter one, the statement in question can't be a reason preventing KeePassXC from supporting their users in this case as well.

**Comment by droidmonkey** [comment]
Fair enough. If you can figure out a compact way to make something like this possible I'm willing to entertain it. We are absolutely trying to avoid the KeePass2 password generator that has 100 options.

**Comment by vasco65** [comment]
To be honest to myself I can't ask for a function that will help to reduce the security of the generated passwords. However, for me, the fact that that function is not implemented will not increase the security of my passwords. I can't really say if it should be a good thing or a bad thing.

**Comment by phoerious** [comment]
Exclude lookalike characters is a trade-off between security and the risk of user locking themselves out of they must type a password manually for some reason.

**Comment by MountainX** [comment]
For passphrase generation, the ideal feature set could be a clone of this:
https://github.com/bbusschots/hsxkpasswd
I use that already and it would be great to have it built into KeePassXC. (Unfortunately, the code is in Perl.) Anyway, maybe it will inspire somebody.

**Comment by SebiderSushi** [comment]
As for a compact way to implement this, i would go with [the regex-style implementation in KeePass](https://keepass.info/help/base/pwgenerator.html#rules) linked to by @drone540.

Sadly, this one comes with a little barrier towards those who might want to avoid its learning curve, but a powerful tool like this is the only option i can see to cover all possible requirements one _might_ need to specify. But, given that most enforced requirements can be enforced by the "Include characters from every set" toggle, not many regular users would ever need to deal with this anyway.

I don't know how you'll implement this or are able to (e.g. whether taking the code from the KeePass project could be an option here), but i guess in the end the crucial factor as to whether this will be implemented at all, would be the cost-benefit ratio.

**Comment by droidmonkey** [comment]
No further changes to the password generator will be made at this time.
