### ISSUE TITLE
Replace or augment existing database icons

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#4071]
> Can we find adequate replacements for the entry and group icons as well? That used to be the blocker in my previous attempts at doing this. They are extremely low-resolution and its an enormous amount of work to find alternatives.
_Originally posted by @phoerious in https://github.com/keepassxreboot/keepassxc/issues/122#issuecomment-569486539_

The current set of default database icons are 16x16 pixels and from a bygone era of computing. We should offer our users a modern set of equivalent icons, at their choice. This can be controlled from within the application settings or within the settings of each individual database.

Existing databases would reference the existing icon set until the user decided to change it. New databases will reference the new icon set by default.

![image](https://user-images.githubusercontent.com/2809491/71557418-e8ff1d80-2a13-11ea-86ea-66aee21612c8.png)

![image](https://user-images.githubusercontent.com/2809491/71557443-4abf8780-2a14-11ea-9cd3-32fedaf12afe.png)

**Comment by droidmonkey** [comment]
> @phoerious That would be great. The default icons for groups/entries (`share/icons/database` in the source code) are ancient, hideous, unintellegible, and 16x16 only, and really should be redesigned. I see some possible issues however:

> First, users consider these icons part of their database, and it could be off-putting for them if a new KeePassXC release suddenly made everything look different. Not all of our users are IT experts who are tolerant about such changes.

> Second, our redesign could mess up people's use of the icons because the redesign would be based on the "semantic" meaning of the icons, but people may have used them "literally" based on their current graphical appearance. For example, there's the C33_Run.png icon that's supposed to resemble a start flag, however I'm using it for games because it also happens to resemble a chess board. C59_Package_Development.png looks like a hammer and C34_Configure.png looks like a wrench; what would break if we changed them into something completely different, e. g. a box and cogwheel?

> Third, people use different KeePass clients across platforms (e. g. KeePassXC on macOS and Strongbox on iOS) and may expect icons to look identical (or at least similar enough be be recognizable) on all of them.

> AFAIK all of these clients are open source and under active development, and I suppose their maintainers are as annoyed by the icons as we are. Maybe we can try and find a solution together with the others, so at least we maintain some consistency across clients.

> Finally, custom icons (e. g. downloaded favicons) don't look too nice next to icons that follow other styles like Material Design. Have a look at this screenshot of KeePassium, a KeePass client for iOS that already uses redesigned default icons:

> <img width="320" alt="2019-12-29 12-08-33-1" src="https://user-images.githubusercontent.com/25565229/71556296-f1b51b00-2a36-11ea-890d-6a3d47f9bb10.png">

> It's not too bad in this case because this database consistently uses default icons for groups and favicons for entries, but it looks totally messy if they are used in a mix.

> For these reasons, I think that redesigning the default icons should go into an issue of its own where we can discuss the solution in detail. IMHO it's independent of the ongoing redesign of the application icons (#475, #4066, #122) which is entirely a question of our own UI design.

> If you agree, I'll create a new issue for the default icon redesign and jot down some ideas there.

> _Originally posted by @wolframroesler in https://github.com/keepassxreboot/keepassxc/issues/122#issuecomment-569497071_

**Comment by phoerious** [comment]
Worst case we need to pull a higher-res copy of Nuvola, but I am all for replacing it with something that actually looks good.

**Comment by droidmonkey** [comment]
This resource looks perfect, we can cull the icons that are needed to do a 1-for-1 replacement while also adding to the default list where necessary:

https://icons8.com/icons/color

They offer a no-strings-attached open source license:
https://icons8.com/license

**Comment by wolframroesler** [comment]
icons8 is amazing, the sheer amount of icons to choose from is totally overwhelming. Many icons come in lots of variations which would make it possible to offer various style sets to the user (as suggested by @droidmonkey above).

Unfortunately, the SVG versions of many of the icons on icons8.com are available to paying customers only, and it's not immediately obvious from the search results which are free, nor have I found a way to restrict search to free icons -- there's https://icons8.com/icons/pack/free-icons but it doesn't contain all the icons to cover our needs. They say "Established open source projects could get the icons for free" (where "established" means that it has a Wikipedia page) with additional details on https://icons8.com/articles/we-contributed-icon-to-imageoptim/; I'll contact them and see what they say.

Of course we should go for SVG instead of PNG to become resolution-independent, just as in #475.

**Comment by droidmonkey** [comment]
I am going to apply for an Open Source license so we can access the SVG versions.

**Comment by wolframroesler** [comment]
I downloaded a handful of 100x100 PNGs from icon8 to see what it looks like in the demo database. LOL, seems like the PNGs are expected to be a certain size, look at this mess:

![main](https://user-images.githubusercontent.com/25565229/71753197-23d4db80-2e82-11ea-9db4-b4394415c47e.png)

![editgroup](https://user-images.githubusercontent.com/25565229/71753196-23d4db80-2e82-11ea-9b2a-8ed9b4beb4f4.png)

Haven't dug into the source code yet. Does anyone have a quick idea where/how to fix the icon sizes?

Anyway, the names of the icon8 icons I used are:

- icons8-folder-100.png
- icons8-globe-earth-100.png
- icons8-monitor-100.png
- icons8-remove-100.png
- icons8-us-dollar-100.png
- icons8-user-male-100.png

**Comment by droidmonkey** [comment]
For reference, we want to use full-color icons for the database icon set. Preferably pastel style / non-loud colors.

The whole handling of icons around the app needs to be addressed. It is likely that a width/height needs to be added to the QPixmap that loads the database icons to scale them down.

**Comment by wolframroesler** [comment]
Full color is reasonable, matches favicons better and is a welcome contrast to the application icons in Material Design (#475). Picking consistent icons will be a challenge because of the huge amount of icons available on icon8; OTOH we'll find all we need there, and in abundance.

Also, we mustn't forget to credit them properly (cf. https://icons8.com/license).

Figured out the icon size thing. We need `DatabaseIcons::iconScaledPixmap` which so far was considered unneeded since all database icons were 16x16 anyway (as described explicitly in comments). Adding width/height parameters to this function is trivial (16x16 is hard-coded in the function now, just as in `Metadata::customIconScaledPixmap`).

Looks much better now:

![main](https://user-images.githubusercontent.com/25565229/71754910-99dc4100-2e88-11ea-8324-e79ddef19c44.png)

**Comment by droidmonkey** [comment]
We should allow for a setting to increase the size of the icons (perhaps in steps of 8px, 16x16, 24x24, 32x32)

**Comment by phoerious** [comment]
That looks so much better already.
Can we get svgs from Icons8? If not, we have to add multiple resolutions, because scaling them down on Qt is a bad idea.

**Comment by wolframroesler** [comment]
SVGs from icons8 require a commercial license. Open source projects can get them for free, @droidmonkey [said](https://github.com/keepassxreboot/keepassxc/issues/4071#issuecomment-569518935) he wanted to apply for a license. I consider the PNGs I did so far experimental and temporary, will replace them by SVGs when they are available.

**Comment by wolframroesler** [comment]
BTW what's the problem with scaling icons in Qt? Doesn't look too bad on my system. Or is it a performance issue?

**Comment by phoerious** [comment]
The results depend a lot on the scaling algorithms. Bicubic is pretty good, but properly rendering the correct resolution from vector line art is usually better.

**Comment by wolframroesler** [comment]
> We should allow for a setting to increase the size of the icons (perhaps in steps of 8px, 16x16, 24x24, 32x32)

Maybe we can support Ctrl-+/-/0 for zooming, just like the web browsers do (Cmd-+/-/0 on macOS). Would increase/decrease font and icon sizes in the group tree, entry list, and entry preview panel. Hiding a size selection in app settings with no immediate visual feedback would be so 20th century. But that should go into another issue.

In the icon selection dialog (in the group and entry editors) the icons should be bigger than 16x16, either a fixed size (32x32 should be enough I think) or also zoomable with Ctrl-+/-/0. Without checking the code I guess that simply increasing the size should be fairly easy.

**Comment by wolframroesler** [comment]
Will continue working on this issue after @phoerious has finished theming (#4110), since that may affect how icons are stored and used in the source code.

@droidmonkey did you manage to obtain the Open Source license for icon8 so that we can use the SVG versions of their icons?

**Comment by droidmonkey** [comment]
Yes, we need to identify which icons we are going to use and they will provide us access.

**Comment by wolframroesler** [comment]
I found this very interesting icon collection: https://github.com/icons8/flat-color-icons

Seems to be part of icon8, free for fair use, all SVG, flat colors, goes very nicely with Material Design. Checking how much of it we can use for the database icons.

**Comment by wolframroesler** [comment]
I've reworked the database icons to be SVG instead of PNG. I wanted to get the technical side done first before deciding on which icons to use, so I took some icons from free SVG icon libraries (credited in the commit messages). Some rework will certainly have to take place, especially since we've got all of the icons8 library at our disposal, as described above (I only took freely available SVGs for my prototype).

Here's what it looks like:

![Screenshot from 2020-04-25 01 34 16](https://user-images.githubusercontent.com/25565229/80264869-e3e66e00-8695-11ea-8496-045d0f737577.png)

I changed the icon picker dialog to display icons in 32x32 instead of 16x16. Surprisingly, most custom icons (all favicons in my case) look good, and so do the new database icons:

![Screenshot from 2020-04-25 01 35 53](https://user-images.githubusercontent.com/25565229/80264917-0d9f9500-8696-11ea-9034-f7b0ecb1e97a.png)

Here's a side-by-side comparison of the classical KeePass icons (16x16 PNG) and the new icons (SVG, displayed in 32x32):

![Screenshot from 2020-04-25 01 38 19](https://user-images.githubusercontent.com/25565229/80264947-2c059080-8696-11ea-8ed0-18b444572321.png)
![Screenshot from 2020-04-25 01 37 19](https://user-images.githubusercontent.com/25565229/80264946-2b6cfa00-8696-11ea-8102-bf9fbc55b239.png)

Not bad for a first shot IMHO :) however someone with a hi-dpi screen should check it.

One more thing, I took the Apple logo from Wikipedia but I'm not sure if we're permitted to use it. If there are objections I'll replace it by something more generic.

**Comment by wolframroesler** [comment]
By the way,

> The whole handling of icons around the app needs to be addressed. It is likely that a width/height needs to be added to the QPixmap that loads the database icons to scale them down.

That's essentially what I did, however I just added a size because the icons are all square. Check the commits for details.

**Comment by droidmonkey** [comment]
NICE

**Comment by phoerious** [comment]
We should check that the semantics match what's described in our rfc.

**Comment by wolframroesler** [comment]
@phoerious Sure, can you post a link to the RFC? Didn't know it exists ...

**Comment by phoerious** [comment]
https://github.com/keepassxreboot/keepassxc-specs/tree/master/kdbx-xml

**Comment by wolframroesler** [comment]
Thanks for the link @phoerious, that makes the job a lot easier :)

To facilitate the discussion, here's the list of the icon semantics from the document you linked:

* 00 : An icon representing a generic password or key
* 01 : An icon representing a network or networking
* 02 : An icon representing a warning
* 03 : Server
* 04 : Clipboard or pinned notes
* 05 : An icon representing language or communication
* 06 : Set of blocks are packages
* 07 : Text editor
* 08 : An icon representing a network socket
* 09 : An icon representing a user's identity
* 10 : Address book
* 11 : Camera or pictures
* 12 : Wireless network
* 13 : Key ring or set of keys
* 14 : An icon representing electric power or energy
* 15 : Scanner
* 16 : An icon representing browser favorites or bookmarks
* 17 : Optical storage medium
* 18 : Monitor or display
* 19 : E-Mail or letter
* 20 : Gears or icon representing configurable settings
* 21 : An icon representing a todo or check list
* 22 : Empty text document
* 23 : Computer desktop
* 24 : An icon representing an established remote connection
* 25 : E-Mail inbox
* 26 : Floppy disk or save icon
* 27 : An icon representing remote storage
* 28 : An icon representing digital media files
* 29 : An icon representing a secure shell
* 30 : Console or terminal
* 31 : Printer
* 32 : An icon representing disk space utilization
* 33 : An icon representing launching a program
* 34 : Wrench or icon representing configurable settings
* 35 : An icon representing a computer connected to the Internet
* 36 : An icon representing file compression
* 37 : An icon representing a percentage
* 38 : An icon representing a Windows file share
* 39 : An icon representing time
* 40 : Magnifying glass or an icon representing search
* 41 : Splines or an icon representing vector graphics
* 42 : Memory hardware
* 43 : Recycle bin
* 44 : Post-it note
* 45 : Red cross or icon representing canceling an action
* 46 : An icon representing usage help
* 47 : Software package
* 48 : Closed folder
* 49 : Open folder
* 50 : TAR archive
* 51 : An icon representing decryption
* 52 : An icon representing encryption
* 53 : Green tick or an icon representing OK
* 54 : Pen or signature
* 55 : Thumbnail image preview
* 56 : Address book
* 57 : An entry representing tabular data
* 58 : An icon representing a cryptographic private key
* 59 : An icon representing software or package development
* 60 : An icon representing a user's home folder
* 61 : A star or an icon representing favorites
* 62 : Tux penguin
* 63 : Feather or an icon representing the Apache web server
* 64 : Apple or an icon representing macOS
* 65 : An icon representing Wikipedia
* 66 : An icon representing money or finances
* 67 : An icon representing a digital certificate
* 68 : A mobile device

Here are the original icons as of KeePassXC 2.5, with row/column numbers so we can locate them in the list: (e. g. hammer is in row 4, column 19 => its icon number is 4*10+19=59)

![icons-before](https://user-images.githubusercontent.com/25565229/80286442-c19f2f80-872b-11ea-899b-a1cac97c9ae3.png)

And here's my preliminary choice so far:

![icons-after](https://user-images.githubusercontent.com/25565229/80286456-d54a9600-872b-11ea-8fa8-4c9722ef48d7.png)

If in doubt, or if a matching icon cannot be found, I suggest we try to keep the visuals intact rather than the semantics, because that's going to cause the least confusion among users. For example, 01 should still be a globe, not some generic networking symbol; 59 should still be a hammer, etc. Also, I'd like to keep the colors intact if possible (e. g. 46 blue, 61 yellow, etc.)

Do you agree with the general style (e. g. flat colors) of the preliminary icons I chose, or would you prefer something different? I'll check the icons8 site to see what they have to offer.

**Comment by wolframroesler** [comment]
OK, I checked the styles of the icons sets they have on icons8. The style of the icons I chose for my prototype (pictured in the comment above) is called "color" (https://icons8.com/icons/color). Three other styles are interesting for us (they have more, but we need something that's in color and works at small sizes); I picked some samples from each of their "free SVG" categories:

**Pastel** (https://icons8.com/icon/pack/logos/cotton)
![cotton](https://user-images.githubusercontent.com/25565229/80287932-b8ff2700-8734-11ea-99c6-64a1a2d3b25a.png)

**Office S** (https://icons8.com/icons/offices)
![offices](https://user-images.githubusercontent.com/25565229/80287954-db914000-8734-11ea-85a8-ae49f5ae0d70.png)

**Blue UI** (https://icons8.com/icons/ultraviolet)
![ultraviolet](https://user-images.githubusercontent.com/25565229/80287978-f5cb1e00-8734-11ea-97e5-8a93006d3c6e.png)

My opinion is that we should go with the "color" style because it looks best next to the vibrant colors you find in favicons. People will have database icons and favicons mixed on their screens, and there shouldn't be too much visual contrast between them. The screenshot in https://github.com/keepassxreboot/keepassxc/issues/4071#issuecomment-619284981 shows that "color" style and favicons blend together almost perfectly. For reference, here's the favicon collection of my personal database (shown in 32x32 as of my latest changes):

![favicons](https://user-images.githubusercontent.com/25565229/80288079-bfda6980-8735-11ea-98c9-839692226178.png)

Opinions?

**Comment by phoerious** [comment]
The RFC is not binding, if you disagree with some of the semantics, we can change it.

**Comment by droidmonkey** [comment]
I like color the best, my alt choice would be cotton.

**Comment by wolframroesler** [comment]
What do you think about enlarging the group and entry icons from 16x16 to 24x24, like this:

Original: 16x16
![group16](https://user-images.githubusercontent.com/25565229/80600025-1bee0800-8a2c-11ea-8fe5-0d9ead4ef055.png)

New: 24x24
![group24](https://user-images.githubusercontent.com/25565229/80600031-1c869e80-8a2c-11ea-82c1-bcc98a29804c.png)

**Comment by phoerious** [comment]
I would need to see that in the context of the whole application window and a larger database. Generally, I am not against it, but it should look like we made the icons too big and forgot to adjust the rest of the UI.

**Comment by wolframroesler** [comment]
@phoerious Here's a full window screenshot of my own database. I find the 24x24 icons fit perfectly, however someone should definitely check it on other systems (I'm on Linux) and on a high-dpi screen. The 24 is hard-coded (as was the 16 before), which may or may not be a good idea.

![Screenshot from 2020-04-29 16 15 24](https://user-images.githubusercontent.com/25565229/80607025-44c6cb00-8a35-11ea-8687-bf22e6113ec9.png)

**Comment by wolframroesler** [comment]
Reworked the new icons a bit according to the specs, still using the free icons8 SVGs only.

![Screenshot from 2020-04-29 17 24 12](https://user-images.githubusercontent.com/25565229/80614395-b3f4ed00-8a3e-11ea-958a-bb848c891653.png)

Here's an analysis of the icon specs wrt to the new new icons I chose so far. Strike-through means "looks good", bold means "must be changed", neither strike-through nor bold means "not too bad but not too good either".

* 00 : ~An icon representing a generic password or key~
* 01 : ~An icon representing a network or networking~ - should change specs to "planet earth"
* 02 : An icon representing a warning - would be better in a triangle
* 03 : ~Server~
* 04 : Clipboard or pinned notes
* 05 : ~An icon representing language or communication~ - should change specs to "person"
* 06 : ~Set of blocks are packages~
* 07 : Text editor
* 08 : ~An icon representing a network socket~
* 09 : **An icon representing a user's identity**
* 10 : ~Address book~ - but what's the difference between 10 and 56
* 11 : ~Camera or pictures~
* 12 : **Wireless network**
* 13 : **Key ring or set of keys**
* 14 : ~An icon representing electric power or energy~
* 15 : ~Scanner~
* 16 : An icon representing browser favorites or bookmarks
* 17 : ~Optical storage medium~ - but why is it in a box
* 18 : Monitor or display
* 19 : ~E-Mail or letter~ - but why the plus sign
* 20 : ~Gears or icon representing configurable settings~
* 21 : ~An icon representing a todo or check list~
* 22 : ~Empty text document~
* 23 : Computer desktop
* 24 : An icon representing an established remote connection
* 25 : **E-Mail inbox**
* 26 : ~Floppy disk or save icon~
* 27 : An icon representing remote storage
* 28 : An icon representing digital media files
* 29 : **An icon representing a secure shell**
* 30 : ~Console or terminal~
* 31 : ~Printer~
* 32 : **An icon representing disk space utilization** -- specs should be changed, icon name is "FSView", it's probably supposed to be a Finder/Explorer window
* 33 : **An icon representing launching a program** - oh I always thought it was supposed to be a chess board; let's change specs to "start/finish flag"
* 34 : ~Wrench or icon representing configurable settings~
* 35 : An icon representing a computer connected to the Internet
* 36 : An icon representing file compression
* 37 : ~An icon representing a percentage~ - but I don't really like the red starry disc
* 38 : **An icon representing a Windows file share**
* 39 : ~An icon representing time~
* 40 : ~Magnifying glass or an icon representing search~
* 41 : Splines or an icon representing vector graphics
* 42 : ~Memory hardware~
* 43 : ~Recycle bin~
* 44 : ~Post-it note~
* 45 : ~Red cross or icon representing canceling an action~
* 46 : ~An icon representing usage help~ - but why does it have ears
* 47 : Software package
* 48 : ~Closed folder~
* 49 : ~Open folder~ - but would be nice if it was the same color as 48
* 50 : TAR archive
* 51 : ~An icon representing decryption~ - should change specs to "open padlock"
* 52 : ~An icon representing encryption~ - should change specs to "closed padlock"
* 53 : ~Green tick or an icon representing OK~
* 54 : Pen or signature
* 55 : Thumbnail image preview
* 56 : Address book - so what's the difference between 56 and 10
* 57 : ~An entry representing tabular data~
* 58 : **An icon representing a cryptographic private key**
* 59 : ~An icon representing software or package development~ - should change specs to "hammer"
* 60 : ~An icon representing a user's home folder~
* 61 : ~A star or an icon representing favorites~ - but one without the red disc would be nicer
* 62 : ~Tux penguin~
* 63 : **Feather or an icon representing the Apache web server**
* 64 : ~Apple or an icon representing macOS~
* 65 : ~An icon representing Wikipedia~
* 66 : ~An icon representing money or finances~
* 67 : ~An icon representing a digital certificate~
* 68 : ~A mobile device~

**Comment by droidmonkey** [comment]
When on High DPI the passed in size for UI elements is scaled according to the overall system scale (unless the Qt scale factor is set in the env var). So 24px is really 24*1.5px if you scale your display by 150%.

**Comment by wolframroesler** [comment]
Here are my picks for the remaing icons: https://icons8.com/icons/share-collections/false.1588179230326

@droidmonkey can you download the SVGs from icon8?

**Comment by droidmonkey** [comment]
@wolframroesler I can't see that collection. I will send the request to Icons8 once we agree on the choices.

**Comment by strongbox-mark** [comment]
Hi, this looks great, excited to see what you come up with here. I'll be happy to add the icon set to Strongbox too so people can have a uniform experience. 

I'm not a UI/Graphics expert but the tendency on the iOS side has been to move towards "Glyphs" which are single colour high resolution icons (they look beautiful and are pixel perfect) which you can set the "tint" on (usually a blue color on iOS which varies slightly between light and dark mode).

Your choices make sense when people have FavIcons mixed in, and I like the "Pastel" or "Color" options you've chosen above too. Might be cool to have an alternative "Glyph" version of each icon too, but that might not be so easy to accomplish and is just a thought.

-Mark

PS. I didn't realise there was an XSD Schema for the XML format (this would have saved me so much time when I was developing Strongbox!) :) Awesome.

**Comment by phoerious** [comment]
We have monochrome icons in the UI already. We decided for coloured icons to make a visual distinction. And as you already pointed out, it just goes better with favicons.

> PS. I didn't realise there was an XSD Schema for the XML format (this would have saved me so much time when I was developing Strongbox!) :) Awesome.

Yeah, we already did the reverse engineering part there.

**Comment by wolframroesler** [comment]
@droidmonkey Here's the icon collection again: https://icons8.com/icons/share-collections/kx6cMH7F8csY

Will use the PNG versions for a first impression. Once we've agreed on everything we can replace them by the SVGs.

**Comment by wolframroesler** [comment]
I picked the remaining icons according to the specs and downloaded them as 100x100 pixel PNGs from icons8. The result is in the [comment above](https://github.com/keepassxreboot/keepassxc/issues/4071#issuecomment-621287528). I decided to go with "color" style because that's what looks best when mixed with favicons.

I'm satisfied with most of the icons now, however some remain debatable, mostly because no exact representation of the original icon exists in the icons8 collection. That's not necessarily a problem, but we should still agree on the choice, and maybe someone finds better solutions than I did. Anyway, above suggestion is the best I can come up with so far.

All opinions are welcome. When everyone agrees I'll update my collection on the icons8 site so that @droidmonkey can acquire the SVGs. Once we've got these, I'll put them in and submit a PR. Would be awesome if we managed to get this done in time for 2.6.0.

**Comment by droidmonkey** [comment]
I made a map of your original choices to the open source available icons. We should try to satisfy the list as much as possible with these choices. I've been negotiating license terms with Icons8 all morning.

![image](https://user-images.githubusercontent.com/2809491/80739542-a3974d80-8ae4-11ea-9d54-6d8c1ccce9a5.png)

**Comment by wolframroesler** [comment]
@droidmonkey I forgot to mention that I made a shell script with that mapping, which I keep up-to-date because it's what I use to assemble the icon files: https://github.com/wolframroesler/keepassxc/blob/feature/feature/4071-database-icons/utils/makedbicons.sh

BTW, I thought getting a license for a popular open source program would be easy. :-/

**Comment by wolframroesler** [comment]
After all they say (on https://icons8.com/license),

> Established open source projects could get the icons for free. For you, we'll opensource the resources that you need.
> 
> By established projects we mean the Wikipedia criteria. If you have a page on Wikipedia and it's not removed for a week, you're qualified.

Anyway, we could still use the SVGs of the free icons and 100x100 pixel PNGs of the non-free ones (only the SVGs require payment). Since we display the icons in 32x32 or less, the difference in quality should be barely perceptible.

**Comment by droidmonkey** [comment]
We just need to identify exactly which icons we want them to "open source" and I will negotiate moving them into their GitHub repository which has a clear MIT license. Or they can issue us an MIT license for the named icons.

**Comment by wolframroesler** [comment]
Very good. My shell script lists exactly the icons we're using, `ls share/icons/database/*.png` lists exactly the non-free ones.

**Comment by wolframroesler** [comment]
For motivation, here's a before-after comparison of KeePassXC, showing the progress we made with application icons, styles, and database icons. It's a huge difference, and a total game-changer for all those who didn't like KeePassXC because it looked too much like an ancient Windows 95 program. Top screenshot is from version 2.3.1, bottom is my current branch, both taken on Linux.

![full_before](https://user-images.githubusercontent.com/25565229/80742522-cbee6e80-8b1b-11ea-8bc7-399cef6eb7a5.png)

![full_after](https://user-images.githubusercontent.com/25565229/80742520-cb55d800-8b1b-11ea-82e1-8ea29e97b3cb.png)

**Comment by droidmonkey** [comment]
Holy cow what a difference!!! Why is the search help question mark so huge? May have to fix that one.

**Comment by keepassium** [comment]
@wolframroesler, great work on the icons! Picking 69 icons from a limited set, with predefined semantics and color, is no easy feat.

This is slightly off topic, but since we are talking about supporting multiple icon sets... Maybe it would make sense to package them as separate user-installable resource files? (As simple as an archive with numbered PNGs and a license text.) 

There are numerous benefits:

- More flexibility for the user (tastes differ)
- Less dead weight in the installation package
- Designers and user can independently create, modify and share
- Flexible licensing: the icons are independent from the application

Finally, this would make it much easier to reuse the same icons across apps and platforms. I mean, iOS apps cannot touch anything GPL due to the infamous [AppStore vs GPL conflict](https://www.fsf.org/news/2010-05-app-store-compliance). But we can empower the user to install the icons separately from the app :)

**Comment by phoerious** [comment]
It's much more efficient for us to bake icons directly into the binaries using the Qt resource framework, but it's worth considering.

**Comment by wolframroesler** [comment]
> Why is the search help question mark so huge? May have to fix that one.

It's the same on develop, so not related to my changes here. Will look into it.

**Comment by wolframroesler** [comment]
Can't see anything wrong regarding the size of the question mark and magnifier, they aren't set explicitly. It's simply

```cpp
    m_ui->searchIcon->setIcon(resources()->icon("system-search"));
    m_ui->searchEdit->addAction(m_ui->searchIcon, QLineEdit::LeadingPosition);

    m_ui->helpIcon->setIcon(resources()->icon("system-help"));
    m_ui->searchEdit->addAction(m_ui->helpIcon, QLineEdit::TrailingPosition);
```

Could this be a theming issue, @phoerious?

**Comment by phoerious** [comment]
More like a GTK/Qt issue, I suppose. It's fine on Windows.

**Comment by OLLI-S** [comment]
Pu, many postings here, I had a quick look.
What I have understood is that users can choose between the classic icons and the modern icons.

So what about a 3rd option: a **black icon pack** that I have suggested in #4285?
If this is an option, then what about using the icons from http://www.iconarchive.com/show/windows-8-icons-by-icons8.html ?
They are **Linkware** (you can use them, but must publish a link to their site).

**Comment by phoerious** [comment]
No, there won't be an option to choose the "classic" icons. We will simply remove them.

**Comment by OLLI-S** [comment]
OK, I just had a look at the first screen shot and there I saw that you can select what icon set you want to use.
So I thought it could be possible to add a new (dark) set.

**Comment by droidmonkey** [comment]
After review of the new icons versus the old ones we are not going to use the old ones ever again

**Comment by wolframroesler** [comment]
@droidmonkey Here are the names of the non-free Icons8 icons I've used:

* apple-logo
* archive-folder
* categorize
* cd
* clipboard
* cloud-storage
* console
* delete
* desktop
* electrical
* error
* finish-flag
* help
* identification-documents
* key-2
* keys-holder
* monitor
* note
* open-envelope
* pencil-drawing
* percentage
* postal
* quicktime-player
* save
* star-filled
* vpn
* wi-fi
* windows-client

I'll now create a PR with my changes so far so you can review the code. We can later replace the PNG versions of those icons with the SVGs as soon as they're available.

**Comment by droidmonkey** [comment]
Great thank you. I will contact Icons8 with those choices to see if they'll add them to the MIT licensed repo. We have decent free backup alternatives for most of them in case we get in a jam.

**Comment by wolframroesler** [comment]
Pull request submitted (#4699).

BTW, if there's trouble with Icon8 making the SVGs freely available, the 150x150 PNGs are free and don't look too bad either.

**Comment by pigsflew** [comment]
Why not use [Google's material design icons](https://material.io/resources/icons/?style=baseline) directly? They're all available under Apache 2.0 and available from the linked website as SVG.

I've already pulled a bunch of them to set as my icons as external ones, and they look like this:
![example](https://user-images.githubusercontent.com/868821/83212799-58894e00-a115-11ea-9203-d0ae7e7448fe.png)

**Comment by phoerious** [comment]
We want coloured icons that are easy to distinguish from the main UI and that go well together with coloured favicons.

**Comment by grenzor** [comment]
The new icons look nice. Can icons be added for the Copy Attribute and TOTP entry right-click menu/sub-menu items? I think doing that would make all menu items have icons.
