### ISSUE TITLE
Native Linux notifications instead of tray icon notifications

### ISSUE THREAD

**Issue by 0x4c47** [keepassxreboot/keepassxc#4073]
## Summary
Currently notifications (e.g. for Secret Service usage) are shown in a custom notification popup that appears at the system tray icon. Like most other applications (and because system tray is dying), native notifications following the Freedesktop specification should be used.

## Desired Behavior
KeePassXC notifications should follow the Freedesktop specification for Desktop Notifications: https://developer.gnome.org/notification-spec/

## Context
Most applications in Linux use native notifications nowadays. This lets users decide how notifications should look like and how they should behave (also save a history etc.) My specific use case is filtering, styling and shorter timing. I want to filter out commonly used Secret Service "clients" but receive notifications for new ones.

**Comment by Aetf** [comment]
It should already be native notifications. The code simply uses `QSystemTrayIcon::showMessage`. According to the d

**Comment by 0x4c47** [comment]
Oh ok. Thank you for the clarification. My desired behavior is a little bit different then:
Imho it's a better design decision nowadays to use desktop notifications instead of tray messages. At least give an option to use desktop notifications for everything.

**Comment by Aetf** [comment]
Qt should already be using `org.freedesktop.Notifications` when using `QSystemTrayIcon` according to this [commit](https://github.com/qt/qtbase/commit/cec103897f5109c70f2fd69460d10d21fa4feded), starting from 5.5. And I do get native notifications on KDE.

Maybe double-check the [notification server](https://wiki.archlinux.org/index.php/Desktop_notifications#Notification_servers) setup? I guess the custom balloon popup is only used when the notification server is not available due to whatever reason.

Another possibility is that KeePassXC was somehow launched into a different DBus session, so the desktop environment's notification server isn't available.

**Comment by phoerious** [comment]
If it's not working, then it's due to a system misconfiguration.

**Comment by phoerious** [comment]
If it's not working, then it's due to a system misconfiguration.

**Comment by rijenkii** [comment]
Was able to reproduce with a clean install of Xubuntu 21.04 with dunst and xfce4-notifyd.

<details>
<summary>dunst</summary>
<img src="https://user-images.githubusercontent.com/5338332/122162853-6cc5f780-ce9e-11eb-80dc-59962929b782.png">
</details>
<details>
<summary>xfce4-notifyd</summary>
<img src="https://user-images.githubusercontent.com/5338332/122162868-751e3280-ce9e-11eb-8ea0-a8a4d1ae0540.png">
</details>
<details>
<summary>KeePassXC Debug Info</summary>
<img src="https://user-images.githubusercontent.com/5338332/122165964-2cb54380-cea3-11eb-92bf-24563e696bca.png">
</details>

**Comment by slpng** [comment]
Having the same issue on Ubuntu 24.04.2 LTS. KeePassXC and Dunst share the same DBus session.

<details>
<summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/9dc92e33-5e6a-4142-99b7-dbe4705a89cf)

![Image](https://github.com/user-attachments/assets/2dd57831-9d5b-483b-967d-28868134b937)
