### ISSUE TITLE
using snap to distribute official packages on Linux is a bad idea

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#408]
Please don't use snap as one of the "officially recommended" ways to install your software on Linux. It's a new, untested technology, riddled with bugs.

On Ubuntu 16.04 snap completely breaks mounting USB volumes, either automatically or manually. And then when you try to get rid of it, it refuses to remove or disable the core package. There's an old bug open with Ubuntu for the failure of "snap remove core" - but as usual Ubuntu is extremely slow to do anything about it.

Stick to tried and true package managers, such as apt/dpkg, for the time being. Switch to newer technologies only when they have matured enough. This way your users will have a much better experience. I've just started using KeePassXC and this is my first impression of it on Linux - a broken system where I can't use SD cards anymore.

**Comment by phoerious** [comment]
I disagree. Snap packages are a good and secure way to install software. The only problem I have encountered so far is that Dolphin shows a lot of loop devices when snapd is running.
Also, we cannot support 10 different package formats for 20 different Linux distributions in 30 different versions. KeePassXC is getting more and more "native" packages on several distributions thanks to the community, but we cannot do that ourselves.
We would also like to endorse cross-platform standards, so maybe one day you can just download a software on Linux and it runs, no matter what distribution you have and only give it the permissions which you want it to have (like you can do it already on Android). Snap isn't as terrible as you think.

**Comment by droidmonkey** [comment]
In my limited experience with it through KeePassXC, I found snap to be awesome and "kinda terrible" at the same time. Here is a brief rundown:

Awesome-
1. Cross platform support, push the details to the snapd instead of on the app itself
2. Plugs and interfaces is a great idea and standard way to define interdependencies
3. User control over access. You can decide to unplug an interface at any time
4. The build definition is pretty straightforward

Kinda Terrible-
1. Documentation is in need of a complete overhaul
2. What is ACTUALLY provided in the plugs/interfaces is not well defined in most cases
3. Connection to legacy interfaces (e.g., X11) provides unfettered access to the users domain. This is not snap's fault, its the fault of the Linux community clinging onto a 30 year old interface design.
