### ISSUE TITLE
Colored Passwords

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4099]
## Summary
Show single elements in passwords with specific colors.

## Details
Like at many password managers and also in KeePass (using the ColoredPassord Plugin) I would love to see my passwords colored.
Means: numbers have a specific color, special characters have a different color and normal characters (a to z) have a 3rd color.
This makes it easier to differentiate between 0 (zero) and O (capital o) and also between 1 (one) and ! (exclamation mark).

Here how it looks with the ColoredPassord Plugin in KeePass (the password is random generated):

![image](https://user-images.githubusercontent.com/8037790/71786523-9bcf0d00-300c-11ea-98d5-0d41e920aed7.png)

![image](https://user-images.githubusercontent.com/8037790/71786508-67f3e780-300c-11ea-91e4-786998834838.png)

**Comment by snhv** [comment]
There needs to be different colors of capitalized and non-capitalized characters as well, for example "I" (capitalized i) and non-capitalized "l" .

**Comment by wolframroesler** [comment]
Do we have to make the colours configurable right away? Perhaps we could just provide default colours (one set for light mode, another for dark mode) in the initial implementation and add a colour configuration dialog later if required.

We could begin with the same colours that Strongbox is using. I'm sure @strongbox-mark will be helpful.

It should be possible to turn off coloured passwords because, you know, colours don't work the same for everyone. They should be on by default because otherwise we'd have to educate users about how to turn them on. I'm thinking about a third icon to the right of the password field (next to the dice and and eye buttons), plus a checkbox in the settings dialog.

**Comment by droidmonkey** [comment]
Definitely not configurable, that is overkill. You'll already have to deal with light and dark themes.

**Comment by wolframroesler** [comment]
The challenge is to tell a `QLineEdit` to paint every character in a different colour. Being essentially a beginner in Qt, I'm afraid this is a bit over my head at the moment. Can someone with more Qt knowledge provide some hints to get me started?

**Comment by droidmonkey** [comment]
Basically you'll need to split the data (the password itself) from the styling of the data. The styled data will contain html wrapping each character to apply a color to it. When the styled data is copied to clipboard you'll have to hand over the original data. 

https://forum.qt.io/topic/118150/how-to-change-color-only-in-selected-letters-in-qlineedit/4

**Comment by strongbox-mark** [comment]
Hey, for sure, happy to help. Yes, it's a bit of combinatorial explosion with light and dark, but I also include a color blind palette too... So 4 different colors (Upper, Lower, Symbol, Number) x 2 (light and dark) x 2 (non/color blind)...

For the color blind palette I'm using "Okabe & Ito (2002): Color Universal Design (CUD)" for help... Link [here](https://jfly.uni-koeln.de/color/)

The relevant code in Strongbox is [here](https://github.com/strongbox-password-safe/Strongbox/blob/860dbce9ea47110747c50a5d8072cf49cdb8cdc4/StrongBox/ColoredStringHelper.m#L41). Sample:
```
        lightColorBlind.numberColor = ColorFromRGB(0xCC79A7); // Purple
        lightColorBlind.symbolColor = ColorFromRGB(0x0072B2); // Blue
        lightColorBlind.upperLetterColor = ColorFromRGB(0x009E63); // Green
        lightColorBlind.lowerLetterColor = ColorFromRGB(0x000000); // Black

        darkColorBlind.numberColor = ColorFromRGB(0xD55E00); // Vermillion
        darkColorBlind.symbolColor = ColorFromRGB(0x56B4E9); // Sky Blue
        darkColorBlind.upperLetterColor = ColorFromRGB(0xF0E442); // Yellow
        darkColorBlind.lowerLetterColor = ColorFromRGB(0x009E63); // Green

        dark.numberColor = NSColor.systemBlueColor;
        dark.symbolColor = NSColor.systemYellowColor;
        dark.upperLetterColor = NSColor.systemGreenColor;
        dark.lowerLetterColor = NSColor.labelColor;

        light.numberColor = NSColor.systemBlueColor;
        light.symbolColor = NSColor.systemPinkColor;
        light.upperLetterColor = NSColor.systemGreenColor;
        light.lowerLetterColor = NSColor.labelColor;
```

There's a complication in my case because iOS has some slightly different terminology than MacOS for the system colors, and also, Dark mode is only available with iOS13+ but I think you can ignore that...

**Comment by wolframroesler** [comment]
I hacked up a simple proof of concept. The implementation is  crude, the colors aren't final, and it's for the preview pane only, but it shows that and how it can be done:

![Screenshot from 2021-10-20 20-52-04](https://user-images.githubusercontent.com/25565229/138155333-3e63d79f-a109-4178-8e66-88394ab9314e.png)

For reference, here's how @strongbox-mark colours passwords in iOS (light and dark mode).

![21-10-20 20-15-25 0081](https://user-images.githubusercontent.com/25565229/138155917-ea6c1515-71fe-410d-bf81-6794ff0f1bbf.png)

**Comment by droidmonkey** [comment]
Pretty cool but it is a rather niche feature. The example provided in the preview pane doesn't make it any more legible then plain white text in my opinion. Even the Strongbox examples are extremely distracting. 

Note that the keepass plugin only colors symbols and numbers, which makes it less crazy.

**Comment by wolframroesler** [comment]
I find it rather useful in Strongbox when reading and typing passwords (rather than copy-pasting them), however I admit that I rarely do that with KeePassXC. Let's do some market research: https://twitter.com/WolframRoesler/status/1452928493549981696

**Comment by Mayurifag** [comment]
I guess thats the feature many people would enjoy, but seems I'm not the one in that list. I don't type these passwords, I'm only copy-paste them and do my things — and I guess its the way password managers are used by many people. I don't even care what my password is, specially if its generated.

For better readability there are many cool monotype fonts existed to solve same problems for coders — and I'd better have that option to choose. And still I won't use it because I don't care — password is hidden and I just copy it via CTRL+C hotkey. 

I don't know if keepassxc has many problems, but it seems to be there are some features, that most of community would like to enjoy in new versions. But still, feature is nice and would find its users 😄

**Comment by wolframroesler** [comment]
Here's how it looks in light mode:

![Screenshot from 2021-10-26 16-56-18](https://user-images.githubusercontent.com/25565229/138914034-b1e4c99d-63a7-4b61-814a-17734549550f.png)

And here's the configuration option to turn it on/off:

![Screenshot from 2021-10-26 16-57-46](https://user-images.githubusercontent.com/25565229/138914094-bcacd620-2ced-4e51-877f-a81eeb715aec.png)

Now checking how to add colours to the password entry widget which is used in the entry editor and other places. Seems less than trivial because QLineEdit needs to be converted to QTextEdit, and the two aren't exactly drop-in replacements for one another. (I tried to colourise the QLineEdit but the tricks suggested online didn't work).

BTW, I used US spelling ("color") throughout the source code, however my PC is set to British, hence "colour" here in the ticket and "minimise" in the screenshot.

Haven't heard from @OLLI-S, the creator of this ticket, for a long time. He used to be quite active; hope he made it through the pandemic.

**Comment by OLLI-S** [comment]
Hello @wolframroesler ,

Indeed, I was inactive here in GH for a longer time.
Thank you for your worries, we (I and my family) are all healthy and we luckily did not get Covid.

But we had a lot of work, because 2 colleagues of mine and 3 colleagues of my wife became ill a longer time (also not Covid, but each of them several months) and we had to compensate them.
And home-schooling is also very stressful.
So a lot of stress, but nothing serious.

The second reason why I was not active is that I moved from KeePassXC to Keeper.
We had some severe sync issues that caused that my wife lost some data (I really don't know why, but this is not the problem of KeePassXC, this was m ore a usability issue) so we decided to move to a cloud-based password manager (where I simply share passwords with my family and that is just working).

Nevertheless, KeePassXC is the best password manager, if you want to keep your data on your own devices and I really loved KeePassXC.
It is also very impressive, how active the project is here on GH.
In the past I donated for some features here and I really hope that they will get implemented (although I am using Keeper now).

An other reason why I retreated is that I was totally overworked on the best way to get a burn-out.
I supported too many projects and had too many things on my ToDo list.

I hope you understand my decision.

Best regards

OLLI

**Comment by droidmonkey** [comment]
This is unfortunately the case for most of us. We are in demand everywhere; need to focus on what matters most: family, work, then hobbies.

**Comment by wolframroesler** [comment]
Thanks for the feedback @OLLI-S, good to hear you're fine, and sorry to hear you had to leave this project. Rest assured that, should Keeper shut down or turn evil or greedy, KeePassXC will still be around, and free as in free beer. :)

Fully understand your decision about retreating, we've all been there I suppose. And thanks for your contributions and donations. Take care.

**Comment by wolframroesler** [comment]
Wondering where else we need the coloured passwords. In the "unlock database" dialog? When changing the master key? When editing an entry? Thinking about it, perhaps it's enough to have them in the preview pane?

**Comment by droidmonkey** [comment]
I agree with preview pane and maybe edit entry.

**Comment by wolframroesler** [comment]
Displaying the coloured password in the edit entry dialog isn't trivial because it uses a QLineEdit that needs to be converted to QTextEdit for the colouring to work, and the code is shared with many other places (e. g. unlock database, change master key, etc.), all of which puts it it a bit beyond my current Qt skills. I suggest I clean up what I have so far (coloured password in the preview pane, light and dark mode, checkbox in settings dialog to turn it off) and submit an MR, then have a deeper look when I find the time.

**Comment by droidmonkey** [comment]
I think it's more than sufficient in the entry preview.
