### ISSUE TITLE
Hotkey for Search-Help

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4100]
## Summary
Add a hot-key to display the help of the search panel (same effect than clicking on the (?) icon in the search field).
Maybe F1 when you are in the search field?

**Comment by kgpjay** [comment]
Hi there, I am new to Open Source and want to work on this issue. Can you please tell me where similar functionality is been implemented before in this project. 
Thanks

**Comment by 0xdeadbeer** [comment]
I have implemented an easy fix for this. Note that I set the shortcut on `CTRL+J` because `F1` seems to already have a purpose. Any feedback would be greatly appreciated. [Here is the commit](https://github.com/keepassxreboot/keepassxc/commit/d4312f979ba32a08d706d76077f12b8cc3e7ebb8) with the appropriate changes.

**Comment by droidmonkey** [comment]
Submit a PR please
