### ISSUE TITLE
Add an email field to entries (so email doesn't have to always be put into notes)

### ISSUE THREAD

**Issue by MountainX** [keepassxreboot/keepassxc#4115]
## Summary
Login credentials for many sites includes both a username and an email address (in addition to password). I find the is common at banks and PayPal when setting up a sub-user account. For example, on PayPal business accounts, when I add users, the login field is cannot be an email address, but entering an email address is required for some functions. 

Is it possible to add "email" as a formal field along with username, title, etc.? Or is the database standard set in stone?

## Desired Behavior
Each entry includes the following fields which users can input values into:

- Title
- Username
- Password
- Repeat Password
- Email
- URL
- Expires
- Notes

## Possible Solution
Add the email field to the database definition.

Consider whether a checkbox is needed to determine whether automated site login (via browser connector, etc.) is done via username or email (when both contain values and the values are distinct).

## Context
This is important for sites where login username and email are separate and distinct values. The example I gave above was sub-user accounts on PayPal business accounts. But this is something I encounter frequently. Having a piece of critical login info in the notes isn't ideal in my experience. A formal field for it would be preferable.

**Comment by droidmonkey** [comment]
This will be handled when entry templates are implemented. There is little value outside of these small edge cases to have both a username and email field.

**Comment by MountainX** [comment]
Thank you. Can you link the issue describing entry templates please?

**Comment by r7l** [comment]
I am planning to migrate to Keepassxc and this was one of the first things i've noted to be missed. There are plenty of places, where you sign up with an email but login with a username. I am always adding the email i've signed up with to any of my entries. So having a field for email by default would be great feature.

**Comment by Daxx** [comment]
I have two domain email accounts and I always use a different address for any sign-up so that I can track who is careless with security if the spamming starts.
e.g. `facebook@email1.org` or `asian-hotties@domain.myisp.com` ;) or `2021-04-23_2200@email1.org`

I didn't realise, until today, that I was a "small edge case" :)

I just found "Add attributes" and got excited adding email until it didn't appear in the main dialog.

( What's a reasonable bitcoin bounty to help 'templates' along? )
Would it be less hassle to add ONE field to the dialog / database with a configurable name (default 'extra' or 'custom') because adding a lot of fields could start to look crowded? Of course, I would use this for 'email', immediately.

I usually fill in the URL field but hardly ever use it, after that, because I'm already there when I need keepass.
Hmmm, I could save the url in Notes and use the URL slot for email in an effort to confuse myself.
The problem with email in Notes is that I can't select it with double-click (single word) or triple-click (whole line including newline at the end) e.g. `email: lawnmower-simulator@email1.org\n`

KeePassXC is really great, even without this. Thanks.

**Comment by CaliforniaMountainSnake** [comment]
I store **hundreds** of emails in the `URL` field. **A lot of** websites use both the username and the email in some cases.
I can't always use the custom field for the email because this is a waste of time (and I can't use a hotkey).

Actually, in my 10 years experience, I just never use the `URL` field to store the URL of the website, haha. Because I see the website name in the `title` field.

I strongly need the `email` field in the same place where the `username` and `password` fields are, with the hotkey.

**Comment by e-t-l** [comment]
> This will be handled when entry templates are implemented.

It appears templates have been implemented but I don't see any that include an email field. I see an "email" template but that's something different.

**Comment by maxaltdev** [comment]
> This will be handled when entry templates are implemented. There is little value outside of these small edge cases to have both a username and email field.

It's not an edge case. Most online services nowadays don't deal with usernames at all - they use an email and/or a phone number for unique identification.

I also strongly need dedicated email and phone number fields in addition to the fundamental ones (username, password).

Putting that info in "additional attributes" (or even worse - in notes) is an ugly workaround, imho.

**Comment by droidmonkey** [comment]
If your email is your username then you.... put it in the username field

**Comment by xaozai** [comment]
This is where keepassxc does not fill in the login: https://app.tuta.com/login
