### ISSUE TITLE
Auto-Type : Differentiate by parent window

### ISSUE THREAD

**Issue by eNTi** [keepassxreboot/keepassxc#412]
I want auto-type to realize the difference between the "Enter Password" window from Firefox and Thunderbird. They use the same title for the window (instead of adding the name of the program) and such I have to select one entry from a liste each time I (re-)start one of those programs. It's a minor annoyance but it adds up.

## Expected Behavior
Make an option or use the parent window info by default to distinguish between windows with the same title.

## Current Behavior
Window pops up that asks me to select an entry.

## Possible Solution
Check for the parent (Name?) and use this as an additional identifier.

## Context
I would like more automation on an already automated tasks.

## Your Environment
* KeePassXC version 2.1.2 (package community/keepassxc 2.1.2-2)
* Qt version 5.8
* Manjaro package (I guess it's gcc)
* Linux eNTi 4.9.13-1-MANJARO # 1 SMP PREEMPT Sun Feb 26 13:27:28 UTC 2017 x86_64 GNU/Linux

**Comment by Francewhoa** [comment]
Any volunteer for a patch for this? 

Both me and the Ubertus team would be happy to contribute testing and documentation if needed

**Comment by Francewhoa** [comment]
## Suggested Collaboration Between HostnameTitleBar & KeePassXC

Hello @Aaron-P, @droidmonkey, @eNTi, @phoerious and all interested contributors :) For those using [KeePassXC](https://keepassxc.org), schmittlauch suggested a new feature for KeePassXC. Which would automatically match the HTTP Basic Auth (HBA) in-window modal with its window title dialogue's parent window.

In other words, this suggested resolution could potentially allow both [HostnameTitleBar](https://github.com/Aaron-P/HostnameTitleBar) & [KeePassXC](https://keepassxc.org) addons to collaborate toward resolving this challenge in those two tickets https://github.com/keepassxreboot/keepassxc/issues/412 & https://github.com/Aaron-P/HostnameTitleBar/issues/2.

## Scenario
1. Using Firefox 78+, user go to this test page at https://www.httpwatch.com/httpgallery/authentication/#showExample10 
    HostnameTitleBar automatically customize this above page window title. HostnameTitleBar is already able to do this. Including automatically injecting a window title into pages that don't have one. So that all pages can both be unique & easily targeted by KeePassXC.
2. User click on the "**DISPLAY IMAGE**" button. Which triggers the opening of a HTTP Basic Auth (HBA) in-window modals. 
3. The challenge is that Firefox changed the way HBA work to make them in-window modals instead of system modals. Notice that this HBA in-window modals that just opened above does not have a title bar.
4. To resolve this challenge, KeePassXC would check for the parent window title. In this example, https://www.httpwatch.com/httpgallery/authentication/#showExample10
    Then KeePassXC would use this as an additional identifier. Which in turn would allow KeePassXC to automatically match each HBA in-window modal with its parent page. In other words, this suggested resolution would use the parent window info by default to distinguish between windows either without name or with the same title.

## Alternative

Alternatively, if somehow a collaboration is not realistic, both [HostnameTitleBar](https://github.com/Aaron-P/HostnameTitleBar) & [KeePassXC](https://keepassxc.org) are with open source licenses. Maybe part of their code could be use and adapted? So that both [HostnameTitleBar](https://github.com/Aaron-P/HostnameTitleBar) & [KeePassXC](https://keepassxc.org) could independently resolved this challenge with HBA in-window modals.

**Comment by droidmonkey** [comment]
We are not likely to work on this issue anymore with the upcoming improvements to the Auto-Type selection dialog. You can now search the open databases for the entry you want.

**Comment by droidmonkey** [comment]
For reference, though, this Win32 API retrieves the parent window and could be used to find title information: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindow
