### ISSUE TITLE
Add keyboard shortcut to toggle password visibility

### ISSUE THREAD

**Issue by Phyxion** [keepassxreboot/keepassxc#4120]
## Summary
I always need to hit the "Toggle password visibility" to verify the password required to unlock my database. For convenience, there could be an option that remembers the visibility. My PC has no spying eyes behind it so I don't need this hidden by default.

## Desired Behavior
An option in in Security > Convenience that doesn't hide passwords to unlock database.

**Comment by droidmonkey** [comment]
Don't agree with this proposal

**Comment by Phyxion** [comment]
There's nobody near my PC to check the password, so now I always need to hit the button for it to show (I use a long password so it's easy to make a typing mistake). Perhaps one of those two options can be reused for this behavior as well.

**Comment by droidmonkey** [comment]
I was thinking the same thing, although one is specifically when editing entries, the other is for the preview widget. A third option wouldn't necessarily hurt if it was very clear as to its purpose.

**Comment by blueclochard** [comment]
Maybe an alternative would be a keyboard shortcut to toggle password visibility? Like Phyxion, I also use a long password and sometimes make a typo. For that reason I prefer to set the password to visible, but right now the only way to do this is by finding my mouse and clicking on the icon next to the password field. 

Switching to your mouse every time you unlock your database does interrupt your workflow, especially when you mostly use your keyboard. Since your hands will be on your keyboard ready to type your password anyway, an easy keyboard shortcut to toggle password visibility would make things much easier.

Then again, I would welcome the proposal to have an option to always show the password too. I also don't have any people standing behind me when I use my computer, at least none that I am aware of ;-)

**Comment by droidmonkey** [comment]
Ctrl+H would be an appropriate shortcut. I like that idea.

**Comment by Phyxion** [comment]
@blueclochard Not as good as good as a permanent setting but it's also a worthwhile addition I think 👍
