### ISSUE TITLE
KDBX 3.1 db gets corrupted after removing yubikey from security

### ISSUE THREAD

**Issue by cristi-t** [keepassxreboot/keepassxc#4146]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

The  KDBX3.1 db gets corrupted after adding and removing yubikey to security

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

8. the db can be opened with the password only

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

8. try to open db with password only - fails - INCORRECT

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

convert to kdbx4.0?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

1. create an empty db KDBX 3.1 with password protection
2. the db can be opened with the password - correct
3. the db cannot be opened with password + yubikey - correct
4. modify the db security by adding yubikey
5. the db can only be opened with password + yubikey - correct
6. remove yubikey from security options
7. try to open db with password + yubikey - fails - correct
8. try to open db with password only - fails - INCORRECT
9 the db cannot be opened any longer ( you lost your db I suppose)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Same behavior on Ubuntu 18.04.3

**Comment by phoerious** [comment]
Holy shit, this is actually reproducible. I checked what's happening there and it turns out that this is an artefact of how CR keys used to work in KDBX 3.1. They are not part of the key transformation, but are added directly to the hash.

The KDBX 4 transform method won't add a YubiKey that was removed to the database, but the KDBX 3.1 method simply adds it unconditionally and therefore relies on the CR key buffer to be empty. At the point when the database is written, however, this buffer still contains the old CR key, so it gets added to the key again. This "corruption" were reversible if you still had your old master seed to recreate the exact same challenge, but since that is that is regenerated on each save, I am afraid the database is lost if you do not have a backup.

**Comment by cristi-t** [comment]
Thank you phoerious.
Impressive response time.

**Comment by phoerious** [comment]
This bug is now fixed in #4147 and we will release a 2.5.3 soon.
Regardless of that, I highly recommend you upgrade your database to KDBX4. There is really no reason to use KDBX3.1 anymmore.

**Comment by cristi-t** [comment]
Thank you again for the quick action.
And thank you for the advice - I already upgraded to KDBX4.
