### ISSUE TITLE
set second database as folder

### ISSUE THREAD

**Issue by jeyca** [keepassxreboot/keepassxc#4198]
I thought I had read somewhere that you can mount other databases as folders, is that true? So I have a passwords.kdbx database where I would set a folder and when you click on that folder it shows the content of passwords2.kdbx

Is that possible? and how? couldnt find anything about it in the menu or documentiation

**Comment by droidmonkey** [comment]
That is called KeeShare. It is not well documented right now. Some simple steps:

1. Create a new group
2. When in that screen click on the KeeShare tab on the left
3. Set it to import/export/or sync
4. Choose the file to use
5. Enter the master password
6. Press ok
7. You will also have to go to the application settings and enable KeeShare

**Comment by jeyca** [comment]
thanks, what is the difference between import and sync?

**Comment by droidmonkey** [comment]
Sync imports and exports

**Comment by ckieschnick** [comment]
Even when the horse already left the barn, I want to make some things clear for the next one stumbling over this issue.

The feature requested here is more likely https://github.com/keepassxreboot/keepassxc/issues/2658 - but this is not (yet) implemented. It's true, that you can use KeeShare to some extend to get the same result, but be aware that this was not part of the use cases, so there are some limitations:
* The database should have never had any entry in common - if the source database has a deleted entry, which is also part of the target database, this may get deleted in the target database since KeeShare synchronizes deleted entries. This is because the synchronization uses the UUIDs of the entries.
* Be aware that synchronize may override the source database when adding/changing a shared entry in the target database. So reorganizing the structure may have an effect to the entries in your "future" source database.
