### ISSUE TITLE
Export database : include SSH keys

### ISSUE THREAD

**Issue by DevOliv** [keepassxreboot/keepassxc#4233]
The primary goal is to have a **printable** document of sensitive data for backup and store it in safe-deposit box.
The minimum info needed in export are : Title, Username, Password, Expires and SSH keys.
It would be a plus to export all other info, so it could be directly imported in empty database, but not essential.

### Expected Behavior
Include SSH keys (pub + private) when export database to XML and/or HTML.

### Current Behavior
SSH keys are not exported whatever the output format CSV, HTML and XML (by CLI).

### Context
SSH keys are stored as Attachments in Advanced section and used in SSH Agent section as Attachment.

### Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.4.12-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Attachments are exported in the XML in their base64 representation. It does not make sense to "decode" most attachments for an export since they may be binary (images) or random text data. It would be a significant "exception" to hunt for SSH keys explicitly and make them available in a different way somehow for export.

Instead, I recommend you simply copy the private key material to the notes field of the entry. Then it will be exported in clear text without issue.
