### ISSUE TITLE
Make it possible to use OpenSSH and Pageant at the same time

### ISSUE THREAD

**Issue by belidzs** [keepassxreboot/keepassxc#4303]
## Summary
OpenSSH is already supported in the newest Windows 10 updates however many of the utilities on Windows are expecting a Pageant based SSH agent. 

Since KeePass XC is already capable of handling both it would be nice if it could do it at the same time

## Desired Behavior
The application should be able to load SSH keys into both types of agents at the same time.

## Context
Most SSH applications still expect PuTTY based agents while some use OpenSSH

**Comment by hifi** [comment]
Configuration wise, what would make the most sense when setting it up? Would it make sense to default to OpenSSH and require Pageant to be checked on manually?

Though for users that want only Pageant they would need to be able to set that up as well.

I don't oppose this change as long as the configuration options make sense and I do a little bit of refactoring to move Pageant code into sort of legacy class that just gets called by the main code only if Pageant is set up.

If the default changes it also requires a configuration migration without messing up for existing users.

**Comment by belidzs** [comment]
@hifi As I'm not familiar with the internals of KeePassXC I can only speak in terms of the UI, but I think I would replace "Use OpenSSH for Windows instead of Pageant" with "Load keys into OpenSSH agent for Windows" and add a new checkbox saying "Load keys into Pageant".

Migrating would be easy: If the user previously had OpenSSH enabled, let it checked, but if not, check the second one.

**Comment by hifi** [comment]
That configuration could end up in a state wherever the agent is enabled but neither is checked.

Three state radio button would work:
 * Load keys into OpenSSH
 * Load keys into Pageant
 * Load keys into both 

New default would be OpenSSH (if it makes sense) but people migrating would have the Pageant option set. 

Setting OpenSSH as the default makes sense as a future proof solution but it creates a non-working configuration out of the box for people still on 7 or 8.

**Comment by hifi** [comment]
One issue that comes to mind is that if we add support to see all loaded keys in the (actual) agent it would create a weird state where you see keys from both but they may be unique to one of them.

**Comment by belidzs** [comment]
I agree, a three-state radio button is a better solution. 

As for setting OpenSSH as the only default agent I'm not sure it would be such a great idea since PuTTY itself doesn't support OpenSSH and it is the de-facto SSH client for many users on Windows.

**Comment by belidzs** [comment]
> One issue that comes to mind is that if we add support to see all loaded keys in the (actual) agent it would create a weird state where you see keys from both but they may be unique to one of them.

This would be easily solved by adding two columns to the grid ("OpenSSH" and "Pageant") and there would be ticks if they are loaded in the given agent. Or you could just duplicate the list containing the keys for each agent.

**Comment by hifi** [comment]
> This would be easily solved by adding two columns to the grid ("OpenSSH" and "Pageant") and there would be ticks if they are loaded in the given agent. Or you could just duplicate the list containing the keys for each agent.

Sure but it would increase Windows specific code deep in the UI which I'd like to avoid as it's the special case here and not the norm. 

For what it's worth, have you looked into any proxy type of agent that would control both instead of just one? Like a forked Pageant that would additionally control OpenSSH? I'd be happier to recommended a special Pageant over supporting both at the same time to be honest as it's a transitional issue. 

Currently there is no way to override the OpenSSH shared pipe name but it would be trivial to add if a solution would be on that side.

**Comment by belidzs** [comment]
> For what it's worth, have you looked into any proxy type of agent that would control both instead of just one? Like a forked Pageant that would additionally control OpenSSH? I'd be happier to recommended a special Pageant over supporting both at the same time to be honest as it's a transitional issue.

No, I haven't. I'm already using `ssh_pageant` for Git for Windows and Ubuntu for Windows, I've set `GIT_SSH` to point to `plink.exe` (makes VSCode work) and of course I have `pageant.exe` for PuTTY. It would be nice if I could simplify this setup, because it is a pain to remember which ssh consumer uses which agent.

**Comment by hifi** [comment]
I spent an hour to test if I could write a Pageant compatible proxy for OpenSSH for Windows and it seems to work just fine (don't actually use it as of now, it's beyond buggy). There's also excessive amount of code for this simple task but I just copied known working things from KeePassXC.

They (Pageant and ssh-agent) are protocol compatible so a shim program that listens to Pageant messages and just passes them to OpenSSH and back is all it takes to have all Pageant compatible applications OpenSSH for Windows compatible without having the keys in two agents.

I'm not sure if the signing message is compatible (when a key is actually used rather than just added/removed) as I didn't test it but I suppose it could be. Need to test that with PuTTy.

If you need to use more than two agents it should be easy to extend this idea to other environments where all of them essentially talk with the Windows ssh-agent service.

I like this approach more than making KeePassXC talk with two agents simultaneously.

https://github.com/hifi/pagedont

**Comment by belidzs** [comment]
> If you need to use more than two agents it should be easy to extend this idea to other environments where all of them essentially talk with the Windows ssh-agent service.

This would be excelent. If you could pull this off, I'm sure people would find it useful. Unfortunately I can't help you with this due to my very limited knowledge of C++.

This might be a bit offtopic, but I've found a solution based on a similar idea to yours, however it uses pageant as the main source of truth. [wsl-ssh-pageant](https://github.com/benpye/wsl-ssh-pageant) is able to forward both WSL and the new OpenSSH for Windows key requests to a pageant compatible agent. This covers every possible SSH need in Windows provided the user don't mind keeping his keys in pageant instead of Windows' built-in ssh-agent.

After setting everything up i was able to to use pageant to provide keys for the SSH client in WSL, the native OpenSSH for Windows ssh client in cmd.exe, Powershell (VSCode too) and msysgit (Git for Windows). PuTTY is still directly using pageant of course.

To achieve this I've downloaded the forwarder, ran it, set up the `SSH_AUTH_SOCK` environment variable in both WSL and Windows, and also `GIT_SSH` in Windows to make sure Git BASH also uses OpenSSH for Windows instead of the built-in msysgit ssh client. I set its value to `C:\Windows\System32\OpenSSH\ssh.exe`

The solution above is kind of similar to what you've proposed, but instead of forwarding everything to OpenSSH for Windows it forwarded everything to pageant. I've also came across [wsl-ssh-agent](https://github.com/rupor-github/wsl-ssh-agent) which forwards WSL to OpenSSH for Windows, but unfortunately it can't act as pageant for clients like PuTTY.

Setting this all up was a huge pain and I think people would prefer a much simpler solution.

**Comment by hifi** [comment]
I'm going to close this issue as it has an interim solution and supporting two different agent implementations simultaneously increases the complexity of the code unnecessarily.

External bridges between different agent implementations seem like the best route in the end.

Thanks.
