### ISSUE TITLE
Exact matching URL

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#4509]
Hello,

I have several access to websites with CMS like wordpress or joomla, where I have to manage test/demo-accounts for the frontend and admin-accounts for the backend like:

https://mypage.de = demo / s3cr3t
https://mypage.de/administrator = admin / s3cr3t

The URLS are inserted in the KeePassXC field, all is configured to ship best matching URLs.

At the moment, the frontend https://mypage.de is autofilled because there is only one matching result.
But the backend is not and shows both entries to select. This should be because the first one acts also as wildcard like https://mypage.de*

Is there an option to get also the second one is the only one matching?
Perhaps to put "EXACTLY" URLS inside " quotation marks?

**Comment by varjolintu** [comment]
Does enabling "Return only best-matching credentials" help?

**Comment by RolandSM** [comment]
No

**Comment by FichteFoll** [comment]
Related: #4047

**Comment by bodograumann** [comment]
This should work since https://github.com/keepassxreboot/keepassxc/pull/5316, where exact path matches are preferred over domain-only matches.

**Comment by KyleWJohnston** [comment]
It works for me on 2.6.2. For this example:
> https://mypage.de = demo / s3cr3t
> https://mypage.de/administrator = admin / s3cr3t

Visiting "https://mypage.de/administrator" will cause KeePassXC to suggest both the "demo" and "admin" login but with "admin" listed first. Both will ask for permission to be accessed unless you have "Never ask before accessing credentials" enabled. Further, if you have "Return only best-matching credentials" enabled, only the first option will be shown ("admin").

**Comment by RolandSM** [comment]
Hello @KyleWJohnston  and @droidmonkey 

sorry but on my Kubuntu System I cannot reproduce with latest 2.6.2.

First of all, how can I ensure that the admin one comes first? Ordering?
Second on my test example it is so, admin is first, demo is second.
Both aks for permission and gets granted, because the "allow" entry is always mypage.de

No if I go to Settings -> Browser Integration -> and uncheck best matching results nothing change? Also if I activate again.
Both are shown.

So for, I want the Demo only on frontend, and the admin only on administrator.

Further I want to exclude several parameters in URL for example the User-Edit-Form in Backend.
When I add or edit a user, for example on mypage.de/administrator/index.php?option=com_user the username and password field gets filled from the plugin but shouldnt! this is very bad.

Last thing, is it possible to edit an Entry -> Settings -> Key "KeepassXC-Browser Setting"?
Its a JSON with the URLs allowed or not. The only way is to remove the complete key and make it all new with my decisions but it would be nice if I can go into this field and remove or add manually...

Greets

**Comment by KyleWJohnston** [comment]
Sorry it's not working for you. Are you saying you are getting "demo / s3cr3t" suggested when on https://mypage.de/administrator and with best-matching turned on? You shouldn't be if the URLs in the entries are exact.

> First of all, how can I ensure that the admin one comes first? Ordering?

KeePassXC should prioritize exact matches before domain-only matches.

> Second on my test example it is so, admin is first, demo is second.
> Both aks for permission and gets granted, because the "allow" entry is always mypage.de
> 
> No if I go to Settings -> Browser Integration -> and uncheck best matching results nothing change? Also if I activate again.
> Both are shown.

Regardless of the best-matching setting, all entries with matching domains will ask for permission to be shown. However, if you have best-matching enabled, only the top result will be shown. Best-matching does not change what that top result would be.

Specifically, it's this code here [BrowserService.cpp](https://github.com/keepassxreboot/keepassxc/blob/91dea9cbc4de91ddd44c8ecb0eff02bf6d570a8c/src/browser/BrowserService.cpp):
```cpp
    auto sortField = browserSettings()->sortByTitle() ? EntryAttributes::TitleKey : EntryAttributes::UserNameKey;
    for (auto key : keys) {
        // Sort same priority entries by Title or UserName
        auto entries = priorities.values(key);
        std::sort(entries.begin(), entries.end(), [&sortField](Entry* left, Entry* right) {
            return QString::localeAwareCompare(left->attribute(sortField), right->attribute(sortField));
        });
        results << entries;
        if (browserSettings()->bestMatchOnly() && !results.isEmpty()) {
            // Early out once we find the highest batch of matches
            break;
        }
    }
```

I tested this on a random website (I used accounts.fitbit.com) with best-matching turned on. I used 3 KeePassXC entries:
- https://accounts.fitbit.com
- https://accounts.fitbit.com/login
- https://accounts.fitbit.com/login?targetUrl=https%3A%2F%2Fwww.fitbit.com%2Fglobal%2Fus%2Fhome (the original URL)

For clarity, the name of the entry is the same as the URL. It returned the correct exact-matching URL both times rather than the more generic https://accounts.fitbit.com.

On https://accounts.fitbit.com/login:
![Fitbit simple login page with best-matching on](https://user-images.githubusercontent.com/7908653/101283500-c7bcba80-37a8-11eb-8539-6bfbf7cd8b96.png)

On https://accounts.fitbit.com/login?targetUrl=https%3A%2F%2Fwww.fitbit.com%2Fglobal%2Fus%2Fhome:
![Fitbit long URL login page with best-matching on](https://user-images.githubusercontent.com/7908653/101283504-d1462280-37a8-11eb-95a7-f1240fa63d25.png)

**Comment by RolandSM** [comment]
Oha, I found something interesting.

URL line in KeePassXC Entry:
https://mypage.de only for Demo
https://mypage.de/administrator only for Admin
But on both URLS both entries was displayed.
Note that mypage.de redirects to mypage.de/de/

Now I changed the Entries URLS to:
https://mypage.de/de/ for Demo
https://mypage.de/administrator/ for Admin
And now it works. Demo is only shown on frontend, Admin only on backend.

Happy so far...

**Comment by Httqm** [comment]
For those landed here by Google search results : I had a similar unexpected behavior with :
* KeePassXC 2.7.6
* Firefox 122 (64-bit)
* KeePassXC-browser 1.8.12

KeePassXC has 2 entries like :
* https://internalDomain/application1
* https://internalDomain/application2

and when opening _application2_ in Firefox, KeePassXC only offered credentials for _application1_.


Turns out I had an obsolete bookmark for _application2_ : http://internalDomain/application2 (http, not https), but I reached the HTTPS page automatically thanks to a redirection made by [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).
After I updated the bookmark to HTTPS, things went back to normal.

Can't explain what happened, hope this may help anyone...
