### ISSUE TITLE
Add option to make password more readable

### ISSUE THREAD

**Issue by TomTom-42** [keepassxreboot/keepassxc#4524]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Give the possibility to have a more readable password when we show it (click on eye)

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
When we click the eye icon in order to show the password, it could be interesting if the password appears with groups of two or four characters. ex: Pa ss wo rd

It could give more readable passwords sometimes complicated to read and type them (when copy is not available), even more when passwords are long.

Having the possibility to set the number of characters by group could be appreciable.

**Comment by droidmonkey** [comment]
How would you determine a space in the password versus a letter group?

**Comment by SVilgelm** [comment]
Sometimes you need to read it to enter on a different laptop/tablet/phone. 👍 for colored passwords. It works great, especially for really long passwords. (Yeah I had to enter the passwords with a length of 100 or more several times manually)
I would prefer to read a password on my phone/laptop and enter it manually instead of sending it through iMessage

**Comment by droidmonkey** [comment]
This is covered in #4099
