### ISSUE TITLE
Open from URL

### ISSUE THREAD

**Issue by Sheldor5** [keepassxreboot/keepassxc#4551]
The lack of this feature is one of the reasons I am still using Windows as primary OS.

I don't see how the arguments against this feature from #868 are a problem.

Those features have no attack vectors, the only real vulnerability is the user itselfe not protecting the web resource (URL of the xkdb) and even if it's unprotected I hope your port of the original project has proper implementations of the used encryption algorithms (otherwise you would consider your own implementation insecure which would make this port pointless if not even dangerous).

Please re-evaluate this feature request as it would add high valuable usability.

Nobody wants to download/upload the kdbx manually every time the kdbx changes ... seriously.

Linux itself is not really user friendly - but your software can be!

**Comment by droidmonkey** [comment]
OPEN from URL is a whole lot different than SYNC with "URL"

**Comment by Sheldor5** [comment]
Well in Windows there is only a "Open URL" Option but yes #1775 is the right FR then. Haven't found it.

**Comment by Blaimi** [comment]
The lack of this feature shouldn't be the reason to not switch to another os. While I also think opening the File directly with webdav or other protocols instead of syncing with clients from the lokal filesystem is better and much more portable, you can still open the files very easy, you simply have to mount the remote with gvfs. E.g. you can type davs://yourcloudinstance.example.com/ in any filebrowser into the url-bar (e.g. in gnome files via CTRL+L or “other locations" / “connect with server”). There are a lot [backends](https://wiki.gnome.org/Projects/gvfs/backends) gvfs can talk. You can then open the kdbx from the file-open dialog at least under the gvfs-mount-directory. This is for me on fedora `/run/user/1000/gvfs` but can differ to distributions. You can even automount with `gio mount …` in autostart.

**Comment by Sheldor5** [comment]
the one FR got closed, the other one (not specific to HTTPS) still open ...

yes I could do all this on the command line but I want ppl without knowledge of bash also can open their database from web locations like the Windows version ...

reasons like this are why ppl still use Windows, because the alternatives (Linux distros) require an IT degree for the most simple tasks ...
