### ISSUE TITLE
Version 2.5.4 Hardwareschlüssel Problem

### ISSUE THREAD

**Issue by xxljerry** [keepassxreboot/keepassxc#4596]
Hallo, ich nutze 2.5.2 schon sehr lange. Als 2.5.3 raus kam, hatte ich das Problem, das ich mich nicht mehr einloggen konnte, und in dem freien Feld wo der Hardwareschlüssel reinkommt, als ein Laufband sich bewegt. Ich nutze auch keinen Hardwareschlüssel. 

Und jetzt wollte ich es mit 2.5.4 versuchen, und habe dort genau das gleiche Problem. 

Wäre nett wenn sich dazu mal jemand äußern würde, denn zu dem Post mit dem 2.5.3 Problem, bekam ich nur den Hinweis, es wurde geschlossen!? Toll

**Comment by phoerious** [comment]
From your description I cannot infer what your problem is. Please do not delete the issue template and use the search function. There are several similar issues already.

**Comment by xxljerry** [comment]
Toll vielen Dank

Markus René Frotscher
Auf den Hohen Gräben 20a
Adresszusatz : 805384700
35781 Weilburg

Tel : 06471 - 954 1607
Mobil : 0179 - 43 94 280
Fax : 03222 - 15 290 52


Jonathan White <notifications@github.com> schrieb am Mo., 13. Apr. 2020,
14:28:

**Comment by wolframroesler** [comment]
@xxljerry I'm sorry you're disappointed but unceremoniously closing the issue was in fact the only possible thing to do. I'm sure your problem will be addressed and solved if you report it in a way that makes it possible for a developer to reproduce it (or even understand what it's about). Filling in the form that appears when you create the issue will definitely help, as will writing in English, since only a fraction of the developers understand German.

**Comment by xxljerry** [comment]
Ich habe keine Ahnung was sie damit meinen. Ich bin in so vielen Foren
angemeldet, wenn man ein Problem hat, öffnet man einen Thread. Was anderes
habe ich nicht gemacht. Das gleiche Problem bestand bei 2.5.3... hat sich
bis heute auch keiner drum gekümmert.



Markus René Frotscher
Auf den Hohen Gräben 20a
Adresszusatz : 805384700
35781 Weilburg

Tel : 06471 - 954 1607
Mobil : 0179 - 43 94 280
Fax : 03222 - 15 290 52


Wolfram Rösler <notifications@github.com> schrieb am Mo., 13. Apr. 2020,
16:03:

**Comment by wolframroesler** [comment]
I already explained why your problem wasn't addressed, and told you what to do in order to get help. Also, your refusing to write in English could be considered rude by the many people here who don't understand German. Also, please be more careful with your private data; @droidmonkey kindly edited them away once but will certainly have little motivation to do that over and over again.

**Comment by droidmonkey** [comment]
I have no problem with native language, translation works well enough.

Wir haben dieses Problem geschlossen, weil es sich um ein Duplikat mehrerer anderer Personen handelt. Auf einem Software-Problemboard ist es nicht akzeptabel, Wiederholungsprobleme zu öffnen, dies ist kein Helpdesk.
