### ISSUE TITLE
About dialog gets detached from window when minimizing

### ISSUE THREAD

**Issue by yennor** [keepassxreboot/keepassxc#4606]
## Expected Behavior
When the about dialog is open, and keepassxc is minimized to system tray, the about dialog should be minimited together with keepassxc.

## Current Behavior
About dialog stays open and gets detached from keepassxc. But it doesn't get an entry in the task bar.
So when you open keepassxc again later, the about dialog is still open, but not on top of the keepassxc window. This leads to that keepassxc doesn't react on any click or anything without the user knowing why.

## Debug Info
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.12.5
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 5.4.0-4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
There is nothing we can do about that except for maybe closing all open dialogues. Minimising a window to the tray on X11 means to hide it entirely. If your window manager breaks the connection between the two, then that's not really our fault.

**Comment by yennor** [comment]
Can't you find that dialog again? or at least somehow show why keepassxc isn't reacting on any input? I've killed it several times, thinking it froze, before I've found out the real reason.

**Comment by phoerious** [comment]
No, we are not managing our windows, that's the window manager's job.

**Comment by droidmonkey** [comment]
It is actually impossible to minimize KeePassXC on any other platform because the about dialog is modal (ie, takes complete focus). This is most certainly a window manager bug.

**Comment by yennor** [comment]
well you can minimize it by doing a left-click on the icon in the system tray. that's how  I always minimize it.
It's indeed impossible to minimize it clicking on the minimize button of the window itself.

I've just tried out if I could to a right click on the entry in the taskbar and choose minimize there. That actually also works (but i guess nobody ever uses that)

**Comment by droidmonkey** [comment]
Gotcha, maybe the tray icon is overriding the modality. I'll look into that.

**Comment by phoerious** [comment]
Windows hides the modal dialogue as well, which is how it should be and the connection isn't broken.

**Comment by droidmonkey** [comment]
Bottom-Line: This is fixed in the develop branch.

Test Results:

**Windows**: (Using 2.6.0-develop) clicking the taskbar icon causes the whole application (about dialog included) to disappear. When clicked again the whole application reappears with the about dialog properly on top.

**macOS**: (Using 2.5.4) clicking the taskbar icon causes the whole application to disappear. Clicking again shows the application but about dialog disappears. User cannot interact with the application. Quitting causes the about dialog to briefly appear then the application quits.

**macOS**: (Using 2.6.0-develop) application properly minimizes and restores with about dialog visible and user can interact.

**Ubuntu 19.10, Gnome**: (Using 2.5.4) same behavior as OP.

**Ubuntu 19.10, Gnome**: (Using 2.6.0-develop) about dialog stays visible, but properly remains on top when the application restores.

**Comment by yennor** [comment]
thanks. That's been incredibly quick :-)
