### ISSUE TITLE
Missing/Ghosted Entry?

### ISSUE THREAD

**Issue by Emily7777** [keepassxreboot/keepassxc#4649]
## Overview
I have an entry I'm certain was saved in the database.  I'm accessed it several times.
I opened the database to find the entry, and it's gone. 
I've checked the recycle bin.  It is not there.

## Steps to Reproduce
Make an entry.  
Save it.
Search for it.  Find it.
Close the database.  
Open.  Randomly, it turned up missing.  Other test new entries saved just fine.

## Expected Behavior
Save the entry, and be able to access it later.

## Actual Behavior
Entry is missing.

## Context
I have the KeepassXC stored within an Veracrypt vault.  I'm not sure if that has anything to do with the bug.

KeePassXC - Linux
Revision: 2.5.3

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
I know we fixed a couple issues with saving to veracrypt on macOS, but to have just one entry disappear is a new one for me.

**Comment by partially-signed** [comment]
I've had this issue twice in the past. One was recently, the other was around 4 months ago. Both times I was certain I saved a password in KeepassXC, however, upon reopening the database, it was not there. In addition, I searched for the name of that entry in the XML output, and read through all of the XML output manually, but, I couldn't find any reference to the missing entry in the XML output from `keepassxc-cli extract db.kbdx`.

**Comment by MarcoGriep88** [comment]
Having the same issue. Transfering alot of passwords from a word document (dont blame on me, i got it from an earlier employee) to keepassXC. I marked transfered passwords. Alot of them are in KeePassXC but i'm missing alot. From ~500 Entries i'm missing approx. 20.

**Comment by MarcoGriep88** [comment]
I exported the KDBX File as XML and the entries are there.... 
Pls investigate this bug. Maybe an invalid character in the Notes field (-&gt) or something?
I'm using KeePass 2.7.4 btw

**Comment by droidmonkey** [comment]
You'll need to provide us the data and evidence of failure for us to investigate.......

**Comment by MarcoGriep88** [comment]
I will To create an File that i can Upload here with Fake passwords.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 7. Juni 2023, 18:30, schrieb Jonathan White :

**Comment by TheTeslak** [comment]
I also encountered this issue. Interestingly, these entries are present in the backups. I definitely couldn't have accidentally deleted them. They disappeared one by one; I'm not sure exactly how many are missing, but I noticed three entries. I can't imagine any situation that might have caused this

Additionally, it seems one entry was reverted to its previous state, but I was opening the main file, not the backup copy, meaning it should have contained the most up-to-date entries

**Comment by TheTeslak** [comment]
I compared the number of entries with last month: 197 versus 189, which means I lost more than 10 entries, even though I added new ones! I'll try to figure out why this happened

**Comment by droidmonkey** [comment]
This is an incredibly old issue that never played out to anything found. Entries don't just disappear "for no reason", that would be a humongous flaw in our code that would be very apparent. Given you have backups and seem to open them often, there is a very good chance you ended up writing new entries to one of your backups and not your main file.

Open your main file then do a Database -> Merge operation with the most full backup. Then make sure you are using your main file from here on out.

**Comment by TheTeslak** [comment]
Thank you. I still haven't opened the backups and have been using one main file.

**Comment by TheTeslak** [comment]
If anyone is facing the same issue and doesn't see suitable alternative password managers, I recommend reinstalling the application. After that, save the database file in a new location with a new name, ensuring the old one is deleted. I will also monitor the number of entries. I hope this helps.

**Comment by vdtoorn** [comment]
Hi @TheTeslak, I've just experienced the exact same issue, some SSH key entries simply disappearing for no apparent reason. I did have some problems synchronizing with keepass2android not so long ago, perhaps that's where the problem is.. I did merge one of my more recent (thankfully) sync errors but otherwise I would have had a big problem.

**Comment by loehnertj** [comment]
I also have this problem frequently, for quite some time now.

- KeePassXC 2.7.9 on Kubuntu 24 LTS (22/LTS until recently)
- kdbx file is on a SMB network share mounted via autofs (Synology DiskStation)
- I put the Laptop in Standby frequently. Occassionaly it's in also another LAN with no access to the share (maybe once a week). KeepassXC usually just staying open all the time.
- I notice missing passwords from time to time (~monthly). It always seems to affect the same passwords (most notably my login for Deutsche Bahn, www.bahn.de, which was gone at least 3 times).
- To remedy, I merge a backup and save, close keepassx, reopen. So in my opinion no old cached state should be left over anywhere.
- Still, passwords go missing again. Not to be found anywhere, looked at the XML export, they're gone for good.

Being a programmer, I'm aware that this isn't really enough info to pinpoint the problem :-(. I'm still trying to figure out the exact sequence of actions causing this. But wanted to report that this is still occuring.

As a workaround (of sorts), I changed the backup target path to ``{DB_FILENAME}.{TIME}.kdbx`` in the settings. This way, *all* old saves are kept. Whenever I notice missing passwords, I can recover them by merging the backups. But still, passwords being "forgotten" without any hint or trace is a *really serious* issue if you ask me, no matter the cause.

Will gladly provide logs or try things, if anyone here has ideas.

**Comment by droidmonkey** [comment]
@loehnertj are you using KeeShare at all?

**Comment by loehnertj** [comment]
No - I'm using plain KeePassXC plus the Firefox Addon.

For the record I also have Keepass4Android, however it only ever looks at a copy of the database file, which is updated from the master by a daily cronjob.

**Comment by droidmonkey** [comment]
Entries don't just disappear. The most likely explanation is that a merge operation is deleting the entry because the database you are merging from has a deleted UUID that corresponds to that entry.

**Comment by loehnertj** [comment]
Found the reason. Suffice to say that it was my own fault. 🤦  I'm sorry for the unnecessary noise.

Please take my excuse and my sincere thanks for this very useful piece of software. Also, I donated 20€ to make up for the waste of time. 😄

**Comment by tbrettallen** [comment]
> Suffice

Could you make just a little more noise and explain what the User Error was; so that if anyone else encounters this issue in the future, we can resolve the problem? Also, would be reassuring to have a valid explanation for your experiences that isn't "unknown bug or malicious activity causing software data corruption" [😂](https://emojipedia.org/face-with-tears-of-joy)

**Comment by loehnertj** [comment]
Sure - makes for a fun little anecdote.

Initially I kept the password file on my laptop as usual. Single PC, single access, all fine.

Then I got the Diskstation (NAS server). In the midst of reconfiguring lots of stuff (moving mp3's, Photos, setting up autofs), I also set up a cronjob that copied the password file to the NAS once a week. So I could edit it locally as before, but were able to access it from outside (Port forward to the NAS) should this ever be necessary. Didn't even have a smartphone back then (this was at least 10 years ago).

Much later, I decided to use the file on the NAS as "master" file. I left the old file on the laptop just in case but now opened the NAS file directly in Keepass. Without me remembering it, of course the cronjob kept doing its thing, and copied the old version over the NAS file. It ran at most once a week, if the laptop happened to be on at the right time. So the file on the NAS was reset only from time to time, and since I didn't add entries that often, it took a while until I even noticed that something odd happened.

In the meantime, having totally forgotten about the job, I instead suspected Keepass2Android, which also accessed the file on the NAS. This is why I reconfigured it to look at a copy of the password file, sitting right next to the master one. Of course that didn't help it. My next theory was that it could be a bug, related to the network share being unavailable at times. That's when I reported here.

Only then I systematically started investigating and comparing dumps. I noticed just by chance that after one of the reset occurences, the file's timestamp was changed to exactly 19:00:00. In that very moment, it dawned on me that the reason was not a bug but something running on a schedule. After this hint, it was a matter of minutes to find the forgotten cronjob.

So as you see, there's basically nothing that Keepass could have done to avert this... Since I disabled the cronjob, everything is running smoothly.
