### ISSUE TITLE
Request: New entries should inherit the icon of its parent group

### ISSUE THREAD

**Issue by geoffgs** [keepassxreboot/keepassxc#469]
Earlier version of KeePassX (<0.4.4) inherited icons new entry icons from it's direct parent group. KeepassX and therefore XC don't share this behaviour. Requesting to bring this feature back to current XC builds! 

## Current Behavior
When creating a new entry in a group, the icon chosen is the default "key". New databases, imported databases, and upgraded databases share the same behaviour. 

## Possible Solution
When creating new entry, inherit default icon as current group icon. 

## Your Environment

* KeePassXC v2.1.3
* Qt 5.5.1
* libgcrypt 1.6.5

![icons](https://cloud.githubusercontent.com/assets/14260308/24687242/bd6bf292-1986-11e7-82b5-212785d2dc5e.png)

**Comment by droidmonkey** [comment]
I do believe there is an option for the group to do this already. Should it be default on? I don't think​so because my group icon needs are very different from my entry icon needs.

**Comment by geoffgs** [comment]
@droidmonkey Could you screenshot an example of this option? I've yet to discover it, but I'll close this request if it exists.

**Comment by weslly** [comment]
@geoffgs 
![untitled](https://cloud.githubusercontent.com/assets/107672/24732211/ca4d6080-1a45-11e7-9e8b-5b269a0b7a3f.png)

Check "Use group icon on entry creation", the last setting at basic settings tab.

**Comment by junderw** [comment]
In general I will make, example, a folder called "GPG" etc. for GPG passwords let's say. Then the folder icon will be, obviously, the key.

Since I will only place key related entries in my GPG folder, it makes sense to have this default...

But I guess it comes down to "Will people who even bother to use folders: A: use them in logical hierarchies to collect similar entries (which will most likely have the same icon needs) or B: use some generic single folder to just randomly put all sorts of entries in there."

I think A is more likely, but the current default assumes B.
