### ISSUE TITLE
Auto-type fails if keyboard mapping isn't english

### ISSUE THREAD

**Issue by HacKanCuBa** [keepassxreboot/keepassxc#474]
If the current keyboard mapping isn't English, auto-type will type wrong keys.

## Expected Behaviour
Auto-type should always type the same, no mater keyboard mapping.

## Current Behaviour
Auto-type types as a if the keyboard mapping is English, thus issuing wrong characters on different mappings.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
1. Change keyboard mapping to, say, ES (Spain).
2. Use auto-type in an entry containing symbols, say dash (-).
3. Wherever you are typing the password, will say it's wrong. Try a text editor, and you'll see that dashes were exchanged for apostrophes (').

## Context
I use two keyboards, one English and one Spanish, thus it took me a while to detect this issue. I believe this is a huge problem for every non-english country where keyboard mappings are different.

## Your Environment
* KeePassXC version/commit used: 2.1.3-76dcfb5ed0c874f6a835ef0347ddf6098b149e9b
* Qt version (e.g. Qt 5.3): 5.7.1
* libgcrypt: 1.7.6-beta
* Compiler (e.g. Clang++3.6.0): ?
* Operating System and version: 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux

Installed via https://github.com/magkopian/keepassxc-debian/releases

**Comment by droidmonkey** [comment]
This seems related to #414 and #367

**Comment by HacKanCuBa** [comment]
Yes, it definitely seems related

**Comment by Roxxor91** [comment]
I am also affected by this bug.
I guess it is a security measure for this function to be typing instead of copy&paste, to circumvent the clipboard.
But as the user with this bug either way is forced to copy & paste, would it maybe make sense to have a workaround option for "auto-copy&paste", until a solution is found?

**Comment by HacKanCuBa** [comment]
@Roxxor91 the workaround is to manually set the keyboard distribution to US-English before autotyping.

**Comment by Roxxor91** [comment]
This is a really inconvenient workaround, considering that auto-type is a convenience feature...

**Comment by droidmonkey** [comment]
This is not an official workaround. This issue should be corrected in 2.3.0 if at all possible.

**Comment by leancode** [comment]
There is another workaround which is the same workaround yubikey uses but it entails for users to use passcodes that only use the modhex allowed characters:
The Modified Hexadecimal encoding scheme was invented to cope with potential keyboard mapping ambiguities, namely the inconstant locations of keys between different keyboard layouts. The YubiKey uses this special data encoding format known as "modhex" rather than normal hex encoding or base64 encoding. ModHex is similar to hex encoding but with a different encoding alphabet. The reason is to achieve a keyboard layout independent encoding.
https://demo.yubico.com/modhex.php

**Comment by frostasm** [comment]
I am also affected by this bug. Does anyone have any idea how to fix it?

**Comment by frostasm** [comment]
I tried to use the [xdotool](https://github.com/jordansissel/xdotool) program today, and it looks like it works perfectly. Perhaps it makes sense to use the libxdo for auto-typing?

**Comment by frostasm** [comment]
This bug makes it impossible to use keepassxc as the main storage of passwords on Linux :(

**Comment by leancode** [comment]
@frostasm I am using it without problem but I had to change my passwords all to be modhex encoded. The Hexadecimal "alphabet" goes like: 0123 4567 89ab cdef, but the modhex uses cbde fghi jkln rtuv. The reason is that these letters are the same on most all keyboards irregardless of encoding. So if you are willing to change your passwords to be mod hex encoded it works perfectly. But you have to update your passwords. But for me that was a small price to pay to get it working. I am changing them one by one each time I hit a site that is not yet working.

**Comment by frostasm** [comment]
@leancode unfortunately, your method does not work for the Ukrainian layout. 
I found another method ["Change the system layout before performing auto-typing"](https://github.com/keepassxreboot/keepassxc/issues/324#issuecomment-342140346)

**Comment by xvitaly** [comment]
Same problem, but I cannot change keyboard layout after using auto-type in KeePassXC. I use global Alt+Shift combination to switch between keyboard layouts. Switch policy set to global.

**Comment by LuisPeregrina** [comment]
> @Roxxor91 the workaround is to manually set the keyboard distribution to US-English before autotyping.

I tried this, but the "at" sign (@) just becomes a (2), I have to also put caps lock to fix it. Which is really inconvenienent.

**Comment by icaid** [comment]
06/30/2019, KeePassXC 2.3.4, Linux Mint 18.3, En/Ru/Ukr layouts - nothing changed from 04/06/2017: if layout is different than "En" then you have incorrect auto complete form with login and password. For example: instead "user" as login you get "гыук" and it is related to password too.

**Comment by droidmonkey** [comment]
Closing this one in favor of #2475
