### ISSUE TITLE
Improve application icons [$50]

### ISSUE THREAD

**Issue by lifepillar** [keepassxreboot/keepassxc#475]
I apologize for the somewhat light-minded request, but… no plan to switch to vector icons? On macOS, at least, they do not look so gorgeous… (the app icon is beautiful, though).

I know that resources are tight and there are other priorities. A good-looking UI, however, may attract a wider public to KeePassXC, making it eventually more popular.

**Comment by weslly** [comment]
I agree. IMHO the current icon theme looks really bad and outdated, I would love to see something more modern, like the [elementary icon set](https://github.com/elementary/icons) maybe.

**Comment by droidmonkey** [comment]
I'm going to table this until 2.3.0, but I am open to seeing some suggestions and sample icon sets posted here. I totally agree the current set of icons is.... dated

**Comment by lifepillar** [comment]
Maybe, something among these sets: https://tagliala.github.io/vectoriconsroundup/.

**Comment by lifepillar** [comment]
Here, there are several open source icon sets: https://icons8.com/welovesvg.

**Comment by phoerious** [comment]
The icons we currently use are from KeePass. I don't really like the myself. Neither are they especially beautiful nor do we have any high-res versions of them. 22x22px is all we have. We need to change the at some point.

**Comment by gagarine** [comment]
A related note about the "add a new key". This icon is not understandable (at least for my mum). It should have a + I guess so it' easy to understand it for "add".

![screen shot 2017-08-12 at 15 07 17](https://user-images.githubusercontent.com/164074/29240969-40dab5ec-7f70-11e7-9cef-484d15562313.png)

This is specially perturbing because the "New database" icon do have a +.
![screen shot 2017-08-12 at 15 11 13](https://user-images.githubusercontent.com/164074/29240980-8f8fbcf0-7f70-11e7-9161-5ed25976ba2f.png)

Anyway, I think the "new database" should *not* be in the toolbar to avoid confusion.

**Comment by gagarine** [comment]
Why not taking https://github.com/mstarke/MacPass icon? 

![screen shot 2017-08-15 at 22 00 17](https://user-images.githubusercontent.com/164074/29333732-28359358-8205-11e7-89ba-4553039ac9ac.png)

**Comment by CoalaJoe** [comment]
How about Material Icons?

**Comment by edubxb** [comment]
As a GNOME user, I really appreciate the integration with the look and feel of the desktop, so the application should use the icons provided by the theme I'm using when possible.

**Comment by phoerious** [comment]
That won't change. We are only talking about fallback icons.

**Comment by cryptomilk** [comment]
On HiDPI screens the icons look pretty horrible. It would be really great to have a new set with higher resolution icons.

**Comment by mueller-ma** [comment]
For openHAB I improved a script that generates icons from https://www.materialdesignicons.com/ (Community driven material design icon). The script renames and changes the color of the source icons.
If you want to use material icons, I can help you with that.

**Comment by ArchangeGabriel** [comment]
@cryptomilk HiDPI is #548, but #756 should solve it. BTW, #756 is what you are looking for @edubxb.

**Comment by wolframroesler** [comment]
For clarification, we're talking about the application icons here (toolbars and menus), not the "default icons" for groups and entries. The latter should remain unchanged ([KeePassium](https://keepassium.com/) has redesigned default icons, and they look awesome unless you have downloaded custom icons, in which case they look terrible).

If we agree upon material design, https://materialdesignicons.com/ seems to have most of what we need. @mueller-ma's script looks interesting however I'm not sure we really need it.

**Comment by wolframroesler** [comment]
Wrote a shell script that converts the existing KeePassXC icons to Material Design. Here are the first screen shots:

* Unlock screen

![unlock](https://user-images.githubusercontent.com/25565229/71490124-86e2c480-2829-11ea-84b6-460a0d1e9f57.png)

* Main screen

![mainscreen](https://user-images.githubusercontent.com/25565229/71490133-8fd39600-2829-11ea-8aaf-6cfa14c391bb.png)

The general idea is a mapping from the existing icon names (e. g. `document-new`) to the icon name in the Material Design repo (https://github.com/Templarian/MaterialDesign; e. g. `folder-plus`). The shell script (makeicons.sh in the utils folder) uses this mapping to re-create the png file in the KeePassXC source from Material Design's svg file. That makes the conversion fairly easy (detailed instructions are at the beginning of the script).

In order to be able to test it, I introduced an environment variable to deactivate the operating system's Qt icon theme. The default is to take icons from that theme if possible, which of course makes it impossible to see all the new icons. To ignore the theme and show built-in icons only, run KeePassXC like this:

```
$ KEEPASSXC_IGNORE_ICON_THEME=1 keepassxc
```

I consider the env variable a (hopefully temporary) hack. If anyone knows a better way to accomplish the same thing, let me know.

**Comment by wolframroesler** [comment]
Note, if we decide to stick with the Material Design icon, someone should add proper credit to the about dialog or wherever they belong (https://materialdesignicons.com/, https://github.com/Templarian/MaterialDesign).

**Comment by mueller-ma** [comment]
How does the settings screen look? IMO the icons for search and help can be a bit smaller.
If you want to use these icons, I recommend you creating an icon request for key-add, key-edit and key-remove: https://github.com/Templarian/MaterialDesign

**Comment by wolframroesler** [comment]
Here are a few more screenshots:

* Entry editor

![edit](https://user-images.githubusercontent.com/25565229/71491650-20ae6f80-2832-11ea-9b77-7079cfda4815.png)

* Application settings

![appsettings](https://user-images.githubusercontent.com/25565229/71491660-27d57d80-2832-11ea-9a32-f7a7c12f3c55.png)

* Database settings

![dbsettings](https://user-images.githubusercontent.com/25565229/71491662-302db880-2832-11ea-8093-f1d6e367fc95.png)

@mueller-ma You're right about the sizes of the looking glass and question mark, however I didn't change anything about the icon sizes, not even the encoding; what was a 22x22 png before is still a 22x22 png now, just created from an svg. I hope that eventually we'll do without the png files entirely and use svg natively, but that will be the second step. I used the "credit-card" icons instead of key-add/edit/remove because these icons refer to the entire entry, not just the password (=key).

By the way, "Secret Service integration" is still blue because it's not a png file in the source, and so far I'm handling the png files only. Will handle it in the second step when switching everything to svg.

**Comment by droidmonkey** [comment]
This could use a bounty

**Comment by wolframroesler** [comment]
Since I'm working on this, I've been noticing that lots of applications use Material Design-style icons these days: Vivaldi, Nextcloud, Twitter, GitHub, GitLab, elementary OS Terminal, Plex are just those that are right in front of my eyes. Seems like we're on the right way.

**Comment by wolframroesler** [comment]
Requested a Material-style version of the KeePassXC icon from the Simple Icons site (https://simpleicons.org/): https://github.com/simple-icons/simple-icons/issues/2268 it could used e. g. in the system tray menu.

Material Design no longer wants to include company or product logos, pointing to Simple Icons instead (https://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by wolframroesler** [comment]
One more thing. Here's how it currently looks with the Material Design icons:

![Screenshot from 2020-01-11 17-45-50](https://user-images.githubusercontent.com/25565229/72207756-31025380-349c-11ea-9d47-f2d8e23d57be.png)

... at least that how it looks when system theme icons are disabled (for which I temporarily introduced an env variable that I can set during development). The regular version (as of #756), however, allows the system theme to override icons, which doesn't look too pretty:

![Screenshot from 2020-01-11 18-03-38](https://user-images.githubusercontent.com/25565229/72207859-e46b4800-349c-11ea-9f95-6e672756c889.png)

How about introducing a check box in the settings dialog that configures whether the system icon theme is to be used or not?

**Comment by droidmonkey** [comment]
I would not allow any system icons at this point

**Comment by wolframroesler** [comment]
> I would not allow any system icons at this point

You mean, undo #756, and behave as if `KEEPASSXC_IGNORE_ICON_THEME` (the env var I introduced to disable the system icon theme, cf. https://github.com/keepassxreboot/keepassxc/issues/475#issuecomment-569132947) was set permanently?

**Comment by droidmonkey** [comment]
Yes precisely. Especially if we package the icons with the executable and eliminate all the filepath nonsense in the code. You either have material icons or you don't. There is no sense in a hybrid icon look.
