### ISSUE TITLE
[Linux] KeePassXC hangs on launch when Tray Icon is enabled

### ISSUE THREAD

**Issue by NoXPhasma** [keepassxreboot/keepassxc#4768]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since last update when the tray icon is enabled and I launch KeePassXC, it hangs the whole tray for around one minute and then gives out this error on console:
```
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.NoReply", "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")
```

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable tray icon in KeePassXC
2. Launch KeepassXC
3. wait

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC should just start without a hang.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC tries to communicate with D-Bus and seems to fail.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: dcca5aa
Qt 5.14.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Manjaro Linux)
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This seems like a Qt bug

**Comment by mtwebster** [comment]
This is hanging in this particular case because MainWindow::isTrayIconEnabled() is being called a second time while the tray is still being registered.
```
MainWindow::MainWindow()
{
..
    applySettingsChanges();
        ...
        ...
        updateTrayIcon()
            isTrayIconEnabled()
                (set up tray icon)
    ...
    ...
    ...
    updateTrayIcon()
        isTrayIconEnabled()
            QSystemTrayIcon::isSystemTrayAvailable()   <---- hangs for 30s (timeout) here
}
```
This all occurs synchronously, and I think there's some collision happening with dbus calls (isSystemTrayAvailable is querying org.kde.StatusNotifierWatcher to see if a host is available, and the tray constructor is trying to register on that same interface).

I'm not familiar with qt, but removing the updateTrayIcon() at the end of the window constructor resolves this issue, though it may be needed there for other reasons.

Note this only happens with qt5's status notifier tray mode (dbus system tray: yes)

**Comment by droidmonkey** [comment]
Good catch!

**Comment by mtwebster** [comment]
Thanks - one question:

Is there any cross-communication with keypassx here - should I open a new issue with them? - it does reproduce there as well, for the same reasons.

Is it a dead project?  Their issue tracker seems to be disabled...

**Comment by droidmonkey** [comment]
KeePassX is dead

**Comment by NoXPhasma** [comment]
@mtwebster The approach you did with xapp-sn-watcher in Xapps fixed it for me.
