### ISSUE TITLE
Touch ID keepass xc doesn't work anymore

### ISSUE THREAD

**Issue by guldarel** [keepassxreboot/keepassxc#4818]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

HI, I did an update to Catalina 10.15.5 and now the touch ID with keepassxc database didn't work anymore. Does anyone know why?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
Please fill out the necessary information. You need the latest version of KeePassXC and perhaps a system restart.

**Comment by guldarel** [comment]
Hi, I did already restart and I have the latest version of KeepPassXC

**Comment by combr** [comment]
Apr 9, 2020: we are releasing KeePassXC 2.5.4, the fourth maintenance update for KeePassXC 2.5. This update ships with a full resolution of the code signing issue and brings back TouchID.

Do you want to write exaclty used version and steps for reproduce on mentioned above version?

**Comment by perdittmann** [comment]
Hi,
I am afraid, I have also not been able to get TouchID to work – simply because I appearantly don't understand the interface.

On the "lock screen", there is a checkbox "TouchID for Quick Unlock". I have checked that box. What do I do next? Simply touching the panel does not work, and there doesn't seem to be any "read Touch ID now" functionality or something.
Is there anything I am missing? I'd really appreciate any clue on this. Thanks in advance!

I am using 2.6.0beta1 under macOS Catalina, but also 2.5.4 had the same behaviour, also under macOS Mojave.

**Comment by droidmonkey** [comment]
You have to unlock your database first with the checkbox checked. Then if it locks, the next time you unlock just check the checkbox and press OK. At that point you can touch. The UI needs a lot of love, but that is tracked in a separate issue. This one needs to be closed.

**Comment by perdittmann** [comment]
Okay, thanks for your help. I have a lot of love for the app, including the UI. :-) Thanks for the great work!
