### ISSUE TITLE
Browser Extension: Allow the correct credentials to have permanent access to passwords instead of always having to confirm.

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4898]
## Summary
Every time that the browser extension visits a website for the first time and the credentials match, we have to confirm permission for the extension to access the website.  This requires us to check a box and then press a button to confirm.  Apparently, I'll have to do this for each of the thousands of websites I have login/passwords that I have.  

I installed the browser extension about a few months ago.  And, I still have to multiple times per day give permission to the browser extension to access websites that I am visiting for the first time after I have installed the KeePassXC browser, about 2 months ago.

## Examples
For example, today, to sell my used car, I visited cars.com for the first time in 2 years.  I used the website 2 years ago so I have an account and my login and password is saved within KeePassXC.  Once again, a dialog box pops up, asking for permission so the KeePassXC browser can use this login and password for this website.

## Context
I'm assuming that these constant confirmations for access are for security reasons.  I can't figure what it's supposed to do but it doesn’t matter.  I'm sure there is a valid reason for it; otherwise, the developers would not have put it in, right?

Is there a way around this?  I'm kinda sick of checking the box that say Always Allow and then clicking the Ok button for every new website I visit.

**Comment by varjolintu** [comment]
KeePassXC settings -> Browser Integration -> Advanced tab -> Enable _Never ask before accessing credentials_.

The reason permissions are asked is that you eliminate the possibility for a possible automatic reading of your credentials, but mostly it's useful when you are using auto-filling (which is disabled by default). Also, if you are using the browser extension API with some 3rd party app (Python client etc.) in this way you can prevent them accessing your credentials automatically even if you have connected your database in to the client.

**Comment by CerebralFreeze** [comment]
Thanks!  I never touched that section before because it had all these danger signs so it made me very scared.  

I guess there really was a legitimate reason for constantly asking for new websites.  Can I ask a question though?  I'm actually asking these questions not for me per se but to help you guys improve your program.

1. Can a website usually read my credentials (login and password) even before I have even pressed the KeePassXC icon in the login field in order to fill in the login and password?  It knows my login and password right away?  So, do websites usually know right away who is visiting their website from the KeePassXC browser if credentials match?  Their obtaining the password is not that important since I'm assuming that they already know but I'm wondering if they can track people that easily.

2. Phishing
Could a website appear to look like another website via a similar URL and then obtain my credentials?  I'm assuming no because that would be the first thing you guys would prevent.  I'm also assuming that if someone owns the domain, nobody else can create a URL with the same domain, right?

3. Should I enable _Never ask before accessing credentials._  I've been thinking it over and I don't see any danger but you guys are the experts.  What could happen if the website you visit already knows your login and password?  The only thing I would prefer, of course, is that they didn't get access to my credentials until I pressed the autologin icon.

**Comment by varjolintu** [comment]
1. Short answer: no. Long answer: we've ensured that the default behavior always requires an user interaction before filling any credentials to websites. Content scripts are also using `isTrusted` check for all interactions, which mean possible malicious page scripts cannot trigger the same actions without user knowing it. And still, the info shown on Autocomplete Menu or popup only shows the username. Content scripts don't hold any password data before actually filling the credentials. So considering this, using _Never ask before accessing credentials_  with Auto-Fill could potentially fill your password to a place you don't want it to be filled. But, for some users this is a must, and it's a preferred usage, so the features enabling this still exist.

2. At this point, no, because we don't support domain wildcards, only subdomain wildcards. The base domain of the site must always match. Also, iframes from another domain don't have a permission to access your credentials.

3. The confirmation dialog ensures you use the entry only for the current site. If you add an Additional URL to the same entry, the confirmation will be asked for that site also. Enabling the option would always grant automatic access to your entry from all URL's you've defined, and for all clients that are connected to your database. If you are only using KeePassXC-Browser as the only client and your entry has only a single URL, it's not a big danger. But of course we encourage to use the default settings, just in case.

When going to a slightly more paranoid side of the issue, imagine a situation where a malicious software reads your browser's unencrypted localStorage and thus gains access to the keys used to connect your database. If _Never ask before accessing credentials_ is enabled, that kind of software could potentially seek your every entry by accessing the corresponding URL. With the setting disabled (default), any request for the entry would require a confirmation from the user. Any malicious app would hit the wall at this point.
