### ISSUE TITLE
Adjust app icon for OSX 11 Big Sur

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4933]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Like demonstrated on the last week WWDC the new OS X Big Sur changes many things . One is the different style of the icons used for Programms 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Look at this page . Apple changed the icon style from round to square 

https://www.cultofmac.com/715717/fantastic-fugly-all-new-app-icons-macos-big-sur/

**Comment by droidmonkey** [comment]
We won't be making a custom icon just for this.

**Comment by martin-sweeny** [comment]
unless....?

**Comment by SebastiaanKloos** [comment]
@martin-sweeny Take a look at https://macosicons.com/. Maybe we can create an icon for now ourselves

**Comment by thrdroom** [comment]
I don't understand why the devs of this project are so adverse against even little wishes from the community.
Circular shaped icons are ugly as hell, imho.

@F3000 @martin-sweeny @SebastiaanKloos 


I have attached two different versions of the keepassxc icons in the macOS Big Sur rounded square shape as svg-files, to this post. Users can do what ever they want with it! Devs of keepassxc, if you use this icons, credit me!

[keepassxc-square-shaped-icons-macOS-Big-Sur.zip](https://github.com/keepassxreboot/keepassxc/files/5135077/keepassxc-square-shaped-icons-macOS-Big-Sur.zip)

**Comment by phoerious** [comment]
The icon is not just some random illustration our brand.

> Devs of keepassxc, if you use this icons, credit me!

With all due respect, this is not how it works. You are using and modifying our branding, which makes you subject to our copyright guidelines, not vice versa.

**Comment by droidmonkey** [comment]
I'll be sure to not use "your" work....

**Comment by martin-sweeny** [comment]
Oh, I don't care. I was making a joke because the issue was reopened lol

**Comment by whitezo** [comment]
An even more interesting thought: not only the icon would need to be updated, but the name of the app as well... Big Sur is macOS 11, not X ;). (jk)

**Comment by phoerious** [comment]
Luckily, we are already referring to it as "macOS" only.

**Comment by Shrinks99** [comment]
Gave this a shot, tried adapting the existing logo to rounded corners, came up with these three versions.

![Keepass Mockup](https://user-images.githubusercontent.com/5672810/99915568-76a1c680-2cd2-11eb-895a-c642d164f25d.jpg)

It's worth noting that theses icons absolutely don't adhere to the [suggested specifications for MacOS icons](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) in any way other than the shape.  I think the middle one is probably the most appealing but also the most iOS like.

**Comment by droidmonkey** [comment]
I like the middle one

**Comment by Shrinks99** [comment]
Tried giving the borderless option a drop shadow on the key too, this one is definitely my favourite!
![Icon-MacOS-512x512@2x](https://user-images.githubusercontent.com/5672810/99917174-a35adb80-2cdc-11eb-8581-ce69d0b60f7f.png)
Should you like this and want to implement it I'll re-make the gradient in Photoshop instead of Illustrator to get rid of the ugly banding.

**Comment by phoerious** [comment]
Why make the icon rectangular? Chrome keeps their logo round and simply adds a white border. We should be doing the same.

**Comment by droidmonkey** [comment]
I thought more about the no border one and I dislike it: it is not our logo, we don't have a full key, the top is flattened. The first one is far better

**Comment by Shrinks99** [comment]
@phoerious Thought it might be fun to try some other options!  Here's that version, it's definitely the safest choice.

![KeepassXC White Circle Logo](https://user-images.githubusercontent.com/5672810/99928692-2fd6bf80-2d18-11eb-85c9-dd902b85141d.png)

**Comment by phoerious** [comment]
I like that one.

**Comment by Shrinks99** [comment]
Okay one more version, original logo but with some shading! A lot of applications [including Chrome](https://twitter.com/elvin_not_11/status/1328833704756617217) seem to be going this route.

![Big Sur Icon](https://user-images.githubusercontent.com/5672810/99936611-8a304a00-2d31-11eb-8cbd-dff746b5d440.png)

<img width="791" alt="Screen Shot 2020-11-23 at 2 15 16 AM" src="https://user-images.githubusercontent.com/5672810/99936698-bcda4280-2d31-11eb-840a-c354f9151230.png">

This one is definitely my new favourite :P  Open to shading adjustments and suggestions!

**Comment by phoerious** [comment]
It's too much. I am not entirely sold on going that route. After all, it's still our logo, not just some random illustration. If anything, it should be more realistic with regards to where to "light" comes from. The Chrome example uses Material-style shading. The example you proposed is not Material-like. At least the gradient in the border is too much.

The grid alignment can be done, I am not against that.

**Comment by Shrinks99** [comment]
Adjusted the shading, agree on the unified light direction, made the highlight on the border less reflective, everything is top down now and I think it looks much better and the change is definitely subtler.  Here it is in context with some other 3rd party applications, I admittedly haven't upgraded to Big Sur yet myself :P

<img width="432" alt="Screen Shot 2020-11-23 at 5 45 01 PM" src="https://user-images.githubusercontent.com/5672810/100023941-dfad3b00-2db3-11eb-896b-77ffc749b6aa.png">

As for staying on brand I'm personally a proponent of changes where applicable to make a brand fit into different contexts, IMO adapting in small ways is an asset and doesn't detract from a brand's overall image.  Sometimes these changes are too drastic (remember the original Windows 10 "it's gotta be white on a coloured tile" system?) and so nobody follows them because they're ridiculous.  I think Apple's new suggested styling is good because it allows for a fair amount of diversity while setting up _some_ standards that make things cohesive across the whole OS.

**Comment by phoerious** [comment]
I still don't like the shading of the dark ring. It doesn't indicate any direction of where the light may be coming from and I alwasy thought of it as more being behind the logo, not as an bevel around it. It should be more like a block of solid material which the logo is painted onto.

**Comment by phoerious** [comment]
Can you provide the AI files of your Big Sur icon?

**Comment by phoerious** [comment]
Working on my own version.

**Comment by phoerious** [comment]
![Artboard 1](https://user-images.githubusercontent.com/911270/102694474-86ed8880-4221-11eb-9a34-09247a7a6f46.png)

**Comment by Shrinks99** [comment]
Hey sorry I kind of dropped the ball on this and let it slide for a month, that version looks good!  Shading on the outer white part looks nice.

Outer shadowing looks different than the spec though, if you'd like me to run it through the macOS icon template to keep things uniform I'm happy to do it.

**Comment by phoerious** [comment]
I was looking for something like this, but couldn't find it, so I had to eyeball it. I don't quite get it, why they only provide Photoshop templates and not Illustrator templates, but whatever. Seems like their drop shadow is really just a blurred rounded rectangle.

**Comment by phoerious** [comment]
![icon_256x256](https://user-images.githubusercontent.com/911270/102718477-91bf2080-42e8-11eb-8921-79060688f2d6.png)

I fixed it and refined the contours and highlights.

**Comment by Shrinks99** [comment]
Apple only provides Photoshop templates because Illustrator can only really export 8 bit sRGB colour and these new icons need to support P3 which is a wider gamut.  Because of this you should also ideally create the gradient in Photoshop using 32 bit mode if you want it to interpolate properly, look nicer, and get have less/no banding.

In short, this one is on Adobe.  [Here's a twitter thread on why gradients suck!](https://twitter.com/Shrinks99/status/1339314848694480900)

**Comment by phoerious** [comment]
Funny thing is: both images in that thread are 8bit. 32bit is a total waste of resources for an application icon. It's a working colour space for image manipulation, not an export format.

**Comment by Shrinks99** [comment]
Images are exported from the template as 8 bit P3 instead whereas Illustrator _only_ supports 8 bit sRGB as it isn't really colour managed AFAIK.  Same bit depth, different primaries.  Gradients should ideally be applied in 32 bit space but exported as whatever.

**Comment by phoerious** [comment]
Of course, Illustrator is colour-managed. It's only less sophisticated when it comes to converting images between colour spaces than Photoshop and it does indeed only support 8 bit, but I don't think that's a problem per se for illustration. In fact, the gradient banding you are referring to is nothing to do with the bit depth, but everything to do with gamma correction.

The Twitter post is quite misleading I would say. Yes, you need 32 bit if you are heavily scaling colours and therefore need HDR, but you don't need it to get correct gradients. If you do it properly, the only banding you get is the normal discretisation banding you get with any low-bit-depth image, no matter if it has been created in 32 bit or 8 bit (you can even see it in the "32-bit" version in the Twitter post). The luminance banding is entirely a result of incorrect gamma.

I tested it in both Photoshop and Illustrator. Here's the normal gamma-incorrect 8-bit sRGB gradient in Photoshop:

![srgb](https://user-images.githubusercontent.com/911270/102772977-b965c580-4388-11eb-9097-2f1c4077bf6a.png)

And here is the same gradient (same colour values), with a linear RGB profile:

![linear](https://user-images.githubusercontent.com/911270/102773027-cda9c280-4388-11eb-85b5-820537810b46.png)

It is virtually the same as creating it in 32 bit and then converting down to 8 bit with gamma 1.0:
![32bit](https://user-images.githubusercontent.com/911270/102773072-e914cd80-4388-11eb-9f9a-75b4364b07a9.png)

The only "advantage" of doing it in 32 bit is that when I convert it back, I can easily choose a gamma of 2.2 (which is the default for sRGB), which results in a much darker image than the linear RGB space. But why would you want to do that? Display correction is what you have "View -> Proof Colours" for and a 32-bit gradient proofed as "Monitor RGB" looks as shitty as any 8-bit sRGB gradient. I believe the confusion here comes from the fact that Photoshop's 32-bit mode automatically uses a linear colour profile, because there is no need for gamma correction if you have such a high bit depth.

Illustrator itself does not really allow for custom gamma correction, sophisticated colour space conversion or profile selection on export, but I can load my linear RGB profile and when I export it for web, I cannot select the export profile like in Photoshop, but it seems to assume sRGB nonetheless, so here's what I get:

Linear RGB working space:
![illustrator-linear](https://user-images.githubusercontent.com/911270/102773883-3e051380-438a-11eb-91e2-0c7f0fa4bee8.png)

sRGB:
![illustrator-srgb](https://user-images.githubusercontent.com/911270/102773892-40676d80-438a-11eb-98cf-6a77ec0458d6.png)

It's the same thing. I believe the main problem here is that Apple, for unknown reasons, decides to go with P3 now, which has a gamma of 2.6 and neither Photoshop nor Illustrator support embedding profiles in PNG images. So if I save out a PNG, it will be interpreted as whatever colour space is your default and that is sRGB on any normal system and now apparently P3 on Apple devices, so the colours will look off. The difference between Photoshop and Illustrator is that in Photoshop I can choose to export in a different profile, although it will still not embed the profile itself, which is a shame (so it will look correct on Apple devices, but wrong everywhere else). Illustrator will export it as is without colour conversion at all or, if I choose "Export for web", it will export it exactly the way I see it on the screen with proofing turned off. If I do that with our icon, the result is way too bright of course:

![keepassxc-linear](https://user-images.githubusercontent.com/911270/102775747-bd481680-438d-11eb-93e2-83541fcf8c87.png)

Here's what happens if I gamma-correct the PNG again in Photoshop (yes, I can do that without 32 bit as well). Corrected version on the left, original on the right.

![keepassxc-gamma-corrected](https://user-images.githubusercontent.com/911270/102776066-5ecf6800-438e-11eb-9b4f-9770a044464e.png) ![icon_256x256](https://user-images.githubusercontent.com/911270/102776147-858d9e80-438e-11eb-898b-b79a6b3c8e05.png)

Are the gradients better? Maybe. Is it worth the hassle to run all the exported PNGs through Photoshop or visually redo all the colours be darker in Illustrator? Probably not. In fact, I barely see a difference at all. The icon is simply not dark and saturated enough for gradient banding to occur.

**Comment by phoerious** [comment]
Actually, the Photoshop gamma correction seems to work a bit differently than the 32-bit upconvert and with a gamma-corrected down-convert. The gamma correction via the exposure adjustment layer produces the same result as the normal "incorrect" sRGB gradient, so no wonder I see hardly any difference. You should be able to achieve the same effect without bit depth conversion somehow, but perhaps Photoshop simply isn't up to the task.

Here's the icon exported in Illustrator and then up/down converted in Photoshop:

![keepassxc-gamma-2 2](https://user-images.githubusercontent.com/911270/102778077-2a5dab00-4392-11eb-9550-28eb4972ff1c.png)

The colours are certainly much darker, but I still don't see a huge difference in the gradients that would justify the extra effort.

Of course, the difference is much larger if you take the saturated colours from the examples above and correct them.

Illustrator export sRGB:
![illustrator-srgb](https://user-images.githubusercontent.com/911270/102778238-81638000-4392-11eb-89d2-fe60b95cfdc8.png)

Illustrator export linear:
![illustrator-linear](https://user-images.githubusercontent.com/911270/102778260-8a545180-4392-11eb-8bfe-a55215671c6f.png)

Linear PNG gamma corrected 32-bit:
![illustrator-linear-gamma-corrected](https://user-images.githubusercontent.com/911270/102778180-64c74800-4392-11eb-9e48-fc2cf9c6e885.png)

Linear PNG gamma corrected 8-bit (same as original):
![illustrator-linear-gamma-incorrected](https://user-images.githubusercontent.com/911270/102778354-b8399600-4392-11eb-93a5-0f78a295eea9.png)

**Comment by droidmonkey** [comment]
A new icon and a lesson! 👏

**Comment by Shrinks99** [comment]
Ah it seems that I am the problem!  Well... at least partially.  My beef still resides with Adobe who don't use a linear working space by default, but it seems I should have taken the time to set up ICC profiles properly to make this happen before being angry on the internet.  I still think that up-converting to 32 bit as a quick workaround for those who don't have ICC profiles set up in order to have proper interpolation is decent hack to make this work without any additional colour management setup, but nonetheless I'll have to make some corrections to my Twitter thread! :P

Also the lack of colour management setting on export from Photoshop is a good thing to know about, this is probably why I had to set it manually in Preview which does seem to save that metadata to the file... Or at least offers more accurate display output.

In any case, I think my job here in this issue with the icon is done, your version looks great.  Looking forward to the MacOS changes in the next update :D

**Comment by phoerious** [comment]
Photoshop does have colour management settings for exporting images, it just doesn't embed profiles in PNGs (it does so for JPEGs). Illustrator is lacking this setting entirely, which is weird, because the rest of the dialogue is more or less identical.

And yes, you can simply go to Edit/Convert to Profile in Photoshop. Select the gamut you want (sRGB, Adobe RGB, P3) and then change the selection to Custom RGB. In the following pop-up you can set gamma to 1.0 and give the profile a name. To save it out, go to colour settings, select the new profile and then change the selection to Save, which prompts you to save it as an icc profile (weird UX here, but anyway). Then cancel out of the settings dialogue.

BTW The 32-bit mode is great for HDR images and funny effects, but I never really use. It is still lacking a lot of features from the lower bit depths. I believe curve adjustments are a new feature only in CC 2020 and some are still missing. And apparently some behave weirdly inconsistently like the exposure layer, as we noticed.

**Comment by Shrinks99** [comment]
Oh yeah, half the tools are missing in 32 bit mode, same deal with After Effects which is quite frustrating as a Nuke user (where everything is 32 bit all the time)  because it makes an especially big difference with video workflows.
