### ISSUE TITLE
Bluetooth HID Plugin/Interface to paste directly from keepassXC to connected device

### ISSUE THREAD

**Issue by OrawnzvaWrafra** [keepassxreboot/keepassxc#4952]
## Summary
Intention: 
Use keepassXC from mobile phone to paste passwords to computer(s) and other devices, on which installing a  an additional app is not possible and running portable software from USB is not permitted. 

Current Workaround: 
Use of an additional app to establish an HID Bluetooth connection and emulate a keyboard for the computer. Exemplary app: "Bluetooth Keyboard" from AppGround IO. 

Drawback: Additional (3rd party) app gets access to the password that is to be transmitted and the password needs to be stored in workspace of the phone for this. 

Desired solution: Plugin for keepassXC (or direct integration of a feature into keepassXC) that provides the HID Bluetooth connection, so that direct pasting from within keepassXC to the Bluetooth receiver becomes possible.

**Comment by phoerious** [comment]
Sorry, but this is entirely out of scope and Bluetooth would just be a huge attack vector.

**Comment by OrawnzvaWrafra** [comment]
Ok!

**Comment by amitjaju82** [comment]
For anyone finding this issue looking for the phone-side equivalent: I've implemented
Bluetooth HID auto-type in a KeePassDX fork, which works against KeePassXC databases since
both read `.kdbx`.

https://github.com/amitjaju82/KeePassDX-bluetooth-keyboard

The phone registers as a Bluetooth keyboard and types into the computer, so nothing is needed
on the desktop side at all — no plugin, no agent, no dongle. It's the inverse of what this
issue asks for, but it solves the same problem for anyone whose database is already synced to
a phone.

Unaudited personal fork, GPL-3, not affiliated with Kunzisoft or KeePassXC.
