### ISSUE TITLE
Allow preview panel to be smaller in size

### ISSUE THREAD

**Issue by Rivanni** [keepassxreboot/keepassxc#4989]
## Summary
Version 2.6.0

I want to be able to set the height of the preview panel the way I want. There's now only a fixed height which is also too large in compact mode. I personally don't have to see the Notes part of this panel since I seldom use is. But it takes up a considerable amount of space.
Another suggestion is to move Notes to its own tab in this panel. This way you can go to the Notes without resizing the panel.

**Comment by droidmonkey** [comment]
It was in its own tab and someone asked for it to be in the general tab :speak_no_evil:

**Comment by droidmonkey** [comment]
We have made it as shrinkable as possible without significantly limiting the information that can be viewed.

**Comment by MaximilianKohler** [comment]
I would not consider this "completed". It's still extremely limited. I hope you can make it more customizable.

**Context**: I am only using KPXC for TOTP 2FA. I have around 12 entries and I want them all to be visible so I can just click one and see the TOTP:
![list of entries](https://github.com/keepassxreboot/keepassxc/assets/3606996/1505c369-9b98-4592-adbe-6a144bc3709a)

In order to do that, I have to expand the window far bigger than it needs to be since I cannot compress the preview panel any more than what's shown:
![full window](https://github.com/keepassxreboot/keepassxc/assets/3606996/96dd147b-9780-4754-8d04-0667b2a48a4b)

I need to compress it more so that I can view the TOTP at the bottom of my screen, under my browser window, when I'm trying to enter it in my browser:
![bottom of screen](https://github.com/keepassxreboot/keepassxc/assets/3606996/33436ca4-452d-46b3-8885-9450b8f23ae6)

I don't need to see any of that "general, advanced, autotype, notes". I only need to see the TOTP at the bottom.

I see there's an autotype shortcut but there doesn't appear to be a way to switch it to TOTP instead of user+PW.
![autotype](https://github.com/keepassxreboot/keepassxc/assets/3606996/a902a280-8457-4c9b-a6e2-a475f77140c3)

And even though it shows control+shift+v, in the settings it's blank:
![autotype settings](https://github.com/keepassxreboot/keepassxc/assets/3606996/ad6cc59a-3ad6-489a-8126-1370d01d4aad)

This is the exact layout I'd like:
![sized](https://github.com/keepassxreboot/keepassxc/assets/3606996/73109807-14b5-437e-96e6-57abc461bfe6)

But doing that hides the login/cancel buttons when opening the app:
![buttons hidden](https://github.com/keepassxreboot/keepassxc/assets/3606996/1af895cb-cc9b-42a4-94d4-ac16fad44b3f)

I can live with it by pressing enter instead, but it's not ideal. It also means I have to keep moving the window around if I ever need to see the whole thing, like when editing entries or viewing settings, etc.

**Comment by droidmonkey** [comment]
@MaximilianKohler, regarding your comments on autotype, you should read the docs: https://keepassxc.org/docs/KeePassXC_UserGuide#_configure_global_auto_type

You can also just double click the totp digits to copy them to the clipboard. 

Having to view the digits to type them into another window is generally the last way we want you to use the program, to be honest.
