### ISSUE TITLE
Easy option to hide expired items from reports

### ISSUE THREAD

**Issue by darkdragon-001** [keepassxreboot/keepassxc#5032]
## Summary
I suggest adding an option/button which allows easy toggle between (not) hiding expired entries. Furthermore, a highlight background color for expired entries when not hidden would be cool. Basically mimicking the functionality of [this traditional KeePass plugin](https://github.com/rookiestyle/kpcolorchange).

Furtheremore, _Database Reports_ (password re-use, HIBP etc.) are supposed to _exclude_ expired items (see https://github.com/keepassxreboot/keepassxc/issues/5032#issuecomment-657107678) which is _not_ the case currently (see https://github.com/keepassxreboot/keepassxc/issues/5032#issuecomment-657121756).

## Examples
See [rookiestyle/kpcolorchange](https://github.com/rookiestyle/kpcolorchange).

## Context
I am trying to migrate from using traditional KeePass to KeePassXC.
I prefer expiring entries instead of deleting them. Over the time, I have three times more expired items than non-expired ones. This would cleanup the view significantly.

**Comment by darkdragon-001** [comment]
Furtheremore, I would like to _exclude_ expired items from _Database Reports_ (password re-use, HIBP etc.).

**Comment by droidmonkey** [comment]
If I recall, expired entries are already excluded from reports, if not then that is a bug. In 2.6.0, we added a red X badge to expired entries and they are crossed out. There is no further styling we will be doing.

**Comment by darkdragon-001** [comment]
I confirm that expired entries are _not_ exlucde in _Health Check_ (they show the red _x_ icon though). In _Statistics_, there is a special _Number of expired entries_, but other fields like _Non-unique passwords_ or _Maximum password reuse_ seem to include expired entries which is confirmed by the field _Entries excluded from reports = 0_.

**Comment by droidmonkey** [comment]
Hiding expired entries is not a desired feature, most people use expired to indicate to indicate the password needs to be changed.

**Comment by darkdragon-001** [comment]
I have about 600 expired entries within 30 groups. I would prefer to have them sorted within the groups. I also use it for expired credit cards, cancelled bank accounts etc. which should be stored at least a few years longer than their expiry.

Unfortunately, this is a blocker issue for me migrating to KeePassXC.

**Comment by droidmonkey** [comment]
Then this isn't the software for you unfortunately.

**Comment by wolframroesler** [comment]
@darkdragon-001 I'm afraid you're using the "password expired" feature in a way that's different from how it's expected to be used. Although, of course, you're free to interpret expiration in any way you like for your database, KeePassXC understands expiration as a problem that needs to be addressed. As described in the blog article about Health Check (https://keepassxc.org/blog/2020-08-15-keepassxc-password-healthcheck):

> A password that has expired [...] is always considered “bad” [...] The reason for this is that you always have a good reason to set an expiry date: Maybe the password is no longer considered secure, or the service may force you to change it, or you may get locked out after that date.

Perhaps you can use the "exclude from reports" feature (right-click an entry in Health Check) to achieve the desired effect.

@droidmonkey's judgement may sound a little harsh but I suggest reconsidering your use of the expiration feature (which I admit is more easily said than done given the huge number of expired entries you mentioned) so you can still get the benefits of migrating to KeePassXC.

Changing the background colour to indicate expiration is a lot harder than it sounds due to theming and accessibility concerns.

**Comment by darkdragon-001** [comment]
@wolframroesler Thanks for your detailed explanation. Which features do you suggest to _document/archive_ items which are no longer valid but should be kept for various reasons (e.g. old bank details, used TAN numbers to detect fraud when asking for the same number again, deleted accounts with the deletion timestamp in order to have it documented in case you notice your account wasn't really deleted to file a complaint)?

**Comment by wolframroesler** [comment]
@darkdragon-001 How about deleting the password from the entry? Entries with empty password don't appear in Health Check. You can move the password (which, as I understand, is no longer valid anyway, so it's not needed for auto-type or similar) into an "additional attribute" on the "Advanced" page (you can check "Protect" to make it invisible if that is an issue). You could also put the deletion timestamp into an additional attribute, if setting the "Expires" timestamp doesn't behave as intended (which, however, I'd consider somewhat counter-intuitive). Checking "Exclude from reports" (also on the "Advanced" page), of course, it what you actually need.

As I understand TANs, keeping a record of used TANs isn't required (but your bank may be using them in a way different from what I'm used to). Do you really have a single database entry for every used TAN? That doesn't seem like how a password database is intended to be used. Maybe you could put the used TANs into the Notes field of a single entry, or into a separate password database (which contains nothing but used TANs), or simply into a plain text file stored elsewhere (because used TANs don't need to be stored as securely as "live" passwords). That way you'll get rid of the better part of your 600 entries, and checking "Exclude for reports" for the remaining ones will solve your issues.

Please let me know if this is a feasible solution for you.

**Comment by darkdragon-001** [comment]
> How about deleting the password from the entry? Entries with empty password don't appear in Health Check. You can move the password (which, as I understand, is no longer valid anyway, so it's not needed for auto-type or similar) into an "additional attribute" on the "Advanced" page (you can check "Protect" to make it invisible if that is an issue).

Deleting the password should also keep the old entry in the history, right? So I guess storing it as additional property won't be needed.

> You could also put the deletion timestamp into an additional attribute, if setting the "Expires" timestamp doesn't behave as intended (which, however, I'd consider somewhat counter-intuitive). Checking "Exclude from reports" (also on the "Advanced" page), of course, it what you actually need.

Sounds like a lot of work for that many entries. _Experes_ timestamp is already pre-filled with "now" at the moment I delete an account. Adding custom fields is a lot more work... Also doing three things (delete password, add custom field deleted, exclude from reports) sounds like a lot of work...

Actually, I am betting on #5677 which would add deletion timestamps automatically and keep the same folder structure in recycle bin in case I am looking for an entry. This seems to support the KeePassXC way of doing things more...

> As I understand TANs, keeping a record of used TANs isn't required (but your bank may be using them in a way different from what I'm used to). Do you really have a single database entry for every used TAN? That doesn't seem like how a password database is intended to be used. Maybe you could put the used TANs into the Notes field of a single entry, or into a separate password database (which contains nothing but used TANs), or simply into a plain text file stored elsewhere (because used TANs don't need to be stored as securely as "live" passwords). That way you'll get rid of the better part of your 600 entries, and checking "Exclude for reports" for the remaining ones will solve your issues.

I used [Keepass2's wizard for TANs](https://keepass.info/help/base/tans.html):
This way, every TAN has a unique entry and Ctrl+C automatically marks it as expired. I think we should maintain compatibility to the _original_ Keepass as much as possible!

**Comment by Philipp91** [comment]
Can we get that same checkbox for the HIBP report?
