### ISSUE TITLE
Allow searching when search widget is not shown

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#505]
KeePassX 2.0.3 for macOS allowed using the search function (⌘F) while the toolbar was hidden. It would be great to have that functionality retained. The toolbar consumes about 40 pixels of vertical space, I never use it. Hotkeys FTW.

**Comment by droidmonkey** [comment]
Hm, that's the unfortunate consequence of moving the search bar outside of the database tab. In Qt, when widgets are hidden they do not respond to hotkeys. Would the desired behavior be to temporarily show the toolbar (and search bar with it) until searching is complete and then hide the bar again?

**Comment by quinncomendant** [comment]
For me, search is the most used function of a password manager. I'm not sure how keepass is normally used, but for me it is like this:

1. invoke keepass (I use LaunchBar, so I type `⌘-space` + `x` and hit return)
2. type `⌘F` and search for an encrypted info
3. type `down arrow` until I reach the matching entry
4. copy (`

**Comment by droidmonkey** [comment]
Here's my proposal:

The option will be created to show search bar in either the toolbar or the database tab.

Searching form the search bar is always global.

Typing keys without modifiers will search / focus on the entries shown in the current folder. This would be similar behavior to file managers.

Whatcha think?

**Comment by quinncomendant** [comment]
Thanks @droidmonkey, I think that’ll do nicely.

The only concern is the added work (by the developers) and complexity (by the developers and users) of having a config option to have the search bar in toolbar vs. database tab. It might be worth doing a poll to see how many people would prefer the search function in the toolbar. If not many, just do the simple option of allowing search only in the DB tab. Does github allow polls?

**Comment by droidmonkey** [comment]
Could also just move it to the db tab if the toolbar is hidden automagically.

**Comment by sergeevabc** [comment]
Whatever you do, please add hotkey sequences into tooltips for actionable UI elements.
Toolbar buttons lacks such information presently, including the search field.
I had to wade through open and closed issues to [url=https://github.com/keepassxreboot/keepassxc/issues/680]grasp[/url] Ctrl+F is involved.

**Comment by TheZ3ro** [comment]
Mmmh, after https://github.com/keepassxreboot/keepassxc/pull/1116 the toolbar will always be visible so I think this issue is not a problem anymore

@sergeevabc please open a new issue about hotkey sequences so we can track it easily

**Comment by sergeevabc** [comment]
Visibility of the toolbar is not the issue, lack of shorcuts in the tooltips is the issue.

**Comment by A1RO** [comment]
Hi, Since this issue is still relevant to some people (myself included), I would like to propose a few ideas to fuel creativity in the design of a **separate search bar** (available as an option, while keeping it in the toolbar by default).

---

From my experience, a search field is typically available on-demand only, and otherwise hidden. With the ubiquity of `Ctrl+F` in most applications, there's no need to have a permanent search bar when navigating with the keyboard.

Two common examples are Chrome and Firefox search boxes.
They show up on `Ctrl+F` and get closed on `Esc`.

![chromesearch01](https://user-images.githubusercontent.com/11812395/36949021-e5b3c4ce-1fb0-11e8-9bb6-f2dd70fdeaa7.png)
![firefoxsearch01](https://user-images.githubusercontent.com/11812395/36949016-dbb2db68-1fb0-11e8-8d64-fd99ab257577.png)

---

As @quinncomendant and @sjaakvandenberg (see #680) have already mentionned, the KeePassX 2 way of dealing with it is clean and useful. For KeePassXC, I would see it merged with the yellow results bar. This bar could be split in half, with an input field on the left and results on the right.

![keepassxc_searchbar01](https://user-images.githubusercontent.com/11812395/36949362-1c0e6494-1fb5-11e8-8c5e-23c841aacf19.png)

---

To go along with @sergeevabc comments, I would definitely add an `Entries -> Find...` menu item to easily focus/bring the search field and to document this `Ctrl+F` shortcut once and for all. It is part of KeePassX 2 but was removed in KPXC for some reason.

![keepassxc_entriesmenu01](https://user-images.githubusercontent.com/11812395/36949405-ef4f0bce-1fb5-11e8-974d-d609dc2c4b5d.png)

---

To explain the context of this post, I'd like to say I totally agree with @SapphirusBeryl (see #1618) that you should keep the ability to hide the toolbar somehow. I'm another one of those guys that always remove those icons from just about every software I use. Since the implementation of a search bar seems to be the only thing blocking this feature, I figured I could help over here.

@droidmonkey  and @TheZ3ro, please bear with us on this one.
I'm sure there's more people like us. :stuck_out_tongue_winking_eye:

**Comment by TheZ3ro** [comment]
Maybe we can do the following: 
- Bring back the hide toolbar option (maybe by right-clicking on the toolbar itself if we don't want an empty `View` menu and fixing #1618)
- Display a Chrome/Firefox-style search box when searching/typing in the main window instead (if the toolbar isn't visible)

**Comment by A1RO** [comment]
@TheZ3ro :
> Bring back the hide toolbar option (maybe by right-clicking on the toolbar itself if we don't want an empty View menu and fixing #1618)

See my reply [here](https://github.com/keepassxreboot/keepassxc/issues/1618#issuecomment-370270790).

> Display a Chrome/Firefox-style search box when searching/typing in the main window instead (if the toolbar isn't visible)

I don't mind the actual implementation of the search box, as long as it stays in line with current user interface design. But what I do believe is that the yellow results box is the right place to put it.

**Comment by vdcbb** [comment]
I want to add my super strong support for being able to Ctrl+F to search when the Toolbar is hidden. I actually came here to post a bug about the inability to hide the Toolbar. From reading here, I see now there is a hidden option of right-click on the menu-bar to hide the Toolbar. But this cripples the ability to Ctrl+F, which is a capability that is critical for everyday use.

Hence this post to urge the developers to fix this bug ASAP. It is one of the most important bugs to address IMHO because it impacts the every-day usability, especially on small screens like I use of 12.5". I need every pixel to count and displaying Toolbars IMHO are a no go. But losing Ctrl+F search functionality cripples my work flow.

Thanks so much guys for accepting feedback. Your work on KeePassXC is amazing!

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#505 - Search without toolbar](https://trello.com/c/Bed6BOlo/12-505-search-without-toolbar)

**Comment by rnc** [comment]
Some of these suggestions are great :-) I would prefer to see a separate search bar versus the toolbar. That way the toolbar can be hidden.  Possibly also the search bar could be hidden but revealed on demand or left permanently visible.

**Comment by iBilley** [comment]
wow open for 2years and still ppl complain lolz

**Comment by alerque** [comment]
@iBilley This is an open source project, everybody (including me) has an idea how this should work but somebody actually has to sit down and do the coding and contribute their time. This project is pretty open to community PRs, if you would like to contribute a solution to this I'm sure we'd all appreciate it.

**Comment by alerque** [comment]
@iBilley This is an open source project, everybody (including me) has an idea how this should work but somebody actually has to sit down and do the coding and contribute their time. This project is pretty open to community PRs, if you would like to contribute a solution to this I'm sure we'd all appreciate it.

**Comment by pigsflew** [comment]
It'd be cool if the search were just moved onto the menu bar and out of the tool bar.

Instead of this:
![original](https://user-images.githubusercontent.com/868821/83213396-e0238c80-a116-11ea-9d80-c33880a12447.png)

Do this:
![search_in_menubar](https://user-images.githubusercontent.com/868821/83214623-df402a00-a119-11ea-8bd6-11eee6f7c8be.png)

because everything that's on the toolbar is also in the menus, so i'd love to be able to hide it but not loose the search box.

**Comment by droidmonkey** [comment]
I don't think we can do that in Qt.

**Comment by pigsflew** [comment]
oh well :/ I suppose the Chrome/Firefox popup search modal way is probably best anyway, I was hoping there'd be an easy way out, but I've never done any QT so I don't know what I'm talking about :D

**Comment by travelalpaca** [comment]
As the window is resized, what about moving the search bar to a second toolbar row of instead of hiding them in an overflow dropdown?  That way the search bar would always be visible.

In my case, I run my Toolbar button style as "Icon only", that way there is pretty much always room for the search bar to fit.
