### ISSUE TITLE
Ask user before executing "cmd://" URLs

### ISSUE THREAD

**Issue by activearts** [keepassxreboot/keepassxc#51]
The option to override the URL for an entry is included in KeePass (Edit Entry > Properties > Override URL). An important use case for this feature is to ensure that bank websites are opened in a web browser that is used for banking only and has no extensions installed, which minimizes the attack surface.

**Comment by droidmonkey** [comment]
So this is when you click on or open the URL from KeePass it opens in a specific browser?

**Comment by activearts** [comment]
Yeah, if a non-default browser is specified for an entry, KeePass will open the URL in the specified browser rather than the user's default browser.

**Comment by TheZ3ro** [comment]
On KeePass you can insert a command in the URL field with "cmd://" and it will be executed, so you can select the Browser by executing its command line. (http://keepass.info/help/base/autourl.html)

Anyway by me is fine but It will be nice if before executing a command, a MessageBox will pop-up asking if the user want to execute that specific command (maybe with a "don't ask anymore" option?)

**Comment by TheZ3ro** [comment]
Turns out that "cmd://" parameter is already supported by KeePassXC. [src/gui/DatabaseWidget.cpp#L485](https://github.com/keepassxreboot/keepassx/blob/82ace81974374365cab83492a4b33720248961de/src/gui/DatabaseWidget.cpp#L485)

@activearts You can simply set the Entry url to: `cmd://process_name` and process_name will be executed.
In case you want to open *github.com* with *Firefox* for example, you need to set the Entry-URL to `cmd://firefox github.com` 

I will leave the issue open for the following

> Anyway by me is fine but It will be nice if before executing a command, a MessageBox will pop-up asking if the user want to execute that specific command (maybe with a "don't ask anymore" option?)

**Comment by activearts** [comment]
@TheZ3ro Thanks! `cmd://firefox`, `cmd://google-chrome`, and `cmd://chromium-browser` all work for me. Nice.

**Comment by TheZ3ro** [comment]
Reopened because #235 does not have the "don't ask anymore" option

**Comment by droidmonkey** [comment]
Does don't ask anymore apply to a specific command string or across the board? Is it also in the options?
