### ISSUE TITLE
Confusing save behavior with non-data changes when auto save is disabled

### ISSUE THREAD

**Issue by ju2wheels** [keepassxreboot/keepassxc#5107]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Made a change to db entry.
2. Saved the entry change using the save button
3. Leave the database open until it decides to lock itself.
4. Database says it needs to be saved via popup dialog and wont lock until you save it via dialog, but if you cancel the dialog, the save button is not available because it was already saved.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Save dialog should not be popping up when it goes to auto lock database since it was already saved.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 16.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
I assume you don't have "Save on exit" enabled. This is actually expected behavior in 2.6.0 since we keep track of non-data changes you make such as group expand/collapse and entry sort order (native sort) and wait to save them until you close the database.

**Comment by ju2wheels** [comment]
No, I dont have "Save on exit" enabled. Even so, if theres something that needs saving why was the save button not available to be pressed in this situation and the only way to save those additional things being counted as changes is now only through the dialog?

**Comment by droidmonkey** [comment]
In your case then, I suggest you disable the setting that prevents non-data changes from marking the database as dirty.

**Comment by ju2wheels** [comment]
OK, ill give it a go.
Thanks,

**Comment by darkwing1** [comment]
> I assume you don't have "Save on exit" enabled. This is actually expected behavior in 2.6.0 since we keep track of non-data changes you make such as group expand/collapse and entry sort order (native sort) and wait to save them until you close the database.

I have a slightly similar issue. You say this is expected to keep track of non-data changes, but why whether "Mark database as modified for non-data changes" is checked/unchecked should there be a forced save everytime?

**Comment by darkwing1** [comment]
@droidmonkey im sorry but expand/colapse groups or other non-data changes should not force save even though this box is unchecked.  Can you please clarify why this is?  This is a bug, should i open a new issue?

Its very inconvenientand time-consuming everytime i expand a group and collapse it after im done with copying an entry, that when closing the keepassxc program it either asks to save or saves automatically, just because i expanded and collapsed the group.

**Comment by droidmonkey** [comment]
The checkbox is not preventing the tracking of non-data changes, it just prevents explicitly marking the database dirty when they occur. This is not just about group expand/collapse but natural order sorting of entries (new feature in 2.6.0). Previous behavior would silently lose information on locking the database, obviously undesirable. There is no bug here and the behavior is not being reverted.

**Comment by darkwing1** [comment]
@droidmonkey Ok so one more question then, is it generally recommended then to check this box? "Mark database as modified for non-data changes"

**Comment by droidmonkey** [comment]
Your choice, all that does is force a save if auto save is on or show the modified mark if its off.

**Comment by RX4NT9UP** [comment]
Your explanation doesn't make sense. Why are you tracking changes for things we have explicitly requested not to track? If the database is dirty show the save prompt. If not, the only possible information loss is non-data changes, which have explicitly requested to be ignored.

I don't want to save my database every time i open it if all I did was view it. Sloppy behavior. At the very least remove the checkbox "Mark database as modified for non-data changes" which in your new broken scenario means nothing.

Please reopen.

**Comment by droidmonkey** [comment]
Just viewing does not trigger a save

**Comment by ju2wheels** [comment]
It does. Thats exactly why I opened the ticket because the behavior is stupid and broken somewhere and your recommended did nothing to change that. I can go into one of my accounts, copy some data out of the advanced section and cancel out and make no changes and randomly end up with a save dialog without having changed anything. Its annoying.

**Comment by RX4NT9UP** [comment]
The session is dirty practically from the moment the database is opened. Even if someone preferred to explicitly save, no one wants to hit cancel every couple minutes and lose locking features. It's can't be a supported case with write on view. If you are determined to break this functionality then I recommend:

1) Replace "automatically save after every change" and "automatically save on exit" with a single dropdown "Autosave on:", requiring one of either "Each change" or "Exit". Because this app does not make sense without one of these enabled. 

2) Remove "Mark database as modified for non-data changes" because this literally has no use case I can discern, nor would it in the scenario above. Unless there is some use you know of.

That said, as users we would much prefer it if instead you restore or improve on the previous behavior of allowing us to choose to discard non data changes.

Thanks

**Comment by droidmonkey** [comment]
Ran some tests:

1. Unlock DB -> Lock DB: NO SAVE
2. Unlock DB -> Open Entry -> Cancel -> Lock: NO SAVE
3. Unlock DB -> Collapse Group -> Lock: SAVE
4. Unlock DB -> Lock DB: NO SAVE

Working exactly as intended. Granted, you are correct there is the "not locking when dialog shown issue" at play here. That happens with normal unsaved changes as well. Why do you have "Save on app exit" disabled if you are worried about that security problem?

I can include a checkbox or even a selection box to explicitly NOT SAVE non-data changes on exit. Will you complain to me when your group expand/collapse state is never saved properly?

**Comment by ju2wheels** [comment]
It looks lie ill just have to enable autosave and hope I dont change something and not realize it and it gets autosaved, thats the entire reason I dont have any of those two auto save features enabled.

But if that mark database dirty doesnt actually cause the UI context to stop requesting a save when these are off then its useless.

**Comment by RX4NT9UP** [comment]
> Working exactly as intended.
I don't think anyone is disputing that, but it's not how it used to work and also not how it appears it should work.

> I can include a checkbox or even a selection box to explicitly NOT SAVE non-data changes on exit. Will you complain to me when your group expand/collapse state is never saved properly?
I'm not sure what others in this ticket are trying to accomplish, but I assume it's similar to me: No auto-save. Prompt for data changes. Don't prompt for non-data changes. I don't consider sort/expand/collapse to be save worthy at all, but rather an ephemeral program state, depending what I'm looking for in the moment.

**Comment by ju2wheels** [comment]
> No auto-save. Prompt for data changes. Don't prompt for non-data changes.

ditto

**Comment by droidmonkey** [comment]
Frankly not auto saving makes very little sense, especially on exit. Every entry item has a history. What risk are you trying to mitigate by not saving your database when changes are made? I just don't see your use case / concern. I will seriously consider an option to totally ignore non-data changes.

**Comment by RX4NT9UP** [comment]
> What risk are you trying to mitigate by not saving your database when changes are made?

I personally don't want to deal with discovering something might have been accidentally altered/deleted a year ago and have to go searching history or trash for the corrected entry (if it wasn't already purged). Perhaps it's a power user feature, but I like to control when a save happens. If I am wrong then there's really no reason to offer turning this feature off.

ju2wheels makes an interesting point that auto-saving non-data OR discarding non-data are both valid fixes. As long as auto-saving data can be turned off and it doesn't result in an unexpected prompt.

**Comment by droidmonkey** [comment]
We don't make a distinction when saving a database, it saves EVERYTHING.

**Comment by darkwing1** [comment]
> I don't consider sort/expand/collapse to be save worthy at all

This. **This** is the problem and this is what has changed from the previous v2.5.x version.
Basically, sort/expand/collapse shouldnt need to be saved everytime (just like it didnt need to be before).  For example, I, like many others have multiple groups, if i want to go in, expand a group just to copy an entry and then closed keepassxc, i dont want to **wait** for it to save just because i expanded a group. I mean this is exactly what this checkbox "Mark database as modified for non-data changes" was there for before!

i still dont understand why this has changed now in 2.6.0.

Again, if i wanted to save non-data changes **constantly** in the previous version 2.5.x, all i would do was check the box.

This issue isnt about aut-saving or manually saving. Its about the non-data changes that are forced to be saved even though we opt out of it in settings.

**Comment by droidmonkey** [comment]
So far two people on the internet find this to be a problem.

**Comment by droidmonkey** [comment]
To be clear, I am going to change the non data changes setting to explicitly enable/disable saving on database close of only non data changes exist.

**Comment by darkwing1** [comment]
> To be clear, I am going to change the non data changes setting to explicitly enable/disable saving on database close of only non data changes exist.

Yes.
So there shouldnt be any security related issues if you do this change, right?  As you have mentioned below.  I mean these are not really "leaks" per say.
> We are a security application that encrypts every piece of information about your database. Not doing so will cause data leaks. This is also part of the KDBX standard, not our rules here.

**Comment by droidmonkey** [comment]
No your choice will be: (1) If non-data changes exist, save on exit without prompt, (2) If non-data changes exit, discard silently (same behavior as 2.5.4).

**Comment by darkwing1** [comment]
Yes, definitely (2). As it was. thank you.
