### ISSUE TITLE
Pressing TAB from master password input no longer selects "show / hide password" icon, now selects "Key File" input

### ISSUE THREAD

**Issue by sebastianklein96** [keepassxreboot/keepassxc#5109]
## Overview
It is no longer possible to show / hide the master password by keyboard controls.

## Steps to Reproduce
1. Start KeepassXC 2.6.0
2. Type in master password
3. Press TAB

## Expected Behavior
Pressing TAB from the master password input previously selected the show / hide password icon so that it can be toggled by pressing space bar.

## Actual Behavior
Pressing TAB from the master password input moves the cursor to the Key File input field.

## Context
In previous versions, the show / hide password icon was an actual selectable element. Pressing TAB from the master password input would select the show / hide password icon. Therefor it was possible to enter your password, quickly select the show / hide password icon pressing TAB, toggling it pressing SPACE and correcting mistakes in the now visible password only by keyboard use.
If it is not possible to bring back said functionality, please provide an easy to use shortcut to show the password in the master password input field.

KeePassXC - 2.6.0
Operating System: Windows

**Comment by droidmonkey** [comment]
Ctrl + H

**Comment by sebastianklein96** [comment]
That would be a good thing to add to the shortcut list then. Because in the shortcut list, CTRL + H is only labeled as "Add key to SSH agent".

**Comment by droidmonkey** [comment]
It's a contextual shortcut though (only applies when the field has focus), whereas the keyboard shortcut list is more global. We can add it

**Comment by sebastianklein96** [comment]
Wouldn't it be an idea to change to an in-application shortcut list then? That could even be contextualized maybe, depending if the database is aleady unlocked, which panel is open etc. Of course that is a big change though.

**Comment by droidmonkey** [comment]
That's way more work than it's worth

**Comment by ian-h-chamberlain** [comment]
Hi, just found this issue as I experience a similar problem. I noticed the new shortcut works great on Linux, but on macOS this is a globally bound application shortcut to hide the application. As a result the KeePassXC window is hidden instead of showing the password as I would like:

![Screen Shot 2020-07-17 at 11 05 44](https://user-images.githubusercontent.com/11131775/87801689-167baf00-c81e-11ea-8ed0-3c63f5c24a2d.png)
![Screen Shot 2020-07-17 at 11 06 51](https://user-images.githubusercontent.com/11131775/87801690-19769f80-c81e-11ea-99a9-c558f17d3ef3.png)

Should I open a new issue for this? I think it most likely affects the macOS version only.

**Comment by droidmonkey** [comment]
That is unfortunate. Yes please open a new issue

**Comment by ian-h-chamberlain** [comment]
Opened #5114
