### ISSUE TITLE
Chromium queries Chrome registry keys under Windows

### ISSUE THREAD

**Issue by BobbyPins** [keepassxreboot/keepassxc#5111]
## Overview
When using the Browser Plug-In for Chromium under Windows, **Chromium** apparently only enumerates the subkeys under HKCU\Software\Google\Chrome\NativeMessagingHosts. The subkeys under HKCU\Software\Chromium\NativeMessagingHosts, created by KeepassXC, are never queried/touched by Chromium.

More of a heads up than an actuall bug on the KeePassXC side, that (under Windows) Chromium shows some odd behaviour. Querying most registry keys from the HKCU\Software\Chromium branch but falling back to HKCU\Software\Google\Chrome for the NativeMessagingHosts subkeys.

## Steps to Reproduce
1. Enable Browser Integration for **Chromium** under Settings.
2. Start Chromium

## Expected Behavior
The keepassxc-proxy.exe module should be started by Chromium.

## Actual Behavior
The keepassxc-proxy.exe module is not started, thus the Browser Plug-In is unable to connect to KeepassXC.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Operating System: Windows 10 OS Version 1909 (Build 18363.900)
Chromium: 84.0.4147.89 (Official Build) (64-bit), Revision: 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}

**Comment by droidmonkey** [comment]
This seems like a bug on chromium side, why would they have any reason to query Google registry keys...

**Comment by varjolintu** [comment]
Chromium is clearly accessing wrong registry keys. You'll get the extension working by enabling support for Chrome instead.

**Comment by michael1maass** [comment]
pls consider this: as a possible reason for failing Communications between the Browser Plugin and the Program. I was going to think that is was a Problem with the f-Secure Installation used in our Company, However, Eric Claw makes another Point: Edge Security Policies make it unable to read the relevant native messaging manifests for the aplication because it expects them in HKLM Hive rather then HKCU. 
I installed KeepassXC with elevated (Admin) rights, however the Keys are not created in HKLM. So I suppose thits might be the reason. Anyone with some expertise in this field? 

pls read and admire https://textslashplain.com/2020/09/04/web-to-app-communication-the-native-messaging-api/ for the detailed description of the general Problem (not focused on KeepassXC)

and help me out with a workaround.... would it be sufficient to copy the keys within the registry? 

Michael

**Comment by droidmonkey** [comment]
We wrote documentation for this: https://github.com/keepassxreboot/keepassxc/pull/5692
