### ISSUE TITLE
No "Repeat" password field in entry

### ISSUE THREAD

**Issue by quadari** [keepassxreboot/keepassxc#5168]
## Overview
When creating a new entry or editing an existing entry there is no longer a "Repeat" field to verify the password.  (This existed in all previous versions of the program, AFAIK.)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.   Create a new entry or edit an existing entry.
2.   Notice that there is no "Repeat" field.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There should be a "Repeat" field.  Or at least there should be an option in the preferences to enable or disable it.  This is a *very* useful feature as it prevents typos in the password before I save them to my database.  Has caught errors many times for me.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
There is no "Repeat" field.

## Context
[NOTE]: # ( Give us any additional information you may have. )
(There's still an entry in preferences to "Require password repeat when it is visible".  But that doesn't seem to do anything.  Passwords are never required to be repeated.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Ctrl + H to toggle password visibility or click the eye icon

**Comment by therealmarv** [comment]
@droidmonkey in my opinion that's only a workaround and not a fix.

Actual use case I had recently:
I wanted to save a hard to remember password which was only in my mind so far so I had to type it in.
Even with visibility enabled I wanted to keep 101% sure I have typed it in correctly. Now I have to use an external editor to compare if I had typed it in two times correctly.

Please re-add the missing double password field:
![image](https://user-images.githubusercontent.com/1050582/91438401-f8b95500-e873-11ea-9806-d3f5752dfd58.png)

Also this option is now totally useless:
![image](https://user-images.githubusercontent.com/1050582/91438480-15558d00-e874-11ea-8f63-7afb74dc02d2.png)

**Comment by droidmonkey** [comment]
That is an insane niche case

**Comment by DJCrashdummy** [comment]
i don't understand why this **security feature** got removed, although it is/was **optional**?!? :disappointed: 

until now, i thought it was a bug somehow related to #5119 and also because (as already mentioned) the setting still exists in 2.6.1.

**Comment by griga-upjs** [comment]
Exactly like  other keepassxc users, I consider as really annoying bug / missing feature, when I cannot let program check typos. It prevent users to comfortably and safely store passwords from their memory to database - so it actually prevent people from letting manager to manage their passwords - in opposite as was said. You simply cannot use program, while some other people are messing around (much easier to read password from screen as from keyboard).

I like keepassxc really much, but if some features (which are common and good practice for a along time) starts to remove, I think it's time to find some other password manager.

**Comment by griga-upjs** [comment]
New feature request here [#5491 ](5491).

**Comment by griga-upjs** [comment]
Or maybe make the feature optional (totally fine, if it will be disabled by default) - but please do not remove them.

**Comment by igorty** [comment]
> That is an insane niche case. You are using a password manager... let it manage your passwords.

That's for sure not an insane and niche case as you have characterized in crude manner.

@therealmarv described a real use case when there is a need to type password twice in order to make sure that it has been entered correctly. It may be really helpful when a password has been initially created outside of password manager and you just want to save it in.

Or do you think that such cases are an insane and niche case as well?

**Comment by EnKrypt** [comment]
@droidmonkey I think you've missed what the actual issue is.

Even with password visibility being enabled, there is no repeat password field anymore. This is a bug as there is specifically an option under Security settings that expects there to be a repeat password field when the password is visible.

I hope that makes it clear. It's really sad to see that this is still an issue in the latest release. This ticket should be re-opened.

**Comment by droidmonkey** [comment]
That security setting is for when you create a new database or change your database password. There is no bug here.

**Comment by EnKrypt** [comment]
> There is literally zero reason for repeated password.

Even everyone on this thread who want it don't count as a reason I suppose.

Anyway, thanks for clarifying. Perhaps that setting under security can be a bit more specific as it would be very normal for someone to imagine with the current phrasing that it pertains to the password field inside an entry and not for the database.

**Comment by michaelk83** [comment]
I guess the intention is that all passwords should be generated and copy-pasted (or auto-typed)? That would be ideal, but realistically, that's not the case for many users. Requiring users to reveal the plain-text password to check it is not a good solution, since users aren't always alone in the room.

FWIW, in Keepass2Android, there is a repeat field when the password text is hidden. When the text is shown, the repeat field is hidden. I think that's reasonable.

**Comment by DJCrashdummy** [comment]
> Perhaps that setting under security can be a bit more specific as it would be very normal for someone to imagine with the current phrasing that it pertains to the password field inside an entry and not for the database.

1\. yes and 2. that's also why i would rather treat all passwords equally... i see no reason to differentiate. -> a password is a password.

> Requiring users to reveal the plain-text password to check it is not a good solution, since users aren't always alone in the room.

this is **especially annoying**, when working together on some accounts **while** i have to do **screensharing**, but not all of the participants (e.g. assistant) should see the passwords.
i can work around it, because i always check if the login still works before i save edits, but hardly any noob does this (even when creating a new entry)... so we already ended a few times with wrong/mistyped passwords. :disappointed: 

> [...] there is a repeat field when the password text is hidden. When the text is shown, the repeat field is hidden.

IMHO this is most common, and what i would expect from a reasonable program with security of all kinds in mind.

**Comment by JohnLGalt** [comment]
> 
> 
> That security setting is for when you create a new database or change your database password. There is no bug here, fully intentional to have one password field when editing an entry. There is literally zero reason for repeated password. Even keepass original doesn't have password repeat.

Hey, man, not trying to create a fight, just clarifying something:  KP original *does* have repeat.  Both for database PW during db creation:

![KeePass 2 47 db creation 01](https://user-images.githubusercontent.com/7432512/118507627-68ba8480-b6fc-11eb-8fc3-5d7b044357cf.png)

As well as during new entry creation, in a special case - if you have to hide the pw view:

With view enabled there is no repeat:

![KeePass 2 47 db creation 02](https://user-images.githubusercontent.com/7432512/118507719-7ec84500-b6fc-11eb-9086-eb2210c530a7.png)

But if you have to hide it for whatever reason, then repeat is automatically enabled:

![KeePass 2 47 db creation 03](https://user-images.githubusercontent.com/7432512/118507790-8f78bb00-b6fc-11eb-8f42-d65425621291.png)

I just tested with 2.48.1, and it is still there as well.

**Comment by droidmonkey** [comment]
Good point I was wrong re keepass2. But still am not reintroducing repeat password on entry edit. If the passwords don't match please tell me how you can determine where your error is without revealing the password. I'd love to know.

**Comment by JohnLGalt** [comment]
I think that for most people, you don't determine where the error is, you delete and type the whole thing again in both fields.

While this sounds counter-intuitive, it does allows you to keep the test masked, which can be considered a good thing in areas where there might be sketchy security, or cameras, or whatever else paranoid people are worried about.  Obviously this wouldn't stop a keylogger, but anything that could take a visual reference / screenshot would be unable to do so if the PW filed characters are masked all the time.

Heck, there are websites that do it this ancient way - only masked pw field characters, and no option to view the typed characters - so if it tells you that the two fields don't match, you go back and delete both fields and start over.

Definitely not efficient, but it is what it is.

**Comment by michaelk83** [comment]
I'll add to John's reply that the key point of password repeat is _detecting_ the error, not _locating_ it. But ultimately, I agree that people should be moving away from manual passwords anyway.

**Comment by 7usr7local** [comment]
Hi @droidmonkey , while I understand that you consider this feature unnecessary, I wonder whether it did any harm?
Meaning: If some users (including me) request it, but it does no harm, why not keeping / reintroducing it? Maybe optional?
I would very much appreciate if you could elaborate on that - thank you!

FYI:
I consider the check-hidden-passwort feature usefull for following use cases:
- Manual entering passwords in areas where eyes or cameras are directed to your screen
- Easy checking whether you memorized (auto-generated) passwords correctly.
Regarding the latter: Using a pasword manager doesn't mean you don't need to remember passwords. There are situations where you need to know your password from your mind while its conveniant to have a copy in a save place (password manager) in case it slips your mind some day. I think of situations where you can neither use autotype/copy-paste (e.g. public terminals) nor want a password displayed on your screen (e.g. public areas).

**Comment by droidmonkey** [comment]
I've said my piece above. It is ui clutter for obtuse reasons (eg, editing your password during a screenshare?).

**Comment by 7usr7local** [comment]
I still don't see any harm in having an option/switch/toggle (in the preferences) to switch on a feature some people deliberately desire although you (and others) consider it "ui clutter".

**Comment by phoerious** [comment]
The additional option certainly IS UI clutter.

**Comment by greenkaktus** [comment]
Since it's not always possible to generate a password, I'm also missing this feature now. The use-cases where I'm missing it: some Apps on my Smartphone (like the Signal app) do generate passwords themselves when creating a backup and I'm supposed to save the password in a secure place. I used the re-enter password for that use case. Now I'll have to use some external comparison tool to check it. I think it's more trustable to enter it twice than to read from screen to check it again. Too easy to overread something.

Other use-cases are real world passwords like a bike lock, a U-lock, a SIM-card PIN, other PIN-based-cards like Smartcards, license keys printed on a box, etc. Yes, I'm also storing some of those in Keepass and they'll never be auto-generated.

> Good point I was wrong re keepass2. But still am not reintroducing repeat password on entry edit. If the passwords don't match please tell me how you can determine where your error is without revealing the password. I'd love to know. Besides retyping the whole thing there is no way to know if the error is in the first field or the second field. There is really no point to typing it twice when you'll have to look at it anyway to figure out your mistake.

I'd always prefer retyping the whole password before making it visible on screen. Beside from that, one wouldn't have to reveal the password in most of the cases because usually they _do_ match. Without the second password field, one would _always_ have to make it visible to check that it is entered correctly, even if it _is_ already entered correctly.

**Comment by therealmarv** [comment]
Maybe it's time for another fork. Most of the other Keepass variants (e.g. Keepass2Android) think differently about double password entries.
