### ISSUE TITLE
Generator: Maximum password length limited to 128 chars (in Version 2.6.0) instead of 999 (in Version 2.3.*)

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [keepassxreboot/keepassxc#5206]
I used Version 2.3.* on Windows and Linux.

When generating new passwords and customizing the length of the password I did not use the slider because it is limited to 128 chars. I used the text/number-entry field on the right of the slider and typed "999" into it because it was the highest accepted number by that dialog. This works for a lot of online portals.

After an update to Version 2.6.0 the entry field is limited to "128", too.

This lower my security. Please fix this asap.

**Comment by droidmonkey** [comment]
No it doesn't

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> No it doesn't

Very valuable reply.
The entropie is different between 128 or 999 characters.

So what is your argument?

**Comment by droidmonkey** [comment]
That is just simple math and totally irrelevant, obviously the longer the key the more entropy you have (if it is random). The real reason it doesn't matter is because after a certain length it is quite literally IMPOSSIBLE to brute force a password. Currently, that length hovers around 15-18 characters when using only random lower/upper letters and numbers. So yes, a 128 character password is extreme overkill, and anything above that provides absolutely no additional "protection".

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
15-18 is based on low evidence because it is theoretical and without the knowledge of all factors.

We do not know what (e.g. level of CPU power) the goverments have in there basements today or in one year.

It is **theoretical** evident that 15-18 is secure. For how long?
Based on the same "simple math" it is evident that **more** then 18 is **more** secure.
Simple.

Please leave it to the user what level of security is needed.

Technical (for you) it its not a big deal to make that field 999 or more characters long.

**Comment by hueychen27** [comment]
Just combine a bunch of passwords generated.
