### ISSUE TITLE
Auto-type Settings for Groups [UX]

### ISSUE THREAD

**Issue by tentacleofdoom** [keepassxreboot/keepassxc#5217]
Summoning the new Auto-type window to fill things in is neat, once you get used to it, but editing every single entry for Window-Associations is going to take ages.
If you'd consider adding the Auto-Type Settings to Groups, but keep individual settings preferred, a whole 'Browser' group, or 'Gmail' group, or 'Teamviewer' group could be updated to the new system/window association quickly and easily.

**Comment by droidmonkey** [comment]
Not sure what you mean by this, can you explain further?

**Comment by tentacleofdoom** [comment]
Gladly. In order to use Auto-fill (using Microsoft Windows as an example), you used to focus the application and its fields (let's take for example a webbrowser, some website and its login) looked for the entry in KeepassXC, pressed Ctrl+V and it'd run through its Auto-fill settings (usually {Username}{TAB}{Password}{Enter}) and log you in. It'd fill these in, no matter what browser or application you were in.
Now you have to assign windows that a login-entry is applicable to, by going to "Edit Entry -> Auto-Type -> Add a Window Association" option. Then you go to the Window, press a Global Auto-Type shortcut you assigned and then pick an applicable entry from those it shows.
So in order to use the new Auto-Type feature, you'd have to go through each entry individually and add a window association for every login entry you've put into KeepassXC.
If, additionally, you could assign a window association to a group, that is inherited by every entry inside that group (unless that entry has a custom ruleset), that'd be an easier way of associating a lot of entries with multiple windows (i.e. if you have several browsers and their incognito modes, or several programs for which you've got a folder where all the entries are contained).

Much like you can inherit Auto-type from parent group, just for window-associations.

**Comment by vetko** [comment]
Usually Window Associations are specific for each entry: e.g. a `"GitHub"` entry will have `"*GitHub* - Mozilla Firefox"` window association, `"Gmail"` will have `"*Google Mail* - Mozilla Firefox*"` association, and so on.
So in this case, I'm not sure the group level associations would help, only if you usually assign very generic wildcards to your entries (e.g. `"*"`).

I would like to second though, that usually people don't want to spend too much time on details with Window Associations.
Me as well, would prefer, not to have to fiddle around with associations for _each entry in particular_, because:
- they are usually the same, e.g.: `"GitHub"` entry will have `"*GitHub* - Mozilla Firefox"` or just simply `"*GitHub*"`
- most of the time you need to auto-fill them in windows which you might not even expect, e.g.: Firefox is an obvious choice for GitHub, but generally you need to auto-fill it in you IDE, in console, in VirtualBox, etc., in which case you would have to create all these associations
- if you don't want to overcomplicate your life with the above, then you just anyway set `"*"` as the window association for _each_ entry, which then becomes just a boring repetitive task.

**My suggestion would be**: would it make sense to have a (Global) Auto-Type setting which makes **all the entries searchable** for auto-type, even if their window association doesn't mach with anything predefined?

@tentacleofdoom: Would that solve your issue as well?

**Comment by droidmonkey** [comment]
Why not continue using entry level autotype? The keyboard shortcut is Ctrl+Shift+V in 2.5 and above.

**Comment by vetko** [comment]
> Why not continue using entry level autotype?

Entry-level autotype is indeed a solution, but Global autotype is more fancy and fluent in my opinion.
I found the thread you were referring to, let me continue what I have to say there (https://github.com/keepassxreboot/keepassxc/issues/429). Thank you.

**Comment by droidmonkey** [comment]
My comment was directed at the OP, sorry.

**Comment by tentacleofdoom** [comment]
Ha. Never even realized, since I instantly put Ctrl+Shift+V for global autotype hotkey. I'm with Vetko, I like the new style, it flows nicely, but could use a search function, or group window associations.
But now that I've switched global hotkey, that works as it used to, thanks droidmonkey.
