### ISSUE TITLE
Data loss when using syncthing

### ISSUE THREAD

**Issue by Bruceforce** [keepassxreboot/keepassxc#5284]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I lost data on a new entry but could not really reproduce it. Anyways I'll provide steps to what I did, maybe someone has an idea on why this happened. The strange thing is, that the downloaded favicon was indeed still in the db, but the entry was gone. After I recreated the entry (entered exactly the same data) and downloaded the favicon again it appeared twice in the favicon list.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new entry
1. Enter username, passwod (generated) and url
1. Click on icon and download new icon
1. Save the entry
1. Close the database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Entry should not be gone after saving.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Entry was gone, but favicon was still there (modification date also changed)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This would imply that your database did not save between step 4 and 5. Favicons are stored immediately in the database causing a save when downloaded.

**Comment by Bruceforce** [comment]
I recommended KeePassXC to my mother who told me she added a new entry and it was also gone the next time she opened KeePassXC. So I think she was experiencing the same problem. 

Is there a setting in "File management" that may reduce the risk of loosing new entrys? Maybe disable the automatic save after every change or something like this?

Further information: I'm using syncthing to sync my files across devices. But I modified the KeePass database file just on one system and the syncthing logs also reported no change from syncthings side to my file.

**Comment by droidmonkey** [comment]
If you can reproduce this without syncthing in the middle please let us know.

**Comment by Zvezdin** [comment]
I was thinking of filing a new issue but maybe this is the same problem. I incur data loss on sync, silently, which is very very critical. Steps:

1. Encrypt database with master password + Yubikey. 
2. Sync via a cloud provider and open same database from two machines.
3. Modify database on machine A and save it. Let cloud sync client sync the new file.
4. KeePassXC on machine B will detect the file update, and try to reload the database.
5. Machine B will fail doing so, because the Yubikey is not inserted. Instead of displaying an error message or prompting for Yubikey entry, KeePass will ignore the new database update and will include a "*" character in its status bar, prompting the user to save unsaved changes (of which there are none). These unsaved changes is actually the older version of the database, and once a user saves this then boom, the new modifications from machine A are wiped out. Ouch.

**Comment by droidmonkey** [comment]
Captured the Yubikey issue in a new issue.
