### ISSUE TITLE
-WITH_XC_UPDATECHECK=OFF should completely remove check for updates feature

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#5288]
Fedora co-maintainer here.
`-WITH_XC_UPDATECHECK=OFF` disables automatic updates check at KeepassXC startup. It would be great if that options removes menu entry `Help-> Check for updates`, because Fedora packages updates are handled by we maintainers.
Often we get tickets opened by users claiming that they found out that a new KXC version is available by using that menu button, but sometimes we decided to not push a new update in stable repository, like the current 2.6.0 version

**Comment by droidmonkey** [comment]
Good point, I thought it did that perhaps it got merged out at some point.

**Comment by Colfenor** [comment]
I just checked the behavior of the current develop branch, I can confirm that the menu entry is not visible with the compile flag set to `-WITH_XC_UPDATECHECK=OFF` 

implemented here:
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/MainWindow.cpp#L504#L516

since commit:
https://github.com/keepassxreboot/keepassxc/pull/2968/files#diff-eadbad473622c6ca681370585fb4d9e4R375

**Comment by droidmonkey** [comment]
I knew I implemented it!

**Comment by Germano0** [comment]
Is this patch included in 2.6.1?

**Comment by Germano0** [comment]
https://github.com/keepassxreboot/keepassxc/issues/5350
