### ISSUE TITLE
Password Generator - Unable increase the password size more than 128 characters

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#5315]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have the problem with version **2.6** of keepassXC to generate passwords with more than **128** characters, due to the fact that I handle for security longer lengths (between **250** to **999**).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open the Password Generator
2. Go to the password length field and enter the size.
3. Just let you write up to the number **128**.
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Before I could create passwords password generator with a size of up to **999** characters.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Now, I can only create passwords with the password generator with a size of up to **128** characters.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Now I can not update the entries with passwords created to the length that was previously, because the password generator has the limit of **128** characters. I would appreciate it if you take into account this feature again where the generator could create passwords of up to **999** characters.

_Thank you very much and best regards._

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versión **2.6.0**
Revisión: **0765954**

[NOTE]: # ( Pick choices based on your environment )
Qt **5.15.0**
Modo de depurado deshabilitado.

Sistema operativo: openSUSE Tumbleweed
Arquitectura de CPU: x86_64
Núcleo: linux **5.8.0-1**-default

Extensiones habilitadas:
- Autoescritura
- Integración con Navegadores
- Agente de SSH
- KeeShare (compartir firmado y sin firmar)
- YubiKey
- Integración de servicio de secretos

Librerías criptográficas:
 libgcrypt **1.8.6**

**Comment by piegope** [comment]
Hello

Excuse my insistence, but is it possible that the password generator in KeepassXC can create passwords with lengths greater than 128, if there are other generators that allow it (in CLI: pwgen, in GUI: keepass)? I know that for most of the scenarios a length handling of 128 is sufficient, but I think that it should not be limited, since in some cases like with LUKS you can use passwords with lengths of 512 characters.

 A greeting

**Comment by phoerious** [comment]
There is absolutely no point in generating passwords that long. Even if LUKS allows passwords that long, there is nothing to be gained, assuming the KDF/hash function is somewhat decent (which in the case of PBKDF2/bcrypt and Argon2/Blake2 we can).

The encryption is done with AES using a 128-bit block size and a 128-256-bit key. That is, your search space for guessing the korrekt key is 2<sup>256</sup> (you need half that on average if guessing randomly). A 512-character ASCII password with only numbers, uppercase and lowercase letters would on average need 62<sup>512-1</sup> guesses. That's somewhere in the order of 10<sup>915</sup>. The atoms in the universe are estimated somewhere at 10^<sup>82</sup> for comparison. So there is absolute no point in trying to guess that password when it is so much easier to just guess the transformed 256-bit AES key instead. With 8 billion guesses per second, you'd be done in about 2*10<sup>59</sup> years instead of  3*10<sup>898</sup>. Easy.

**Comment by glubsy** [comment]
I also face this issue. I strongly suggest increasing the limit back to what it was before. 

In some cases, long passphrases of 512 characters are mandatory in cases where there is no hash being applied to them, for example in the case of a plain dm-crypt volume (no LUKS header). 

Please remove this arbitrary limitation.

**Comment by phoerious** [comment]
Did you even read my response? There is no way you need 512-character passwords unless you are trying to create a one-time pad.
