### ISSUE TITLE
Visual bug when creating a new entry

### ISSUE THREAD

**Issue by 0xNeffarion** [keepassxreboot/keepassxc#5371]
## Overview
GUI Visual bug while creating a new entry.    
There is a "Line" which looks like a scroll bar in the middle of the UI when trying to create a new entry in a database.  

![image](https://user-images.githubusercontent.com/6073640/91892064-871d4480-ec81-11ea-9613-a3a6580bc46c.png)

## Steps to Reproduce  
1. Have a database open (Dark theme)
2. Click on new entry

## Context
This "line" is visible until I resize the window. However, if I open the password generator while having the new entry open the line will appear again. 

[Video of this happening](https://imgur.com/a/PTDHJlu)

This only happens when creating an entry and while in Dark theme. Creating a group does not have this issue.

## More info

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by 0xNeffarion** [comment]
Seems to have fixed itself after a reinstallation. Not sure what it could be

**Comment by mlippert** [comment]
I'm seeing this too, on that dialog, create or edit. However it goes away if I resize the dialog. It is happening on my system running Linux Mint 18.3 KDE (so an older distro). I have Keepassxc installed on Kubuntu 18.04 as well and I don't see it there.
I've got at least 1 other visual oddity, I don't see a cursor in the edit controls. I've just been chalking it up to my KDE settings on my system.
If you want more system info let me know. Otherwise I'm just adding the comment here to say that this has been seen elsewhere.
