### ISSUE TITLE
Notes section in the Password Entry Widget should be fixed width.

### ISSUE THREAD

**Issue by grim210** [keepassxreboot/keepassxc#540]
I have a lot of information in the notes field that is better served by a monospace font.  Since the widget is plain text anyway (as opposed to rich text with bold/italics/highlighting/etc), it makes more sense in my opinion for it to be fixed width.

**Comment by highend** [comment]
Please add this...
I store belonging sensitive information in the notes field and it's incredible annoying that it uses a non-monospaced font here...

A simple option in the preferences
```
[x] Use monospace font in notes field
```
With default = off

could please all users

Thanks!

**Comment by Throne3d** [comment]
This looks solved in #1124

**Comment by tomhundt** [comment]
FYI:  As of right now (KeepassXC 2.3.1), the Notes field is _not_ monospaced on Mac (OSX 10.13.3), though the password one is.

**Comment by highend** [comment]
It is neither on Windows 8.1 (more specifically: Server 2012 R2 U3)...

**Comment by b0ssi** [comment]
Since this has not been addressed (yet) and `v2.3.0` has been released, should this get removed from the [`v2.3.0` milestone](https://github.com/keepassxreboot/keepassxc/milestone/3) and possibly get re-scheduled?

**Comment by Tux** [comment]
I want fixed fonts too *And* have an option to make notes the default tab

**Comment by ba32107** [comment]
Making the notes the default tab is not necessary anymore after https://github.com/keepassxreboot/keepassxc/issues/1564 is closed.

I am working on the monospaced font option.

**Comment by droidmonkey** [comment]
IMO the font option should be part of a larger font choice.

**Comment by ba32107** [comment]
Agree, that would be better. However, in order to address this issue, it has to be a per-field setting - surely the users wouldn't want the font to be monospaced all over in the application. 

There is already #621, but that only tracks the font size. I see three options now:
- Roll this issue out as it is with the monospace option (it's more or less done in my repo), and track the future "Style" tab in another one
- Change #621 to incorporate the changes you mentioned and close this (might slow down development on that issue which has strong demand)
- Change this issue to add the changes you mentioned (in that case I'll throw away my changes regarding only the monspaced setting)

How do you want to proceed?

**Comment by droidmonkey** [comment]
We should create a new issue for the style tab. Go ahead and make the notes monospace and we'll see how they look.

**Comment by ba32107** [comment]
Thoughts?

![Screenshot from 2019-06-25 20-19-21](https://user-images.githubusercontent.com/26036493/60126801-afa8d500-9786-11e9-9bdc-a37c538b6b89.png)
---------
![Screenshot from 2019-06-25 20-19-37](https://user-images.githubusercontent.com/26036493/60126803-afa8d500-9786-11e9-9bd6-77ff900db6cc.png)
---------
![Screenshot from 2019-06-25 20-19-53](https://user-images.githubusercontent.com/26036493/60126805-afa8d500-9786-11e9-8c7e-fca34a0003f2.png)

**Comment by droidmonkey** [comment]
Yes that actually looks great, lets run with it
