### ISSUE TITLE
Yubikey is not recognized right after boot

### ISSUE THREAD

**Issue by ibahnasy** [keepassxreboot/keepassxc#5614]
## Overview
On Linux, KeePassXC cannot detect Yubikey righter after boot and it has to be removed and re-plugged to work.

## Steps to Reproduce
1. Boot the computer
2. Insert the Yubikey before login to the session
3. Login to start a session, for example GDM
4. Start KeePassXC and try to unlock the database by clicking on "Refresh" to detect the hardware key.

## Expected Behavior
Yubikey should be detected 

## Actual Behavior
The Yubikey won't be detected at all unless it's is removed and re-plugged, now it can be detected.
This behavior isn't new, it has been there from previous versions as well.
Other programs (such as Yubikey Authenticator) can detect the key without re-plugging it.

KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: gnome-shell
Windowing System: X11

**Comment by droidmonkey** [comment]
Not much we can do about this, we detect the key the same way the yubikey programs do.

**Comment by CerebralFreeze** [comment]
Hey iba,

Does Yubikey really do anything anyway?  I purchased it and tried it and it's a marketing scam to me.  It's not a scam in the sense that they are lying but it _effectively_ just stores a password on like a USB drive.  There is really nothing special about it.

If at all, it's an annoyance since you have to press the key every time you log in.  _And_, there is a good chance that you might accidentally erase the password on the key by mistake.

Don't you agree?

> ## Overview
> On Linux, KeePassXC cannot detect Yubikey righter after boot and it has to be removed and re-plugged to work.
> 
> ## Steps to Reproduce
> 1. Boot the computer
> 2. Insert the Yubikey before login to the session
> 3. Login to start a session, for example GDM
> 4. Start KeePassXC and try to unlock the database by clicking on "Refresh" to detect the hardware key.
> 
> ## Expected Behavior
> Yubikey should be detected
> 
> ## Actual Behavior
> The Yubikey won't be detected at all unless it's is removed and re-plugged, now it can be detected.
> This behavior isn't new, it has been there from previous versions as well.
> Other programs (such as Yubikey Authenticator) can detect the key without re-plugging it.
> 
> KeePassXC - Version 2.6.2
> Revision: [e9b9582](https://github.com/keepassxreboot/keepassxc/commit/e9b9582817affd7936d4b6b07c22c482d7d0d3a6)
> 
> Operating System: Arch Linux
> Desktop Env: gnome-shell
> Windowing System: X11

**Comment by charlie89** [comment]
Hi, i have the same issue since about 2-3 years.
The Yubikey won't be recognized after boot until it is removed and plugged in again. For me this only happens when the Yubikey is plugged into a USB hub, which is integrated into my monitor and my Apple aluminium keyboard (it has a USB port on both sides).

As a workaround i configured my system to run the following commands via an autostart script: 
```bash
echo -n "0000:00:14.0" | tee /sys/bus/pci/drivers/xhci_hcd/unbind
echo -n "0000:00:14.0" | tee /sys/bus/pci/drivers/xhci_hcd/bind
```
This basically just disconnects the whole USB3 controller (the one on the mainboard) and then reconnects it, then KeepassXC recognizes the Yubikey instantly. Just make sure the Yubikey (or the USB hub the Yubikey is connected to) is on the specified USB3 controller (the "0000:00:14.0", you can pretty easy find it with `dmesg | grep Yubikey`). If you autostart KeepassXC, you may need to delay it for a few seconds to be sure the USB devices are already connected with i.e. `/usr/bin/bash -c "/usr/bin/sleep 4 && /usr/bin/keepassxc"`.

Sidenote: On Gnome 3.38 with X11, USB keyboard connected to the specified USB controller and using XKB keyboard options you may stumble across [this Gnome bug](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/555).

**Comment by ibahnasy** [comment]
I found that the issue is about udev rule that doesn't get triggered by the first insertion.
If you executed: "sudo udevadm trigger", it will make the key visible and work without re-plugging it.
