### ISSUE TITLE
Hidden and minimized KeepassXC cannot be re-opened using gnome shell and keyboard

### ISSUE THREAD

**Issue by philipreimer** [keepassxreboot/keepassxc#5776]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
A hidden and minimized KeepassXC cannot be re-opened using gnome shell and keyboard.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable the following options in in KeepassXC options
   - "only start one KeepassXC instance"
   - "minimize instead of shutting down program"
   - "show tray icon"
   - "hide window when minimized"
2. Press `Super` key (usually the windows key), type `kee` so that KeepassXC is selected. Press `Enter` and KeepassXC should open.
3. Press `Alt+F4` to hide KeepassXC window again
4. Immediately afterwards repeat step 2.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC window should re-appear

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. Mouse pointer turns into some kind of spinning ball.

If you wait around 10 seconds or so between step 3 and 4, then KeepassXC window re-appears.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux
Desktop Env: Gnome 3.38.2
Windowing System: X11

**Comment by droidmonkey** [comment]
So it works if you wait a period of time?

**Comment by philipreimer** [comment]
> So it works if you wait a period of time?

Yes. My mouse pointer turns into some kind of spinning ball / busy indicator. Once the mouse pointer returns to normal state - usually after around 10 seconds - KeepassXC window re-appears using the method in step 2 above.

**Comment by philipreimer** [comment]
Actually, I just noticed that whenever I open KeepassXC using the method described in step 2, KeepassXC itself shows a busy indicator for a while - see 
![keepassxc-busy](https://user-images.githubusercontent.com/5737222/101068778-6ffc3480-3599-11eb-8164-c8c2c116ad8d.png)

**Comment by droidmonkey** [comment]
Then this isn't a bug, this is your system taking a longer time to actually start KeePassXC.

**Comment by philipreimer** [comment]
The thing is that KeepassXC seems to be working fine. I can re-open the KeepassXC window without problems using the tray icon and clicking the first entry `Show/hide window`. Even if KeepassXC and my mouse pointer show this busy indicator: ![keepassxc-busy](https://user-images.githubusercontent.com/5737222/101068778-6ffc3480-3599-11eb-8164-c8c2c116ad8d.png)

It's just not working if I use the keyboard to do it:
> Press `Super` key (usually the windows key), type `kee` so that KeepassXC is selected. Press `Enter` and KeepassXC should open.

**Comment by droidmonkey** [comment]
This is not something we are going to investigate or fix. Seems very specific to your use case/system.

**Comment by nitinab** [comment]
I can reproduce this behavior, but it doesn't seem to be KeepassXC specific. Also, the spinner/busy indicator is from application launch, rather than when you close the app. So my guess would be this is related to how Gnome launches applications or there's a delay built in Gnome launcher to prevent multiple app launches, although I couldn't verify that.  I was also able to reproduce this with Slack. In short: 

- launching the app from the command line works just fine, even for within short intervals.
- launching using the .desktop app specification from Gnome start menu starts the apps and a spinner for 5-10 seconds.
- closing the app and relaunching using the Gnome start menu doesn't work while this spinner is active.
- you can still activate/launch the app from the command line while the spinner is active.
- you can launch the app, wait for the spinner to stop, then close the app and launch immediately afterwards using Gnome start menu
