### ISSUE TITLE
Make TrayIcon on MacOS smaller

### ISSUE THREAD

**Issue by lqiang79** [keepassxreboot/keepassxc#6074]
## Current Tray Icon on MacOS Big Sur is too big.

[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/750346/106957241-10a4d700-6738-11eb-918a-59fdc9e84f76.png)
As you can see. The Trayicon is a bit more oversized than other application and system icons. 
![image](https://user-images.githubusercontent.com/750346/106957993-0a632a80-6739-11eb-92e3-cc807e8db380.png)

Make the TrayIcon has a commer size like other applications on the MacOS, it will shows better intergration to the UX.

**Comment by varjolintu** [comment]
Catalina doesn't seem to have this problem.

**Comment by phoerious** [comment]
This is a problem everywhere, not just an macOS and I really don't understand why. Every tray seems to have different requirements for icon sizes and paddings. Instead of just taking an icon without any padding and fitting it properly, the tray makes the appearance is completely unpredictable. Sometimes it's just right, sometimes it's too large and needs an arbitrary amount of padding. This is extremely annoying and near-impossible to get right.

**Comment by droidmonkey** [comment]
This should be a bug filed against qt imo

**Comment by droidmonkey** [comment]
Qt bugs:
https://bugreports.qt.io/browse/QTBUG-88600
https://bugreports.qt.io/browse/QTBUG-90370

Appears to be fixed in Qt 6.1.0 which isn't a linear upgrade path for us at this time.
