### ISSUE TITLE
Can't pin KeePassXC to panel (taskbar) in Linux Mint 20.1

### ISSUE THREAD

**Issue by sergeantbl** [keepassxreboot/keepassxc#6090]
## Overview
Hey guys, I have a simple issue. I'm using the AppImage with the version 2.6.4 and I am not able to pin KeepassXC to the panel (taskbar). 

## Steps to Reproduce
1. Open the AppImage
2. Right-click on KeePassXC icon in panel 
3. -> No option "pin to panel" shows up

## Expected Behavior
Usually, there is with right-click the option "Pin to panel" so that you can start from the panel. Currently, I've put it on my desktop to run it.

## Actual Behavior
-> No option "pin to panel" shows up
-> instead there is the option "Create Shortcut" but this doesn't trigger any action.
(see first picture)

## Context
I was having this issue all the time. Since I've installed it (started with 2.6.2). I'm also using the AppImage of the email client Tutanota and and there it works. (see second picture)

[NOTE]:
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 20.1
CPU architecture: x86_64
Kernel: linux 5.4.0-65-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # 
Operating System: Linux Mint
Desktop Env: Cinnamon

**How it's currently with KeePassXC**
![how its currently with KeePassXC](https://user-images.githubusercontent.com/78814465/107406924-4c111e00-6b09-11eb-823e-399e0f455958.png)

**How it should be (with Tutanota)**
![How it should be_with Tutanota](https://user-images.githubusercontent.com/78814465/107406938-4f0c0e80-6b09-11eb-949c-740ea5b6b213.png)

**Comment by FaMux** [comment]
Same for KDE, i am able to pin but cannot start KeePassXC - Plasma is complaining 
> Unable to run the command specified. The file or folder **keepassxc** does not exist.

The problem might be insight the AppRun.wrapper script - KPXC is called inside the wrapper script with `exec keepassxc "\$@"`.
I tried calling KPXC with `exec "$APPDIR/keepassxc" "\$@"`  and Plasma is complaining again
> Unable to run the command specified. The file or folder /tmp/.mount_KeePasx9mZlf/keepassxc does not exist.

which is the path of mountpoint of the SquashFS image contained in the AppImage + keepassxc.

Tutanota is doing the same (exec "$APPDIR/tutanota-desktop"), and i get the same error
> Unable to run the command specified. The file or folder /tmp/.mount_tutanota9mZlf/tutanota-desktop does not exist.

I think it looked like it worked for tutanota, because they have the option _minimize instead of exit_ as default activated. Applying the described patch for KPXC and activating **minimize instead of exit**, and everything works fine, unless you reboot - so that does not solve the problem.

A easy workaround is manually creating a _Link to a Application_ / desktop shortcut which is pointing to the appimage file.

The nextcloud appimage is "pin able", but they to do not use a custom AppRun and AppRun.wrapper script - AppRun is only a symlink to usr/bin/nextcloud inside the appimage. KPXC need a wrapper script to get cli and proxy working with the appimage...

**Comment by droidmonkey** [comment]
Going to close this as won't fix. Thank you for the analysis @FaMux
