### ISSUE TITLE
Delete key do not delete the entry

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#6153]
## Overview
Using the delete key do not delete the selected entry. Was tested on MacOS.

## Steps to Reproduce
1. Select an entry
2. Press the "delete" key

## Expected Behavior
Should delete (move to trash) the entry as indicated in the shortcut in the menu:
![Screenshot 2021-02-19 at 19 20 56](https://user-images.githubusercontent.com/164074/108545102-a2d7de00-72e7-11eb-8d13-e866562c9b46.png)

## Actual Behavior
Nothings happens.

## Context
KeePassXC - 2.6.4
Operating System: macOS

**Comment by droidmonkey** [comment]
Does it work if you press backspace?

**Comment by droidmonkey** [comment]
Does it work if you press backspace?

**Comment by droidmonkey** [comment]
Does it work if you press backspace?

**Comment by gagarine** [comment]
No :/. I tried different combination too using CMD/CTRL I was not able to delete a selected entry with the keyboard.

**Comment by droidmonkey** [comment]
Works fine for me on macOS 11.1

**Comment by gagarine** [comment]
That is super strange. I will try another machine with another account.

**Comment by gagarine** [comment]
I confirm, this work on other Mac.

**Comment by JambonBeurreVodka** [comment]
Same issue for me. Super annoying, I have to right click, click "Delete entry", then click "Move" to confirm. 

Macbook pro 11.2.3
KeepassXC 2.6.4

**Comment by droidmonkey** [comment]
It's not our application.

**Comment by JambonBeurreVodka** [comment]
Same issue for me. Super annoying, I have to right click, click "Delete entry", then click "Move" to confirm.

Macbook pro 11.2.3
KeepassXC 2.6.4

I tried backspace and different combinations, nothing works

**Comment by JambonBeurreVodka** [comment]
(deleted previous message by error)

Ok yeah it's good there's a delete button at least. Here's the UI on my mac : 

<img width="1422" alt="Screenshot 2021-03-14 at 21 46 50" src="https://user-images.githubusercontent.com/80606161/111082020-d389ec80-850e-11eb-866c-b69aa59a2f17.png">

**Comment by droidmonkey** [comment]
You can show icons from the application settings

**Comment by am1444** [comment]
I got the same thing on macOS 26.0.1. I managed to make a temporary fix on macOS' part by:

1) going to macOS System Settings >> Keyboard >> Keyboard Shortcuts >> App Shortcuts
2) Clicking "+"
3) Setting "Application" to "KeePassXC.app"
4) Setting "Menu title" to "Delete entry..."
5) Setting "Keyboard shortcut" to a different keyboard shortcut (personally I set it to cmd+\)

Also, from my observations, "Keyboard shortcut" cannot be set to "cmd+delete" or "delete". Maybe macOS doesn't like delete being used in keyboard shortcuts because [insert Tim-foolery here].
