### ISSUE TITLE
OSUtils is used before qApp is initialized

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#6169]
## Overview
After #6030 was merged we introduced a crash on Linux where `osUtils->canPreventScreenCapture()` is being called in `src/main.cpp` before `Application app(argc, argv);` initializes qApp which is used in the singleton pattern of OSUtils to initialize the class on first call.

I suggest we make it an ifdef instead of using OSUtils as the condition whether we can prevent screen capture or not cannot change during runtime anyway.

Additionally to prevent this from happening silently in the future we should check qApp in `*Utils::instance()` before passing it along.

**Comment by smlu** [comment]
I'm just trying to understand what's going on here. I'm guessing the crash is caused due to uninitialized `QApplication` when calling either of these 2 static functions in [NixUtils.cpp#L66-L67](https://github.com/keepassxreboot/keepassxc/blob/61b85183f938498142a921db11dbeac9a876b3d4/src/gui/osutils/nixutils/NixUtils.cpp#L66-L67) ?

To avoid introducing new macros a simple solution would be to move this if statement in [main.cpp#L82-L84](https://github.com/keepassxreboot/keepassxc/blob/a5094dd3eaaa5e82220108ca86d062381b4eb300/src/main.cpp#L82-L84) after `Application app(argc, argv)`. 
Another solution is to declare `canPreventScreenCapture` as `static` function and define return value for each platform there. And then define if statement in main as `if (OSUtilsBase::canPreventScreenCapture())...`.

**Comment by hifi** [comment]
I created #6177 with a simple change of initializing Application before it gets to building the parser arguments.

Maybe it's fine we assume qApp exists and ensure we initialize it as the first thing in our main.
