### ISSUE TITLE
Find and remove duplicate entries

### ISSUE THREAD

**Issue by blub4747** [keepassxreboot/keepassxc#6170]
Hello community,
Very nice feature to merge additional different databases into one.
However I did notice though that the second database is just being added at the end of the first one.
Which leads to tones of duplicate entries

Is there a feature to search  databases for duplicate entries ?
If not could that  be please be included for the future ?
Thx,blub4747

**Comment by droidmonkey** [comment]
Discussed already please search the issues.

**Comment by mmahmoudian** [comment]
@droidmonkey I'm having trouble finding any issue related to this matter to which this one is duplicate of. I have only managed to find [this answer in the discussions](https://github.com/keepassxreboot/keepassxc/discussions/8420#discussioncomment-3500084) which is definitely not helping because:
1. lots of manual work and eye-balling
2. "modification date" column is not a good measure

I personally would have liked if keePassXC while merging two databases ( A->B ) was:
1. adding anything in A that is not in B
2. ignoring duplicates: those that other than the date fields, they are 100% identical in all other fields
3. help in merging by either of:
    3.1. updating the entries in B that have a newer version in A
    3.2. asking what to do and how to merge

Therefore, imho this feature request have merit and I would be thankful if it can be opened again :)

-------

Some related (but not the same) issues that I found:
- #1152
- #2202
- #9143

**Comment by droidmonkey** [comment]
I know it's confusing to think there must be a problem when multiple entries have the same information. Some may even be exactly the same. However, in the KeePass world, the only thing that matters when merging is UUID and Modified Date. Adding a feature to ask the user what to do with seemingly duplicate entries (but not the same UUID) could be useful if you tend to merge from totally unrelated sources. It could also be incredibly annoying (suppose you'd want an ignore feature) if you know they are duplicates.
