### ISSUE TITLE
Add instructions to build the browser extensions

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6182]
I've followed the instructions to compile KeePassXC, but for the browser extension, I need to trust what's been uploaded to Mozilla/Chrome Store.

**Comment by droidmonkey** [comment]
You can't build your own without invalidating the extension ID. The correct ID is needed for native messaging. You can hack that with the json config files but it gets complicated. For production use just use the store versions. They are controlled by us and wouldn't work anyway if they were invalid versions due to the ID matching requirement.
