### ISSUE TITLE
MacOS menubar doesn't work sometimes

### ISSUE THREAD

**Issue by chessgriffin** [keepassxreboot/keepassxc#6234]
After minimizing (by clicking small yellow circle in upper left corner) KeepassXC 2.6.4 on a M1 MacBook Air on Big Sur 11.2.2, sometimes the menubar is not functional after I maximize the app.  I can work around this by opening KeepassXC and focusing on another app window and then switching back to KeepassXC.

Possibly related - normally on MacOS when you minimize an app, a small black dot appears under the dock icon.  However when I minimize KeepassXC, the small black dot disappears.  It's almost like KeepassXC quits rather than minimizes and then when it reopens, the menubar is not functional until I do the workaround.

**Comment by droidmonkey** [comment]
I am pretty sure this is a Qt bug.

**Comment by chessgriffin** [comment]
Yeah makes sense, thanks.

**Comment by phoerious** [comment]
I think that's because we're converting the app to a background app so get rid of the Dock icon when minimise to tray is enabled. I wonder why the menu is still there at all in that case.

**Comment by chessgriffin** [comment]
It looks like if I uncheck "Hide window to system tray when minimized" then the menu works after I maximize the app.

**Comment by enkeys** [comment]
It must be QT related bug. Today happens to me on Linux with Qt 5.15.2. I'm really not sure what conditions caused it.  (KeePassXC 2.6.4)

**Comment by mpas97** [comment]
Copy of https://github.com/keepassxreboot/keepassxc/issues/5617

**Comment by georgesnow** [comment]
I believe this relates to the method being used for toggleForegroundApp

The method being using is for modifying the process type as opposed "activating" or showing the windows for the app itself. 

Generally, if you want just "menubar app" (status bar item is api name) so there is no dock icon shown or menu bar options "File, Edit, ..."  You change (transform) the app to be UIElement and have just menu bar (status bar icon in the top right) be shown (yes confusing terms). 

FastScripts would be example of this type of app. And when you open a window there is no menu bar or dock to interact with just windows.

I haven't quite followed all the logic flow in the code. It seems this method for transform is being used for the minimize to system icon preference. 

The menu bar lock occurs if you minimize KPXC and active the app via Spotlight, Alfred, from applications folder because the app has be changed to a UI Element app so the menu bar is disabled. 

Technically, if you change this it is rather straightforward should resolve this bug, but also allow for adding hot key to show KPXC in another issue.

**Comment by droidmonkey** [comment]
I think you are 100% correct, that is a smoking gun. Worth a test, I don't even know why that is there... perhaps related to hiding from the Dock tray.

**Comment by georgesnow** [comment]
I think the solution would be to use NSApplicationActivationPolicyAccessory 

And you would use an observer for 

NSWindowDidResign (Key and Main) Notification 
(Not sure if need both or just main)
And the window would be defined as 
NSApp.mainWindow

with a selector using [NSApplication.shared.application hide:nil]

**Comment by droidmonkey** [comment]
I figured this out, what we are seeing is the single instance feature bringing the application to the foreground. The function called to do that does not actually call the toggleForegroundApp function. I added that call and everything works properly now.

**Comment by georgesnow** [comment]
Nice quick question how come you decided to use NSApplicationActivationPolicyProhibited

instead 

NSApplication.ActivationPolicy.accessory

The prohibited api means the app can’t have windows or dock icon. The idea is to be able to activate the window but not have dock icon correct?

**Comment by droidmonkey** [comment]
Cause I tested both and prohibited made it work

**Comment by georgesnow** [comment]
Hmm ok. 

Cause I believe when using prohibited those windows for autotype will be blocked from activating. 

https://developer.apple.com/documentation/appkit/nsapplication/activationpolicy/prohibited

“ The application doesn’t appear in the Dock and **may not create windows or be activated**” (my emphasis added)

But  I will test it out cause maybe it works for this case.

**Comment by droidmonkey** [comment]
It likely doesn't matter because the only time it is in prohibited state is when it is hidden to the tray icon. Whenever a popup window is created, we raise the main window and thus enter into regular state.

**Comment by droidmonkey** [comment]
Thank you for bringing this up because you were correct, the prohibited state causes the unlock, autotype, and browser dialogs to fail. I found an elegant fix though, pushing it to the PR now.

**Comment by georgesnow** [comment]
Awesome
