### ISSUE TITLE
Pinned icon loses icon after MSI upgrade install

### ISSUE THREAD

**Issue by xpusostomos** [keepassxreboot/keepassxc#6242]
## Overview

KeepassXC is the only WIndows program I've ever seen that seems to lose its identity on upgrade. That is, if you have it in your taskbar.. after an upgrade the icons goes blank and you end up having to remove it from the task bar, add it again, and move it to its original location.

As an aside, the Android version also was losing its identity on every upgrade. That is, its Android entry point name contained some sort of hash value that changed on every upgrade. This broke a lot of things, for example, custom icon packs that had a KeePassXC icon. Don't know if this was ever fixed, I eventually gave up on it.

## Steps to Reproduce
1. Add to Windows taskbar.
2.  Upgrade.
3. Observe the old taskbar icon is broken.

## Expected Behavior
The upgrade should leave your icons intact.

## Actual Behavior
Taskbar icon broken.

KeePassXC - Kind of not relevant since it happens on every upgrade. Including the most recent.
Revision: REVISION

Operating System: Windows... (And Android!)

**Comment by droidmonkey** [comment]
We don't have an android app. Also I fixed this a long while ago on the windows installer.

**Comment by droidmonkey** [comment]
It was precisely this code change that fixed the problem: https://github.com/keepassxreboot/keepassxc/pull/3296

That was two years ago!

**Comment by xpusostomos** [comment]
Well.. if you fixed it 2 years ago, I don't know why I saw it on the 2.6.4 upgrade.

**Comment by xpusostomos** [comment]
I just upgraded another machine to the latest version.. same problem. Every upgrade I've done for years on every one of half a dozen machines I have access to has shown the same problem.

**Comment by droidmonkey** [comment]
OK I just reproduced this

**Comment by phoerious** [comment]
I have seen the same thing from time to time with other applications such as the JetBrains products.

**Comment by xpusostomos** [comment]
I just installed 2.6.6 and now the installer auto launches it with a blank icon in the old spot where the icon was. When I exit the program, instead of leaving the vestigial blank icon, I get a little popup saying "this app has disappeared, can I remove the icon". Then I have to launch it again, pin it again, and move it again to where it belongs.  This is not really an improvement, this is just as annoying.

**Comment by droidmonkey** [comment]
Blame windows for being bat shit stupid when it comes to Taskbar icons. Have no idea why it's happening. And yes, this happens to a lot of applications when you pin them to the Taskbar. The easy fix is to unpin it and pin it again while the app is running.

**Comment by droidmonkey** [comment]
Looks like the might be a solution https://stackoverflow.com/a/33402698

**Comment by xpusostomos** [comment]
I'm certainly no expert on Windows installs, I've never gone down that rabbit hole...  but... why can't the installer... when upgrading... just overwrite .exe and .dll files in c:\Program Files\KeePassXC without getting Windows involved at all?

**Comment by JohnLGalt** [comment]
The same reason that a lot of programs that have access to network resources / the Internet will be forced to re-authenticate through the Windows Firewall (that stupid little popup asking you if you want to allow the program to have access to 'blah blah blah' over 'xyz connection') - because something has changed, and the average user doesn't pay enough attention, so the OS has to prompt them.

That, couple wit the fact that the 'standard' / currently adopted model for MSI installs is to use the 

```
<InstallExecuteSequence>
  <RemoveShortcuts>0</RemoveShortcuts>
</InstallExecuteSequence>

``` 

As part of the installer script causes this.  It's _technically_ to protect the idiot users who click on everyting and install everything they see without reading anything - but I don't think M$ published the workaround for the taskbar icon directly, probably other than buried deep within their Docs on how that code for the install script works.

Think about what you're asking for.  You want direct actionable file replacement for your programs without Windows involved.  So, I can write a script that, for all intents and purposes, you only encounter when you happen to have a web browser open and view my 'mock' advertisement at any given website.  Now, the script downloads file parts in the background, in such a way that Windows doesn't see it as an actual executable file.  Then, after all the parts are downloaded, it is assembled together into an actual file, and the script then replaces a file that normally exists in the system with the fake file, and because Windows isn't watching, *poof* I now have access to your system because the file is actually a secret keylogger.  Or Trojan.  Or Backdoor.

Sound familiar?

**Comment by droidmonkey** [comment]
Meanwhile, I figured this out, will be PR'd with other msi fixes. The stackoverflow code is actually wrong (go figure), you need to do `<RemoveShortcuts Suppress="yes"/>`
