### ISSUE TITLE
Font size in notes too small

### ISSUE THREAD

**Issue by Mourick** [keepassxreboot/keepassxc#6286]
I like to adjust the font size in notes
actually font size too small
last keepass xc version
windows 10 20h2

**Comment by droidmonkey** [comment]
Screenshit please. The font size should be the same for every field.

**Comment by rioser** [comment]
I second this suggestion. I've been using KeePassXC for only a couple of days but since the software is so great, I've already started to use it for extensive notes. However, the font size is too small for my eyes to read and edit the notes comfortably. It would be fantastic if you included in some of the future updates the option to change the font size.

PS: Yes, the font size is the same for every field but it becomes an inconvenience only when trying to read and edit longer notes

**Comment by droidmonkey** [comment]
Still need a screenshot please

**Comment by rioser** [comment]
Please check the attached print screen (I have a standard full HD resolution LCD). Generally I don't have a problem with small font size on my PC - even Steam chat window uses a considerably bigger font than that in KeePassXC. I also believe my system's font size is set to default, I don't remember tinkering with it.

![Small Notes Font Size Demonstration](https://user-images.githubusercontent.com/50234365/112044009-972b4180-8b49-11eb-95e3-cc66180e848b.png)

**Comment by rioser** [comment]
Not sure what happened yesterday, I was under the impression that my post with a screenshot was published here, but after checking this thread now there is nothing.

So one more time I attach the screenshot, I hope it will help. As a side note, I don't usually have a problem with reading text in my desktop programs, but reading and editing notes in KeePass strains my eyes. I also checked my system (Windows 10) font settings and they are set to default (100%).

![Notes - Small Font Size Demonstration](https://user-images.githubusercontent.com/50234365/112185101-3448b180-8c00-11eb-8cf2-1aa2cb9305b7.png)

**Comment by inkista** [comment]
Sorry. Left this on a closed issue. :)  Screen shots.  The issue looks like the proportional font is set/scaled incorrectly vs. the monospace font.  Suspect the font size may be hard-coded, since changing QT scaling via environment variable doesn't have any effect. 

![proportional](https://user-images.githubusercontent.com/81258790/112208452-98a24b80-8bd5-11eb-9ba0-89abe272d1b0.png)

![monospace](https://user-images.githubusercontent.com/81258790/112208465-9cce6900-8bd5-11eb-9c2d-678545e7872c.png)

**Comment by rioser** [comment]
Thank you very much, this helped a lot! I really love this app and the community around it, and will definitely consider a donation to this project.

**Comment by droidmonkey** [comment]
This actually might be a bug with Qt TextEdit box versus a LineEdit

**Comment by inkista** [comment]
Okay, just for kicks, I went back to confirm: Windows 10 scaling has no effect on the font size; it remains fixed at the same tiny size while the rest of the UI scales; QT_SCALE_FACTOR _does_ scale the Notes text, but it remains proportionately smaller than the main UI font.

**Comment by droidmonkey** [comment]
Your tip actually found the bug, thank you! We were pulling the system font for the notes TextEdit which does not scale with the system's font scaling. It was returning a font with the _default scale_. This was easily fixed by polling the application's font which is properly scaled to the system's font scaling. Here is how it looks with the fixes in place:

![image](https://user-images.githubusercontent.com/2809491/112221469-dc10b000-8bfd-11eb-9403-b7b33ed00d35.png)

![image](https://user-images.githubusercontent.com/2809491/112221477-de730a00-8bfd-11eb-945c-6d528c654527.png)

**Comment by inkista** [comment]
Woot!  Nice job on the fix!!
