### ISSUE TITLE
Global Auto-Type Shortcut does not map keys on the keyboard

### ISSUE THREAD

**Issue by MarkusMad** [keepassxreboot/keepassxc#6305]
Hi

When I press Ctrl+Alt+A on my keyboard this gets displayed (I have **US international** keyboard layout configured)

![image](https://user-images.githubusercontent.com/22813790/111773654-be1a1700-88ae-11eb-88f5-5100dc38572e.png)

In order to get what I want I have to switch to the normal **US** keyboard layout, then it works
![image](https://user-images.githubusercontent.com/22813790/111773471-8317e380-88ae-11eb-894e-628ae2e33cd3.png)

But even then the desired hotkey does not work on Windows 10, instead still á is typed (instead of performing auto-type) when Ctrl+Alt+A is pressed

Not sure if this helps but the "normal" KeePass does not have this "bug".

**Comment by droidmonkey** [comment]
This would be a Qt bug, we use a standard control here to capture the key pressed. Agree it shouldn't "translate" the key, but use the actual key code.

**Comment by droidmonkey** [comment]
Also dup of #2129

**Comment by Chealer** [comment]
Thank you very much for reporting
This persists in the Windows build of 2.7.12, built against 5.15.18, due to [QTBUG-60768](https://qt-project.atlassian.net/browse/QTBUG-60768).

> Not sure if this helps but the "normal" KeePass does not have this "bug".

Right, KeePass does not depend on Qt.

Please vote for the Qt ticket so it can be prioritized and retitle this to something like:
> Global Auto-Type Shortcut fails with some combinations using AltGr on Windows (e.g. Ctrl+Alt+E on Polish, USA International or CAN/CSA Z243.200 layouts)

<details>
  <summary>License</summary>
All comments and attachments from myself on this ticket are offered under the terms of CC0 1.0.
</details>
