### ISSUE TITLE
virt-manager (Virtual Machine Manager) can't retrieve password from Secret Service

### ISSUE THREAD

**Issue by WGH-** [keepassxreboot/keepassxc#6314]
## Overview
virt-manager can store, but not retrieve the password back.

## Steps to Reproduce
1. Have virt-manager patched with patch from here https://github.com/virt-manager/virt-manager/issues/237, as it has its own problems implementing the client side of Secret Service protocol
2. Open a VM console that has password-protected SPICE server (might also apply to VNC, I didn't check)
3. Save the password in the keyring
4. Try to open a console again

## Expected Behavior
* The password is loaded from the keyring

## Actual Behavior
* The password is not loaded from the keyring

## Context
The password is successfully stored in KeePassXC, you can find it in UI. But virt-manager can't load it back.

I've looked at the `bustl --user monitor` output.

To store a password, virt-manager does this method call: `Path=/org/freedesktop/secrets/aliases/default  Interface=org.freedesktop.Secret.Collection  Member=CreateItem`, and it returns this path: `/org/freedesktop/secrets/collection/db/fbd4586232634f9593c38c409da3a242`.

However, when retrieving password, it calls `Path=/org/freedesktop/secrets/aliases/default/fbd4586232634f9593c38c409da3a242  Interface=org.freedesktop.Secret.Item  Member=GetSecret`, which returns `ErrorName=org.freedesktop.DBus.Error.UnknownObject  ErrorMessage="No such object path '/org/freedesktop/secrets/aliases/default/fbd4586232634f9593c38c409da3a242'"`.

It looks like KeePassXC allows using the default alias to create password, but not to retrieve it back? I couldn't infer from the Secret Service specification whether clients should record the returned full path or not.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Operating System: Linux
Desktop Env: N/A (no desktop environment)
Windowing System: X11

**Comment by Aetf** [comment]
Items are exposed only under their canonical paths (`/org/freedesktop/secrets/collections/xxx/iii`). The spec doesn't mention that items should also be exposed under the collection alias path.

As far as I understood the spec, assembling object path on the client-side is quite questionable given even storing the object path is not recommended.

> It is strongly recommended that client applications use lookup attributes to find items rather than recording the object path of a stored item. This allows maximum interoperability.

virt-manager should at least uses the path returned by `CreateItem` to perform further operations on the item, rather than parsing the returned path.

Also, if the default alias can change anytime, using it to access items is very unreliable.

**Comment by WGH-** [comment]
@Aetf so I ended up submitting a patch to virt-manager, so it would use attributes to lookup stuff, and it was accepted.
