### ISSUE TITLE
Hiding to systray on app-start shouldn't depend on app-exit

### ISSUE THREAD

**Issue by JosefVitu** [keepassxreboot/keepassxc#64]
In the current state, the "Hide window to system tray on App start" option depends on enabling the "Hide window to system tray on App Exit" as mentioned in https://github.com/keepassxreboot/keepassx/pull/57#issuecomment-256855469. As those are (in my understanding of them) completely unrelated actions, they should be made independent.
## Expected Behavior

One should be allowed to enable the "Hide on App start" option even when the "Hide on App Exit" option is turned off.
## Current Behavior

The "Hide on App Exit" option has to be turned on in order to enable the "Hide on App start" option.
## Your Environment
- KeePassXR version/commit used: develop branch
- Qt version (e.g. Qt 5.3): 5.6.1
- Operating System and version: GNU/Linux

**Comment by TheZ3ro** [comment]
👍

**Comment by JosefVitu** [comment]
Follow-up: The initialization of the GUI for these options is broken.

## Steps to reproduce
1. Check these options: _Hide window to system tray when minimized_, _Hide window to system tray instead of App Exit_.
2. Uncheck the _Hide window to system tray when minimized_ option (the _Hide instead of App Exit_ checkbox gets disabled, but stays checked).
3. Save the settings and exit the app.
4. Open the app and go to Settings.

## Expected Behavior
_Hide instead of App Exit_ and _Hide instead of App start_ are disabled.

## Current Behavior
_Hide instead of App start_ is enabled (i.e. checkable).

Fortunately this minor GUI bug doesn't affect the actual program behavior.

**Comment by anatoli26** [comment]
Addition to this issue, as initially filled under #104, sub-issue 3:

IMO the 3rd sub-option (minimize to tray on exit) should be on the same level as the 2nd (minimize to tray on minimize) as they are independent, though related. The user may want to be able to minimize the app to taskbar on minimize, but minimize to tray on close (a rather common combination).

The 4th option (minimize on start), IMO, shouldn't even depend on tray icon at all (though be connected). The user may want to minimize the app on startup, no matter if it minimizes to tray or taskbar. If the 2nd option is selected (minimize to tray on minimize), then minimize on start should minimize to tray. If not, it should minimize to taskbar as if no tray is enabled.

Also, I would suggest changing the labels for the checkboxes as follows:
Hide window to system tray when minimized -> Hide window to system tray on minimize
Hide window to system tray instead of App Exit -> Hide window to system tray on close
Hide window to system tray on App start -> Minimize on start (separated from the other 3 items).

**Comment by anatoli26** [comment]
Just tested 19a9608, everything works as expected now (including my addition to this issue). Great job, guys!
