### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by roundoutandabout** [keepassxreboot/keepassxc#6415]
No issue here, just wanted to say thank you for KeePassXC. I think it's an awesome password manager. You are doing a great job!

*(please close immediately)*

**Comment by droidmonkey** [comment]
Thank you very much! Sometimes GitHub becomes a drag because you see a lot of errors, unreproducible problems, and complaints. It means a lot to me to see other users really enjoying the program and making it a critical part of their workflow. I'm leaving this open 😀

**Comment by SmileyStiles** [comment]
I'll add my two cents.  I store passwords for personal use, not for a company and I'm not sharing with other employees or anything like that so I want a simple password manager.  I'm currently using KeePass.  I'm testing and thinking about switching over to KeePassXC.  Why?  Because it seems to be so much easier to use and in my opinion it even looks better.  Also it seem to work better on my large monitor when other programs don't.  No it's not as powerful as KeePass but the average user doesn't need that.  KeePass because of all it's power can get too complicated.  The programmers of KeePassXC seem to strive on keeping KeePassXC friendly and as an end user, I appreciate that!   Thankyou guys, nice program alternative to KeePass.
