### ISSUE TITLE
Current URL subdomain matching might be a security issue

### ISSUE THREAD

**Issue by mjohannfunke** [keepassxreboot/keepassxc#6454]
Hey,

I read the paper "Revisiting Security Vulnerabilities in Commercial Password Managers" from Michael Carr and Siamak F. Shahandashti [1]. They listed "Ignoring Subdomains Vulnerability" (Page 7) as a possible security issue, and KeePassXC / it's browser extension is having that one as well, since it matches an entry with the URL `https://example.com` to `https://*.example.com`. To cite the paper: 
> An attacker in a subdomain can hence steal user credentials for the parent domain or other subdomains. This is an issue in many websites such as forums and blogs where different subdomains host different services.

Have you considered that as an issue? I have two suggestion how to mitigate the issue: 

1. One would be to add another option in the KeePassXC browser integration settings, to require an explicit `*` to make a matching / don't assume the `*` and only match the exact URL.
2. Add another field to the browser extension when allowing access to an entry to also display the saved URL with it (given, that it would request the data for each subdomain independently - I didn't check the behaviour there).

Best regards
Marcel

[1] https://arxiv.org/pdf/2003.01985.pdf

**Comment by varjolintu** [comment]
It's suggested to use `https://subdomain.example.com` instead of the top level domain, but of course that's not always possible. And yes, there's already a feature request for wildcards in the URL's. Also, the access is not currently granted for each subdomain. That should be fixed, and the feature request for that also exists.

As for stealing the credentials, the extension always requires an user interaction for filling them. The only exception is that if user has understood the risks and enabled auto-fill for single credentials manually. That's basically the only situation where this kind of credential steal can happen.
