### ISSUE TITLE
Feature Suggestion - Improved Security

### ISSUE THREAD

**Issue by 0xWhoa** [keepassxreboot/keepassxc#6471]
## Summary
Would've been ideal if opening a DB would only decrypt metadata, and then when attempting to copy a username or password to clipboard it would require a Yubikey touch to decrypt that specific entry.
This is more relevant for Yubikey users since it's a easy and fast to authenticate via touch.
This will be awesome feature if you can make it happen.

## Context
This feature will provide security assuming the computer is compromised, when opening the DB the attacker doesn't get access to all the passwords but rather only to the ones the user had to access at the time (since passwords and users are only decrypted upon copying them to clipboard using Yubikey touch).

**Comment by droidmonkey** [comment]
We already have plans for inline decryption of protected attributes on access. In reality it doesn't really matter because the decryption key is stored in memory so an attacker that determined can steal all necessary bits to make the attack successful. 

Having to press the yubikey every single time you access an entry is untenable and won't be implemented.
