### ISSUE TITLE
CSV Import doesn't handle millisecond times correcrly

### ISSUE THREAD

**Issue by mmokrejs** [keepassxreboot/keepassxc#6498]
Hi,
  on a 64-bit Linux I see in the listing of entries wrong date in the right-most column tagged "Modified". 
![keepassxc_wrong_date](https://user-images.githubusercontent.com/3297852/117432415-a2d09d00-af2a-11eb-8353-64e26ba7bc49.png)

  The expiry date is shown correctly if I double-click the entry and view its details in a dedicated window on "Expires:" line.

**Comment by droidmonkey** [comment]
What is wrong about it? I don't understand what your are trying to point out.

**Comment by droidmonkey** [comment]
Don't know what to do about that

**Comment by mmokrejs** [comment]
The year `51514` doe snot make sense, actually I doubt about the other day, month and other values but they at least seem possible.

**Comment by michaelk83** [comment]
@mmokrejs He means he needs more useful info to fix this. Steps to reproduce, etc. Check the issue template when you report a new bug.

**Comment by mmokrejs** [comment]
Maybe the datatype used to show the same data is of different type in different parts of hte code?

![edit_entry](https://user-images.githubusercontent.com/3297852/117480747-48ebc980-af62-11eb-9dca-5800df0caded.png)

The only think I can add is that I typed in the data manually into the GUI, no CSV import involved. But maybe re-exported the KeepassXC database into a different file due to master key change. That could have caused some havoc.

**Comment by droidmonkey** [comment]
Explain the full sequence of actions taken. This could be a csv import error.

**Comment by mmokrejs** [comment]
I do not remember much. Luckily, I see based on file timestamps that I have an older version of the keepassxc database called Firefox.kdbx (last modified on Apr 10 01:26). after opening that datbase I also see this entry with exactly same wrong `Modified` timestamp. I even see other enries with same problem. This was, guessing its name, a fresh import from a `CSV?` file created from Firefox browser with its passwords exported. I had www-client/firefox-87.0 installed at that time, and still have.

It would be better to install some sanity checks into keepassxc code, and execute them also during data import. A check, whether a date is meaningfull, and whether a `modified timestamp` is >= `an entry created timestamp` is simple and could prevent broken import altogether.

**Comment by JohnLGalt** [comment]
Are those passwords still in Firefox for you to attempt a new CSV export from Fx?  You could then look at the .csv file itself and see if it is Fx creating the havoc, or if the items are fine in the initial export, and then import that into a new separate database and verify if the times get b0rked during the import process.  As of right now, you can't rule out Firefox actually causing the issue versus KPCX causing it during import....

**Comment by droidmonkey** [comment]
I'm hesitant to add "sanity" checks to date imports, we do what you tell us to do. The only thing we are concerned with is security of data. If the date is wrong in the csv then that is on you. If we misinterpret a valid date then that is on us, but technically it's on qt because we just tell qt to parse the date string.

**Comment by alimas7** [comment]
[20211025-github.com_keepassxreboot_keepassxc_issues_6498.csv](https://github.com/keepassxreboot/keepassxc/files/7414188/20211025-github.com_keepassxreboot_keepassxc_issues_6498.csv) is a test CSV file, exported from Firefox, containing just one header row + one data row that can be used to reproduce this timestamp resolution problem.

My environment:

- Firefox 93.0 (64-bit)
- KeePassXC - Version 2.6.2, Revision: e9b9582, Qt 5.15.2
- Ubuntu 21.04 (Hirsute Hippo), x86_64, linux 5.11.0-38-generic

On the `about:logins` page, Firefox shows the following for the source of that test data in that Firefox-exported test CSV file: `Last modified: October 3, 2021`

That corresponds to the timestamp value found in the test CSV file, i.e., `1633301193303`.

After importing the test CSV file into KeePassXC (mapping `"timePasswordChanged"` -- Column 9 in Firefox CSV -- to KeePassXC `"Last Modified"`), details for that imported entry shows the unexpected/incorrect timestamp: `Modified: 3 Apr 53727 16:55:03`

The problem is due to timestamp resolution.
- Firefox exports in **milli**seconds since the Epoch.
- KeePassXC importer (which uses `QDateTime`?) works at/expects a lower resolution: seconds.

The below is just to illustrate the same problem of the unexpected/incorrect date+time when the milliseconds are not properly taken into account.
```
$ TZ='America/Los_Angeles' date -d @1633301193303
Thu Apr  3 04:55:03 PM PDT 53727
```

Truncating the `303` milliseconds yields the expected/correct timestamp:
```
$ TZ='America/Los_Angeles' date -d @1633301193
Sun Oct  3 03:46:33 PM PDT 2021
```

Some users can `sed` the Firefox CSV to remove the milliseconds before importing into KeePassXC.  However, there are probably more of KeePassXC users who don't know how to do that.

If the millisecond resolution is not already supposed to be taken into account somewhere in KeePassXC importer, one way for the importer -- to **not** require timestamp values to be in seconds -- can be to present a "_Timestamp in milliseconds_" checkbox, deselected by default, to divide by `1000` if selected, similar to the division seen through https://github.com/keepassxreboot/keepassxc/blob/2a9d92faeb48ec284700fd0ee5307cd0e36160f7/src/fdosecrets/objects/Item.cpp#L231
