### ISSUE TITLE
[DOC] Clarify KeeShare synchronization / "outside" entries

### ISSUE THREAD

**Issue by ulab** [keepassxreboot/keepassxc#6499]
## Summary
I was [looking into KeeShare](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/KeeShare.adoc), but the following phrase irritates me and results in some questions:

> KeeShare does not synchronize group structure after the initial share is created. At this time, KeeShare operates at the entry level; shared entries moved outside of a shared group are still synchronized. 

1. Does that mean that new entries will not be synchronized after the "initial share"?
2. How do I identify shared entries that were moved outside?
3. In what directions are these entries synchronized when they are not in the group anymore?
4. How do I "unshare" entries?

**Comment by engelhro** [comment]
Hello,

I'm trying to get familiar with KeeShare currently, and have asked myself some similar questions. Unfortunately that whole export/import/synchonize concept is *not* explained very well in the user guide…

Here are my findings so far, maybe we can develop a better understanding together:

- The main database is called `A` form here on, an external database (for export or import or sync) is called `B`
- The connection to outside databases `B` (for whatever purpose, import only, export only or sync) gets stored at the folder level. As long as the folder exists (even in the trashbin!) of your main database `A`, the external database `B` is "connected" and will be considered when evaluating the tasks to do (again: export, import or sync).
- The sync itself happens at entry level (I assume the UUIDs are the relevant criterion).
- So: if the group with the database link still exists anywhere in the structure of your groups in `A`, any entries in your database `A` (no matter where they are stored now, still within that group or elsewhere) will get updated based on the contents in `B` (at least for the import or sync case).
- Assumption (not tested yet): deleted entries in `B` are simply not updated in `A` anymore (and also deleted there), as there's no UUID match any longer.

> 1. Does that mean that new entries will not be synchronized after the "initial share"?

No. New entries within a group with a database connection are exported (or synchronized) the next time the main database `A` gets saved. 

> 2. How do I identify shared entries that were moved outside?

That's indeed a very nasty thing, there currently seems to be no way to identify such candidates (with a "twin" in database `B` outside the main database `A` with the same UUID).

> 3. In what directions are these entries synchronized when they are not in the group anymore?

From my tests: imports are performed as expected (the entry is overwritten with the external information from `B`, even it it has been moved outside the import group in `A`).

I don't know what happens in the "sync" or the "export only" case for these entries (are they still exported? If yes: to which folder/group, where do they appear in `B` afterwards?).

It's also open what happens if I move entries in `A` between folders with different directions (e.g. a former "import only" entry to an "export only" or "sync" group, or vice versa). I also don't know yet how structural changes in `B` get reflected in `A` on import or sync?

There are so many cases and so many possible conflicts, and probably all these corner case have not been considered in detail (at least it would be difficult to list them in the user guide). So one needs to try to find out what happens.

> How do I "unshare" entries?

Either get rid of all connections to external databases `B` which contain that entry (i.e., delete all corresponding groups in `A`, also from the trashbin), or clone the shared entry and delete the old one (new UUID, which has then no counterpart in the external databases `B`).

**To the developers**: was all that orrect? Or did I get something wrong? We'd be glad about some more insight on that KeeShare mechanism for export/import/sync.

**Comment by droidmonkey** [comment]
Keeshare is being recoded to address all these issues. They are all covered under their own issues.

**Comment by droidmonkey** [comment]
@engelhro your analysis is accurate, great job
