### ISSUE TITLE
Web requests to 13.233.76.15

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [keepassxreboot/keepassxc#6572]
Hi, I am curious about some web requests KeePassXC recently started making. Can you provide some insights about these?

![image](https://user-images.githubusercontent.com/52948878/120102439-a68dc300-c168-11eb-98a6-bc90a13919be.png)

**Comment by YuvrajRaghuvanshiS** [comment]
BTW

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

**Comment by michaelk83** [comment]
https://whois.domaintools.com/13.233.76.15 :
> IP Location | India                        Mumbai                         Amazon Data Services India
ASN | AS16509                             AMAZON-02, US                            (registered May 04, 2000)
Resolve Host | ec2-13-233-76-15.ap-south-1.compute.amazonaws.com

Does it look familiar?

**Comment by droidmonkey** [comment]
This is Firefox

**Comment by droidmonkey** [comment]
Just opened the ip and it is github

**Comment by YuvrajRaghuvanshiS** [comment]
> 
> 
> https://whois.domaintools.com/13.233.76.15 :
> 
> > IP Location | India                        Mumbai                         Amazon Data Services India
> > ASN | AS16509                             AMAZON-02, US                            (registered May 04, 2000)
> > Resolve Host | ec2-13-233-76-15.ap-south-1.compute.amazonaws.com
> 
> Does it look familiar?

I did a whois search before opening and found out about AWS (did not put IP in browser) my concern was with what payload it is carrying while request.

**Comment by michaelk83** [comment]
If you can reproduce the request, you can try disabling the relevant features and see if goes away (or invoke those features manually, and see if it's the same request).

The most likely culprit is the update service. FavIcons are less likely, because they're usually on static file storage, and this IP is a compute instance (*ec2*....*compute*.amazonaws.com). Another possibility is if you have a KeeShare file there, but again, I'd expect that to be on static file storage (and KPXC doesn't talk to cloud storage directly, AFAIK).

If you know what's on that AWS server, that should give you a hint as well.

**Comment by droidmonkey** [comment]
It's the update service.

**Comment by ghost** [comment]
I noticed that too. Many connections to both Google and Amazon servers immediately after starting Firefox with the KeePassXC browser extension.
![Screenshot](https://user-images.githubusercontent.com/35380225/122657072-ae30fe00-d14f-11eb-99fd-3c75e33e809d.png)

**Comment by droidmonkey** [comment]
That is Firefox... their telemetry service to be exact
