### ISSUE TITLE
manually fillable "stack" of OTP recovery codes

### ISSUE THREAD

**Issue by wwlwpd** [keepassxreboot/keepassxc#6663]
## Summary

many services that require OTP provide back up codes. Github is one. This feature requests is for a simple way to manage a list of them.

## Examples

what I currently do when these codez are available:

a. copy all codes from service (e.g., github)
b. paste them as "notes" in the service entry in kpxc
c. when I need one, I just open up the "edit entry", the cut it to clipboard and save
d. paste recovery code as appropriate

## Context

If possible, I like to use backup codes rather than generated OTP; this is helpful for a variety of reasons - recovery being just one.

**Comment by JohnLGalt** [comment]
It's not easy, but you could add them to the advanced section under the additional attributes, then each one would be usable directly from the main entry via sight click.

And, yes, I do know just how cumbersome this is to set up - I used to have a Micro$oft TechNet subscription, which (at the time) included 10 license keys for every edition of Windows 7, each one unique - it took me a while to get all of those added as attributes to each version of Windows 7 entry that I have.

Since I cannot take screenshots of the KPXC dev install, I can't show you - but I have entries for Win7:

- Enterprise / K / N / KN
- Home Basic
- Home Premium / K
- Home Premium N / KN
- Professional / K
- Professional N / KN
- Starter / K
- Starter N / KN
- Ultimate / K
- Ultimate N / KN

Every entry except the first Enterprise has 10 keys each.  I simply created Items 1-10 and copied a key to each item.

Like I said, cumbersome to set up - but much easier to use when it is established.

Right click on the entry --> Copy Attribute --> select any number from 1 - 10, and the key gets copied to memory just like a password.

**Comment by droidmonkey** [comment]
Just put them in the entry notes. We won't support this directly in the ui.

**Comment by wwlwpd** [comment]
Thank you for your consideration and suggestion.
