### ISSUE TITLE
Changing an entry's note with another program doesn't trigger a DB sync in KeePassXC

### ISSUE THREAD

**Issue by peter-dvlpr** [keepassxreboot/keepassxc#6683]
Basic info:
- I have my kdbx file on Dropbox so it's easily accessible from all my devices.
- On my PC I use KeePassXC v2.4.3, my OS is Ubuntu 20.04.2 LTS.
- On my phone I use Keepass2Android v1.08d-r5.

The issue:
- I updated an entry's note on my phone and saved the database.
- When opening KeePassXC on my PC, it didn't detect that the database was changed, it showed the note without the recent change.
- As a test, I updated the note of the same entry in KeePassXC and saved the database.
- After doing a sync in Keepass2Android, the note was in a state KeePassXC had it, i.e. my previous change done via Keepass2Android was lost.

**Comment by droidmonkey** [comment]
Your database file is not syncing from your phone back to Dropbox. Make sure you have KeePass2Android setup correctly to directly access the database from Dropbox and not a local file. This isn't our bug since we do not have any control over the android app. 

FWIW, I personally recommend using KeePassDX on Android.
