### ISSUE TITLE
Add support for importing multiple URLs in CSV

### ISSUE THREAD

**Issue by coughingmouse** [keepassxreboot/keepassxc#6691]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add support for importing multiple URLs to KP2A_URL in csv.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
When importing from Bitwarden, let there be a way to import to something like
URL: https://www.mathworks.com/
KP2A_URL: https://www.google.com/
KP2A_URL_1: https://www.naver.com/

Instead of 
URL: https://www.mathworks.com/,https://www.google.com/,https://www.naver.com/

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Bitwarden supports multiple urls and can export them to csv. Although KeePassXC [supports multiple URLs](https://github.com/keepassxreboot/keepassxc/pull/3558) by adding entry attributes with ```KP2A_URL```, it seems KeePassXC does not import them as multiple URLs.

(Btw, having multiple urls support under browser integration while having one url slot on the main entry panel seems counter-intuitive. Just saying.)

**Comment by droidmonkey** [comment]
The only feature of the program that uses multiple urls is the browser integration. Unlikely we'll support this in the CSV parser, it is pretty feature rich and complex as is.

**Comment by michaelk83** [comment]
> The only feature of the program that uses multiple urls is the browser integration.

IMO this is more about import not dropping data and not mangling data too much (like placing stuff in the wrong fields or combining multiple fields into one), so that it would be easier for people to migrate. Less clean-up after an import. I suppose this will be affected by #863.

Also, I think I saw some similar request before, but I can't find it.

**Comment by droidmonkey** [comment]
We will not support expanding the CSV importer to additional attributes. You will have to move those in manually after the initial import. This feature is just not feasible for CSV since each attribute will require it's own column and a way to match that column to something in the UI. Another option is to add multiple url's to the notes, do the import, then copy the url's into the browser settings.
