### ISSUE TITLE
key file creation encodes as ANSI instead of UTF-8

### ISSUE THREAD

**Issue by SidMautteLowes** [keepassxreboot/keepassxc#6712]
When executing the keepassxc-cli binary to create a keyfile.keyx file the resultant XML file is encoded as ANSI instead of UTF-8. This comment is not speaking to the content of the XML (which states that the file is encoded as UTF-8) but rather the actual file encoding itself.

**Comment by droidmonkey** [comment]
In this case it doesn't matter because there is no chance of utf-8 characters appearing in the xml. Will correct though.

**Comment by SidMautteLowes** [comment]
Agreed that only low order bits are used and the codes are identical it's a low priority fix.

**Comment by phoerious** [comment]
I'm not sure I follow. The generated key file is valid UTF-8. We are using a QXmlStreamWriter, which assumes UTF-8 by default, but since there are no non-ASCII characters in the file, it is identical to ASCII or any western single-byte encoding.

**Comment by SidMautteLowes** [comment]
The file created is actually encoded as ANSI not UTF-8. While the byte sequences are the same for the lower order characters, if any other characters in the higher order were added the difference would present itself. A tool like NotePad++ can be used to validate the encoding.

**Comment by droidmonkey** [comment]
Actually I think you are seeing a bad judgement by Notepad++. UTF-8 doesn't have any byte order mark or distinguishing characteristic that identifies it as that encoding. Most text editors guess which encoding it is in based on the content. Given that the XML itself says UTF-8, Notepad++ should have chosen that encoding. If the entire file is within ANSI range then it is actually correct to say it is ANSI encoded (subset of UTF-8).

Closing this cause the code is correct on our end.

**Comment by phoerious** [comment]
I think this is a misunderstanding of how encodings work on your end. There is no way to "validate" an encoding. In fact, it is absolutely impossible to determine what encoding was used to produce a given byte string, because the encoding is just your interpretation of what those bytes mean. If Notepad++ says ANSI it's as correct as UTF-8, ASCII, ISO-8859-1, Windows-1252, or almost any other encoding. You can rule out some (especially multi-byte) encodings if the byte sequence contains code points or sequences that are illegal or undefined in that encoding, but the other way round is impossible to say.

Just try this Python snippet:
```python
print('äöü'.encode('utf-8').decode('cp1252'))
```
What you get back is `'Ã¤Ã¶Ã¼'`, which is a totally valid (although perhaps unexpected and for us humans nonsensical) interpretation of the bytes produced by the `encode()` call.

So for your key file, Notepad++'s guess of "ANSI" is technically correct, but I would argue that it's actually a very poor default. UTF-8 wouldn't be any more (or less) "correct", but it would certainly be the more sensible guess and Notepad++ simply shows its age by defaulting to a single-byte interpretation (actually, ANSI isn't really an encoding, it's just an alias for your default encoding, which is probably Windows-1252).

**Comment by SidMautteLowes** [comment]
I see that you have closed the ticket and that is fine.
I cannot tell you how many companies I've had to correct improperly "UTF-8" encoded files at over the years which were created as ISO8859-1 with characters in the high order byte sequence in them. There is actually a way to validate an encoding which is why a BOM was created.
Powershell has a similar method of identification of the output type as UTF-8 (Out-File -Encoding "UTF8").

**Comment by phoerious** [comment]
Have you read my answer? Adding a BOM doesn't magically make a text UTF-8 and not having a BOM doesn't mean it's not UTF-8. BOMs are actually discouraged for UTF-8 for various reasons and you should not be using one (and strictly speaking, it's also just a heuristic, since a BOM could also be interpreted in many other ways). If you are, you're doing it wrong. The only encodings that definitely need a BOM are UTF-16 and UTF-32, but you shouldn't use either of them for all sorts of reasons. Our code is correct, the file is correct and valid UTF-8, and there won't be some magical accident where non-ASCII characters do something funky with our key files. The only thing that would happen is that your Notepad++ would (hopefully) switch its broken default prediction to UTF-8.
