### ISSUE TITLE
Password replaced with .........., no entry history to be found.

### ISSUE THREAD

**Issue by georgehank** [keepassxreboot/keepassxc#6715]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

See title.

## Steps to Reproduce
How the f*** should I know?  I saw it happen.  Once, fortunately.  If it should happen again, I'm *DONE* with this.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Duh: DO NOT REPLACE PASSWORD WITH NOTHING… and DO THAT HISTORY THING THE DOCS TELL ME ABOUT.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See title.

## Context
[NOTE]: # ( Give us any additional information you may have. )
It was a browser-integration password entry.  I'm using Dropbox to sync with a second PC BUT I ONLY CHANGE PASSWORDS ON THE ONE PC.  I did use that website but I'm sure I told the keepassxc-browser to add a NEW entry (because different account used).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 7

**Comment by droidmonkey** [comment]
Going to need more information. What exactly happened,  what were you expecting to happen?

**Comment by michaelk83** [comment]
> no entry history to be found

History is in the bottom of the left sidebar in the entry edit form. You may need to scroll down the sidebar to see it. It needs to be enabled in the database settings first, but that should be the default (at least for new DBs created in KeePassXC).

If history is enabled but empty, then this may have been a display error, with no data changed.

> **Steps to Reproduce**
> How should I know?

1. Back up your database. You should keep backups of all your important files anyway, since no software is perfect.
2. Try to remember what you did before the problem occurred.
3. Repeat those steps to see if the problem repeats. If so, post those steps here.
4. If not, try some other step combinations to see if you can reproduce the problem. If you find reproducible steps, post them here.
5. If you can't reproduce the problem, be happy that everything works. This was probably a rare occurrence, otherwise it would've been reported already.
6. Remember that the devs can't fix what they can't reproduce. Shouting and cursing doesn't help anyone.

>  If it should happen again, I'm DONE with this.

As noted, this is probably a rare fluke. Keep a back up, and you should be fine. And if this does occur again, that might give you a hint on how to reproduce this.
