### ISSUE TITLE
Integrate into Tails

### ISSUE THREAD

**Issue by sowbug** [keepassxreboot/keepassxc#677]
It would be really nice if this app were part of the Tails live Linux distro. They migrated to the KeePassX 2 database in 3.0, so it'd be compatible.

**Comment by phoerious** [comment]
Hey, thanks for your suggestion. Please don't delete the issue template next time.

For Tails, we unfortunately missed the release train, so 3.0 keeps shipping KeePassX. But in the end it's not our decision anyway. Thus I think you should rather post a bug report with Tails instead of here.

**Comment by sowbug** [comment]
Okey dokey, thanks.

**Comment by TheZ3ro** [comment]
They are releasing 3.1 in August, maybe we can beg them to integrate KeePassXC

**Comment by Jon-guy30** [comment]
Are you still open to the possibility of keepassxc being included in Tails? The reason Tails does not include keepassxc in their included software is because keepassxc is not in Debian. First it needs to be included in the Debian repositories and only after that may the Tails developers consider replacing keepassx. 

It's not only keepassxc that don't make it into Tails. There are other privacy applications that don't make it. If you're interested, check out this page. https://tails.boum.org/support/faq/index.en.html#index8h1

Work with Debian first, then Tails. If keepassxc made it into Tails, it would make this application much more popular than it already is.

I checked the debian package search on their website, it did not find keepassxc.

I don't use Tails, but I've been reading about it. Also, instead of opening an entirely new "issue" I thought I'd search first and found this thread.

**Comment by phoerious** [comment]
KeePassXC is in Debian Sid and Testing.

**Comment by Jon-guy30** [comment]
Oh? I didn't check those repositories. My bad.

Is it because KeePassX is more "established" as a gnu/linux password manager? Have any significant problems or security issues been disovered in it? Latest build is from 2 years ago, so it's not _that_ old, in my opinion. 

Maybe they (Tails developers) just prefer it, I don't really know.

**Comment by phoerious** [comment]
AFAIK tail plans to replace KeePassX with KeePassXC in the next release.

**Comment by Jon-guy30** [comment]
Nice!
