### ISSUE TITLE
Yubikey reinsert before being recognized by KeepassXC

### ISSUE THREAD

**Issue by koerli89** [keepassxreboot/keepassxc#6841]
I recently startet using Yubikey 5 NFC with KeypassXC.

The Yubikey works, with one small issue, though. When i start my computer my yubikey is already pluged in and is being recognized by Yubikey manager and Yibikey authenticator. However, KeepassXC only recognizes my Yubikey when i remove it and replug it into my computer.

This creates unnecessary wear on the USB contacts of the key, so i would love if this got fixed. 
I setup my key with CR in pasive mode (without having to touch it). Is this the problem?

**Comment by droidmonkey** [comment]
What operating system? What version of keepassxc?

**Comment by koerli89** [comment]
Sry. KeepassXC 2.6.6 on Ubuntu 20.04

**Comment by droidmonkey** [comment]
This is likely a problem with your udev rules. We dynamically detect yubikeys when you press refresh. Evey time is a fresh look. This will fail if udev is not exposing the usb key because it was registered prior to udev being available (for example).

If you are using the snap version make sure you've given permission to access raw USB.

**Comment by koerli89** [comment]
thanks for the hint. How would i give keepassXC raw USB permissions if there is not a keepassXC-related file in /etc/udev/rules.d/

**Comment by droidmonkey** [comment]
Are you running the snap version? If not then it's not relevant.

**Comment by koerli89** [comment]
Ahh, no i am not. ^^

**Comment by koerli89** [comment]
still not solved

**Comment by droidmonkey** [comment]
Well it's not going to be because it's not reproducible by us. You need to investigate your udev rules and startup sequencing. This isn't something that we can fix. We look for all connected and available USB devices every time you hit the refresh button. That would mean Ubuntu is not making the device available after startup. 

Please confirm if you are running yubikey manager as root. That would explain why it works. Please also see if running keepassxc as root detects the yubikey after startup. These are important tests.

**Comment by koerli89** [comment]
yubikey manager detects the yubikey right away, without running it as root. I have keepassxc installed as appimage, how do i run it as root? I looked into my udev rules, in /lib/udev/rules.d and /ect/udev/rules.d i have the file 70-u2f.rules which contains the lines:

> Yubico YubiKey
> KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0121|0200|0402|0403|0406|0407|0410", TAG+="uaccess", GROUP="plugdev", MODE="0660"

In /lib/udev/rules.d also have the file 69-yubikey.rules which contains

> 
> ACTION!="add|change", GOTO="yubico_end"
> 
> Udev rules for letting the console user access the Yubikey USB
> device node, needed for challenge/response to work correctly.
> 
> Yubico Yubikey II
> ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0010|0110|0111|0114|0116|0401|0403|0405|0407|0410", \
>     ENV{ID_SECURITY_TOKEN}="1"
> 
> LABEL="yubico_end"

No keepassxc specific file in any of those two folders. Should there be one?

**Comment by droidmonkey** [comment]
No there is no need for keepassxc specific rules.
