### ISSUE TITLE
Add type attribute option on Auto-Type Popup Window

### ISSUE THREAD

**Issue by Lumenbolt** [keepassxreboot/keepassxc#6869]
## Summary
Auto-Type implementation in 2.7.0 is a lot better! However, it'd be great if we could quickly search and copy an entry's attribute from the auto-type popup (triggered by an hotkey).

## Examples
Expecting a way to copy an attribute from an entry from the dropdown shown below

![Untitled](https://user-images.githubusercontent.com/63922865/130535028-0716e005-2d97-4b61-a4da-dc99b67bfa77.png)
(or from the _Type Sequence_ dropdown beside _Cancel_).

I really like the way it was implemented for the browser extension for `KPH: ` attributes. (Except here it'd allow _copying_ for any one of the attribute(s) available to clipboard).

![2021-08-24_03-17](https://user-images.githubusercontent.com/63922865/130535877-a4d5e710-d6e7-4183-8ea9-f49a92626e48.png)

## Context
Would be helpful if one has to copy & enter a specific attribute on a random form quickly instead of opening up the KeepassXC instance to copy the attribute to clipboard. Eg. Credit Card Number, etc.

**Comment by droidmonkey** [comment]
We will not do this, define an Auto-Type sequence for the custom attributes instead. That dialog is not meant to allow copy paste for everything, we just allow it for user pass and totp for oddball dialogs. Copy paste is the antithesis of Auto-Type.

**Comment by droidmonkey** [comment]
Although I could entertain a "Type attibute" option.

**Comment by Lumenbolt** [comment]
> Copy paste is the antithesis of Auto-Type

I do agree. I was looking for a quick and dirty way of obtaining a particular value of an attribute from an entry from a popup that can be instantly triggered by an hotkey, and the new Auto-Type popup in 2.7.0 seemed to be a viable solution to this.

**Comment by hifi** [comment]
I actually needed this myself for AWS console where you first type in the account name/number so I'd probably implement this at some point. I'd leave it to the user to decide which input method they need (type or copy) because you could need to copy to some programs over typing and if the custom attributes are not extremely secret but more like metadata (e.g. AWS account number) the security implications of copying wouldn't be that worrying.

Defining a sequence for every field combination requires associating a window which makes it inconvenient if you use global search. I also slightly disagree with the notion of "not meant to allow copy paste for everything" as the dialog is _very_ convenient and replaces the main window for pretty much everything else than editing entries for me. Custom attributes is the only thing it can't do besides making coffee. :coffee: 

@droidmonkey what's your thoughts on implementing this now that we have some experience using the new dialog ourselves?

**Comment by droidmonkey** [comment]
Implemented by the feature introduced in #7391
