### ISSUE TITLE
KeepassX Release GPG-Key has expired

### ISSUE THREAD

**Issue by soerenkoehler** [keepassxreboot/keepassxc#6911]
## Overview
GPG-Key has expired

## Steps to Reproduce
$ gpg -d KeePassXC-2.6.6-Win64-portable.zip.sig

## Expected Behavior
gpg output without expired note

## Actual Behavior
gpg: assuming signed data in 'KeePassXC-2.6.6-Win64-portable.zip'
gpg: Signature made Sat Jun 12 04:23:57 2021 WEDT
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
**gpg: Note: This key has expired!**
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8

## Context
KeePassXC-2.6.6-Win64-portable.zip

**Comment by phoerious** [comment]
The release key expires 2024. Please update your key cache.

**Comment by Avispa** [comment]
Not sure if I do something wrong, since nobody else is complaining here but... (self translated from native):
```
> gpg --keyserver keyserver.ubuntu.com --search-key release@keypassxc.org
gpg: data source: http://162.213.33.9:11371
gpg: Key "release@keypassxc.org" not found on the key server
gpg: Search on the key server failed: not found
```
... or we are the only two windows users really wanna check the file integrity.

[phoerious](https://github.com/phoerious) commented [on 12 Sep 2021](https://github.com/keepassxreboot/keepassxc/issues/6911#issuecomment-917602050)
> The release key expires 2024. Please update your key cache.

It's a fresh install of _gpg4win_. Actually just installed to verify your file.

Okay, already spend over an hour to figure out this issue. And to be honest, I'm pretty sure I'm not the only one with that problem-- just the only one (actually second) posting here. Guess I'll go on with my life. Whatever the problem is, please seriously consider to put it on top of the README or at *least* into the wiki. (Searched both, couldn't find any hint.)

**Comment by droidmonkey** [comment]
There was a bug in wingpg that caused key updates to fail last year, but the problem is likely on your end.

**Comment by droidmonkey** [comment]
Actually it is entirely on you, our email address is **release@keepassxc.org** not @keypassxc.org

**Comment by phoerious** [comment]
Yes, if you want to verify our release, please copy and paste *exactly* what is written on our web page, otherwise there is no point in doing it. Anybody could upload a key with that (or any other) email address. You have to retrieve the key by its exact fingerprint.
