### ISSUE TITLE
Auto SSH key config file

### ISSUE THREAD

**Issue by zyzyx159** [keepassxreboot/keepassxc#6925]
## Summary
Most SSH config files only contain the Host name, User name, SSH key. All of that information can be stored in KeepassXC. I would like to have an export button that would product a SSH config file for all the SSH keys stored in my KeePassXC database.

## Context
I use KeePassXC to hold and manage all my SSH keys and it would be nice if I didn't have to manually update my SSH config file after entering the same data into KeePassXC.

**Comment by hifi** [comment]
There is no notion of "hostname" in a KeePass database so it isn't something that could be done with the current data structure without using custom fields except if the URL is used when the protocol bit is `ssh://`.

The `IdentityFile` option is also problematic because it expects a private key but you _can_ feed it a public key as well even though it doesn't claim to support it. We can't export a config file with `IdentityFile` set unless we also export public keys into some path it can refer to.

It's possible your use case is a bit excessive if you have a unique SSH key per host which would require you to maintain a massive configuration file.

You could build a script with some KDBX library to interpret your entries however you see fit to build a config file automatically but I don't feel this is necessarily something we want to implement.

**Comment by droidmonkey** [comment]
I'm not in favor of implementing

**Comment by zyzyx159** [comment]
I will work on a script as hifi suggested. Thank you for your considerations.

**Comment by zyzyx159** [comment]
I will work on a script as hifi suggested. Thank you for your considerations.
