### ISSUE TITLE
KeepassXC doesn't work with Firefox (snap) on Ubuntu 21.10

### ISSUE THREAD

**Issue by bungabunga** [keepassxreboot/keepassxc#7022]
## Overview
Ubuntu 21.10's default Firefox is a snap package and it doesn't work with KeepassXC. It's still possible to install FF via apt but this would probably be abandoned with the next Ubuntu LTS version. Is it possible to make KeepassXC work with snap version of Firefox?

**Comment by phoerious** [comment]
See #1598

**Comment by fubar-coder** [comment]
@phoerious Please reopen this issue, because it's not related to #1598, according to the [this comment](https://github.com/keepassxreboot/keepassxc/issues/1598#issuecomment-827639075) from @droidmonkey.

**Comment by phoerious** [comment]
It's the same issue. We have no way of enabling snap support at the moment. We are aware of that problem and we don't need more open issues for it.

**Comment by banholzer** [comment]
@phoerious as @fubar-coder said, the linked #1598 is about issues regarding keepassxc as snap. 

But: as cannonical will serve browsers in future as snap only it is already the case for chromium since 20.04 and will probably extend to 22.04.

So this issue should maybe kept to think about a solution to still enable the browser extension. But eventually this should be continued here: https://github.com/keepassxreboot/keepassxc-browser/issues/1426
