### ISSUE TITLE
Set additional Clipboard security flags on windows

### ISSUE THREAD

**Issue by thedewi** [keepassxreboot/keepassxc#7127]
## Overview

Unlike KeePass 2.x, KeePassXC is not setting the "Clipboard Viewer Ignore" format when populating the clipboard, resulting in plaintext passwords being saved by clipboard history tools and similar.

Source code: https://github.com/dlech/KeePass2.x/blob/0defb69f48687de62a4dbfad3213387371a3e8be/KeePass/Util/ClipboardUtil.Windows.cs#L189-L194

Sorry this isn't a PR.

I possibly shouldn't have classed this as "Bug" - but it was surprising behaviour to me, and has left me with passwords in a database they shouldn't be in.

## Steps to Reproduce

1. Highlight an entry and press Ctrl-C.
2. Open clipboard history tool (eg Ditto).

## Expected Behavior

No password entry.

## Actual Behavior

History has recorded password entry.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

**Comment by thedewi** [comment]
Workaround: Some clipboard managers, such as Ditto, have an Exclude list to which you can add `KeePassXC.exe`

**Comment by droidmonkey** [comment]
Uhhh we do set the exclude flag https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Clipboard.cpp#L65

https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#cloud-clipboard-and-clipboard-history-formats

**Comment by thedewi** [comment]
There appear to be multiple conventions in use, and my clipboard history tool (`ditto`) does not know `ExcludeClipboardContentFromMonitorProcessing`. KeePass appears to support 4 of them - 

https://github.com/77/keepass2/blob/49373d56801495919f19b2cd1cfdeb741135c479/KeePass/Util/ClipboardUtil.Windows.cs#L43-L48

**Comment by starsoccer** [comment]
Might be a nice feature if it could be customized if there is no standard. Just as another data point, seems like copyq looks for other information, https://github.com/hluk/CopyQ/pull/2500 but also supports custom format values as well as mentioned here, https://copyq.readthedocs.io/en/latest/faq.html#faq-ignore-password-manager

**Comment by Chealer** [comment]
## KeePassXC
> Uhhh we do set the exclude flag https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Clipboard.cpp#L65

To clarify, [this is the line](https://github.com/keepassxreboot/keepassxc/blob/439c155552f6508ae26a7a43f9361fc0ee23a307/src/gui/Clipboard.cpp#L65) @droidmonkey was referring to. KeePassXC versions [prior to 2.6.3](https://github.com/keepassxreboot/keepassxc/commit/4b5248ee989ec889294a05ed2895768acefdf562) did not set any custom format on Windows. Starting from 2.6.3, the `ExcludeClipboardContentFromMonitorProcessing` format is set. Starting from 2.7.10, the `CanIncludeInClipboardHistory` and `CanUploadToCloudClipboard` formats are also set.

## CopyQ
@starsoccer wrote:
> Might be a nice feature if it could be customized if there is no standard. Just as another data point, seems like copyq looks for other information, [hluk/CopyQ#2500](https://github.com/hluk/CopyQ/pull/2500) but also supports custom format values as well as mentioned here, https://copyq.readthedocs.io/en/latest/faq.html#faq-ignore-password-manager

For CopyQ's evolution, see [ticket #2679](https://github.com/hluk/CopyQ/issues/2679).

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>

**Comment by Chealer** [comment]
# Ditto

> There appear to be multiple conventions in use, and my clipboard history tool (`ditto`) does not know `ExcludeClipboardContentFromMonitorProcessing`.

Ditto checks the "Clipboard Viewer Ignore" format [since 2003 or before](https://github.com/sabrogden/Ditto/blob/0cff727c74dd0bea435c9412f9d11f0d548b4193/ProcessCopy.cpp#L57). However, its stable version indeed does not check for any other format.

So, there are 4 formats designed to avoid this. The first is [the entirely unofficial `CF_CLIPBOARD_VIEWER_IGNORE`](https://web.archive.org/web/20200720154713/http://www.clipboardextender.com/developing-clipboard-aware-programs-for-windows/ignoring-clipboard-updates-with-the-cf_clipboard_viewer_ignore-clipboard-format), which [Chris Thornton introduced in ClipMate more than 2 decades ago](https://stackoverflow.com/a/20558943/5405434). The 3 others are those documented on Microsoft Learn. Since the current version of KeePassXC only supports the last 3 while the current version of Ditto only supports the first, KeePassXC and Ditto are currently incompatible in that regard. [This changes starting from Ditto 03.25.119](https://github.com/sabrogden/Ditto/commit/b0533af4033b724dd59b9c6a61448bc3104564cc) (a pre-release) though.

# KeePassXC
To clarify, the issue reported here is not solved. However, in addition to the upcoming solution from Ditto, KeePassXC 2.7.10 and ulterior set more formats.
It is not clear whether `CF_CLIPBOARD_VIEWER_IGNORE` is worth implementing, since it is not official and seems effectively replaced by the formats Microsoft documents.

For background on `CF_CLIPBOARD_VIEWER_IGNORE`, see [this post by its creator](https://stackoverflow.com/questions/20480117/how-not-to-save-passwords-and-sensitive-data-in-quicksilver-alfred-clipboard-his).
