### ISSUE TITLE
Shrink layout gaps and icon size of sidebar tabs

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#713]
I just updated to 2.2.0 on macOS and noticed the entry function tabs are now icons. There're too big and I must click the `▼` button to scroll down to access the lower tabs. Having them as text links was better. 

It'd also be a shame to add one more option to the settings. Perhaps make icons smaller? Or reduce spacing between icons, labels, and between tabs?

![screen shot 2017-06-29 at 16 47 13](https://user-images.githubusercontent.com/6884276/27674899-0bd5e558-5ceb-11e7-8d87-6506b390de61.png)

**Comment by sts10** [comment]
Agree 100%. The icons should be made to fit in one "screen" height, if nothing else so that new users can more easily find the sections toward the bottom (like Auto-Type). I'd vote for smaller icons and less space in between.

Separately, I feel like that "Icon" icon look a little too similar to a die (random password generator)?

**Comment by phoerious** [comment]
You guys seem to have pretty tiny screens. The search field is also not visible.

**Comment by sorcix** [comment]
I'm having the same issue on Linux/Gnome, where my KeepassXC window is usually not fullscreen. The properties and history buttons are not visible. To make things worse: there is no indicator that I can scroll down.

![screenshot](https://user-images.githubusercontent.com/65006/27710757-16c324e0-5d21-11e7-9868-b94ea78207f6.png)

**Comment by droidmonkey** [comment]
The icons are rather large.

**Comment by sts10** [comment]
Sorry, I was a little sloppy with my words earlier when I wrote, "The icons should be made to fit in one 'screen' height." I simply meant that users should be able to see all of the icons with _most_ _window_ sizes. I also didn't mean to sound so blunt! I'm loving the new version-- thank you for all your hard work. 

By my measurements (using OS X), KeePassXC needs to be about 715px tall for users to see the top of the History icon. My MacBook Air's display is 900px tall, minus 22px for the menu bar at the top of screen and perhaps 50px for a fixed dock, leaving me only 828 pixels of usable height. That means KeePassXC needs to be about 86% of my screen height to make all the icons visible. 

The point I was trying to make above was that new users with 900px resolutions might never see the History icon (and thus not learn that KeePassXC has an awesome history-keeping feature) unless/until they happen to nearly max out the height of the window while creating or editing an entry. Since all the other parts of KeePassXC fit so nicely into, say, a 550px height (which helpful for seeing the browser window that I'm attempting to Auto-Type into), I think it's reasonable they might never maximize it. Even if it's a small risk, I think it's worth mitigating for by shrinking the icons a bit.

**Comment by wolframroesler** [comment]
With SVG instead of PNG (as of #475/#4066), perhaps this is simply an issue of changing some numbers in a .ui file?

**Comment by droidmonkey** [comment]
Yes please make this happen in your PR

**Comment by wolframroesler** [comment]
Here are some screenshots from the current version (using the new icons from #475). The sidebar width looks good in app settings and entry editor but too wide in DB settings. Vertical spacing could be reduced in all three. Icon size is good, smaller icons wouldn't buy much because the texts are wider than the icons (and I wouldn't reduce the font size). And, of course, all three should use identical sizes. Haven't checked the upcoming Report dialog (#551) but will make it behave accordingly. By the way, there _is_ a can-scroll-vertically indicator on my system.

* App settings
![before_appsettings](https://user-images.githubusercontent.com/25565229/71533312-5453cd00-28f8-11ea-9948-a027d1570781.png)

* DB settings
![before_dbsettings](https://user-images.githubusercontent.com/25565229/71533313-5453cd00-28f8-11ea-8f00-25e69da3a52e.png)

* Entry editor
![before_entry](https://user-images.githubusercontent.com/25565229/71533314-5453cd00-28f8-11ea-9649-930e943254b5.png)

**Comment by droidmonkey** [comment]
There is a lot of vertical padding that can be reduced.

**Comment by wolframroesler** [comment]
Will look into it.

Are you sure you want it in the same PR? It doesn't seem to be related to the icons really.

**Comment by droidmonkey** [comment]
It can be in a different one, that is fine.

**Comment by phoerious** [comment]
This whole thing is a custom widget I wrote years ago. The inconsistent widths look like a bug to me.

**Comment by wolframroesler** [comment]
@phoerious you're right, it looks like a bug in `CategoryListWidget` or `CategoryListWidgetDelegate`. Do you remember enough about how it works to have a look into it?

**Comment by phoerious** [comment]
Only the basics. I know I had to implement some workarounds to make the selection highlight colour span the whole width and height of an entry on Windows.
