### ISSUE TITLE
Support live theme switching for Linux

### ISSUE THREAD

**Issue by shbach** [keepassxreboot/keepassxc#7146]
## Summary

[Live theme switching](https://github.com/keepassxreboot/keepassxc/pull/6034) works for Windows and Mac but on Linux I still need to close and reopen the application for the theme to switch.

## Context

Getting feature parity would be most appreciated as having to manually close the app, reopen the app, and finally unlock the database again is not ideal.

**Comment by phoerious** [comment]
This is supported already, check your KeePassXC version.

**Comment by shbach** [comment]
@phoerious In what version was support added? I'm on 2.6.6 which is the latest available.

**Comment by phoerious** [comment]
Not sure. Long ago. Live switching is supported for light and dark mode on all platforms. Only switching between our themes and the classic theme isn't, because too many components need to be redrawn and the UI ends up a complete mess.

**Comment by droidmonkey** [comment]
If you are using the snap distribution that has a hard time picking up themes. That is a known problem with snaps in general.

**Comment by phoerious** [comment]
To be clear: By live switching I mean clicking the desired theme option in the view menu without a restart. KeePassXC doesn't detect if your desktop theme changed, because Linux desktops don't send the appropriate signals for that. If you mean this, then there is indeed a feature imparity, which we can do absolutely nothing about.

**Comment by shbach** [comment]
@droidmonkey I'm not using snap/flatpack but what is available in the package manager (Solus Linux).

@phoerious I am indeed referring to detecting if the system theme changed and updating accordingly when using the "Automatic" theme option. KeePassXC is actually essentially the only app on Linux I use that doesn't update on system theme change. e.g. Firefox, Geary, all the GNOME apps, Signal, Joplin, etc all update fine without needing a restart but I guess KeePassXC is implemented differently?


If I use the "Classic" theme option, then KeePassXC actually does update on system theme change without needing a restart (for the most part) but there are elements that remain illegible:
![image](https://user-images.githubusercontent.com/5298745/142741998-7da02c16-5e28-4494-a8f9-6db556a08b5a.png)
![image](https://user-images.githubusercontent.com/5298745/142741969-71ae0971-55aa-4d8f-afd7-d9fcbb2b9ff4.png)

Unless I restart:
![image](https://user-images.githubusercontent.com/5298745/142742008-26ebf2b6-7139-4f80-b93b-067006eeda9d.png)
![image](https://user-images.githubusercontent.com/5298745/142742234-9a0c9d22-9682-4f26-8b0a-b3a69852aef9.png)
In which case it then displays as expected.

**Comment by phoerious** [comment]
The classic theme simply uses your system's Qt theme, so that it out of our hands, but tends to work.

In the other hand, it is not possible to detect that for our custom themes, because there is no real indication as to whether the new theme is a "dark" theme or not. Our way of detecting that when you choose "Automatic" is to check whether the current palette is "light-ish", but that only works once at startup before we modify the palette with our custom theme. Secondly, there isn't even a signal that we could listen for when a theme change happens. We could check if there are some global QEvents being sent around, but that is highly desktop-specific.

**Comment by shbach** [comment]
Oh I see. I guess it's because this uses Qt and everything else I listed as being able to do it uses GTK.

**Comment by shbach** [comment]
@phoerious 

> In the other hand, it is not possible to detect that for our custom themes, because there is no real indication as to whether the new theme is a "dark" theme or not.

It may be possible now:
https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference

**Comment by phoerious** [comment]
Coming in 2.7 with #7422.
