### ISSUE TITLE
Chrome Addon not available

### ISSUE THREAD

**Issue by cf-rewe** [keepassxreboot/keepassxc#7147]
## Overview
The Website which should provide the chrome addon is not available.
https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk

You'll get a http error 404.

**Comment by michaelk83** [comment]
@droidmonkey You may want to pin something about this on the main board. Many people aren't aware that there's a separate board for the extension.

**Comment by cf-rewe** [comment]
Hi @droidmonkey 
sorry, you are right. I'll post it there.

regards

**Comment by droidmonkey** [comment]
We are well aware of this situation

**Comment by varjolintu** [comment]
Related: https://github.com/keepassxreboot/keepassxc-browser/issues/1457

**Comment by aydintb** [comment]
Chrome add on is causing some weird problems with web pages after the Chrome update two days ago.
For example, it interferes with the Notion functionalities and makes is useless.

**Comment by varjolintu** [comment]
@aydintb Yes it does. And because Google removed our extension from the store, users are locked to the buggy version.

Your options here is to use another browser (Firefox or Edge), or download the current release and load it as an temporary extension (which needs native messaging script modifications).

**Comment by aydintb** [comment]
I just downloaded and loaded, it works smooth. Thanks.
