### ISSUE TITLE
Snapshot 2.7.0 from '2022-01-08 23:52': KeeShare destroys the linked .kbdx database file (size of 0 bytes)

### ISSUE THREAD

**Issue by mgeramb** [keepassxreboot/keepassxc#7310]
Steps to reproduce:

create new database "Project" and create one Entry in this DB.
save this db as "Project.kdbx"
close the database "Project"
create new database "Import"
create group "Project" and enable KeeShare with the mode "Syncronize"
enter path to "Project.kdbx"
enter password of "Project" and press 'OK'
a red banner with an error "access denied" with the path to the "Project.kdbx" appears.
The Project.kdbx files have now a size of 0 bytes.

For me this sounds that the problem is not in the syncronization logic itself. It seems the problem occurs in the file handling which causes the 0 bytes file.

## Overview
Sync with KeeShare destroy linked database file

## Steps to Reproduce
1. create new database "Project" and create one Entry in this DB.
1. save this db as "Project.kdbx"
1. close the database "Project"
1. create new database "Import"
1. create group "Project" and enable KeeShare with the mode "Syncronize"
1. enter path to "Project.kdbx"
1. enter password of "Project" and press 'OK'. 

## Expected Behavior
The Project.kdbx should have the same size at it was before it was linked,
The Entry which was created in the "Project" database will now be shown in the linked group of the "Import" database

## Actual Behavior
A red banner with an error "access denied" with the path to the "Project.kdbx" appears.
The Project.kdbx files have now a size of 0 bytes.

## Context
Snapshot 2.7.0 from '2022-01-08 23:52'
OS: Windows 10
Tested also without any active maleware scanner to be sure that there is no sideeffect from it.

**Comment by droidmonkey** [comment]
OMG I made a dumb error. You saved my bacon!

I left this old cold in place which opens the share file for writing... but never closes it. So when the new code, which uses the database class's saveAs method instead, tries to write to the file... it cannot because it is held open. Easy fix thankfully, just delete this remaining old code.

https://github.com/keepassxreboot/keepassxc/blob/56a1b465a15f27f21de9df1e0eb48f8ac94662fd/src/keeshare/ShareExport.cpp#L158-L163
