### ISSUE TITLE
Unable to connect native KeePassXC to flatpak Firefox

### ISSUE THREAD

**Issue by WineBottles** [keepassxreboot/keepassxc#7352]
I followed the instructions here: https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437 to expose Firefox/KeePassXC to each other but I am not having luck actually getting them to connect.

## Steps to Reproduce
1) Downloaded the attached keepassxc-proxy and placed it in ~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts
2) Created the file org.keepassxc.keepassxc_browser, copy and pasted the lines and replaced the path with my username where required
3) Rebooted. Started KeePassXC first then Firefox

## Expected Behavior
Flatpak Firefox should be able to connect to native KeePassXC

## Actual Behavior
Clicking on the KeePassXC add-on in my browser bar says:
```
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
```

Going into about:debugging says:
```
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1187:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1104:13
Failed to connect: Unknown error
```

## Context
I am not sure if I need to be changing the "browser integration" settings in KeePassXC, as the article I linked at the top here says it should just work. I tried turning off and on integrated with Firefox as well as  going into the advanced tab and turning off and on "Use a custom browser configuration location:
```
Browser type: Firefox
Config Location: /home/MYUSERNAME/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts/
```

When I have "Update native messaging manifest files at statup" it changes
```
/home/MYUSERNAME/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts/keepassxc-proxy
```
to
```
"path": "/usr/bin/keepassxc-proxy",
```
So I know that is not as expected and I should probably not use that config.

[NOTE]: #
KeePassXC 2.6.6
Firefox flatpak 96.0.3

[NOTE]: #
Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.16-hardened1-1-hardened (64-bit)
Graphics Platform: X11

**Comment by droidmonkey** [comment]
You cannot use the browser extension when the _browser_ is in a flatpak or snap. It is impossible until they introduce a plug that let's that communication happen.

**Comment by WineBottles** [comment]
> You cannot use the browser extension when the _browser_ is in a flatpak or snap. It is impossible until they introduce a plug that let's that communication happen.

I'm confused. This article discusses how to connect KeePassXC and Mozilla Firefox even if both are. I had only did the half part because KeePassXC is native.

"Hooray!: For those, who install KeePassXC on the host (without any sandbox/flatpak), this is enough. Start KeePassXC and then Firefox and it should be able to connect. :tada:
Please note the “existing problems” section at the bottom, though."

https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437

**Comment by droidmonkey** [comment]
That isn't posted by our team and I have no idea if it still works. You are on your own here.

**Comment by remyabel2** [comment]
@WineBottles https://github.com/flathub/org.keepassxc.KeePassXC/issues/29

**Comment by zeitisen** [comment]
Unfortunately there is no native Firefox anymore with Ubuntu 22.04. Even if you install from packet with apt, you end up with a snap. So what now?
Should I change to Windows or to Chromium? Or setup from tar? There should be a simple solution

**Comment by droidmonkey** [comment]
Petition canonical if you want a simple solution. Snaps ain't it.

**Comment by mo8it** [comment]
@zeitisen Take a look at this guide:
https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

Maybe try [Fedora](https://getfedora.org/en/workstation/) in the future. It is very stable, more up to date and has no snap crap. There are many installation guides and reviews in the internet (including YouTube).
Fedora has Gnome by default. If you like Gnome, then [Gnome itself recommends Fedora on the first place](https://www.gnome.org/getting-gnome/).

I hope that Flatpak Firefox can handle KeePassXC in the future. Thanks to the developers anyway. I know that Canonical does weird things, but I think that the users should not be blamed for not doing a new install of another distro. Lets help euch other :)
No offense to anyone :)

**Comment by westonstewart** [comment]
Ran into this same issue in the last few weeks, as I transitioned my 2012 MacBook Pro from macOS Catalina (10.15.7) to Ubuntu 22.04.1.  My solution was to:

1.)  Uninstall snap entirely (https://github.com/MasterGeekMX/snap-to-flatpak)
2.)  Follow the manual installation instructions for Firefox (https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-from-mozilla-builds-for-advanced-users)
3.)  Install KeepassXC from the Ubuntu PPA (https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc)

Once Firefox and KeePassXC were installed, I added KeePassXC-Browser to Firefox ... and KeePassXC and Firefox connect as designed; indeed, this setup works pretty much the same as it did on macOS.

Other thoughts:  I should note that Firefox (and Thunderbird, which I installed using the same method) receives its updates internally (going to Help > About Firefox or Help > About Thunderbird).  This may not be standard Linux behavior, but it was normal under macOS (and I actually prefer it) and thus is "more of the same" for me.  Having all three apps installed and working properly (without the need for either snap or flatpak) was an important goal for me ... and this browser extension issue forced me to find a solution that would work independent of those environments.

EDIT (8/23/23):  This setup continues to work for me today (running Ubuntu 22.04.3), and specifically works while running Wayland (re noisystuff's post below).  Although I haven't tested it with other Linux distros, it should work with KeePassXC installed via any standard package manager (apt, dnf, pacman, et cetera).  It also worked for me using the AppImage version of KeePassXC, which I didn't really expect to work, but it did.

Above, droidmonkey said "Petition canonical if you want a simple solution. Snaps ain't it."  I would say much the same about Flatpak.  This is one use case where I think sandboxing hurts more than it helps.

**Comment by eklenin** [comment]
It would be very nice to have the way to connect keepassxc to sandboxed browser.

**Comment by noisystuff** [comment]
Hi Folks.
I like my security :-) so I'm running Keepassxc, Firefox and most other applications as Flatpak (on Kubuntu). I plan to soon use Wayland, but as we know, it won't 'permit' autotype (no API for passing characters between applications and I can't see that ever being permitted for security reasons). Looking forward, I suspect Flatpak will become more and more popular as being the default way to install graphical applications (and of course, more people will start using Wayland) so to me it would seem prudent to ponder  some form of a robust solution (for a Flatpak browser addon to be able to communicate with Flatpak Keepassxc). I'm an old geezer, so ctrl+c and ctrl+v are 'muscle memory', but I'd expect gen z and the likes might expect a pointy clicky solution (just trying to raise a smile with that last comment); heck, even I'll massively miss autotype so yes, even I would like a pointy clicky solution. 
All the best, Briain

**Comment by PhrozenByte** [comment]
I followed the initially mentioned guide (also on [Stack Exchange](https://unix.stackexchange.com/a/584522/568971)) a few days ago and since it didn't work at first because the paths are outdated, I did some research and it seems like one really just needs two things today: Allow the sandboxed Firefox to access KeePassXC's socket and copy the `keepasxc-proxy` binary to Firefox's sandbox. It doesn't matter whether KeePassXC itself is sandboxed or not. So, in the end this is as simple as:

1. Allow Firefox's sandbox to access KeePassXC's socket: `flatpak override --filesystem=xdg-run/app/org.keepassxc.KeePassXC/:create org.mozilla.firefox` (with either `--user`, or `sudo`)
2. Copy the `keepassxc-proxy` binary to the sandbox; since the Firefox sandbox naturally can't access shared libs of the host (or even of the KeePassXC sandbox), we need a statically linked binary here; I don't know anything about KeePassXC's source code, thus I don't know whether it's possible to build the original `keepassxc-proxy` like that (probably needs some changes), but in the meantime one can use [`varjolintu/keepassxc-proxy-rust`](https://github.com/varjolintu/keepassxc-proxy-rust) instead; it's so tiny that one can check the source code line by line themselves (I did, it's safe)...
3. Manually setup the browser extension as usual (i.e. create `~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts` and create a `org.keepassxc.keepassxc_browser.json` referencing the copied `keepassxc-proxy`, then link the extension with the database as usual)

I believe that KeePassXC could do steps 2 and 3 automatically with a new "Firefox (Flatpak)" browser type. Step 1 surely needs some documentation, but truly isn't that big of a deal.

There's one limitation though: The sandboxed Firefox can't start KeePassXC. Thus the user must start KeePassXC themselves. This is a permanent limitation for now. ~~However, there's yet another, a little more annoying, but probably solvable limitation: KeePassXC must even be started *before* Firefox (this also means: if one restarts KeePassXC, one must also restart Firefox). I'm not entirely sure whether this is a limitation of KeePassXC, the browser extension, `varjolintu/keepassxc-proxy-rust`, or Flatpak, but following https://github.com/varjolintu/keepassxc-proxy-rust/pull/11 I think it's due to both the browser extension and `varjolintu/keepassxc-proxy-rust` - i.e. it appears to be solvable by incorporating some changes.~~ For now this limitation can be circumvented by using KeePassXC's "Automatically launch KeePassXC at system startup" and "Minimize instead of app exit" options (optionally combined with "Minimize window at application startup" and "Show a system tray icon"; personally I used these options before anyway…).

Since `keepassxc-proxy`'s only purpose is to speak with the socket, it's a perfectly safe solution and utilizes full sandboxing for both KeePassXC and Firefox.

Besides, I'm aware that a native messaging portal has been suggested as a permanent, fully functional and "native" (in the sense of "not requiring workarounds") solution. However, it has been three years now and still I didn't find anything about its status. Flatpak matured in the past years and is more commonly used, personally I'm even thinking about whether I want to have native apps on my system. So, I guess this might be a working solution for now that could be implemented in KeePassXC?

Cc: @droidmonkey @rugk

---

Here's the full instructions for others to get this working in the meantime:

```sh
# install Firefox and KeePassXC
flatpak install flathub org.mozilla.firefox
flatpak install flathub org.keepassxc.KeePassXC

# create native-messaging-hosts
FLATPAK_FIREFOX_CONFIG="$(realpath ~/.var/app/org.mozilla.firefox/.mozilla)"
mkdir "$FLATPAK_FIREFOX_CONFIG/native-messaging-hosts"
cat > "$FLATPAK_FIREFOX_CONFIG/native-messaging-hosts/org.keepassxc.keepassxc_browser.json" <<EOF
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "$FLATPAK_FIREFOX_CONFIG/native-messaging-hosts/keepassxc-proxy",
    "type": "stdio"
}
EOF

# build varjolintu's keepassxc-proxy-rust and copy it to native-messaging-hosts
# you might need to install Cargo first, but can remove it after building the project again
git clone https://github.com/varjolintu/keepassxc-proxy-rust.git
cd keepassxc-proxy-rust
cargo build --release
cp ./target/release/keepassxc-proxy "$FLATPAK_FIREFOX_CONFIG/native-messaging-hosts/keepassxc-proxy"

# allow the Firefox sandbox to access KeePassXC's browser socket
# with `sudo` it's a system-wide change, without one can add the `--user` option instead to make it a user-specific override
sudo flatpak override --filesystem=xdg-run/app/org.keepassxc.KeePassXC/:create org.mozilla.firefox
```

**Comment by droidmonkey** [comment]
Placing the proxy within another apps sandbox is not a solution we endorse. It may work but that is definitely not something we will implement.

**Comment by PhrozenByte** [comment]
> Placing the proxy within another apps sandbox is not a solution we endorse. It may work but that is definitely not something we will implement.

What is the reason for that? The proxy doesn't implement any logic on its own, but just connects the application (Firefox) with KeePassXC running in another sandbox. Can you please elaborate on possible security implications and/or other general disadvantages of this solution, especially in comparison with (1) the currently endorsed non-sandboxed approach (i.e. both KeePassXC, or at least Firefox running on the host), and (2) a native messaging portal? Since (1) doesn't include any sandboxing or sandboxing that matters (running KeePassXC in a sandbox protects the host from KeePassXC, not KeePassXC from Firefox) I'd say it causes an overall lower security than the suggested solution?

**Comment by darkfessing** [comment]
@PhrozenByte 

Interesting solution. I tried to compile it this way and with x86_64-unknown-linux-musl. But it doesn't work. Got error "Key exchange error". Checked everything, permissions, paths.. What could go wrong?

Browser extension debug in Firefox says:
```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:383:13](moz-extension://175aeae6-9267-47da-b024-f6e3bfb9530c/background/client.js)
[Error ] KeePassXC-Browser - Failed to connect: Unknown error [global.js:168:13](moz-extension://175aeae6-9267-47da-b024-f6e3bfb9530c/common/global.js)
[Error client.js:402] KeePassXC-Browser - No content script available for this tab. [global.js:168:13](moz-extension://175aeae6-9267-47da-b024-f6e3bfb9530c/common/global.js)
[Error keepass.js:810] KeePassXC-Browser - 9: Key exchange failed. [global.js:168:13](moz-extension://175aeae6-9267-47da-b024-f6e3bfb9530c/common/global.js)
[Error keepass.js:421] KeePassXC-Browser - No content script available for this tab. [global.js:168:13](moz-extension://175aeae6-9267-47da-b024-f6e3bfb9530c/common/global.js)
```

**Comment by rugk** [comment]
@PhrozenByte yeah AFAIK flatpak also [supports extensions](https://docs.flatpak.org/en/latest/extension.html) which are like plugins. In this way, one could ship a `KeePassXC` extension for the Firefox (or other browsers) flatpak, which does all this automatically, and then you can install and use `KeePassXC` as usual.

**Edit:** I've pitched this idea to the Mozilla devs in https://bugzilla.mozilla.org/show_bug.cgi?id=1942175 and on Flathub's forum: https://discourse.flathub.org/t/pitch-idea-firefox-flatpak-extension-to-run-keepassxc-with-a-flatpaked-firefox/8673

**Comment by jeriox** [comment]
> [@PhrozenByte](https://github.com/PhrozenByte)
> 
> Interesting solution. I tried to compile it this way and with x86_64-unknown-linux-musl. But it doesn't work. Got error "Key exchange error". Checked everything, permissions, paths.. What could go wrong?
> 

I got the same error when trying this for myself. Would love to get this working

**Comment by PhrozenByte** [comment]
@darkfessing @jeriox You should probably report that directly at https://github.com/varjolintu/keepassxc-proxy-rust, maybe the developer has an idea and can provide a fix.

**Comment by jeriox** [comment]
> [@darkfessing](https://github.com/darkfessing) [@jeriox](https://github.com/jeriox) You should probably report that directly at https://github.com/varjolintu/keepassxc-proxy-rust, maybe the developer has an idea and can provide a fix.

The developer seemingly has no interest in making this work.... https://github.com/varjolintu/keepassxc-proxy-rust/issues/23#issuecomment-2601029651

**Comment by droidmonkey** [comment]
This isn't on us. Flatpak has _not yet incorporated_ the necessary desktop portal for browsers to offer native messaging support. Snap hasn't either, but Firefox basically backdoor implemented it on their snap. The whole thing is a mess, ~~just don't come here and claim it's ours~~ please send complaints to the browsers themselves so they can press on Snap/Flatpak maintainers.

**Comment by jeriox** [comment]
> just don't come here and claim it's ours.

this was definitely not my intention, sorry if it came across that way!

I just saw the workaround above that was proposed by @PhrozenByte which sounded like a good idea to me and which apparently worked for him. I just hoped for some support to get that running as well.

**Comment by droidmonkey** [comment]
No worries, my frustration is with Snap/Flatpak and not with anyone here. Pretty crappy to force all browsers into that standard and leave a gaping hole in capability quite a few extensions rely on.

**Comment by PhrozenByte** [comment]
@jeriox

I think you unfortunately misunderstood me: I didn't want to suggest that you ask him whether he wants to support this workaround (remember, `varjolintu/keepassxc-proxy-rust` has absolutely nothing to do with it, we're just exploiting his work for our workaround), but to ask him about your key exchange issue. I don't think your key exchange issue is even related to this Flatpak workaround.

@droidmonkey

I absolutely agree with you that this primarily is an issue of Flatpak and Firefox. They must provide the necessary APIs to integrate this nicely. I can absolutely feel your (and, by proxy, the project's) frustration about the matter, because more and more people want to use Flatpak and consequently ask why it isn't working. The reason I can feel your frustration is because I feel the exact same frustration when looking at https://github.com/flatpak/xdg-desktop-portal/pull/705: Work on the portal started three years ago (!!) and it still didn't make it into Flatpak, even though the code is ready for years now.

However, I also feel like that the workaround presented in this GitHub Issue isn't given enough consideration on KeePassXC's side, too. I absolutely agree that the original concept of a workaround (I mean the one that basically meant running KeePassXC from within the Firefox sandbox) wasn't even remotely an option. However, thanks to [`varjolintu/keepassxc-proxy-rust`](https://github.com/varjolintu/keepassxc-proxy-rust), @rugk's research, and KeePassXC's work on consolidating the socket paths, I feel like we [now have a well working workaround](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409096972) that could be integrated into KeePassXC with minimal documentation and thus at least deserves some consideration.

That is why [I asked](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409101664) earlier why [you rejected](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409099707) the [latest workaround](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409096972) so categorically. I honestly don't see an issue with it, but I could absolutely miss something. Maybe you've provided reasoning elsewhere earlier already, unfortunately I didn't find any even though I definitely looked for it while summarizing @rugk's workaround. I could also massively underestimate the work required. Or you could also say that you (and, by proxy, the project) don't want to invest resources into integrating such workaround, but then whether you'd accept a pull request. That's why I asked for reasoning. I can't and won't ever demand anything from you, we're all participating in our free time here and it's absolutely up to you what you do with your free time, but in my experience not giving at least basic reasoning leads to even more frustration.

This should not disguise the fact that it still is a workaround and the problem definitely lies with Flatpak and Firefox. However, making this workaround more accessible would surely reduce frustration on all sides - unless there are good reasons why this workaround is a bad idea in general of course. Yes, none of this is KeePassXC's fault, not even its job, but if KeePassXC could improve the situation, why not do it if it's reasonably possible?

Thank you for your help @droidmonkey :heart:

**Comment by droidmonkey** [comment]
I rejected it because that is a dangerous precedent to set by injecting binaries into another app's sandbox. Would you like it if a random app injected their stuff into KeePassXC's flatpak or snap sandbox? That is a major violation of the sandbox principles. Sure you can do anything as root, but "with great power, comes great responsibility".

**Comment by moberer** [comment]
(Not an expert in this, this is just an idea that came to my mind; Please disregard if it completely misses the point;)

Would it be feasible to switch the communication between the Browser Addon and the KeepassXC-Instance to use dbus instead of using raw sockets?

As far as I understand Flatpak natively understands DBus and permissions can selectively be given to access certain endpoints (and also after installation - with a single command) and show an endpoint to the rest of the system.

This would allow the permissions to be tweaked without much fiddling and without an additional proxy inside the sandbox.

What I do not know is whether it is possible to make DBus-Calls from a Firefox Addon.

**Comment by droidmonkey** [comment]
That wouldn't solve anything because browsers do not allow extensions to connect to dbus. The only other solution is to switch back to http based communication which brings its own complications.

**Comment by PhrozenByte** [comment]
> That is a major violation of the sandbox principles. Sure you can do anything as root, but "with great power, comes great responsibility".

I agree. However, that's true for basically any sandbox portal, and isn't much different from https://github.com/flatpak/xdg-desktop-portal/pull/705. In fact, the current proposal for the portal is way more critical than our workaround, because the portal allows starting processes outside the sandbox from within the sandbox. It can't really get any more critical than that - and is a major reason why the portal still didn't make it into Flatpak: The portal can be abused by an attacker to escape the sandbox and there's no accepted proposal for a security model. In contrast, the workaround only allows for communicating with KeePassXC and requires KeePassXC to run already (which is a major limitation of the workaround). IMHO that's actually less critical than the portal. Or do I miss something?

> I rejected it because that is a dangerous precedent to set by injecting binaries into another app's sandbox. Would you like it if a random app injected their stuff into KeePassXC's flatpak or snap sandbox?

Depends. If it requires user interaction (which it does, it even requires root permissions) I don't really see much of an issue. More importantly, KeePassXC can't tell the browser sandbox to run that binary and it doesn't "trick" the browser sandbox to run it. The workaround rather works precisely as expected by the Native Messaging API. One might criticize the Native Messaging API that it runs arbitrary binaries, but what am I missing that it is more critical now, but wasn't that much before?

Another thing to consider are the alternatives: KeePassXC currently endorses users to *not* run the browser in a sandbox. Is it safer to not run the browser in a sandbox, than running the browser in a sandbox with this workaround? What am I missing here?

**Comment by moberer** [comment]
Yes, running the browser in a sandbox is generally preferable from a security standpoint;
Even with a slight weakening through some added permission.


Though I can understand why the KeepassXC team do not currently endorse this solution:

With the current situation, the user needs to download random code from a git repo, compile it and place it somewhere it can be run.
If users follow these kind of instructions, it would be pretty easy to insert some malicious code in the proxy, allowing for e.g. browser cookies / logins to be sent to a malicious entity from within the sandbox. (I'm not saying it currently is; it is just happens to be quite easy with these kinds of things.)

Same thing if this was "built in" into KeepassXC:
The program (or worse - the browser addon) show some random command, you need to run as root?
Just copy-paste and run it! - I think it is pretty clear why we don't want this sort of thing to become the norm.

Nevertheless, I'd have to argue that it would be good to at least have an up-to-date guide in the official documentation (with an adequate disclaimer, of course), instead of people who want this having to run commands from random Stack Overflow answers or forum threads.

---

I think, what we'd really want here is a change in firefox itself to expose a better kind of API with which extensions can talk to other programs on the system, even through the flatpak isolation layer. 

(As far as I know, there has been some talk about something like this, but nothing has materialized yet. Edit: Here: https://bugzilla.mozilla.org/show_bug.cgi?id=1621763)

**Comment by acolomb** [comment]
Pardon my ignorance, but talking to a specific different program on the same machine sounds like the perfect use-case for a socket bound to localhost on a specific port.  Has something like that been tried already?  Of course, KeePassXC would need to listen on it and the port must be configurable in the extension.

Is it possible to allow specific TCP ports on localhost to be accessed from inside the flatpak sandbox?

Connection security / authentication can still be handled easily through the pre-shared secret, as it is now with the Native Messaging solution.

**Comment by darkfessing** [comment]
The only solution I found is to disable KeepassXC addon in browser and use KeepassXC directly (copy-paste). So much for user experience :)

**Comment by noisystuff** [comment]
I've used  Flatseal to disable Wayland (socket=wayland) for KeepassXC and  Firefox  and by forcing them to use Xwayland (socket=x11) as that facilitates using hot-keys and KeepassXC's auto-type feature to populate the browser fields. Okay, it defeats a key security enhancement offered by Wayland (so risking text being captured by a keystroke logger) but my network's pretty well bolted down and I use my head for storing banking passwords (or the likes), so in my case it's a useful solution with a reasonably low risk. Interestingly, I haven't had to change the default Flatseal settings for Linux Edge (socket=x11 and socket=wayland are both enabled) as Edge defaults to using Xwayland. 
All the best to all, 
Briain :-)

**Comment by Korydween** [comment]
@noisystuff unfortunately this did not work for me (Ubuntu 24.10). I have both installed as flatpaks, I disabled socket=wayland and left activated socket=x11. I can see from the terminal that my browser is switching to X11, but unfortunately the connection window does not appear when I am trying to connect. 

I am not sure from keepassxc though if it is switching to x11... I do have an error message "Could not load the Qt platform plugin "wayland" in "" even though it was found", but unsure if that is enough...

**Comment by boukendesho** [comment]
> [@noisystuff](https://github.com/noisystuff) unfortunately this did not work for me (Ubuntu 24.10). I have both installed as flatpaks, I disabled socket=wayland and left activated socket=x11. I can see from the terminal that my browser is switching to X11, but unfortunately the connection window does not appear when I am trying to connect.
> 
> I am not sure from keepassxc though if it is switching to x11... I do have an error message "Could not load the Qt platform plugin "wayland" in "" even though it was found", but unsure if that is enough...

I'm ubuntu 24.10 too. Firefox snap + keepassXC snap works OOTB for me.

**Comment by mpeter50** [comment]
@PhrozenByte 

> Depends. If it requires user interaction (which it does, it even requires root permissions) I don't really see much of an issue.

the proxy can be moved to the flatpak package's data directory at ~/.app/..., which does not require root permissions. and droidmonkey has a point, that we don't want to popularize the wild west that is on windows, that certain utility programs just haphazardly replace files in your profile directory, just because it has the access

> However, there's yet another, a little more annoying, but probably solvable limitation: KeePassXC must even be started before Firefox (this also means: if one restarts KeePassXC, one must also restart Firefox). I'm not entirely sure whether this is a limitation of KeePassXC, the browser extension, varjolintu/keepassxc-proxy-rust, or Flatpak,

did some experiments a few weeks ago and I'm almost sure its flatpak. 

Part of the problem that causes this to be hard to see is that at a lot of places the rust proxy just unwraps the errors, which naturally leads to a crash, instead of printing out the error, and also that firefox does not show the proxy's stderr messages on the addon's about:debugging page, but only in the browser console. 

I have added a bunch of debug printouts in the rust proxy, and turns out the issue is that changes to socket files (maybe others too) won't be visible inside the running flatpak environment until restarted.  
If keepass is started later than flatpakd Firefox, the socket file won't be visible for the proxy, and `UnixStream::connect()` [here] (https://github.com/varjolintu/keepassxc-proxy-rust/blob/a77ce2d573a1fa3826f894b7fea54b3000530891/src/proxy_socket.rs#L96) will result in a `NotFound` error kind.  
If Keepass is restarted while flatpakd firefox is running, it recreates the socket file, and if the proxy tries to connect it will receive a `ConnectionRefused` error kind. This is also what happens if you start firefox, stop keepass, and delete the socket file.

if you want to see it for yourself, wrap the UnixSocket::connect() call in a dbg() macro like this:
```rust
        .find_map(|dir| dbg!(UnixStream::connect(dir.join(socket_name))).ok())
```
then recompile, replace, restart firefox, try to connect the addon and watch the browser console. 

so I'm pretty sure this is flatpak's, or bubblewrap's filesystem sandboxing. I don't know if this is by design or a bug.

**Comment by rugk** [comment]
> so I'm pretty sure this is flatpak's, or bubblewrap's filesystem sandboxing. I don't know if this is by design or a bug.

@mpeter50 As you have investigated this quite much (which I appreciate), what about asking or creating an issue in the flatpak repo about this? After all it's either a bug or at least maybe something to document on their side or so?

**Comment by mpeter50** [comment]
Sure, but I think maybe I found something in the documentation, now that I checked.

> If `--filesystem=host` is used `/media`, `/run/media` is shared automatically if they exist.

https://docs.flatpak.org/en/latest/sandbox-permissions.html#external-drive-access

The gist is the part "if they exist". This is at the external drives section, but I think this applies to everything else too.
But, both [PhrozenByte](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409096972) and me have committed to only passing the socket file to the flatpak container, because why not keep the filesystem access tight:

![Image](https://github.com/user-attachments/assets/4b82d323-df28-41d7-aa18-85c31db3b203)

And you know how linux usually handles files.. often not by the path but by the inode. And when Keepass starts up, it recreates the socket file (I assume), and now that is _technically_ a different file than what was passed in to Librewolf's sandbox. Librewolf's sandbox still keeps a reference to the old socket file, similarly to when you delete files that have been opened by a program. And the sandbox does not see at all if the file is recreated, because the specific file (by its inode) was bind mounted into the sandbox or something like that.
So, this probably explains why does it not work if Keepass is started after Lirbewolf.

**Comment by mpeter50** [comment]
It seems this was the cause of it. After removing the filesystem access override for the full path of the socket file, and adding a new override to the directory of it, and restarting Librewolf, now it does not matter anymore if I restart Keepass, Librewolf will still be able to use it.

I added the override for the directory with create mode so there is no problem if the directory does not exist yet (otherwise Flatpak would just ignore that override) when  Librewolf starts up, like if you just logged in.

```
$ flatpak --user override --show io.gitlab.librewolf-community
[Context]
filesystems=xdg-run/app/org.keepassxc.KeePassXC:create;
```

**Comment by mpeter50** [comment]
@rugk now that we know what was the problem, do you think it would be worth to report it?

**Comment by PhrozenByte** [comment]
@mpeter50 I've updated [my instructions](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409096972) accordingly for now and will give it some testing later. Thanks for investigating!

@droidmonkey Does KeePassXC create any other files in the `$XDG_RUNTIME_DIR/app/org.keepassxc.KeePassXC/` directory? We're exposing this directory to another sandbox after all. I'm well aware that you're no fan of the approach in general, but I'd like to keep it as safe as possible. Unfortunately, a real solution on Flatpak's side is further away than before and unlikely to materialize in the next few months.

**Comment by droidmonkey** [comment]
We only put the browser socket file in there.

**Comment by rugk** [comment]
> [@rugk](https://github.com/rugk) now that we know what was the problem, do you think it would be worth to report it?

If you think it is by design then not, otherwise asking won't hurt. 🤷

**Comment by mpeter50** [comment]
Posted a question on the Flatpak forum: https://discourse.flathub.org/t/cannot-share-a-single-file-to-app-if-it-is-recreated-after-app-startup/9391

Please have a look to see if I explained our situation clearly.

**Comment by mpeter50** [comment]
Writing here to connect the issues on github: rugk found an existing issue in the flatpak repo for this same problem.

flatpak/flatpak#5370

It does not look like it can be solved from the flatpak side. A workaround may be to put the socket file into a directory where it is alone, e.g. in a subdir of the current location.
I wonder if that may be achievable as a user with a symlink. Or with some FUSE filesystem that mounts the directory in a subdirectory, but only actually makes the wanted file visible and accessible, but that sounds very ugly.

**Comment by PhrozenByte** [comment]
@mpeter50 See https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2792269044, it is the only file and I've updated [my instruction](https://github.com/keepassxreboot/keepassxc/issues/7352#issuecomment-2409096972) accordingly already.

**Comment by mpeter50** [comment]
Yes, for now

**Comment by Utini2000** [comment]
I don't understand why this is closed when flatpaks become more and more the usual standard. Atomic OS like Fedora Kinoite will be also the new standard (e.g. Fedora will default to Atomic OS by 2028). 

I am a big fan of KeePassXC on Linux and Windows but this really needs to be resolved cause it will annoy a lot of users.

**Comment by droidmonkey** [comment]
Because it's literally not our problem to solve. The desktop portal has yet to merge in support for native messaging for flatpaks (or snaps for that matter). It's crazy.

**Comment by Utini2000** [comment]
> Because it's literally not our problem to solve. The desktop portal has yet to merge in support for native messaging for flatpaks (or snaps for that matter). It's crazy.

You mean https://github.com/flatpak/xdg-desktop-portal/ ?

Is there already an ongoing issue there opened or should I create a new one there? I think we should link this issue to the xdg issue then?

**Comment by AesaraB** [comment]
@Utini2000 https://github.com/flatpak/xdg-desktop-portal/pull/1537

To anyone about to ask "wtf is happening???" please **read the thread before posting**. Chances are your question has already been answered.

**Comment by droidmonkey** [comment]
Most up to date status: https://github.com/flatpak/xdg-desktop-portal/pull/1537#issuecomment-3013428674
