### ISSUE TITLE
List flatpak in Linux cross-platform section on website

### ISSUE THREAD

**Issue by cardil** [keepassxreboot/keepassxc#7373]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
There is already a KeePassXC package available, at flathub: https://flathub.org/apps/details/org.keepassxc.KeePassXC. It make sense to list it in Linux cross-platform section on website: https://keepassxc.org/download/#linux

## Examples
![Screenshot from 2022-02-02 17-12-50](https://user-images.githubusercontent.com/540893/152192625-32daf64a-268f-408f-a699-bafb33df75ed.png)

## Context
Flatpak has many advantages over Snapcraft. It's installed by default on RHEL-like systems. It has better security, and sandboxing. The flathub has automation to always fetch the deployed packages, so it's quickly updated.

**Comment by ghost** [comment]
Looks like the Flatpak package is no longer marked as official in the download section of the website.
However, the heading still says "Official cross-distribution packages". My question in this context would be, if you are planning to release an official Flatpak for the milestone 2.7.1 as KeePassXC Team and to sign and maintain this in the future.
The current package on Flathub looks like it is a modified third party developer variant of the app.

**Comment by droidmonkey** [comment]
It never was, the above is a mock up image.

**Comment by prefixtry** [comment]
Thanks for the hint!
My question is still open for me. The header "Official cross-distribution packages:" currently still suggests that the Flatpak on Flathub is an official package. However, since https://github.com/keepassxreboot/keepassxc/issues/1524 is open at the same time, I assume that it is not an official package. And my additional question was whether you want to change that as part of the next minor version.

**Comment by ghost** [comment]
Thanks for the tip!
My question is still open for me. The headline currently still suggests that the Flatpak on Flathub is an official package: "Official cross-distribution packages:" 
However, since https://github.com/keepassxreboot/keepassxc/issues/1524 is open at the same time, I assume that it is not an official package. And my additional question was whether you want to change that as part of the next minor version. Either by changing the header or by publishing your own Flatpak version of KeePassXC

**Comment by droidmonkey** [comment]
It's built from a github repository automatically, we audited the repository, there is nothing special going on.

**Comment by ghost** [comment]
It looks like the Flathub version has some non-official patches. https://github.com/flathub/org.keepassxc.KeePassXC/tree/master/patch
And the version is different from what I would expect from a version maintained by you, not up to date with your latest releases.

**Comment by ghost** [comment]
Which repository did you audit? The one from Flathub?

**Comment by ghost** [comment]
It also looks like the package creates its own issues that are not part of the official issue tracking. https://github.com/flathub/org.keepassxc.KeePassXC/issues

**Comment by droidmonkey** [comment]
If you are so concerned don't use it.
