### ISSUE TITLE
Non-ASCII Passwords have low entropy

### ISSUE THREAD

**Issue by DarkKirb** [keepassxreboot/keepassxc#7481]
## Overview
I have some passwords I generated using a script that chooses characters from all printable non-zero width unicode characters. One example of such passwords is the following:

```
𝘳ꌨ𐴏ᣱ益🆘𒉳𐲜ܗᇐꚮ𑛅𖥆ᙻ𒀜‿❱𒃊ꍻ𖫑꣙৺ќ𑜾𐤓𐘍ᕗꑇ𑠝ퟤꅘ𐡏ɹ𞡋⥅↣ꑭ𝕽𑜷𘤓ⴼ᳓𝪁ýካᕢﶞꕇꡍ𝄌𐕀𑆤ꀤ⥂㋡𝂄ہ⾽ᥣ𖮊𑚜ꢲⲌ𐅿
```

however, according to KeePassXC, a password like this is “very weak”

## Steps to Reproduce
1.  Open the password generator
2. Paste the above password into the password field

## Expected Behavior
The entropy value should be greater than a 64 character password with all ASCII and Extended ASCII characters enabled (~500bits),
or closer to 1000 bits (log2(100000^64))

## Actual Behavior
The entropy value is 30.63 bits

## Behavior in other programs
zxcvbn claims a guesses_log10 of 91, which is much closer to the real value

## Context

KeePassXC - Version 2.6.6

Qt 5.15.3
Debugging mode is disabled.

Operating system: NixOS 22.05 (Quokka)
CPU architecture: x86_64
Kernel: linux 5.15.24-xanmod1-tt

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Sway
Windowing System: Wayland

**Comment by phoerious** [comment]
When I paste that password into the password field, it shows 1421 bits here, so I cannot reproduce this at all. But anyway, the calculation is merely a hint. The actual entropy is unknown, because it depends on the alphabet size (which is undefined) and the generation mechanism (which is assumed to be random, but taking into account common patterns). It's definitely not an accurate calculation at all. All you should care about is a green bar with "Password Quality: Excellent". Everything else is purely for entertainment, shits and giggles.

In any case, I strongly recommend NOT to use such passwords. It is easy to mess up the encoding either on your end or on the server and then you are locked out of your account. It's also impossible to type on a keyboard should the need arise. Simple yet long ASCII passwords are sufficiently secure. Anything beyond, say, 256bit adds no practical protection and is nothing but feel-good security.

**Comment by droidmonkey** [comment]
There is no security benefit to using unicode passwords over ascii. None, zero, no. At the end of the day the bits are from a defined lookup range and an attacker has no idea if you are using ascii or unicode passwords anyway. It only adds unnecessary complications to you and other programs. 

An ascii password over 15 characters in length is generally uncrackable.

**Comment by DarkKirb** [comment]
1. Due to the low measured entropy the password is rated as poor, the other passwords I have of that kind also rate “poor”
![image](https://user-images.githubusercontent.com/23011243/156314593-4f6ac65b-a652-4c9d-b6d7-bbd93a37be3f.png)
2. These are passwords I am currently using, not ones that I’m currently generating. I still believe it is a bug that a 64 unicode codepoint password scores lower than a 16 digit PIN (both in terms of entropy and password quality)

**Comment by phoerious** [comment]
As I said, I cannot reproduce it. And as mentioned already, there is no security benefit in using such passwords. In the end, all that counts is the byte sequence. Whether that decodes to unreadable Unicode garbage or ASCII characters is totally irrelevant.

**Comment by tcanders** [comment]
I could reproduce what @DarkKirb describes in v2.6.6.

But in the more recent v2.7.1 the problem is gone, reproducing what @phoerious describes.

The fix came coincidentally, it seems, in commit [022154462e24551c...](https://github.com/keepassxreboot/keepassxc/commit/022154462e24551cb8a674ab5cc25b84599f3613) related to issue #4216.

The password entropy is calculated with a call to ZxcvbnMatch in PasswordHealth.cpp:

`PasswordHealth::PasswordHealth(QString pwd)
    : PasswordHealth(ZxcvbnMatch(pwd.toUtf8(), nullptr, nullptr))
{
}`

In the previous version, `.toUtf8()` was `.toLatin1()` whose result is undefined for non-Latin1 characters[undefined for non-Latin1 characters](https://doc-snapshots.qt.io/qt5-5.15/qstring.html#toLatin1).

`.toUtf8()` returns a correct QByteArray even when the input QString contains Unicode characters.

**Comment by DarkKirb** [comment]
Just retested and I cannot reproduce it anymore either. have upgraded to 2.7.1 around two weeks ago
