### ISSUE TITLE
Database Reports - Find and merge duplicated password entries

### ISSUE THREAD

**Issue by anatol** [keepassxreboot/keepassxc#750]
Hello folks

I have a database that has a lot of duplicated entries. I believe it happens because I converted my database from KDBv1 twice: once using keepassx and then converted/merged using keepassxc tool.

I do not see how to find and automatically delete all the duplicated entries. It would be great if keepassxc helped to resolve the issue. e.g. it should be great to have "delete duplicate entries" menu option. As well as check entries content during merge - if similar entry already exists then keepassxc should not merge one to the database.

**Comment by akelsch** [comment]
I would also love KeePassXC to show duplicate passwords!

I switched from Enpass which offers three tabs that help a lot to detect such passwords easily. These are _weak_, _identical_ and _old_.

Something similar would be a very nice addition to KeePassXC.

**Comment by droidmonkey** [comment]
This is covered by #551

**Comment by droidmonkey** [comment]
As discussed in #551, this feature should be built into the new Database Reports. Entries should be evaluated based on a "duplicate score" mechanism that tries to find similarities between entries based on various criteria. Entry title, URL, username, and password should all be scored for similarity.

**Comment by rugk** [comment]
**Use case** was mainly Stackexchange.
**Proposed Solution** was 
* link items together (just as clone feature)
* show a duplicate score in percent (100% duplicate, 80% etc.)

Note these two points, because finding dupes is only step 1, step 2 is how to fix them. (as in Stackexchanges case: let me link them all to the same password & username of one entry.)

**Comment by OLLI-S** [comment]
Here my posting from #551 (so we have all information in one place):

You should add a feature called "Find Duplicates" and show a list with possible duplicate entries.
In the first column you show the title of the entry, in the second column you show a percentage of equality (100% means all fields are equal, 90% means that all fields except one field are equal).
You also should show the columns Username, Password (masked) and URL and above the table a checkbox to show the password in clear text.

In this form (below the table) you should also show a link to a documentation that explains how to avoid duplicate entries and how linking entries works (and what the benefit of linking is).

**Comment by LightTemplar** [comment]
And I would like to add another use case, with which I have to fight: some entries were created because browser add-on was buggy and couldn't find original entry, but I had to save a new changed password. So I pushed the "new" button.

**Comment by Janaue** [comment]
hello

I am new to keepass. I have exported my passwords from old firefox as .csv and quantum firefox also as .csv. then I created a kdbx for each csv and now I want to merge those 2 kdbx and remove lots of duplicates.
I see on keepass it is possible https://keepass.info/help/kb/faq.html#deldup , is it possible on keepassxc ?

**Comment by droidmonkey** [comment]
Database -> Merge

**Comment by tunbridgep** [comment]
Another reason why there might be duplicates is because, from what I remember, the original KeePass browser extension addons had no way of using additional URLs with an entry. As a result of this, a common workaround (at least for me) was to make "reference entries" that simply reference the username and password of a given entry, with a different URL.

so for example, I might make an Amazon entry
Username: blahblah
Password: 1283ty182nhiuh\\
URL: amazon.com

Then an Amazon AU entry:
Username: @Ref{etcetc}
Password: @Ref{etcetc}
URL: amazon.com.au

This allowed the original KeePass browser addons to log into Amazon and Amazon AU using the same credentials.

The report should also detect and (optionally) remove these, instead adding their URL to the list of URLs for the parent entry.

I can see some cases in which a purely referential entry like this could be useful for organisation. For instance, a workplace might use domain logins for PCs as well as an intranet. Someone might argue that having the intranet entry in a different category to their PC login is of value to organising their database, and so keeping a fully-referential entry is beneficial to them. Given this, entries should NOT be fixed if they are excluded from database reports.

**Comment by rugk** [comment]
> Another reason why there might be duplicates is because, from what I remember, the original KeePass browser extension addons had no way of using additional URLs with an entry

They still don't have that ability… or have I missed sth.? I still use the workaround you describe e.g. for notorious Stackexchange with these many URLs… :thinking:

**Comment by gruentee** [comment]
@rugk 
In current versions of KeePassXC there is the option to add additional URLs for an entry under "Browser integration":

![Add ](https://user-images.githubusercontent.com/923759/132673286-6e2f2fcc-1eee-4294-a537-ef8b0d33e8f3.png)

**Comment by rugk** [comment]
Oh wow, why did not I know this? Thanks a lot! :smile:

**Comment by gruentee** [comment]
you're welcome ;-)

**Comment by droidmonkey** [comment]
We offer many ways to do this. You can use the search feature on specific attributes. You can also search for `*` and sort by title or URL. You can use database reports. etc.

**Comment by rolltidehero** [comment]
I would like this feature as well, because I had 2 LastPass accounts and I imported and merged them, but 90% are duplicates and the other 10% are where I updated passswords on one of the LastPass accounts

**Comment by Lalarian** [comment]
Yes, my database is a chaotic mess, full of not just duplicated but triplets and more, because the extension multiple times simply did not finde the old exising entries and I saved them again. The old entries are still in the database, somtims very often, and I don't know why the extension doesn't use the older entries anymore an needed creation of a new one.
So: Features for merging and/or removing multiples are urgently needed! It's keepassxc that created the problem itself, so it should be able to to ixt.

**Comment by Ember-ruby** [comment]
the health check page also seems to be missing an option to show all entries with whichever re-used password (or an option to exclude passwords above a certain strength)

anyway, it would be incredibly helpful to have an at least semi-automated way to de-clutter the DB
