### ISSUE TITLE
KeyPassXC 2.7.0 fails to run on Windows 7 SP1 x64

### ISSUE THREAD

**Issue by H-andy** [keepassxreboot/keepassxc#7578]
After installing either the MSI or Portable packages of version 2.7.0 on Windows 7 SP1 x64, when attempting to run keypassxc.exe on this platform the following error is seen in a popup window:

The program can't start because api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll is missing from your computer.
Try reinstalling the program to fix this problem.

The same error is not seen on Windows 10.

Is this a bug or a windows version compatibility issue?

**Comment by droidmonkey** [comment]
We don't support Windows 7

**Comment by H-andy** [comment]
Does the documentation reflect this?

All I have seen is "You can run KeePassXC on Windows, macOS, and Linux systems".

Plus, the MSI does not stop you from installing version 2.7.0.

**Comment by droidmonkey** [comment]
Windows 7 has been end of life for 2 years. You are a sitting duck on that operating system.

**Comment by H-andy** [comment]
It's air-gapped and only used for old satnav software that I haven't yet replaced in Linux.
Just figured that since 2.6.6 worked, 2.7.0 would also work.
Thanks for the clarification.

**Comment by phoerious** [comment]
The fact that 2.6.6 works is coincidental. We haven't supported Windows 7 for a while.

**Comment by Taiyoumaru** [comment]
It is disappointing to read this, it was such a great password manager as well, now I'll be forced to find another password manager when 2.6.6 no longer works. 

I certainly respect your decision and don't expect this to be changed, however I did want to chime in as I needed to correct the misconception that you are a sitting duck when using Windows 7. 

This may be true for a baseline Windows 7 user or old folks using very old hardware that they will not change, but I honestly doubt those remain a significant portion of its userbase, and certainly would not be people interested in using an offline password manager. 

I would wager said userbase at the moment is likely majority comprised of expert user enthusiasts and organizations that need to deploy mission critical software and cannot make the switch. It still holds a commanding 12% (well over 100 million devices) market share as of last month, above 11's 7.9% and well above Linux's 2.5%.

Microsoft continues to provide all security updates that 10 receives to Windows 7 users on a paid basis until 2023, and that's if they don't extend support again, which they most likely will. It is actually trivially simple to configure any Windows 7 installation to receive those updates without registering with Microsoft or paying a dime. 

Given this and coupled with the facts that 10/11 are a privacy nightmare (and a security one by extension), the much increased attack vectors due to poorly implemented and secured features (including 10's Windows Update itself!) and the fact that its majority market share alone makes such a system the prime target by far, you are actually MORE secure when using 7 as it stands.

This was a long rant and I apologize to those who made it this far, it just is frustrating to see software support in general being dropped for a perfectly functioning and in many ways better operating system due to what can essentially be considered a meme. Especially considering that the error both H-andy and I are receiving when we are trying to run 2.7.0 is essentially a missing library file. 

For reference to those who attempt to do so in the future, installing the latest VisualC++ redists (I use abbodi1406's AIO solution) did not allow 2.7.0 to run on my Win7 machine. If someone finds a fix please let us diehards know. Thank you!

**Comment by michaelk83** [comment]
@Taiyoumaru They've added a legacy build on the [release page for 2.7.0](https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0), but since they switched to a new build system and as they add features that rely on it and on newer Windows APIs, that will eventually not be possible anymore.

**Comment by phoerious** [comment]
> It is disappointing to read this, it was such a great password manager as well, now I'll be forced to find another password manager when 2.6.6 no longer works.

You can continue using KeePassXC 2.6.6 for as long as you like. You will just not get updates.

> I would wager said userbase at the moment is likely majority comprised of expert user enthusiasts and organizations that need to deploy mission critical software and cannot make the switch. It still holds a commanding 12% (well over 100 million devices) market share as of last month, above 11's 7.9% and well above Linux's 2.5%.

11% market share means nothing for actual user base. We have about 1% Windows 7 users in our website statistics, steadily decreasing.

**Comment by Taiyoumaru** [comment]
> 11% market share means nothing for actual user base. We have about 1% Windows 7 users in our website statistics, steadily decreasing.

That is certainly a good point that I concede to. It does not make sense to use a lot of development time to design software for a sub 1% user base. Although, while I would wager power users would not show up in those statistics if proper browsing precautions are taken, the complete statistics wouldn't be much different.

That said, I would very much like to heartily thank the developers for the legacy build that I have successfully installed and am currently happily using. It is much appreciated, especially if it wasn't trivial to release and it took up valuable development time. Much obliged 🙇

**Comment by PatRiot1337** [comment]
I have exactly the same problem here with Win 8.1 (my personal preference to win 10 and 11....).

Thanks for the legacy dl, that worked for me after second installation.... hope u bring the legacy dls for future updates, too....

> Does the documentation reflect this?
> 
> All I have seen is "You can run KeePassXC on Windows, macOS, and Linux systems".
> 
> Plus, the MSI does not stop you from installing version 2.7.0.

**Comment by droidmonkey** [comment]
Use the legacy windows installer

**Comment by sergeevabc** [comment]
@Taiyoumaru, here's a different perspective on the betrayal of Windows 7 users — isn't it a relief to realize what kind of people are behind XC password manager?

Community edition, huh? The original KeePass continues to work because there's no reason for it not to work, because nothing new is required to render the password table, accompany its modifications, and even add modern crypto like ChaCha and Argon. That's where the community care is, that's what called a future proof design.

Whereas XC renegades base their development decisions on the greed of the Silicon Valley hegemon, who has moved from developing breakthrough complete solutions (NTFS over FAT32, for example) to a program-as-a-service (SaaS) model resembling the relationship of a drug addict and a drug dealer. The latter comforts the former weekly with a dose of patches and reminds that they cannot get off this needle, otherwise viruses and hackers will pop up. Fearmongering, anxiety, patch, repeat.

Until recently, however, apps were designed differently — to be sufficient enough (not perfect, but sufficient enough) for the task at hand and to require fewer and fewer updates, like hammers and refrigerators that work even after the company that produced them has ceased to exist. Windows 7 is one of them, I use it with pleasure.

And the reference to some site's statistics to determine the share of users of a particular OS is ridiculous, considering how these statistics are gathered. Blocking of trackers via extensions, firewalls, and even hosts file, is a promoted thing to do for more than a decade. So they detect mostly those who live under a rock and forget to count those who could not care less about corporate tricks like [artificial obsolescence](https://en.wikipedia.org/wiki/Planned_obsolescence) and forced upgrades for the sake of anything but the progress.

``` console
$ rg --no-line-number --no-filename -g rules-black.txt keepassxc
analytics.keepassxc.org

$ rg --count --no-filename -g rules-black.txt matomo
600
```
![](https://imgs.xkcd.com/comics/the_history_of_unicode.png)

**Comment by phoerious** [comment]
@sergeevabc I see you have no idea about software, software development or our project. But thanks for the warm words.
