### ISSUE TITLE
api-ms-win-cor-kernel32-legacy-ansi-l1-1-0.dll missing error (Windows 7)

### ISSUE THREAD

**Issue by AncapAviator** [keepassxreboot/keepassxc#7637]
## Overview
When I try to open KeePass, I get a "System Error: The program can't start because api-ms-win-cor-kernel32-legacy-ansi-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem." pop-up. I tried to reinstall, as well as tried installing the [Microsoft Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) linked on the [blog post](https://keepassxc.org/blog/2022-03-21-2.7.0-released/) referencing this kind of issue. No luck.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.7.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 7

**Comment by phoerious** [comment]
Windows 7 is unsupported. You can download the legacy installer from here, but we may discontinue those builds at any time: https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0

I recommend you upgrade your system to a Windows version that is not end-of-life.

**Comment by bish0polis** [comment]
It's understood that Microsoft gave up on Windows7, just as it's understood that more people still use Windows7 than may be using Mac.  These are just facts and numbers.  It could be as high as 1 in 6 people running windows who understand the risks they take on by continuing to run an OS the manufacturer has become bored with.

We don't have to be Microsoft, and as working PCs drop out of Microsoft's preferred support window they don't need to be shunned completely.

But you may want to keep a FAQ together for common issues like this one, so people know we no longer care.  Ideally it could be pointed out that the problem is an incomplete library or whatnot, for searching the error message occasionally comes up with an accusation that the installable is broken or trimmed.
