### ISSUE TITLE
Some settings are apparently no longer saved

### ISSUE THREAD

**Issue by braunharald** [keepassxreboot/keepassxc#7686]
Apparently, some settings, such as the sorting used for one or more fields, the last group used, etc., are now no longer saved or set when KeePassXC is called up.

Steps to reproduce:
1. I was last in the Homebanking group and sorted the banks there by title in ascending order.
2. I exit KeePassXC via Database -> Exit.
3. I open KeePassXC again.
4. I am now in the Expired group.
5. when I switch to the Homebanking group, the banks are no longer sorted in ascending order by title, but are displayed for me in random order.

Expected behaviour:
1. I was last in the Homebanking group and sorted the banks there by title in ascending order.
2. I exit KeePassXC via Database -> Exit.
3. I open KeePassXC again.
4. I am in the last group used - in our example Homebanking AND the banks are sorted by title in ascending order.

Debug info:
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Diagnostic mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-105-generic

Enabled extensions:
- Auto-Type
- Browser integration
- SSH agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

With kind regards
Harald Braun

Translated with www.DeepL.com/Translator (free version)
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
Sort your entries and then make some sort of data change to force a save. The sorting my be an actual issue, but the last-used group is saved only if something else changes, otherwise your database would constantly be rewritten as you click on groups.

**Comment by droidmonkey** [comment]
You likely have your ~/.cache mounted to ram disk.  Either don't do that or put your local config somewhere else. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

**Comment by michaelk83** [comment]
Also, regarding returning to the Expired group (or tag, rather) on startup - that's a new feature to let you know which passwords need attention. I think there's a setting for it, maybe.

@droidmonkey , can the expired report be set to show once a week for example (instead of every time)? IIRC there was a request for periodic reminders. Or maybe show just a banner "You have passwords about to expire." with a link to the report. (Just thinking of some ways to make it less obtrusive, while still making it discoverable and still making users aware of expired passwords.)

**Comment by droidmonkey** [comment]
I like the banner idea
