### ISSUE TITLE
Ignore BEEP placeholder when validating Auto-Type 

### ISSUE THREAD

**Issue by amccombsahce** [keepassxreboot/keepassxc#7726]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have Database\General\Windows shortcut to login to the Think or Swim app
when the login dialog is open, I press alt-ctrl-B to fill out the fields. Worked great for the past 4 months, now shows error.
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install Think or Swim, and have an account
2. start Think or Swim
3. when the dialog appears, click on the username field, then  press alt-ctrl-B

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The fields are populated and I am logged into Think or Swim

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
An Auto-Type Error dialog appears with Invalid placeholder: {BEEP 800 200}

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision:  d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-105-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1
- 
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 20.04
Desktop Env: Gnome
Windowing System:

**Comment by droidmonkey** [comment]
We don't support the BEEP placeholder, and there are no plans to support it. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences

**Comment by amccombsahce** [comment]
Worked fine for several months with the BEEP.

**Comment by mgalvey** [comment]
Sorry to revive a closed issue, but I hope you'll reconsider this. Whether the functionality of this placeholder is supported by XC or not, the current behavior basically kills any chance at cross-compatibility with (for instance) shared password DB files that get used with multiple platforms and KeePass clients. It has also put me in the frustrating position of having to try to root out every last occurrence of the beep placeholder (which the use of has grown organically over the many years I've had my primary DB file; most of that time I used this file with the "standard" KP client on Windows, but subsequently moved my primary desktop to Fedora), and I have found no good way to streamline or do that in bulk.

Would a compromise perhaps be in order? Could the default behavior be to throw an error if an invalid placeholder is detected, but allow the user to configure the client to instead fail silently (but otherwise work as expected), as previous versions did?
