### ISSUE TITLE
CSV Import should add items to database not create a new one

### ISSUE THREAD

**Issue by simonsmiley** [keepassxreboot/keepassxc#793]
I would like to be able to import passwords into an existing database. Sadly there doesn't seem to be an easy way to do it. Importing a csv creates a new database. Entries can't be copied and pasted as a whole, so transferring them isn't an option either
## Expected Behavior
csv import adds passwords to existing database (maybe a new folder)

**Comment by louib** [comment]
@simonsmiley What about importing to a new database and merging the new database to an existing one (using the merge functionality). Would that solve your problem?

**Comment by simonsmiley** [comment]
Oops. I didn't see that. I never the less would have expected an import to add items, not create a new one. But since it works for me now, feel free to close the issue

**Comment by louib** [comment]
@simonsmiley I'm glad that solved your problem!

**Comment by droidmonkey** [comment]
I still think this issue has a good feature that we are missing. Having to make new and then merge is a silly multi step process.

**Comment by seatedscribe** [comment]
I agree with you. Nevertheless I find it more strategic to have a drag&drop
feature instead of a blind import-and-merge, as usually one wants to check
the correctness of the import before melting the new data into other
databases. Moreover, drag&drop could be useful for other situations too...
My two cents.


On 19 Jul 2017 11:37 p.m., "Jonathan White" <notifications@github.com>
wrote:

I still think this issue has a good feature that we are missing. Having to
make new and then merge is a silly multi step process.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/keepassxreboot/keepassxc/issues/793#issuecomment-316525417>,
or mute the thread

**Comment by simonsmiley** [comment]
if it adds them to a new folder `import-<counter>` then you can manage them before you move them to other locations...

**Comment by seatedscribe** [comment]
...and how would you move them?

**Comment by seatedscribe** [comment]
So what do you guys think about opening a feature request for drag&drop of
items? Is there something I am missing?

Enrico

**Comment by simonsmiley** [comment]
I'm not sure what you mean by drag and drop. I can drag and drop items between groups. And to my surprise also between databases...

**Comment by seatedscribe** [comment]
...me neither :)
Sorry, I was misleaded into thinking nonsense.

I will take care of this feature in the near.... future!
