### ISSUE TITLE
Need more icons for group 

### ISSUE THREAD

**Issue by 0xShree** [keepassxreboot/keepassxc#7948]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Need more group icons than default(e.g., colored folders, sign symbols, emojis)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Having different icons to each group helps visually distinguish and to navigate easy

**Comment by droidmonkey** [comment]
You can add whatever custom icons you like from the icons tab when editing a group or entry. See the user guide for more info.

**Comment by daviddavo** [comment]
I think it would be nice to add support for Unicode icons (emoji). Each device would display them differently, but on par with general UX. Furthermore, most people know them by heart and it would be way easier to select an emoji using the system keyboard than downloading the icon and setting it.

**Comment by droidmonkey** [comment]
Not supported by the kdbx standard.

**Comment by piegamesde** [comment]
If the format supports custom icons, then it would be great to automatically create and embed emoji images for that purpose. Of course I could manually do that myself, but that would be rather tedious.

Alternatively, maybe it would be an idea to put the emoji in the title instead. If the entry then has no icon but starts with an emoji in the name, use that instead of the fallback icon. That's e.g. how Matrix and other chat clients solve this.

**Comment by daviddavo** [comment]
Btw, does anyone know any website that has sets an emoji as a Favicon? It would be a great workaround if we could use something like https://emoji2favicon.example.com/grapes
