### ISSUE TITLE
HMAC mismatch after comment change

### ISSUE THREAD

**Issue by foobar13372** [keepassxreboot/keepassxc#7958]
I encrypted my Database with a private SSH keyfile. Then I changed only the comment of that file, using `ssh-keygen -c -C "new-comment" -f my-key-file`.

KeepassXC rejects it now (HMAC mismatch), but I can still use this key for SSH totally fine. What to do? Can I fix this? From where is the HMAC calculated and where is it stored?

**Comment by phoerious** [comment]
KeePassXC doesn't use SSH keys. A key file in KeePassXC is an arbitrary file containing a bunch of bytes. If you change some of them, it won't work.

**Comment by foobar13372** [comment]
Then I suggest making this clear in the docs and UI. I totally assumed for years that you need a private SSH key file and not any arbitrary key file...

**Comment by phoerious** [comment]
The user interface clearly says that the file must not change. We also have an FAQ entry about key files: https://keepassxc.org/docs/#faq-keyfile-howto
A single SSH public key file wouldn't make any sense at all, since SSH keys always come in pairs. If we really used your public key to encrypt something, we would need your private key to decrypt it again.
