### ISSUE TITLE
Cannot access passwords

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7992]
A few weeks ago, I  noticed the KeePassXC desktop icon had changed to look like a piece of paper. Didn’t think anything of it until I tried logging in 2 days later. The password wouldn’t work. Got the message: “Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch).”

I know I am using the correct password.

I spent several days trying to figure out what went wrong. Nothing online helps, just points to the importance of having backups.

I have 3 forms of recent backups. A  USB that backups with Grsync, a USB that uses Backup Tool, and the database printed out stored in a fire safe.

I used the Grsync USB and copied the kdbx file onto my computer. I then went to open the file with KeePassXC, and got the same error message.

The same process with the Backup Tool USB’s kdbx file gave the same error message.

I downloaded the most recent version of KeePassXC as an AppImage, and tried the same thing with all 3 kdbx files. This also did not work.

Any clue what’s wrong? I’m not proficient with Linux and this is the 1st time I’ve tried getting files from a backup USB so I may be doing something incorrectly. 

Steps to Reproduce
1. Tried to access passwords as normal with correct password
2. Recieved error message
3. Tried using files from backups with same error message

Expected Behavior: accessing passwords as normal

Actual Behavior: receiving an error message

Context: I use Linux Mint and don't have much experience accessing kdbx files from backups.

KeePassXC - VERSION 2.7.1 
Revision: REVISION 5916a8f 

Operating System: Linux
Desktop Env: Cinnamon

**Comment by droidmonkey** [comment]
> I know I am using the correct password.

This is the number one reason for receiving this error, especially if your backups fail as well. You are not typing in the correct password. Have you recently updated your backups?

Unless... are you using a key file and/or yubikey as well?

**Comment by ghost** [comment]
I have had this password memorized for months. I had used it just 2 days before I started having issues. 
My backups were created about 3 weeks before the day I couldn't access my database. 
I know nothing about key files so I probably am not using one. I've never tried using a yubikey with keepassxc.
Would my desktop icon changing out of no where indicate anything? 
Thank you for taking the time to respond.

**Comment by droidmonkey** [comment]
The desktop icon changing could be due to an automated update, perhaps your system updating, or losing the .desktop file. None of that has anything to do with unlocking your database though. 

Do note that if you have a special unicode character in your master password that you need to type your password with it visible due to a qt bug.

You can try downloading an older version of keepassxc appimage to be sure it's not the version update. These are in our releases section. 

Given your 3 week old backups don't unlock, the most plausible explanation is a mistyped password.

**Comment by LaneCools** [comment]
Same problem. Today I could not enter the database with a password, although I opened it a couple of days ago. The backup does not open on any of the devices. I am sure of the correctness of the password, memorized by heart.

**Comment by rolsim** [comment]
I love KeePassXC and synchronize the database between all of my devices. But today I almost had a heart attack...

**Problem**
Under Windows I could not open my new database, created under Fedora 36.

**Explanation**
Thanks to @droidmonkey mentioning some _qt bug_ in his [recent answer](https://github.com/keepassxreboot/keepassxc/issues/7992#issuecomment-1114354817) the issue could quickly be fixed.
> Do note that if you have a special unicode character in your master password that you need to type your password with it visible due to a qt bug.

In my case, the "special unicode character" was a ^-character ([caret](https://en.wikipedia.org/wiki/Caret_(computing))) in my database password. In order to generate it, one has to press [space] immediately after ^.

Toggling the password visibility - after having entered the password - revealed that instead of a caret only the [space] had been registered and stored. As one gets always the same (wrong) password under Qt, this has never been noticed under Fedora. Windows on the other hand registers the caret correctly, which lead to not matching the stored (wrong) database password. Consequently, opening the database under Windows was possible by replacing the ^ with a simple [space].

**Solution**

In order to properly enter passwords with "special unicode characters" under Qt, either
- avoid them altogether or, if not possible
- enter them in clear view (only under Qt)

Generated passwords seem not to be affected.

**Important:** Make sure stored passwords really match what you meant them to be.

**Background**

I found a promising candidate for the unspecified qt bug titled [QLineEdit password echo mode odd behavior with composite characters](https://bugreports.qt.io/browse/QTBUG-23626?jql=text%20~%20%22unicode%20password%22). It's that old, it might even be considered a feature. To get it fixed seems unlikely, especially facing the consequences that typed passwords suddenly become what you ever meant they were.

**Further questions**

- What about other "special unicode characters"
  Although this particular bug is bound to Qt, Unicode itself seems to have other challenges as some characters can be represented in different ways.

  Does KeePassXC handle such Unicode normalization (i.e. [Canonical Equivalence](https://unicode.org/reports/tr15/#Canonical_Equivalence_Figure))?

- Are there other known quirks like that (maybe under other environments)?

- Shouldn't this be documented explicitly in the [User Guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html)...or is it me, not being able to see it there?

**Comment by droidmonkey** [comment]
Just avoid non ascii characters altogether. They don't make your password any stronger. Under the hood they repeat common bit sequences (that's how unicode works) so it's not adding any real randomness to your password. 

Closing this since OP abandoned.
