### ISSUE TITLE
Username/login name generator

### ISSUE THREAD

**Issue by mdxe** [keepassxreboot/keepassxc#8010]
## Summary
When you don't care about your username and just want something random, a username generator would be nice.

## Examples
something similar to this: https://www.lastpass.com/features/username-generator

## Context
I tend to use different usernames on all sites to increase privacy and would like an automated username generator

**Comment by droidmonkey** [comment]
Just use the passphrase generator with no separator and add a number or something to the word. We won't be adding an explicit username generator, it's been requested before and we already have the ability through the password generator.

**Comment by bspinner** [comment]
Hey @droidmonkey,

that was my initial thought as well, since the linked solution isn't that different from a password generator.

But have a look at Bitwarden's username generation feature:
https://bitwarden.com/help/generator/#generate-a-username

In my opinion that'd be a clear improvement to the user.

**Comment by rambda** [comment]
> Just use the passphrase generator with no separator and add a number or something to the word. We won't be adding an explicit username generator, it's been requested before and we already have the ability through the password generator.

If I using the password generator to generate usernames, isn't a preset system very handy?

Because in practice, I need to first change the generation length, the character set used, etc. to ensure that the username is short and simple enough to meet the standards of the platform's database; and then change the generation settings again to ensure that the password is complex enough.

Isn't the workflow for most people like mine? Can you please illustrat me what's the best practice?

**Comment by xa4hf8** [comment]
> **Just use the passphrase generator**

When a free web service requires e-mail address validation but there is some risk that the address could be stolen or sold, some users will generate random addresses from the same domain to facilitate registration without compromising the privacy of their personal e-mail account.  In many online service contexts, _the user name is an e-mail address_, so **the first character must be alphabetic and extended ASCII characters are prohibited**. This means that you must reconfigure the password generator every time that you need to switch between user name and password generation.  It's really a terrible nuisance.

**Comment by droidmonkey** [comment]
PassPHRASE generator. Or just literally type in random characters, what difference does it make?
