### ISSUE TITLE
Keepassxy 2.7.1 on ARCH and Ubuntu does not start completely

### ISSUE THREAD

**Issue by zash1958** [keepassxreboot/keepassxc#8019]
## Overview
As stated above. Verion 2.6.x runs flawlessly, version 2.7.1 could be started and the gives no screen output.
Downgrade to 2.6.1 helps.

System is a completely actual Arch Linux with KDE/X11 as Desktop Environment.
Snap packages 2.7.1 show also the same problem.

Any hints or any way to activate an extended logging? Journalcontrol shows absolutely nothing about.

**Comment by OskarKarpinski** [comment]
I use bspwm and it works without any problems

**Comment by OskarKarpinski** [comment]
Are you all packages up to date? Try typing `keepassxc` in the terminal and check the logs.

**Comment by zash1958** [comment]
If I start keepassxc from console there is no further output and the app does not show any screen output. It hangs without any further reaction. Release 2.6x starts without any issue if I do so.
Can there any logfile be enabled in keepassx ? Journalctl also show nothing here.

**Comment by Franz-Heinz** [comment]
Same problem here but on Ubuntu 18.04 LTS (maybe the title of the thread could be changed?)

Since installing keepasxc 2.7.1 (from ppa) I'm experiencing that I can start keepassxc right after booting ubuntu. Than it works fine the hole time - regardless of what other programs I use.

If instead I first do some other stuff (haven't tried specific tasks, yet) and then try to start keepassxc it doesn't appear. With `ps -e | grep keepassxc` I can see that a process has been started. Most interesting: I could not find any way to kill this process). Every time try to start it again it just adds another of this processes.

When I tried to start keepassxc from the console (still after doing some other stuff before) I don't get any output. Not even `crtl+c` is able to quit the running process. It even persists after quitting the console window.

@ [zash1958](https://github.com/zash1958): Can you start your keepassxc right after booting your arch?

**Comment by zash1958** [comment]
Absolutely same here, process cannot be killed wit CTRL-C and prcess persits also after closing konsole app

**Comment by Franz-Heinz** [comment]
@zash1958: Did you try if you can start keepassxc right after starting your system? Strangely on my system keepassxc works fine if I do so just right away.

**Comment by zash1958** [comment]
Tested this also, no way. Same problem as starting it automatically.

**Comment by vimpostor** [comment]
> Any hints or any way to activate an extended logging? Journalcontrol shows absolutely nothing about.

You can try building keepassxc with debug symbols to see where it hangs by starting it through `gdb`, press `Ctrl+C` as soon as it hangs and type `backtrace` into the gdb shell.
Since you are on Arch Linux, building with debug symbols is as easy as downloading the attached `PKGBUILD` and just running `makepkg -si`.
[PKGBUILD.txt](https://github.com/keepassxreboot/keepassxc/files/8692967/PKGBUILD.txt)

**Comment by Offerel** [comment]
If you have enabled to open a database automatically, please check that the path is available when starting KeepassXC. For example I use one db at a mounted SFTP path. Mounted via sshfs. If the laptop is connected to a different Wifi, I can't mount the share and get the same behavior. This is also the same for davfs2 or any other cloud mounts.

Maybe there should be some timeout setting or check if the db can be reached and if not loading of the db should be stopped.

**Comment by zash1958** [comment]
No way, Keepassxc does not start without config/database or even on a fresh configured new user.

**Comment by droidmonkey** [comment]
There isn't anything we can do here without logs or stack traces so closing.

**Comment by egg-juxt** [comment]
Hi, I'm experiencing the same as described here: KeepassXC not starting, not able to kill. KeepassXC remains in an uninterruptible state, waiting channel intel_pxp_get_readiness_status:
![image](https://github.com/keepassxreboot/keepassxc/assets/98806249/e08975b9-7177-475d-8f86-78fabcf73138)

**Comment by zash1958** [comment]
Cardreader with an inserted Security Card inserted?

Or any USB device is blocking the startup of KPX ?

**Comment by egg-juxt** [comment]
None of those. Dell XPS laptop running Gnome Wayland on Arch. KeepassXC installed from Flatpak.

**Comment by Offerel** [comment]
The real question is: Where do you have your database saved. On a USB drive, Cardreader, Network mount or a local ext3/ext4 partition...

**Comment by egg-juxt** [comment]
Local SSD, LUKS-encrypted ext4.
