### ISSUE TITLE
Option to automatically download the favicon when entry is created

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#8057]
## Summary
When I add a new entry (in whatever way) I may want to have KeePassXC to automatically download the favicon for it. (when I save it e.g.)

## Examples
A setting in the settings that allows you to automatically download the favicon.

## Context
I want all my websites/URl entries (when I add URLs) to have a favicon, as that looks nicer.

**Comment by droidmonkey** [comment]
This exists already as part of the browser extension

**Comment by rugk** [comment]
> This exists already as part of the browser extension

Okay, but what if I do not use the browser extension to add an entry? I just did (it's a game, and I needed to sign-up in the game, so did not use the browser extension. But they also have a website, so a download URL would have been there.)

**Comment by droidmonkey** [comment]
We decided to not enable this within keepassxc. There is a button right next to where you enter the url to download the favicon. Just tap that after you put the url in.

**Comment by rugk** [comment]
Oh missed that button. Thanks!

**Comment by christhomas** [comment]
@droidmonkey Why did you decide to not enable this?

**Comment by droidmonkey** [comment]
Any call out to the internet must be initiated by an explicit user action.

**Comment by hackel** [comment]
@droidmonkey Would you consider adding this as an explicitly opt-in feature?  I honestly just forget to press the button 90% of the time and it would be a big convenience not to have to think about it.  It seems a bit silly to tell the human operator they are required to do this manual task that could be trivially automated.  (I'm not demanding you or anyone else *implement* it, I'm just hoping that it can be approved/issue re-opened.)  I totally understand the concern regarding outgoing communication from a password manager and agree, but if users choose to take the "risk", shouldn't they have that choice?

Also FYI, I've never gotten password saving from the browser extension to actually work right.  Maybe that's user error, but I always end up entering new entries manually, so I just disabled the banner.  I usually have to customize the password generator settings for each site anyway, since they're all so finicky about special characters.

**Comment by droidmonkey** [comment]
We implemented this through the browser extension. When you add a site match from the extension, you can enable the setting to auto download the icon when that entry is created.
