### ISSUE TITLE
Crashes When Database is On a Virtual Drive Using Linux

### ISSUE THREAD

**Issue by dvngnt** [keepassxreboot/keepassxc#8131]
Attempting to open an existing database when the file is location on a virtual drive crashes the application. 
I'm using gnome's online accounts feature to add a google drive account
Copying the file to the local home folder works as expected.

**Comment by droidmonkey** [comment]
You need to include all the debugging information in the about dialog. You also need to clarify if this is the database file itself or the key file to open your database.

**Comment by henrique-belo** [comment]
I'm having the same issue with virtual google drive mounted through online accounts on Ubuntu 22.04.2.
Issue happens when "Openning database file":

1. The file explorer identifies the mounted drive but once inside its root, names of the folders are gibberish of letters and numbers.
2. When I open any folder on drive's root the app crashes.

It's a big limitation, this issue does not alow me to have my keepass synced on this machine. I'm also open to other workarounds to have the database synced with Google Drive ;)

Debug Info:
`KeePassXC - Version 2.7.5
Revision: 9d0537b
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Ubuntu 22.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.19.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
`
