### ISSUE TITLE
Modification time and creation time not preserved while moving items

### ISSUE THREAD

**Issue by zzh1996** [keepassxreboot/keepassxc#8170]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Modification time and creation time not preserved while moving items
This issue makes it impossible to know when an item was actually created/modified after moving items.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Move existing item(s) to another folder

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Modification time and creation time should not change (just like how filesystems work)
Even if you decided to let the modification time change (which is really strange), please at least store the old modification time in item history.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Modification time resets to current time
When moving across databases, creation time also resets to current time

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
#6202

**Comment by droidmonkey** [comment]
Switching the open issue to yours, it is more complete.

**Comment by tehmasterer** [comment]
Same issue here. When moving or copying from one database to another, the modification dates are set to the current time. This should not be the expected behaviour.

Also, because there is no "undo" feature when moving entries between databases, if you move an item back to the original database, the date is changed again.

Ex: 
1. Move entry1 from a > b === new modification date.
2. Move entry1 back, b > a === new modification date again.

**Comment by nemothorx** [comment]
recently migrated to keepassxc and encountered this same frustration - especially since migration is a time of key reorganising - and losing that "how long has this been unchanged" was frustrating. 

My workaround - when importing (from csv) set the key create time AND mod time to the imported mod time field. The create time isn't changed when the key in keepass is renamed or moved, so acts as a proxy for the original mod time.

**Comment by Dogway** [comment]
Was also frustrated with this, since I have to move old migration folders (old keepass Backup and ThrashBin folders) to the XC Recycle Bin. I also want to move all groups up in the stack, but fearing all the modification dates will be updated.

**Comment by jamesquilty** [comment]
I think the fundamental question is: should changes to the entry metadata (group, icon, tag) update the modification timestamp of the entry?

The usual convention, cited by others, is that changes to metadata don't change the modification timestamp because the modification timestamp is metadata with a specific meaning: the date and time the data (username, password, URL, etc.) were last changed. As pointed out by others, the modification timestamp metadata has value and updating the modification timestamp when other metadata is modified constitutes dataloss.

I have need to change the group, icon and tag metadata for many entries, resulting in a modification timestamp which misrepresents the date and time the entry data were modified. It would be helpful (at the very least) if metadata changes didn't cause this.

A related point: since the modification timestamp is metadata, there's no particular reason why it shouldn't be modifiable by the end-user. At present it's not possible to correct timestamp errors in the database.

**Comment by droidmonkey** [comment]
Icon and Tag(s) are not metadata. In fact, thinking about this further, we have to update the modification time when moving between groups because that is how we know which entry is the "most recent" when doing a database merge. That is also why you can not just arbitrarily change the modified time. That is a very important piece of information for the proper functionality of the database.

**Comment by jamesquilty** [comment]
Excuse me @droidmonkey, I believe you're looking at this issue from a backend perspective when you really should be looking at it from the frontend perspective. It's not relevant to the frontend that a modification timestamp for the entry - data _and_ metadata combined - must be maintained for database management which is a backend concern.

What several people have stated here is a reasonable expectation that the KeePassXC frontend will behave in ways consistent with the system within which it is running where, for example, filesystems have groups (folders), icons and tags which are treated as metadata (data that describes data) and where changing the metadata does not change the other meatadata attribute, the modification date. There is a reasonable expectation on the part of users that KeePassXC will follow that convention.

As it stands, there's a leaky abstraction of the modification timestamp of the entire entry, required for internal database operations, from the backend to the frontend. The same fundamental problem (and question) forms the motivation for #9108, in which one commenter explicitly references "metadata". The entire point of _this_ issue is that the leaky abstraction is problematic when presented to users in the frontend.

Could you please reopen this issue?

**Comment by droidmonkey** [comment]
There are other issues requesting specific things like password modified date which I will implement. This isn't about your desires or my desires. KeePass (original) dictates the date fields and how they are used. We can certainly calculate arbitrary last modification dates, but that is NOT the focus of this issue.

> The entire point of this issue is that the leaky abstraction is problematic when presented to users in the frontend

Incorrect. This issue was asking to change a "backend process" which would end up causing significant problems upon further reflection.
