### ISSUE TITLE
"Clipboard clear" not working while keepassxc running in the background (Fedora 36 (Wayland) / Gnome 42)

### ISSUE THREAD

**Issue by hexchills** [keepassxreboot/keepassxc#8171]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When i change focus to another app, at the time when I use button - "Copy Password", with clipboard timeout (5 seconds) from password entry or password generator, after timeout i still have my password at clipboard and can paste it anywhere

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Settings -> Security -> Clear clipboard after -> Turn on (any time)
2. Copy password from password generator entry or just from passwords base entry 
3. During the timeout countdown, change the focus to another app 
4. After timeout, paste password in a text editor / browser or anything else (Don't open the app until the countdown has passed. In that case, clipboard clear - works just fine)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Clipboard clear should work, in any case, except if i close database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Clipboard clear not working (after countdown timeout) when switching focus to another app.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Fedora 36
Desktop Env: Gnome 42
Windowing System: Wayland

P.S. Sorry for my English :)

**Comment by droidmonkey** [comment]
This is a qwayland or wayland issue, not us.

**Comment by PaulRivier** [comment]
Hello,

same issue here, debian 12, gnome, wayland, KeePassXC.
Being on Wayland, I can't use autotype, and as it seems, clipboard does not get cleared of my passwords.
I understand this comes from wayland, however there is some usability concern here, since as secure as KeePassXC may be, having no safe way to actually use passwords is a problem.
For some reasons, using "wl-paste" (from "wl-clipboard" package) does not exhibit the same problem. wl-paste will replace clipboard selection, even if terminal is out of focus when command get called (sleep 10 && wl-paste ...). 
I have not investigated more why it does work with wl-clipboard, but hopefully there is a solution to be found.
Thank you for your good work on KeePassXC.

Regards,

**Comment by droidmonkey** [comment]
This is actually a gnome issue, not a wayland issue

**Comment by PaulRivier** [comment]
Thank you. Can we envision a fix, or a workaround, so that it works on Gnome ? 
Since "wl-paste" succeeds at changing clipboard content in Gnome whatever the focus, there must be a way.
If you feel like this is an ever moving target, maybe the workaround can take the form of a few settings for custom shell commands to control the clipboard copy/past/clear operations. They would be used by KeePassXC to interact with the clipboard of the user, according to the desktop of the user.  I am pretty sure there are CLI tools on most environments to interact with clipboard variants. Using CLI would allow to adapt without bindings to unwanted dependencies.
Regards,

**Comment by droidmonkey** [comment]
We already did: https://github.com/keepassxreboot/keepassxc/pull/10624

However this won't work for snap or flatpak right now

**Comment by PaulRivier** [comment]
Great. Can't wait to try.
Regards,
