### ISSUE TITLE
Don't hard depend on dbus

### ISSUE THREAD

**Issue by trilean** [keepassxreboot/keepassxc#828]
Currently, KeePassXC (but not KeePassX) requires dbus as a hard depenency.
This should be an optional dependency IMO. There are some folks out there running a dbus-less system (it's quite easy on Gentoo actually).

The only thing I've seen that requires dbus is the ScreenLockListener. Can you make that optional?

I tried (and almost succeeded) to shoehorn it into building without dbus. It did compile, but doesn't run (segfaults).

Thanks!

**Comment by phoerious** [comment]
We also need DBus for mnandatory global menu workarounds on Ubuntu, so we can't make it optional. I'm sorry.

**Comment by trilean** [comment]
I meant as a build-time dependency. So for anyone who wants this feature (and Ubuntu) nothing changes.

I have a preliminary patch that introduces a WITH_SCREENLOCK flag. It compiles & runs without linking to (qt)dbus, albeit tested so far only on a system with DBus installed. It's not quite finished, but if it's ok with you I'll send you a pull request when I'm done.

**Comment by phoerious** [comment]
The "feature" is a working menu instead of no menu. I would consider that pretty important. 

But honestly, I don't really see the point of supporting DBus-less systems. Usage of DBus will rather increase than decrease. It's a core component of modern Linux systems. You wouldn't ask for such a thing on other platforms.

**Comment by brokensh3ll** [comment]
> Usage of DBus will rather increase than decrease.
This is higly incorrect, dbus less system aren't going to disappear or decrease in anyway. The point of a Dbus-less system is to increase the security of the system, you can check on Google why dbus is major source of vulnerability. I was using dbus before and keepassxc as well, I do use now the original keepassx which allow to be build without dbus, no matter if it isn't updated for a decate, as long it is more secure, that is all matter.

**Comment by TheZ3ro** [comment]
@brokensh3ll using an outdated program and telling that is "more secure" doesn't really make sense.
the Linux kernel is a major source of vulnerability, should we stop using it as well?  

IMHO we can re-introduce the -WITH-DBUS flag, enabled by default but I don't really see many people using it.

**Comment by phoerious** [comment]
The most secure computing method is still manual slide rules. Maybe we should all resort to that in the future. ;-)

**Comment by phoerious** [comment]
Sorry, but I cannot take systemd bashing seriously anymore. But as said before, feel free to create hardened builds of KeePassXC.

**Comment by brokensh3ll** [comment]
KeepassX should work on minimal system for a long time so will stick with it.
  
another thing, do keepassXC hard depend on qtnetwork ?

I tried with the useflag -http -browser -nework still need qtnetwork, Gentoo ebuild broken or hard dependency ?

Integration of a password manager with a web browser is insecure by design...

For instance
https://www.cvedetails.com/product/15031/Google-Chrome.html?vendor_id=1224

**Comment by phoerious** [comment]
You can turn off network stuff via cmake. If the Gentoo ebuild doesn't do it, it's a bug in the package definition.

**Comment by phoerious** [comment]
Dude, nobody forces you to use the browser extension.
