### ISSUE TITLE
Re-enable "Forget TouchID after session is locked" option

### ISSUE THREAD

**Issue by nikp79** [keepassxreboot/keepassxc#8318]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

macOS 12.4
KeepassXC 2.7.1

In versions previous to 2.7.1, there was an option to "Forget TouchID after session is locked", which I found to add an extra layer of security.  Was there a reason this was removed in the first place?  I do not see any mention of it in the changelogs nor doing multiple searches in GitHub and Google.  If I have missed the explanation, I apologize and would appreciate the link to the information.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

If was originally found in Preferences>>Security>>Convenience

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Key example (as far-fetched as it is) why this is important to me is if anyone is able to grab my laptop as soon as I unlock my computer at any point via TouchID, at least KeepassXC will require the full on password at that point because the TouchID session would expire upon locking my computer (assuming I havent entered the password yet).

**Comment by droidmonkey** [comment]
There really is no security benefit to be had here. You are better off just disabling touchid and only lock your database on session lock instead of timeout. This setting was removed due to user request. 

Your concern is that after you unlock your computer someone steals it? They would still need to present your biometrics to unlock the database with touchid. If you already unlocked your database then this setting would not even apply in this scenario.
