### ISSUE TITLE
"Load previously open databases on startup" not working on Windows

### ISSUE THREAD

**Issue by Dogway** [keepassxreboot/keepassxc#8444]
## Overview
When starting Windows (in "minimize on startup" option at least) the last used database isn't autoloaded.

## Steps to Reproduce
Configure the following options and start windows:
- [x] "Automatic launch KeePassXC at system startup"
- [x] "Minimize window on application startup"
- [x] "Remember previously used databases"
- [x] "Load previously open databases on startup"

## Expected Behavior
Would expect the last used database to be loaded automatically on startup

## Actual Behavior
Actually forces me to open KeePassXC, and double click on last used database, which is a very counter-productive method for the above enabled settings.

## Version
KeePassXC - Version 2.7.1
Revision: 5916a8f

## Environment
Operating System: Windows 7 Ultimate SP1 x64

**Comment by droidmonkey** [comment]
Are you closing the database before quitting the application? You can also try quitting keepassxc and then deleting: C:/users/yourusername/AppData/local/KeePassXC/keepassxc.ini 

There is nothing wrong with the setting, it works perfectly for me every day.

**Comment by Dogway** [comment]
No, I simply shutdown Windows. It was working before in version KeePassXC-2.3.4-Win64 from where I updated.

I can show a video for more proof if necessary.

**Comment by droidmonkey** [comment]
Since you updated from such an old version, recommend going to application settings and hit "Reset Settings" at the bottom.

**Comment by Dogway** [comment]
Thanks, working great now!

**Comment by Gittyperson** [comment]
I have the exact same problem. I did not update from an old version. I simply shutdown Windows, without closing the database. I see my recent databases in the Recent databases list but 9 out 10, the previously open database is not opened. I have to manually open it every time. I don't know why 1 out of 10 it will work as expected. In the past it did work, but at some unknown point this started to happen.

Perhaps this is related to how a database is first opened? Does it make any difference if a database is opened from the recent list, from the Database menu or by double-clicking a database file?

I guess I can try resetting all settings, since it is my last resort.

**Comment by Gittyperson** [comment]
Resetting the settings solved the problem. Will post again if it reappears.

**Comment by Gittyperson** [comment]
Just FYI, this issue keeps cropping up fairly often on me lately. Everything is as described above. Simple Windows shutdown while one or two databases are open and unlocked. No KeePassXC updates from older versions.

Resetting settings to default now does not solve it (it did at some point in the past).
Deleting \Roaming\KeePassXC\keepassxc.ini does not solve it.
Deleting \Local\KeePassXC\keepassxc.ini solves it - until the next time.

KeepassXC 2.7.9, Windows 10.
