### ISSUE TITLE
Error while reading the database. Not a keepass database

### ISSUE THREAD

**Issue by 2411TrollFarmer** [keepassxreboot/keepassxc#8459]
## Overview
When I open my database file I put in password but get greeted with Error while reading the database. Not a keepass database
.kdbx file

## Steps to Reproduce
1. Open the db from desktop
2. Enter password
3. Takes it but doesn't open up the database 

## Expected Behavior
It should open and show my passwords 

## Actual Behavior
Gives error Error while reading the database. Not a keepass database

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Home

**Comment by droidmonkey** [comment]
It's not a keepass database. You either have a corrupted file with corruption at the very start of the header or its notna keepass database at all.

**Comment by SummaCumWilly** [comment]
I just hit this same error on a file of mine, too. The circumstance was that the file is on a shared drive (Mac M1 Pro is my side and Windows Server is the SMB share). I had the file open last night and I shut down my Mac. When I went to open the file this morning, I got this same error. Using the file command, BOTH the KDBX file AND its "old" backup file are corrupt since they both show up as merely "data" unlike the other saved KDBX files in that directory which show up as "Keepass password database 2.x KDBX" files. The date for the live database seems to be the time I most recently added an entry to it, but I'm not exactly sure of it. Filestamp is Jan 18 and Jan 19 was when I shut down.
My version is 2.7.3. Ventura 13.1. Posting this as a data point in case another shows up.
The file is simply 37KB's worth of null characters.
