### ISSUE TITLE
Configure autosave delay per database

### ISSUE THREAD

**Issue by spotlesscoder** [keepassxreboot/keepassxc#8553]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I want a per-database file setting on how long the application should wait before committing confirmed changes into the database file on disk. 

E.g. I want to set a timeout of up to 5 minutes so that I can make multiple edits but the changes are saved only 5 minutes after the last edit or when I force saving by pressing CTRL + S

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
When performing multiple edits in a row, especially with larger databases, the saving after clicking OK in the detail view, the saving takes quite a lot of time

**Comment by jNullj** [comment]
Can i get assigned to do that? I would love to try.
I belive there is no risk in making this setting part of the metadata and i think it will best fit in General window of the database settings - under the "Additional database settings".
@CodingSpiderFox Wouldn't it be better to save after X minutes since the **first** change that triggers the timer to avoid data loss? Sure it will lag once in a while to save but you will have more control over the level of risk regarding losing information. That way you still get "forced" into saving once in a while. If i implement the timeout since the last edit there might pass a long time between edits. Altho i agree its nicer to get the app to lag on save only after a few min it is not in use.

**Comment by droidmonkey** [comment]
Yes please do try this
