### ISSUE TITLE
No text on Ubuntu 22.10 snap

### ISSUE THREAD

**Issue by exander77** [keepassxreboot/keepassxc#8579]
![image](https://user-images.githubusercontent.com/2256039/195939569-309712d4-d49d-4a3a-accb-db95852455b4.png)

**Comment by droidmonkey** [comment]
Seems to be an issue with your system. Please use our appimage or flatpak distribution.

**Comment by exander77** [comment]
> Seems to be an issue with your system. Please use our appimage or flatpak distribution.

I doubt it as not other applications exhibits the similar issue and all requirements are fulfilled. And the issue was not there before update to 22.10.

**Comment by droidmonkey** [comment]
This problem doesn't happen for anyone else. It actually reminds of some of the Qt high dpi problems from a couple years ago.

**Comment by exander77** [comment]
> This problem doesn't happen for anyone else. It actually reminds of some of the Qt high dpi problems from a couple years ago.

I have seen a similar issue from the past. The Ubuntu 22.10 is still development version, so not many people run it and I would note that I have a 4K laptop screen. So it may be a combination of several factors.

But between it working and it not working there was only update from Ubuntu 22.04 to Ubuntu 22.10.

**Comment by droidmonkey** [comment]
Right, so if keepassxc didn't change versions then it isn't us. Either way, the snap distribution is deprecated in favor of flatpak which is far more reliable.

**Comment by exander77** [comment]
> Right, so if keepassxc didn't change versions then it isn't us. Either way, the snap distribution is deprecated in favor of flatpak which is far more reliable.

Issue resurfaced again. And I am 100% sure it is keepassxc issue as it no other application was affected, it resolved itself after a while and now after updading an update of packages the issue resurfaced again.

**Comment by michaelerule** [comment]
I'm working on debugging this issue right now.  User [exander77](https://github.com/exander77)  appears to be correct that this is a GUI toolkit issue that somehow only affects keepassxc on the systems where it appears.

However, it is not a problem with *only* KeePassXC. I have binaries for KeePassXC `2.6.6` and `2.7.9`. On `Ubuntu 22.04 LTS` the GUI text is invisible. On `Ubuntu 22.04.4 LTS`, it is visible. 

Thus, it appears that this is an *interaction* between KeePassXC and some Ubuntu configurations you can find out in the wild. The fix may be to change KeePassXC's documentation, rather than its source code.

I will try to move the 22.04 system up to 22.04.4 and see if the issue resolves.
