### ISSUE TITLE
Implement QMacToolBar on MacOS

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#871]
MacOS GUI provide a standard application toolbar. This toolbar is supported by Qt by http://doc.qt.io/qt-5/qmactoolbar.html (apparently it's native).

It's of course platform specific, and I understand you don't want to make to much platform specific code. But It can really make the app feel more natural on macOS.

## Expected Behavior
Having a native/standard application toolbar like most macOS application.

## Current Behavior
The toolbar look kind of like a mac application but do not behave like one (can't change icon order).

## Possible Solution
Implement QMacToolBar

Operating system: macOS

**Comment by phoerious** [comment]
I looked into replacing the toolbar with a QMacToolBar as part of our restyling effort, but I came to the conclusion that it is impractical to implement, since QMacToolBars only allow for adding simple buttons and not other widgets such as our search field. Thus, we have to stick with our almost-native "unified" QToolBar.
