### ISSUE TITLE
MSI installer always creates a desktop shortcut

### ISSUE THREAD

**Issue by Vanerio** [keepassxreboot/keepassxc#8711]
## Steps to Reproduce
1. Install MSI x64 file in windows 10. Uncheck creating a shortcut in desktop. (it may happen with other options too)
2. Check desktop icons

## Expected Behavior
Desktop shortcut not created.

## Actual Behavior
Desktop shortcut is created.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

Operating System: Windows 10

**Comment by droidmonkey** [comment]
Can't reproduce this at all, are you sure this is happening from our installer or something setup on your computer specifically. Your other issue seems highly suspect as well, not reproducible.

**Comment by philipmgrant** [comment]
I get the same behaviour on Windows 10 with the MSI installer for KeePassXC 2.7.4 and 2.7.3 (I can't remember whether I had this on previous versions).

**Comment by Vanerio** [comment]
Yes. This happens to me with your installer.

**Comment by philipmgrant** [comment]
Looking in my registry, KeePassXC has set a property "DesktopShortcut" with a value of 1: presumably from a previous install.

When I run the installer, the checkbox for "Create Desktop Shortcut" is checked by default, which seems reasonable given the registry entry.

The problem is that manually unchecking that checkbox does not stop the creation of a desktop shortcut for the current install (and nor does it remove or change the value of that registry entry).

I'm guessing that if I deleted the registry key, subsequent installs would work correctly.  But the current behaviour seems suboptimal: my choice on a past install means that only by going into the Registry Editor can I ever suppress the creation of the shortcut in future.

**Comment by droidmonkey** [comment]
That's a good finding but certainly not unique to 2.7.3. The installer code to add desktop shortcut hasn't changed for years.

**Comment by philipmgrant** [comment]
Sure, I definitely wouldn't swear to it not being an issue on previous versions :)

Looks like the WIX config was overhauled in June 2021 - possibly the `SetProperty` on `INSTALLDESKTOPSHORTCUT` here is involved? https://github.com/keepassxreboot/keepassxc/commit/724f691e159f69c16d01ca00908452d2d8d6c5d4

**Comment by Vanerio** [comment]
well seen!
