### ISSUE TITLE
[Windows Error] KeePassXC doesn't immediately pick up changes in time zone

### ISSUE THREAD

**Issue by pqne** [keepassxreboot/keepassxc#8723]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When changing the time zone in Windows while a database is unlocked, TOTPs get created with respect to the old time zone. Locking and re-opening the database resolves the issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database with at least one TOTP entry
2. Change time zone in Windows settings
3. Create TOTP

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The correct TOTP is created.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
And incorrect TOTP is created.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I change time zones manually on my computer. If automatic switching is enabled, the problem might not surface, as Windows probably changes the time zone before I manually unlock my Keepass database.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19042

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
TOTP doesn't care about your timezone setting, it is calculated based on current seconds since epoch. It is likely a Qt bug if anything. All we do is ask Qt what the current time in UTC is and convert that to seconds since epoch. Locking and unlocking your database is irrelevant to this, what is relevant is likely you waited for a couple seconds for Qt to catch up. Either way there is nothing we can fix here.
