### ISSUE TITLE
Do not compromise entire DB when a single entry is accessed

### ISSUE THREAD

**Issue by hofesh** [keepassxreboot/keepassxc#884]
## Desired Behavior

If a PC is compromised, and a user unlocks his KP file to get a single password, the rest should not be compromised as well.

## Current Behavior

Currently unlocking the DB to get even a vanilla password (say a social website credentials) expose all of the passwords, even hyper sensitive ones like those of financial institutions.

## Possible Solution

The inspiration comes from how Trezor encrypt passwords in their password manager implementation, discussed here: https://github.com/keepassxreboot/keepassxc/issues/746
I think this could be possible to achieve with the newly introduced Yubikey support.
If within the DB, each entry is encrypted using a combination of MasterPassword + EntryID + Yubikey challenge-response, then after unlocking the DB (with/without using a Yubikey) and requesting the password for a single entry (say by hitting Ctrl+C) a challenge would be sent to the Yubikey with the combined key. This way, even if the PC is fully compromised, the user has only lost the single password(s) he used while it was compromised.

IMO this will be a big leap forward in terms of securing the most sensitive data.

Note: I'm currently experimenting with using a bunch of separate KP files for different sensitivity categories, but unlike the proposed solution, it is:
- much weaker than an entry-level separation
- cumbersome
- requires remembering a bunch of Master passwords instead of just one

**Comment by droidmonkey** [comment]
This breaks compatibility with other keepass apps. If you have hyper sensitive entries just put them in a totally separate database that is locked with yubikey and a strong password.

**Comment by phoerious** [comment]
I also thought a little about it and came to the conclusion that besides breaking compatibility, it imposes very much effort for very little to no gain.

What are the scenarios in which your DB gets compromised? These are basically:

1. Someone gets hold of your master password
2. Someone is snooping on your PC while your DB is open
3. Someone figures out a way to break AES or Twofish

3. is extremely unlikely and 1. and 2. eventually come to the same result. In combination with a Yubikey you might argue that the attacker still doesn't necessarily know the HMAC secret, but if they managed to break into the database in the first place, that's a very faithful assumption.

**Comment by hofesh** [comment]
> This breaks compatibility with other keepass apps.
I don't mind having an incompatible KP file if it increases security.




> If you have hyper sensitive entries just put them in a totally separate database that is locked with yubikey and a strong password
as I noted, this is a less secure solution and more cumbersome which in turn discourages it's use.




> it imposes very much effort for very little to no gain

what is the added effort?
If the KP file is protected by a master password only, and it's stored in memory after the DB in unlocked, then copying a password triggers an Yubikey challenge-response interaction without any further required interaction from the user. The total number of action the user performs is exactly the same. Of course that various combinations of friction / strictness can be made (e.g. a master password + Yubikey to unlock DB, and also require master password to copy a password to avoid storing in memory).
The gain on the other hand it HUGE - never ever expose all of your passwords, only the ones you used. That is a categorical difference. 



> What are the scenarios in which your DB gets compromised

The likely scenario this benefits the most is a key logger on the PC which also picked up the KP file. The PC can be kept compromised in this manner for days / weeks / months before the user realizes the breach. during this time, a single access to the DB (in the correct implementation) is GAME OVER, while in the suggested implementation the damage is strictly limited to which ever passwords the user accessed during that time. Not only does it contain the damage, it also allows the users to know which information was and was not compromised, which has value in itself. 

Even if the scenario is DLL injection into the KP application or any other tinkering, the result is the same - without knowing the Yubikey secret no other password is exposed (which there is no reason to assume he has - that is the entire point of the Yubikey - protection on a compromised computer).

I appreciates your response, although I believe that this feature has merit as an opt-in feature for users who aspire for maximum security. Even today the Yubikey support breaks compatibility with many other implementations, and since this is only feasible with Yubikey, there isn't a big difference in the end result.

**Comment by phoerious** [comment]
> what is the added effort?

There is a lot of implementation effort involved in this. The KDBX format already has encrypted inner streams for in-memory protection (that's what happens when you click "Protect" on an advanced attribute, for instance). The decryption key, however, is stored inside the database and is supposed to be stored in a non-swappable protected memory area (yes, this feature is only meant for in-memory protection). KeePassX(C), however, only reads in those encrypted inner streams and stores them unencrypted in memory, because nobody has yet wanted to invest time in implementing a feature which adds rather theoretical extra security. Unless you have very limited memory and your system starts swapping KeePassXC out to disk, there is no real benefit to be gained. Sure, it won't hurt and add some extra security in certain cases, but the actual scenario is rather academic. In most cases the premise is "if the attacker is on your system, you lost."

The same is true for what you are proposing. It takes a lot of time for implementing this properly which is probably better spent on features which actually have a larger benefit.

> The likely scenario this benefits the most is a key logger on the PC which also picked up the KP file. The PC can be kept compromised in this manner for days / weeks / months before the user realizes the breach. 

When you have a key logger on your system, it is game over anyway. Inner stream encryption won't save you in any way. The key logger could simply trigger a copy command on all of your DB entries and unless you have your YubiKey configured to require button presses for HMAC (which is neither the default, nor how this mode is meant to be used), you won't even notice. People still appear to have the mental picture of key loggers being dumb programs which only log your key presses to a file and send it to some FTP server on the web. Those times have been over for a decade or more. Modern key loggers are principally fully-fledged remote access terminals with loads of automated logging capabilities built in.

**Comment by phoerious** [comment]
Also another huge drawback is that you can't ever change your YubiKey's secret or you will lose access to all your passwords. If only the full DB is encrypted with a YubiKey, changing the secret only requires you to open it, change the secret on the key and then refresh the database key via the "Change database password" dialog. If you encrypted each entry individually, all those entries needed to be decrypted first using the old secret (which probably doesn't exist at that time anymore) and then re-enrcypted with the new secret. I don't see how this can be implemented in a safe and efficient way.

**Comment by hofesh** [comment]
> There is a lot of implementation effort involved in this

I though the effort comment was regarding user interaction effort, not implementation wise. As I'm unfamiliar with the code base I can't comment on that.



> In most cases the premise is "if the attacker is on your system, you lost."

Not in this case, which is what makes it a desirable feature.



> The key logger could simply trigger a copy command on all of your DB entries and unless you have your YubiKey configured to require button presses for HMAC (which is neither the default, nor how this mode is meant to be used), you won't even notice

True, it will only work with button press, which is how I use Yubikey, and it's also how a security-oriented user who would like to use the proposed feature would configure the Yubikey. This is a matter of choice / documentation, not implementation - but the key point is that it *would* work. 




> Also another huge drawback is that you can't ever change your YubiKey's secret or you will lose access to all your passwords. If only the full DB is encrypted with a YubiKey, changing the secret only requires you to open it, change the secret on the key and then refresh the database key via the "Change database password" dialog. If you encrypted each entry individually, all those entries needed to be decrypted first using the old secret (which probably doesn't exist at that time anymore) and then re-enrcypted with the new secret. I don't see how this can be implemented in a safe and efficient way.

That is a valid point, but can be resolved automatically - when a master password is changed and is using a Yubikey, all of the entries are re-encrypted. To avoid forcing the user pressing the button for each entry, the Yubikey would have to be reconfigured to not require a button press with the same secret, and after the password change is complete reconfigured back to require a button press. Of course, like any master password change, this should be performed on a trusted computer. The point is that preventing this is enforceable without loss of any data.

**Comment by phoerious** [comment]
> Not in this case, which is what makes it a desirable feature.

See my comment about modern key loggers.

> and it's also how a security-oriented user who would like to use the proposed feature would configure the Yubikey

I would doubt that. YubiKey HMAC CR is meant to be used as interaction-less dongle mode. The fact that you can configure it to require a button press is only due to the fact that the YubiKey already has a button for FIDO-U2F, so Yubico added that for the extra cautious.

> That is a valid point, but can be resolved automatically

And that's where you are missing half of the process. You can't just plug in the new YubiKey and tell KeePassXC to re-encrypt. You need to plug in the old one first, tell it to decrypt everything and save it in memory, then insert the new YubiKey and tell it to re-encrypt everything. In both cases with being annoyed to death if you forgot to turn off button presses for the YubiKey. This process is extremely error-prone and unsafe.

>  Of course, like any master password change, this should be performed on a trusted computer. 

This kind of defeats the whole purpose, doesn't it? Let me put that in contrast to what you said earlier:

>  The PC can be kept compromised in this manner for days / weeks / months before the user realizes the breach.

**Comment by hofesh** [comment]
> See my comment about modern key loggers.

I have. What am I missing? How can an sophisticated attacker reveal passwords the user has not accessed in the proposed solution (with button press required)?



> This kind of defeats the whole purpose, doesn't it? Let me put that in contrast to what you said earlier:

Yes, the proposed feature will only hemetically protect the passwords in every day usage, but not in a master password change event (which can be performed on a clean environment for the extra cautious).

I understand that in your view the costs are greater than the benefits, so let me ask an open question then - given that both Trezor+its PasswordManager app and KeePassXC+Yubikey are physical and offline desktop application based implementations - what are the architectural design differences that make one a simple and viable solution for isolating individual passwords and the other complicated and error prone? I'm asking this as a way to looking forward, in an ever growing information oriented society with more at stake, what is the correct approach to securing secrets?

**Comment by phoerious** [comment]
> I have. What am I missing? How can an sophisticated attacker reveal passwords the user has not accessed in the proposed solution (with button press required)?

Without button presses, it's rather trivial. With button presses you can still trick the user into pressing the button twice when they save changes to their DB, so an attacker can extract individual high-value entries. That wouldn't even be obvious. I regularly have to press the button two or three times when logging into GitHub or Google, because the first press wasn't recognized. There are lots of tricks you can do to work around the user factor. Keep in mind that for your full DB to be actually in danger, you already need a rather targeted attack, so those extra tweaks aren't even as improbable as they may sound.

> I have. What am I missing? How can an sophisticated attacker reveal passwords the user has not accessed in the proposed solution (with button press required)?

The difference is that Trezor is designed for managing a password vault, while YubiKey HMAC CR was originally designed for authentication (therefore HMAC). The fact that we are using it for enhancing the encryption key is actually kind of a hack which works quite well in the scenario we use it in, but becomes a lot unsafer and trickier in the scenario which you are proposing.

If you want your YubiKey to encrypt the data, the Neo's CCID OpenGPG feature is much better suited, but an entirely different application. It isn't inherently incompatible with the KeePass format, but very different from how any KeePass-compatible password manager works.

**Comment by hofesh** [comment]
@phoerious 
thank you for the comments. 
I have nothing more to add on the issue, so you can close it if you see fit.

**Comment by phoerious** [comment]
I'm closing this as WONTFIX then. We might re-evaluate some ideas if someone finds the time to implement in-memory protection, but right now, I don't see how this can be implemented in a safe and reliable way or how the required development effort would justify the gains.
