### ISSUE TITLE
Show all entries in group including those of subgroups (optional)

### ISSUE THREAD

**Issue by leonbohmann** [keepassxreboot/keepassxc#8871]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
What I'd really like is an optional feature where, when activated, one is able to see all entries in a group including those of sub folders.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Consider this structure:
```
Group:
  SubGroup1:
     Entry1
     Entry2
     Entry3
  Entry4
  Entry5
```
Currently, if I select "Group", only Entry4 and Entry5 will show up and therefor using Search I can only find either one of them.
If we were able to show all entries in a group and its subgroups the search would be easier! If I chose "Group", all Entries 1..5 would show up and be "findable".

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This would give me more control because I could see all contents of a group without having to click every subgroup.

**Comment by droidmonkey** [comment]
> using Search I can only find either one of them.

That's not true even if you have group scoped search enabled since it includes subdirectories.

![image](https://user-images.githubusercontent.com/2809491/205927733-7d9ebb05-cd1a-47a8-a8b8-29e69b41c282.png)

Search is by default global so... you should be able to find them.

Also you can search for `*` to see all entries, by default it flattens the groups and shows them in a column. You can also add a `g:groupname/` to your search to scope it dynamically to that group and subgroups. 

![image](https://user-images.githubusercontent.com/2809491/205928440-645744ac-034f-45a5-8eb1-c48f9ebe0349.png)

In 2.7.4 you can save your searches for easy repeat.

![image](https://user-images.githubusercontent.com/2809491/205928158-9fde8a3c-c20a-44ae-9cc5-58a85bb88414.png)


All this to say, no we won't implement that feature, it doesn't make sense. If you want a flat view, place your entries in 1 group.
