### ISSUE TITLE
Windows: "Making sure it's you" can be skipped

### ISSUE THREAD

**Issue by miguelanjo** [keepassxreboot/keepassxc#8897]
## Overview
"Making sure it's you" check on Windows can be skipped and database opens anyway

## Steps to Reproduce
1. Give password to unlock database
2. "Making sure it's you" window appears
3. Click the top right X
4. Database opens anyway
5.

![image](https://user-images.githubusercontent.com/40229929/208241313-8567fffa-5b6a-459c-a19e-bdf4712ceb12.png)

## Expected Behavior
Database should remain closed as I did not verify myself

## Actual Behavior
Database opens

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: Windows

**Comment by droidmonkey** [comment]
Skipping this just means quick unlock is not enabled...

**Comment by ikarmus2001** [comment]
I have quick unlock enabled, experiencing the same bug
My version is up to date, just checked

Imo if Windows Hello check is skipped anyway why bother user with dialog?

**Comment by JohnLGalt** [comment]
Windows Hello is used **for quick unlock**. If you skip it you're effectively disabling Quick Unlock for that session, nothing more.

https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_quick_unlock

IOW - if you want to use Quick Unlock, **don't skip the Windows Hello prompt.**

If you want to always skip the Windows Hello prompt **then disable Quick Unlock.**

**Comment by jcewinggh** [comment]
The description of the intent of this new feature implies that the quick unlock is an alternative to specifying the master password.  That says to me that if the master password is specified when initially unlocking the database, that you shouldn't then also be asked to supply Quick Unlock credentials, which it always seems to request AFTER the correct master password has already been supplied.  That seems like overkill.   Yes, it turns out it will let you in after a password has been supplied if you just Cancel the fingerprint/PIN request, but if its going to allow that it shouldn't ask for it and imply it is needed.

After the initial unlock, subsequent unlocks during that same KeePassXC session begin with request for a fingerprint or PIN on Windows 11.   There are legitimate reasons why one might prefer always forcing use of the master password to unlock a KeePassXC database even though the system permits a fingerprint or PIN to logon/unlock a user account -- a locked system left unattended with KeePassXC active on a locked database would only require hacking a simpler PIN to get to the desktop and also gain access to all account information in the KeePassXC database.  

It turns out you still can choose to unlock KeePassXC with only a  master password on subsequent unlocks, but it is a convoluted process -- cancel the request for the fingerprint, giving a window to supply the master password;  after supplying the master password you get another fingerprint request and after canceling that you finally get the database unlocked-- three  interactions where previously only one was required -- surely not an intended design.

I couldn't find any option in KeePassC 2.7.5 settings on Windows 11 to totally disable this Quick Unlock feature, although there is documentation that suggests that was intended .  There should be a way to give the user the option of totally disabling this feature.  I personally like to be forced to use the master password for each unlock so I use the master password often enough to not forget it.

**Comment by droidmonkey** [comment]
Application Settings -> Security tab -> under convenience, uncheck the first option which will disable quick unlock

**Comment by jcewinggh** [comment]
Dang!

I checked and rechecked those "Convenience" options multiple times and never saw it.   I guess the last place my mind expected to see a new option to appear was at the top of the options list and my mind just tuned out the first option.  That option definitely gets me back to the behavior I prefer.  My primary KeePassXC usage is on a Linux desktop and it was very confusing to have unlock start working differently on my Windows laptop.

I am still  puzzled why the Windows interfaces would be designed to require the Windows Hello handshake (as documented in KeePassXC "Quick Unlock" Help documentation) on the initial database unlock just "to access the hardware certificate store".   If the Quick Unlock option is enabled, it seems like the logical time to try to establish whether Quick Unlock support is available would be when a database first locks later on and that support might actually be needed.

There is still a inconsistency between documentation and the actual behavior.  The documentation says the redundant Windows Hello invocation is only needed on the initial database unlock; but it also occurs on a subsequent unlock if you Cancel the Quick Unlock and elect to instead use the master password to unlock -- which is once again followed by a redundant Windows Hello invocation as if this were an initial unlock.

**Comment by droidmonkey** [comment]
Initial unlock means you do not have quick unlock credentials stored in the windows store. The documentation is not inconsistent with that. You will be asked for quick unlock every time you unlock unless you disable it in settings. 

Another feature request on our board is about updating the unlock dialog user interface to let you choose whether you want to enable quick unlock or not at the time of unlocking.

**Comment by jcewinggh** [comment]
Most users will have no concept about KeePassXC internals involving credentials and will interpret "initial unlock" as the first unlock after the database is opened (which can successfully occur by supplying a password even if the following Windows Hello window is  Canceled).  Perhaps the informational comment should be clarified to give a more complete description of behavior from the user's perspective.  The following may be  overkill and can possibly be simplified, but it is the actual behavior I seemed to observe with version 2.7.5 on Windows 11.

"With Quick Unlock enabled, on the first unlock of the database after open the password is required followed by a Windows Hello authentication to setup subsequent Quick Access Unlock access.   If the Windows Hello authentication part fails and is Cancelled the database is sill unlocked, but subsequent unlocks will continue to request the password, followed by Windows Hello authentication for setup until a successful Windows Hello authentication occurs, after which subsequent unlocks will only need a Windows Hello Quick Unlock.  If a Quick Unlock is successfully setup but at some point can't be made to work and is Cancelled, the setup status is reset and behavior reverts to a password request followed by a Windows Hello authentication for Quick Unlock setup, as on the first unlock after database open."

It would certainly be less confusing from the users viewpoint and easier to explain the behavior if there were some way to title the  Windows Hello authentication as a "Quick Unlock Setup" window when that is its only function, rather than have all occurrences appear to be required as authentication just to unlock the database; but perhaps Windows Hello logic has no way to support that.

**Comment by JohnLGalt** [comment]
> If the Windows Hello authentication part fails and is Cancelled the database is sill unlocked,

I would say:

If the Windows Hello authentication part fails **_or_** is Cancelled the database is sill unlocked,

As each can occur without the other.
