### ISSUE TITLE
Add GPG key pair support

### ISSUE THREAD

**Issue by j-lakeman** [keepassxreboot/keepassxc#8902]
## Summary
I really appreciate the SSH key integration! Is it possible to also implement this for GPG key pairs?

## Examples
Upon unlocking the database, key pairs could be added to GNOME or macOS keychain and removed vice versa, just like with the SSH keys.

## Context

GPG key pairs are needed for the following:

- sending / receiving E2EE e-mails using OpenPGP
- signing Git commits or anything really
- asymmetric encryption of files

**Comment by RaafatTurki** [comment]
Any updates on this?
This is the missing puzzle piece that would make keepassxc truly the one stop shop for personal security.

**Comment by droidmonkey** [comment]
This is not going to be implemented by us anytime soon. A community submission would be considered.

**Comment by pryndor** [comment]
As far as i know, Instead you can save the same exported file in attachments?

**Comment by 0xIO32** [comment]
> This is not going to be implemented by us anytime soon. A community submission would be considered.

Proposal:
- KeePassXC mounts its own fuse-filesystem (it is mounted, even if no database is open)
- The unmodified gnupg agent will be started with the home directory set to the fuse-filesystem.
- KeePassXC notes the pid of the gnupg agent and only allows access to the filesystem through this pid.
- On database open the fuse filesystem will be populated with the private and public keys found in the database (via attachments)
- The fuse filesystem will be read and writable (on closed database write: it will throw an error)

The following is ensured:
- Access to keys is only granted by user confirmation (the gpg agent takes care of the confirmation). Direct access to the key files is not possible, due to the pid check.
- Keys are never stored on the disk (this would have been the case if the gpg key would have been imported on open and removed on close)

Would a pr with these changes be accepted?

This would require the libfuse3 dependency and would only work on linux + bsd (or similar operating systems).

Technically there is "WinFSP" (filesystem in userspace for windows), but that requires an kernel driver to be installed and doesn't work out of the box.

@droidmonkey

**Comment by droidmonkey** [comment]
No we would not integrate this.

**Comment by 0xIO32** [comment]
> No we would not integrate this.

I could also write an own gnupg agent for keepassxc, but that could be a maintenance burden.

**Comment by droidmonkey** [comment]
You are welcome to do anything on your own fork, but we won't incorporate this feature, it is just not something that we want to deal with to be honest.
