### ISSUE TITLE
KeeShare needs a keyfile option for container files

### ISSUE THREAD

**Issue by clintonsasoft** [keepassxreboot/keepassxc#8960]
## Summary
Using Keeshare makes a kdbx file that can be opened with KeePassXC and it reduces the security of access these share kdbx files by only allowing a password to protect these files but there is no option to add a key file to access them. When using a key file and Keeshare, this makes the use of the key file redundant because if somehow an attacker got hold of the shared kdbx and password they would be able to access its data not my database that I use a key file to unlock but the shared kdbx container file created and used by Keeshare. I want the highest security here I can obtain without a penalty of making myself insecure due to collaboration. I want to use a key file with Keeshare container files to retain the key file for extra security which is highly desirable for me and my organization.

I added a mock of the button in the edit group frame/view:

![keepassxc-edit-group-add-key-file](https://user-images.githubusercontent.com/77098724/210832006-05d400e5-9078-4497-8d1a-6104dbd1bcaf.png)

**Comment by droidmonkey** [comment]
You don't want to use keeshare then. Use auto open instead, see our user guide. 

KeeShare with a key file or yubikey doesn't make sense because we embed the credentials to open the share within the database itself. A long secure password provides equal protection. You would necessarily have to share both the key file and the keeshare file with your collaborators. If an attacker gets hold of the keeshare file, and the password, there is an incredibly high likelihood that the key file is also easily obtained.

**Comment by clintonsasoft** [comment]
Hi @droidmonkey thanks for your reply. I don't agree its equal protection.

First we send key files in password protected 7z files via communication channel A, password for 7z file containing key file in communication channel B, and lastly the password to access the kdbx file communication Channel C. Each channel representing a different communication platform, in our case, email, WhatsApp and Slack. So you not likely to get the key file and password in our case.

If you can get hold of the share kdbx file that KeeShare creates then you can open it directly just with a password. We use a key file to open our main kdbx file which contains the shared group that is using a container kdbx copy of the database that doesn't require a key file. So it seems pointless using a key file for my main kdbx then.

Our organization requires to use a key file in order to make use of the password database. So KeeShare won't work for us without it, and adding the feature to allow it, in our opinion, enhances the security of KeeShare and gives the key file a strong use case.

Please consider it, I am willing to contribute in development. We want to use Keeshare for its merging feature.

**Comment by droidmonkey** [comment]
You can transmit the information however you want, but the key file still needs to be stored somewhere and also in a location that keepassxc can access and read from in order to do its job. Also everyone necessarily has the same password and keyfile so that's a lot of trust in various people.

A keyfile is just a poor man's yubikey without dedicated hardware protection and revolving challenge. It's actually a terrible way to add security to your database unless you store it on a dedicated usb drive and only plug it in when necessary to unlock and save your database.
