### ISSUE TITLE
Auto-type selected entry

### ISSUE THREAD

**Issue by SwarfegaGit** [keepassxreboot/keepassxc#9014]
## Summary
In KeePass, you can assign a hotkey to 'Auto-type selected entry'.  

## Context
I mainly use Auto-type in applications rather than websites and the majority of my apps already populate my username so therefore only require a password. I have multiple entries in KeePass each with different auto-type sequences.  For my password-only entries, they are simple {PASSWORD}{ENTER} and I use this in combination with the 'Auto-type selected entry' hotkey.  
Without this feature, I can't use KeePassXC which I sooner would as it has native security key support, unlike KeePass.

**Comment by droidmonkey** [comment]
Not sure what version you are on but sounds like you need to upgrade. We are up to 2.7.4 and this feature is available. Read our user guide for more information.

**Comment by SwarfegaGit** [comment]
I have 2.7.4 but I do not see this option. Can you please tell me where it is? 
I have looked through the guide but see nothing that represents the 'Auto-type selected entry' that is found in KeePass.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_performing_entry_level_auto_type

**Comment by SwarfegaGit** [comment]
Whilst that works it's not the same thing that is available in KeePass.  
That requires me to open up KeePassXC and then use the GUI or use Ctrl + Shift + V.  With KeePass, the keyboard shortcut is user defined (I personally use Ctrl + Alt + S) and it also does not require me to maximise KeePass as it is a global hotkey.  Basically, I never need to leave my program's window for the password to be auto-typed into it.

**Comment by droidmonkey** [comment]
Look one section above, that is how KeePassXC handles global shortcut based auto-type today. The selection dialog is very powerful and would most definitely meet your needs. What you are specifically looking for is #5962

**Comment by SwarfegaGit** [comment]
That actually looks slightly different to what I need.  What I need is to have a global shortcut to perform the auto-type sequence of the entry that I currently have selected/highlighted in my database.  This gives me the ability to auto-type the sequence of the selected entry in any window I need. KeePassXC doesn't need to search window titles etc.  When done in KeePass it doesn't open anything, it just runs the auto-type sequence which in my case is {PASSWORD}{ENTER}.

Does that make sense? I don't think I am being all that clear. It may be easier to understand if you try the feature in KeePass to see what I need.

**Comment by droidmonkey** [comment]
That feature itself makes no sense and we wouldn't implement it. You are either interacting with the main window or the autotype select dialog. There is too much that can go wrong with the requested feature.

**Comment by cyberroneous** [comment]
Necro-posting to make a renewed argument and case for this feature, as follows.

Currently my more tedious procedure for each login is, starting within KeepassXC:

1. Select specific entry from list
2. Open URL in browser by hitting Ctrl-Shift-U
3. Hit Alt-Tab to go back to KeePassXC
4. Hit Ctrl-Shift-V to activate autotype for currently selected entry
5. Wait for login to complete as expected

What I am trying to do is eliminate the need for step 3, switching back to KeepassXC in order to activate auto-login using the currently selected entry. Ideally, there should be a global hotkey, usable from anywhere, that triggers KeepassXC to behave as though someone just typed Control-Shift-V from its main screen. Instead of having to switch back to it first, from the browser.

Reasons why this is needed:

Currently the global autotype hotkey almost always brings up the entry search dialogue, which if you have hundreds of entries, is quite cumbersome and time-consuming to either scroll through or type enough letters to narrow down to the entry you're looking for. Nowhere near as ideal as hitting one hotkey combo, and being done.

Even when "use entry title" and/or "use entry URL" to match windows are selected under settings, the entry search dialogue still almost always comes up and necessitates further searching. But even if the title/URL matching does work, there are still cases where it's ineffective, such as:

1. Cases where you have multiple accounts/logins at the same site, such as Amazon, Gmail, Discord etc. In that case, the title and URL will match several entries, and you have to subsequently choose which one you want.

2. Even if you only have one account, often the URL will get changed randomly by the website you're loading, so that if your entry is "https://www.whatever.com/login", the website will change it upon load to: "https://www.whatever.com/login?token=23423534534326723" and the match will not occur.


Therefore, it would be incredibly useful to be able to set a single global hotkey which, instead of trying to match a title/URL or bringing up a selection dialogue, simply pretends the user hit Ctrl-Shift-V and sends the autologin sequence for the ***currently selected entry***.  (Or clicked the "Perform Auto-type" button, in case the specific sequence is different for each entry).

At the moment as a workaround, to accomplish this I am using a shell script and external tools, to wit:

`#!/bin/bash`
`wmctrl -a "KeepassXC" `
 `sleep 1s  `
`xdotool keydown ctrl key V keyup ctrl `


This works but requires installation of wmctrl and xdotool, and still visually causes the momentary toggling back to KeepassXC screen before flipping back to the browser again.

Hope the feature request might be reconsidered, thanks.

**Comment by droidmonkey** [comment]
1. https://keepassxc.org/docs/KeePassXC_UserGuide#_configure_auto_type_sequences

2. Use browser extension 

3. Use browser extension, but use the "Request Auto-Type" shortcut to pre-filter by url

**Comment by cyberroneous** [comment]
Thanks for the quick reply and suggestions. For various reasons, chiefly that I run all browser instances in Firejail sandbox containers which isolates them from the rest of the system, the browser extension is unable to interact/connect with the running instance of KeepassXC. Thus I am reliant on autotype exclusively.
