### ISSUE TITLE
File Dialog could use xdg-portals to use native filemanager

### ISSUE THREAD

**Issue by ChrTall** [keepassxreboot/keepassxc#9057]
## Summary
On KDE Plasma most applications use the native filemanager when you want to open a file from your filesystem.
Firefox for example has an option to use xdg-desktop-portal.
[Reddit](https://www.reddit.com/r/kde/comments/sd1v2a/tip_set_widgetusexdgdesktopportal_to_true_in/)

## Context
This has the advantage that your pinned folders that you access frequently are also in the file dialog when you want to search for your database or keefile.

**Comment by droidmonkey** [comment]
This would have to be supported by Qt. If you are using snap distribution then this is likely broken. Native install and flatpak should work fine.

**Comment by cardboardcpu** [comment]
Hi, sorry to necrobump, but I think circumstances have changed since the last comment was written.
> This would have to be supported by Qt.

According to [Flatpak's Docs](https://docs.flatpak.org/en/latest/portals.html#portal-support-in-qt-and-kde), support for the [XDG File Chooser Portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.FileChooser.html#file-chooser)  is available in Qt5 via [QFileDialogClass](https://doc.qt.io/archives/qt-5.15/qfiledialog.html).

With toolkit support out of the way, could this issue be considered again? Better platform integration is always a win.

Thanks.

**Comment by droidmonkey** [comment]
That would require no changes from us
