### ISSUE TITLE
Allow for second Yubikey (for 2FA) - Not closed.

### ISSUE THREAD

**Issue by techrivertree** [keepassxreboot/keepassxc#9061]
Thank you for allowing the challenge response for logging with a yubikey. I was finally able to set this last night. One yubikey is good, two yubikeys are great. One primary, one backup. If you loose your primary you have a back up.

Two challenge responses for yubikeys would help just in case we lost our primary yubikey.

**Comment by droidmonkey** [comment]
Make a copy of the keys. Use the same secret on both.

**Comment by techrivertree** [comment]
Yubikeys cannot be copied

https://support.yubico.com/hc/en-us/articles/360016614880-Can-I-duplicate-or-clone-a-YubiKey-

"For security, the firmware on the YubiKey does not allow for secrets to be read from the device after they have been written to the device. Therefore you cannot duplicate or back up a YubiKey or Security Key. "

**Comment by droidmonkey** [comment]
Use the same secret key on both.....

**Comment by techrivertree** [comment]
Why would I do that? That is a huge security issue. Linux allows two hardware keys. I would hope that keepassxc would allow the same thing in the future.

**Comment by droidmonkey** [comment]
I don't understand how that is a security issue. One key is your primary the second is your backup. Store your backup in a safe place in case your primary is lost, stolen, destroyed.

**Comment by techrivertree** [comment]
A backup key allows you to login to devices, programs, or websites with different keys, keys that are registered with the device, program, or website. You are correct about the storing of backup keys but they need to have the credentials to allow you to login to whatever.

**Comment by techrivertree** [comment]
I should add that I am using the challenge response mode for my yubikey...

**Comment by droidmonkey** [comment]
First off, it is not possible for us to allow more than one yubikey with different secrets for the same database. It breaks the kdbx standard. Secondly, there is zero difference between two different keys that can "unlock" the same resource and two of the same keys that can unlock it, especially when the resource is an offline database file in this case.

**Comment by techrivertree** [comment]
So is the problem related to kbdx or yubikey? If its yubikey, I can engage the developers.

**Comment by kaoneko** [comment]
Hey @techrivertree, I get the idea you don't fully grasp how all of this works. Correct me if I'm wrong.

When you use a YubiKey with the FIDO2 standard, the secret the YubiKey uses to assert its authenticity never leaves the YubiKey, ensuring there can ever only be one copy of the key.

When you use a YubiKey in challenge-response mode, as KeePassXC does, the secret stored on (a different part of) the YubiKey is actually shown to you while configuring it and can at that moment be copied to be programmed into another YubiKey. As only the same secret results in the same response to a challenge, and this response is used in en-/decrypting the database key, it's not possible to use a second YubiKey with a different challenge-response secret to decrypt the same database. It has to have the same challenge-response secret.

When using the FIDO2 standard, as you might be doing to login to Linux, you can register two different keys each with their own FIDO2 secret. Using the FIDO2 protocol to en-/decrypt a database is not possible however, because it's designed for authentication, not encryption of data, [as I understand it from the KeePassXC FAQ](https://keepassxc.org/docs/#faq-yubikey-2fa).

So your only option really is to program your backup key with the same challenge-response secret. I don't think engaging the YubiKey developers is going to change that.
