### ISSUE TITLE
Not a request, but rather a suggestion

### ISSUE THREAD

**Issue by tfavreau** [keepassxreboot/keepassxc#9063]
I believe that under settings - security - lock databases after inactivity of - checkbox should be on by default.

The purpose of having a password database is to be secure; however, walking away from your workstation is a real world event that happens to all of us. We get interrupted, then forget we left the password manager open.

This one change would make the default settings more secure.

I did a new install of 2.7.4 for reference.

**Comment by droidmonkey** [comment]
We have decided to not enable this by default because it can be unexpected behavior for new users and seen as a frustrating feature. We do enable "Lock on Screen Lock/Saver" by default which is our preferred way to secure your database. Typically a timeout of any relevance would also lock your screen.
