### ISSUE TITLE
Additional Tools: MD5/SHA Hash

### ISSUE THREAD

**Issue by im-richard** [keepassxreboot/keepassxc#9097]
## Summary
I cannot speak for others, however, I am in my KeePassXC database a fair bit. And I'd love to see a converter which can take normal strings and convert them into various other hash types such as MD5, SHA256, SHA3-256, etc. Frequently I have to keep a website up to do the conversions because of how I utilize my passwords and it's just an extra step that becomes a pain.

## Examples
I suck at mockups, but this gives the just idea. Definitely sure there are better ways to implement.

![kpassxc_mockup](https://user-images.githubusercontent.com/13498846/217994294-b18384bc-6f64-4e4f-bfa3-f78152fb6335.png)

A few websites as a source:
- https://www.pelock.com/products/hash-calculator
- https://www.tools4noobs.com/online_tools/hash/

## Context
Some people utilize the password field to enter raw text, however, will go a step further and convert that raw string into a hash which ends up being the actual password to use for more sensitive logins.
Also it's just nice to have a localized hash converter without keeping a website open or having 3 different programs that give different algorithms.

**Comment by droidmonkey** [comment]
You take your password in keepassxc and then hash it to make your real password for a website? Why not just make your password 32 characters long?

**Comment by user23498723452** [comment]
@droidmonkey I'd agree.  This request seems like an ill advised practice, as the hash provides no better security than a password of the same length, but due to the fact it (very likely) reduces the character space used , you are reducing "complexity".  In addition, I'd be concerned the user is NOT typing out a longer password, but instead assuming the "longer" hash is protecting them,  ignoring the fact that hashes for well known passwords and shorter strings exist and hashes are just as trivial to guess/test.  The only way I'd consider this interesting, is if the user had a complex salting technique for the passwords and kept the "salt" separate from the "password".  But not sure that would be helpful in the end user scenario.  Not to mention,  a random long password can easily exceed the character space for a hash of any type.  Plus what do you do when the site doesn't permit more than 15 characters? (which is still all over the place)

Not saying I'm right, but I definitely wouldn't want the team spending time on this vs *any* bug fixes needed.
