### ISSUE TITLE
Feature request: Propose a username using "plus" email addresses

### ISSUE THREAD

**Issue by e2jk** [keepassxreboot/keepassxc#9134]
## Summary
When creating a new entry, this new feature would automatically use the entry's name or URL/server name to propose a username/email address using the "plus" mechanism.

## Examples
One (largely used) email service that proposes "alias" email addresses is GMail. For example, if you have the joe@gmail.com address, you can add anything after the username and the plus symbol, and the emails sent to these addresses will still end up in your inbox. Example:
- joe+facebook.com@gmail.com -> joe@gmail.com
- joe+randomwhatever@gmail.com -> joe@gmail.com
- etc.
(by the way, it's also often not known that [dots are of no importance in GMail](https://support.google.com/mail/answer/7436150?hl=en). So j.o.e@gmail.com also goes to joe@gmail.com, and you can combine that with + as well - but I digress...)

So if you're creating an entry named Facebook, the email address could automatically be proposed to be joe+Facebook@gmail.com (if using the title) or joe+facebook.com@gmail.com (if the URL of the entry is defined, and using only the domain name (second level + TLD - I would personally prefer that second way, since it's what I already do manually for my usernames)

## Context
Using different email addresses for each service increases our users' resiliency if one of the external services is breached, the credentials can not be reused in an automated way to try to breach other services. Like using a different password for each site, using a different username/email address improves the overall security of our users.

For official documentation from Google, expand "Filter using your Gmail alias" on [this page](https://support.google.com/mail/answer/22370?hl=en).
(this + aliasing also works for custom domains using the Google Mail services on the backend, like Google Workspace [or however that service is called now])

Note that here I'm mentioning GMail, but other email providers also allow this type of "plus aliasing".

**Comment by e2jk** [comment]
Can be interesting to review together with this other feature request, #9133 "generate random usernames with DuckDuckGo.com email addresses (@duck.com)"

**Comment by droidmonkey** [comment]
Combine this with #8254

**Comment by mosbey** [comment]
I really like this idea in + subaddressing and want to note that it's supported by other providers like Microsoft and is based on RFC.

https://www.rfc-editor.org/rfc/rfc5233

I am not sure I would support the . method, as that is, AFAIK, not supported by RFC and is exclusive to Gmail, and not even Google's business email offering.

**Comment by JohnLGalt** [comment]
Furthermore, Google actually just strips out the . in the username - no matter how many of them are in there - so it is ineffective.

One thing that concerns me about + addressing is that, you'll still need to use different passwords, otherwise the account it is attached to can be compromised anyway with just a little engineering. So, you'd still need to enact overt strategies like not using the base account to connect to services (which is very hard for some people to do in this day and age), strong passwords and multi-factor authentication, and all the other usual suspects you currently have to do anyway.

In the end, it merely becomes another layer of complexity more than anything, as far as I can see.

And I'm trying to (and failing!) to ask the question: Please explain how this is any better than just using strong PWs + MFA for every account with the same email account.

**Comment by droidmonkey** [comment]
After further review, I do not understand the need to bake this into KeePassXC as a _feature_. It is beyond trivial to just add the `+sketchy-site1` to the end of your email username in KeePassXC. Adding it as a feature will just lead to very cumbersome UI interactions.

**Comment by ghost** [comment]
Apologies if this is the wrong issue to add a comment, but i'm unsure to which of these similar issues i should reply to.

In the case of appending `+sketchy-site1` to the email user name i don't see the advantage.  But this isn't my strategy, instead i have a totally random email address at my domain, for example `dream.mansion5678@example.com`, which is two words and some random numbers at my own domain.

Previously i did that in fastmail using the masked email feature, which has integration only with onepassword.  In order to avoid the feature reliant on one email provider i set up a catch all email for my domain and now i come up with my own random emails to input into keepass, but this is cumbersome itself so i have a script to do it for me, so i still have a middleman step.  I think it would be really great to have this just in keepassxc.

In terms of being a cumbersome ui, for the most part i don't think so.  There can be a dice icon next to username as well as password, and the popup it would be very similar to the passphrase generation screen, with "prefix" and "suffix" as options (i would want to use suffix and put `@example.com` in that field, and people using gmail plus addressing could put `username+` in the prefix and `@gmail.com` in the suffix field).

This is just my vote for reconsidering this feature.

**Comment by droidmonkey** [comment]
Since randomness is irrelevant for your scenario, just choose two words and a number for yourself... we don't need code to do what you can do trivially. 

If you want some seed words, use the passphrase generator. 

Honey.Dream5473
Salty.Fighter34443
Thanos.Snap2433
Corn.Meal33432

**Comment by ghost** [comment]
As i said, i already have code to do this for me, but i would rather this feature be in keepass to streamline the process.

> we don't need code to do what you can do trivially

I can see where you're coming from, but it seems like the software has other features which could be done trivially manually but have been added because it makes for a better experience for some of the users.  It seems that enough people want this feature that it wouldn't go unused or unappreciated.

If i wrote code for this is there any chance of it getting merged?

**Comment by droidmonkey** [comment]
See #8254, it would have to damn near perfect code with enough options to make it worthwhile. Your very specific use case doesn't move me to want to make a boat load of ui and code changes.

**Comment by ghost** [comment]
I can't work out from that issue whether this is a feature that will be in the 2.8.0 release or not, because in all the other issues you close them and don't seem convinced by the idea.

> Your very specific use case doesn't move me to want to make a boat load of ui and code changes.

Sure, i don't want to waste your time.  But i contest that this is a very specific use case since i expressed how my format could be part of the same ui as those desired by other people in similar issues.  It also seems that most of the code has already been written as like you say the passphrase generator can almost do what i want already.  So the code would be being reused from there.

But if you don't see the value in this, that's okay.  Like i say, i already have a script to generate what i want, i just thought that it would be useful to have in keepassxc too.

**Comment by droidmonkey** [comment]
I have come around to a username generator, but it needs to be done well and complete. Not piecemeal. Sorry for being confusing, this debate has been going around for a while. It is a useful feature, but the temptation to add a hundred different sub features is very high. We see that with the password generator, everyone wants a little niche feature. When you add all those up it becomes a lot of code to maintain and test.

**Comment by ghost** [comment]
Thanks for the clarification.  Then i wish you the best in finding a solution that is maintainable :)
