### ISSUE TITLE
Unble to open database with known good credentials (Master PW and Yubikey)

### ISSUE THREAD

**Issue by techrivertree** [keepassxreboot/keepassxc#9196]
## Overview
Yesterday I could login to my database but in the afternoon I saw some sort of error. I cannot remember what the error said. I saved my session, logged off, and tried to login. KeepassXC tells me "Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

## Steps to Reproduce
1. Enter in master password
2. Plug in yubikey
3.  Try to log in. Yubikey works but the database does not open

## Expected Behavior
Login

## Actual Behavior
Error: "Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

## Context
I mistakenly thought I had to change the secret key on my yubikey but after hours of frustration I remembered that I had saved the private key. I used terminal to change the private key back to the good private key (the key from yesterday).

KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

Qt 5.15.5
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.15.0-67-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux (Zorin 16.2)
Desktop Env: ?
Windowing System: ?

**Comment by techrivertree** [comment]
I am willing to send the devs my database and private yubikey.

**Comment by droidmonkey** [comment]
There is absolutely nothing we can do to help you. You will need to revert to a backup database or figure out whether it's your password or yubikey that is wrong.

I personally recommend downloading our appimage and trying to open your database with that. We don't support our snap install anymore because of how awful that platform is. 

One question, which save method are you using? This is found near the top of the application settings.
