### ISSUE TITLE
KeePassXC sync Across Virtual Machines and Host on shared folder

### ISSUE THREAD

**Issue by qdrddr** [keepassxreboot/keepassxc#9315]
As a KeePassXC user on macOS, I would like to use the app on my Mac and the Virtual Machines with Windows that I run on my macOS. 

So currently, I have two instances of the KeePassXC app: one on a macOS host and one KeePassXC app inside my Windows Virtual Machine that runs on the same Mac machine. 

When I open the same KeePass password file on both macOS and Win VM simultaneously using a shared folder, I can read and work with the file in read-only mode.
But if I try to add new items to my password database, I end up with conflicting versions of my KeePass password database.

As a user, I would like to work with the same file simultaneously from multiple computers without producing conflicts. Ias a user, when I add new items, they would synchronize automatically, so if I add an item to a KeePass on the Win VM, I can see this item on my opened KeePassXC app on Mac and vice versa. 

This might also be useful if you are simultaneously working with the same password file via a network-shared folder on multiple computers.

**Comment by droidmonkey** [comment]
This is already a feature. Sounds like you need to fix the data sharing you have between the host and virtual machines.

**Comment by phoerious** [comment]
Pretty sure the issue is the file system interface between the host and the VM, which doesn't trigger on external changes, so the VM doesn't see when the file changed on the host. This is most common with Samba-based file shares. There is nothing we can do to fix that. However, you should be able to Auto-Type from the host into the VM without issues. You can also use the clipboard if your VM supports clipboard sharing. Only the browser extension inside the VM wouldn't work this way.
