### ISSUE TITLE
Revert colourful tray icon  on Windows - 2.7.5

### ISSUE THREAD

**Issue by jonathanlermitage** [keepassxreboot/keepassxc#9432]
## Summary
On Windows 10, with a 125% UI scale, KeePassXC 2.7.5 updated the **colourful** tray icon (for locked and unlocked database). It is now a bit smaller, and a bit blurry, even after a computer restart. The monochrome tray icon did not change, and this one seems OK.   
I reinstalled KeePassXC 2.7.4, and the colourful tray icon has a better dimension. I don't know if you have similar feeling about that...

## Examples
The 2.7.5 colourful tray icon:
![image](https://github.com/keepassxreboot/keepassxc/assets/857535/5cad4f9c-a5d0-4d92-b53d-ca91e9d1ddd9)

The 2.7.4 colourful tray icon which, for me, seems better:
![image](https://github.com/keepassxreboot/keepassxc/assets/857535/5a61352e-f682-45c7-9ad0-1794df8e1c8a)

Regards,

**Comment by phoerious** [comment]
Doesn't really look any blurrier to me. Just a bit lighter.

**Comment by droidmonkey** [comment]
I think the blur is more noticeable

**Comment by phoerious** [comment]
That's more of a contrast issue.

**Comment by koitsu** [comment]
It (2.7.5) looks highly anti-aliased, the white border/edge around the lock symbol being completely removed, a gradient added to the background behind the key icon, and shading being added around the edges of the key to give it depth.  These icons seem to be SVGs, based on a quick source review.

To confirm my statements and the OPs statements, [refer to the actual diff of the icons themselves](https://github.com/keepassxreboot/keepassxc/commit/64b3695e5136efef519105d46e128fee44aca683) since they're SVGs. Search the page for `share/icons/application/scalable/apps/keepassxc-locked.svg` and you'll see a side-by-side comparison (deleted=2.7.4, added=2.7.5).

I don't know why the aspect ratio looks skewed (in the OP's screenshot), so there may be something amiss with the SVG data itself.

That said, I agree that the 2.7.4 icon looks better in general.  SVG scaling never looks particularly good, *especially* when scaled to a small size (like tray icons).  You are literally better off having a pixel artist draw your tray icons, else keep the icons extremely simple.  Yes, high-res versions look great, but not until you scale them down do you notice usability/visibility problems.
