### ISSUE TITLE
Copy TOTP value in preview pane on double click

### ISSUE THREAD

**Issue by ytqxyd** [keepassxreboot/keepassxc#9545]
## Sum
![keepassxc](https://github.com/keepassxreboot/keepassxc/assets/3675060/fef59962-5567-4777-b810-b8cb136e51f0)

Add a copy button that allow quickly copy TOTP from this menu

## Examples
![image](https://github.com/keepassxreboot/keepassxc/assets/3675060/02c0894d-96a4-4ebb-ae2f-3337275da094)

Add a button here

## Context

It's more clear where to get and copy TOTP code

**Comment by droidmonkey** [comment]
Not going to add another button, just implement double click to copy

**Comment by foss-** [comment]
+1 for this feature request (double click is a good solution). When adding value to clipboard, please remove the space in the middle of the 6 digits.

Currently when copying the TOTP to clipboard the result is `123 456`. However when pasting this may then result in `123 45` since the field the value is pasted to only allows 6 digits.

**Comment by foss-** [comment]
Verified in KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 5fb26d6

Thanks for implementing.
