### ISSUE TITLE
Patreon?

### ISSUE THREAD

**Issue by NIXOYE** [keepassxreboot/keepassxc#956]
Are their any plans to make a Patreon or OpenCollective for the KeepassXC development team? I for one would definitely support you guys for the amazing work being put into KeepassXC

**Comment by magkopian** [comment]
As far as I know, the KeePassXC team accepts donation through [Flattr](https://flattr.com/submit/auto?fid=x7yqz0&url=https%3A%2F%2Fkeepassxc.org).

**Comment by NIXOYE** [comment]
Barely anyone uses Flattr though so it's extremely unlikely they will get any donations through there

**Comment by magkopian** [comment]
The purpose of my comment was strictly to inform you how you could support the project by donating. Since you've clearly expressed in doing so, but from your comment it seemed like you were not aware about how.

Now whether or not Flattr is the best platform for this is another story. And that's something which is up to the KeePassXC team to decide.

**Comment by droidmonkey** [comment]
I never heard of open collective. Decided to sign up after visiting their site. Way better than flttr.

**Comment by NIXOYE** [comment]
Consider Patreon as well more users there

**Comment by phoerious** [comment]
Paypal is also planned.

**Comment by TheZ3ro** [comment]
Maybe also Bitcoin?

**Comment by strixaluco** [comment]
For the FLOSS projects, which obviously KeepassXC is, [Liberapay](https://liberapay.com/) seems like more appropriate, than Patreon.

**Comment by jankudrik** [comment]
Maybe I am doing something wrong but it seems to me that Flattr has closed new registrations, so even thought I would like to support this project, I cannot :-(

Anyway I am strongly in favor of the idea to accept donations via Liberapay.

**Comment by NIXOYE** [comment]
Again the problem with liberally is barely anyone using it so you have to convince someone to sign up for a new service and donate where with Patreon you can convince me to donate with 2 clicks since I and hundreds of thousands of other users are already supporting projects

**Comment by rugk** [comment]
Can you please reconsider Liberpay? (and, @droidmonkey, could you please reopen this issue)

It is not about getting users to sign up for that, but rather letting users, who are already signed up for that, to donate. Also Patreon got bad news coverage recently, because they increased their prices. Liberapay does not take any provisions and does also sem to fit into the FLOSS world a bit better.

And BTW, Liberapay can also work with few clicks.

> Again the problem with liberally is barely anyone using

Hey, don't say you'd want to exclude users because of that. If you had a Twitter account or so for KeePassXC Liberapay users could already promise you some money (I'd would do.), even as you are not signed up. Maybe that would change your decision.

The current donation methods are not really nice… Also for you, there is no donation method, where you can get money regularly, except for Flattr, but there the amount is arbitrary and not really controllable by the user.

**Comment by rugk** [comment]
I have to corret my statement. It does not only work with Twitter, but also with GitHub.

So **Liberypay users** (you are at least 6 persons, when I see [the upvotes for that comment](https://github.com/keepassxreboot/keepassxc/issues/956#issuecomment-330112350) **let's promise KeePass some donations via LiberaPay!**

➡️  https://liberapay.com/on/github/keepassxreboot/

**Comment by phoerious** [comment]
I feel like payment providers are a bottomless pit. We already support three of them. Perhaps Liberapay is another good option, but it's also just one more service of hundreds.

**Comment by rugk** [comment]
Actually Liberapay is not yet another payment provider AFAIK, they use Mangopay for payments (because they have to use something, …, obviously).

**Comment by scheunengeist** [comment]
End of last year, I was about to donate, but I had just left Flattr behind me after they've become even more intransparent with their latest changes, and so I couldn't. Both Paypal and Patreon sound like a good idea, so I second the notion. I have no experience with Liberapay, so no idea if it's a viable alternative.

**Comment by ArchangeGabriel** [comment]
Liberapay is very nice. It’s a non-profit, with FLOSS truely in their mind.

**Comment by phoerious** [comment]
We do support PayPal already.

**Comment by TheZ3ro** [comment]
I've looked into liberapay and I've set up my personal account (https://liberapay.com/TheZero/) pretty easy and intuitive.

You can't make single payments but you can start a recurrent payment and end after the first one.

But I still can't find how to withdraw the received money

**Comment by ArchangeGabriel** [comment]
Maybe because “We quarantine money for 1 month to protect ourselves from credit card fraud, sorry for the inconvenience.”?

**Comment by NIXOYE** [comment]
you guys are missing the point. There are hundreds of thousands of Patreon users. There are a ton of open source projects using it Ura Design, Flarum, 100 Rabbits, off the top of my head. being on patreon will open you to support form users who haven't heard of keepassXC but find out about it through Patreon. For those of us who already know about KeePassXC and are already on Patreon (like me) its only 2 cicks away from me donating monthly to the project. It's such a minimal setup it'd be kinda absurd for the team not to set it up.

**Comment by droidmonkey** [comment]
I'll be setting up Patreon this week.

**Comment by xCapRx** [comment]
Is there any update on Patreon?

**Comment by droidmonkey** [comment]
Check it out: https://www.patreon.com/keepassxc

You may now contribute via Patreon!

**Comment by xCapRx** [comment]
Awesome! Will do :)

**Comment by xCapRx** [comment]
BTW, have you guys considered adding a donation menu to your UI? It could have links for people to check out your PayPal, Patreon, LibraPay, etc. This might help spur more people to support you since those links would be in a more accessible/prominent position. You guys are volunteering your time to develop XC so I see no shame in doing it.

**Comment by droidmonkey** [comment]
Not a bad idea!

**Comment by xCapRx** [comment]
Thanks. I hope to see it implemented some day :)

**Comment by xCapRx** [comment]
Thanks. I hope to see it implemented some day :)

**Comment by droidmonkey** [comment]
@NIXOYE just wanted to ping you that we have opened our [Patreon](https://www.patreon.com/keepassxc) and [OpenCollective](https://opencollective.com/keepassxc) donation platforms.

**Comment by rugk** [comment]
BTW your [liberapay donations](https://liberapay.com/keepassxc/) do not work currently, because you have not filled out the identity form.

**Comment by droidmonkey** [comment]
I am not interested in another payment platform. Please use the ones above or Bitcoin or PayPal.

**Comment by rugk** [comment]
> I sincerely do not appreciate liberapay just posting our project without permission.

You had to sign up there to collect donations, so all stuff you entered of course appears there. Otherwise nothing is "posted".
So you already signed up there – or is not the account legitimate?

> grant them access to our repository

That is needed when you want to collect donations as obviously donors have to identify/validate you of course. They have to know that you really belong to KeePassXC.

> The only way to remove it

You can always delete your account, AFAIK. Not sure what problem you face here.

> As a result, I am boycotting.

You are not. You are leaving a stale account at some platform and don't notify donors that it is actually not "enabled".

/cc  @liberapay

**Comment by droidmonkey** [comment]
Nobody created that account...

**Comment by droidmonkey** [comment]
Looks like I was not well informed on how LiberaPay works... apparently anyone can initiate donations to any project, but the donations are not drawn until the project maintainer claims the team. Unfortunately, their website does not make it possible to claim the team... I submitted a help ticket with LiberaPay.

**Comment by tuxayo** [comment]
> apparently anyone can initiate donations to any project

Anyone can make a pledge to any project https://en.liberapay.com/on/github/nextcloud

But the liberapay page isn't in the pledge state anymore: https://liberapay.com/keepassxc/

The fact that the GitHub account is linked shows that one the keepassxreboot repo owners linked the account to make the donation collection effective. I hope that you will be able to agree with each other about accepting Liberapay :)

Thanks for your work!

**Comment by droidmonkey** [comment]
I think I uncovered a bug. I had initiated it but cancelled the authorization. Now it's stuck in a half configured state

**Comment by TheZ3ro** [comment]
The account is linked to the team email and to the github organization correctly.
To actually receive payment we need to set payment information :)

**Comment by droidmonkey** [comment]
Yah i don't want it to be an organization then we can't individually receive donations. According to the maintainers we can't transition to a team... So now we are stuck.

**Comment by droidmonkey** [comment]
They fixed it in the back end. I'll set this all up later.

**Comment by thearkadia** [comment]
why is there no patreon link on the website?
