### ISSUE TITLE
dots are absent with automatic entry

### ISSUE THREAD

**Issue by Bundy01** [keepassxreboot/keepassxc#9576]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Register a login (mail) or a pwd with a dot
2. Set automatic entry
3. Try to connect to the site

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
keepassxc 2.7.5-2 on Arch

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
What do you mean? This doesn't make any sense unfortunately.

**Comment by Bundy01** [comment]
Sorry if I wasn't clear.
If my password contains a dot or if the login is my e-mail address, I get an error telling me that the password or my login is wrong.

I haven't had this error for long. It appeared with version 2.7.5

Edit: Looking at the update dates for Keepassxc on Arch, I don't think it's from that. The problem is more recent. It must come from a dependency, but I don't know which one.

**Comment by droidmonkey** [comment]
You have this problem: https://github.com/keepassxreboot/keepassxc/issues/9564#issuecomment-1599422486

It was induced by an update outside KeePassXC

**Comment by jpggithub** [comment]
I have the same problem (XFCE 4.18, Debian testing Trixie, keepassxc 2.7.9).
I use BEPO (variant for french texts).
On Debian, I have 2 choices :
- BEPO 
- BEPO AFNOR

There is no problem with BEPO AFNOR.

With BEPO
- Emacs : no problem
- Firefox, Libreoffice, terminal : the problem is there.

I also tried other french variants : some have the problem (eg. DVORAK) but others have not the problem (ex. AZERTY, ERGO-L).

So the problem seems to be a problem from the keymap used.

My solution : I now use the BEPO AFNOR variant.
