### ISSUE TITLE
SSH Agent support for WSL 

### ISSUE THREAD

**Issue by psztoch** [keepassxreboot/keepassxc#9585]
## Summary
Windows users commonly use WSL now.
It would be convenient to support OpenSSH agent in WSL (as an independent third option) additionally to Pageant and local OpenSSH.

**Comment by droidmonkey** [comment]
Pretty sure you just need to expose the ssh agent running in WSL (Version 2) to the outside world. Otherwise it would be impossible to communicate with it from the Windows side. 

https://github.com/rupor-github/wsl-ssh-agent#wsl2-compatibility

**Comment by Okeanos** [comment]
As an update to this: I recently stumbled across [OmniSSHAgent](https://github.com/masahide/OmniSSHAgent) that may be of interest here.

**Comment by mdonoughe** [comment]
According to the documentation (my SSH key is in hardware so I don't use this feature), KeePassXC does not contain an SSH Agent. It has code that can manage keys inside another agent. If that agent happens to be the one used for Linux it should just work.

If KeePassXC wanted to additionally load keys into a separate agent running under WSL, it's possible but not as simple as just loading it into WSL. I'm pretty sure the `\\wsl$\` share doesn't allow socket connections from Windows to Linux because Windows named pipes and Unix sockets are very different. However, it is possible to write keys over stdio, so KeePassXC could do something like spawn an ssh-add process inside a Linux distribution and pipe the keys into it.

However:
1. Not all WSL distros are active at all times. KeePassXC should only add keys into distros that are active, not activate inactive distros just to manage transient SSH keys, and distros may become active or inactive at any time after KeePassXC has loaded its keys. I guess KeePassXC would need to somehow monitor WSL distros starting and stopping. Windows can stop the distro and unload the SSH agent if it determines that the distro is not being used.
2. I'm pretty sure WSL doesn't normally run an SSH agent. On my Linux system, the SSH agent is a systemd unit, but WSL doesn't normally run systemd. On my WSL installation I have an SSH agent that I installed and I'm pretty sure I didn't need to disable any preexisting agent to do that.
3. Because KeePassXC is not an SSH agent, it must export the full private key to the real SSH agent that is going to be doing the signing. Care should be taken to ensure that the WSL distro receiving the unencrypted private key is really one that the user intends to load the private key into. Otherwise the private key can be easily exported by temporarily registering a malicious distro containing only a fake ssh-add executable.

It's probably best for users that want to use the same SSH keys in Linux and Windows to use one of the existing Linux SSH agent replacement solutions.

**Comment by droidmonkey** [comment]
Agreed, we really have nothing to implement here on our end. This is about using the tool I posted above or just running keepassxc in WSL itself. I do this all the time when testing.

**Comment by OlivierMary** [comment]
Hi,

My solution if it helps anyone:

- Use OpenSSH Agent in KeepassXC config.

If all is good in powershell, test:
```powershell
 ssh-add.exe -l
256 SHA256:5Jxxxxxxxxxxxxxx

# or

ssh.exe user@example.com

...
```

then in WSL 2:

```shell
echo 'export PATH=~/.local/bin:$PATH' >> ~/.zshrc
# or ~/.bashrc

# refresh zsh
zsh

# find ssh.exe
 which ssh.exe
/windir/c/Windows/System32/OpenSSH//ssh.exe

# create symbolic link
ln -s /windir/c/Windows/System32/OpenSSH//ssh.exe ~/.local/bin/ssh

# verify that the good ssh return
which ssh
/home/<your_user>/.local/bin/ssh

#enjoy
```

It works for:
- SSH (of course 😄 )
- Git
- Docker remote context

You can also just make an alias `alias ssh=ssh.exe`  if only need ssh, 
if need git you can use `export GIT_SSH_COMMAND=ssh.exe` 
but no other solution for docker remote context so prefer the symbolic link :)

cya

**Comment by Bargamut** [comment]
IT MIGHT BE SOLUTION for somebody.

Hi there! )

Sorry for necropost but I think it will be useful for other seekers:
we can use **OpenSSH** and **Npiperelay** on the Windows side + **Socat** on the WSL side.

Thanks for this post: https://code.mendhak.com/wsl2-keepassxc-ssh/ - there are description & troubleshooting for the script below.

Run bash script on WSL:
```bash
npiperelaypath=$(wslpath "C:/npiperelay")

cd ~

echo "Get npiperelay"
wget https://github.com/jstarks/npiperelay/releases/latest/download/npiperelay_windows_amd64.zip
unzip npiperelay_windows_amd64.zip -d $npiperelaypath
rm npiperelay_windows_amd64.zip

echo "Install socat"
sudo apt -y install socat

echo "Add to .bashrc"
cat << 'EOF' >> ~/.bashrc
export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock

ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0 ]; then
    rm -f $SSH_AUTH_SOCK
    (setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"$npiperelaypath/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork &) >/dev/null 2>&1
fi
EOF

echo "Reload ~/.bashrc"
exec bash

echo "Done"
```

In my case it works. 👍
