### ISSUE TITLE
Password lifetime calculator

### ISSUE THREAD

**Issue by QuAzI** [keepassxreboot/keepassxc#9663]
Is it possible to add a new filed "Time to local brutforce" near Password Quality and Entropy in the password generator?
And maybe it is a good hint to propose this Time as the latest preset in "Expires" or to highlight password strength (if Modified + Time To Brutforce already happened)

**Comment by droidmonkey** [comment]
The password quality indicator is essentially the same thing. There is no such thing as "time to brute force". That is entirely up to the compute power of the adversary and your choice of password. If your password is "good" or better, then it will be impossible to brute force.

**Comment by QuAzI** [comment]
The password quality indicator isn't very obvious to ordinary people. The computer power can be selected as one of the most powerful at release date for approximate calculation. 
The main idea is to show password vulnerability in as much practical form as possible to let people see why passwords weak.
As an example, Bitwarden has "Estimated time to crack" https://bitwarden.com/password-strength/

**Comment by JohnLGalt** [comment]
Key word - **_estimated_**.

What Droidmonkey was saying was that the computer power levied to crack a password is **extremely relevant**. Most malicious actors are _not_ going to use a **single computer** or even just _a small cluster_ - they are more than likely going to throw a **BotNet** at it as a cluster to highly decrease the time / increase the efficacy. Even if they have to 'rent' a BotNet lol.

Do we estimate for 10 computers? 100? 1000? 10000? More? Regardless of what value you pick here, the estimate is for that set of computers comprising that compute cluster - nothing more, No more relevant unless you can give exact numbers at every BotNet out there that could possibly be levied to assist in cracking any give password.

What level of computer power (or, in this case, size of BotNet) is considered 'acceptable' in generating said estimate?

`Estimated time to crack` is, really, as pointless a statistic as `how secure` the password is - because the end user making use of the password and all of their policies / procedures / actions are going to factor into that security. We can't account for 8 billion+ possible scenarios in terms of individual user actions. Likewise, we cannot account for all the different BotNets and computer clusters out there that could be leveraged into cracking passwords.
