### ISSUE TITLE
Windows Build: libyubikey v1.5+ not found

### ISSUE THREAD

**Issue by dsbert** [keepassxreboot/keepassxc#967]
Attempting to build on Windows using the set up guide. I'm running into problems building `libykpers`.

## Expected Behavior

Running `./configure` in `libykpers-1.18.0` directory should report success.

## Current Behavior

Running `./configure` in `libykpers-1.18.0` directory reports the following error.

```
configure: error: libyubikey v1.5+ not found, see https://developers.yubico.com/yubico-c/
```

I'm pretty sure `libyubikey` built successfully (did not see any errors) and I see the following.

```
$ ls /usr/lib | grep yubikey
libyubikey.a
libyubikey.la

$ ls /usr/bin | grep yk
ykgenerate.exe
ykparse.exe

$ env | grep LIBRARY
LIBRARY_PATH=/usr/lib
```

## Steps to Reproduce (for bugs)

I just walked through the development setup guide.

## Context

Build keepassxc on Windows.

**Comment by droidmonkey** [comment]
I just resorted to downloading the prebuilt libs from yubikeys website and unzipped them into the mingw path.

**Comment by luzat** [comment]
I would suggest to reopen this or use my documentation fix. I do still get the same error. It is probably a bug in ykpers' configure, because it does not find the `<yubikey.h>` include even when using `--with-libyubikey-prefix=/usr`. The problem can be worked around with `CPPFLAGS=-I/usr/include`, but this still gives a missing libusb reference. The complete solution is to adjust the ykpers configure command to:

    CPPFLAGS=-I/usr/include ./configure --with-backend=windows

I suggest using that in the [documentation](https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows).

**Comment by phoerious** [comment]
The package should be installed into the /mingw64 prefix.

**Comment by luzat** [comment]
You are right. I got both to build with `./configure --prefix=/mingw64` and `./configure --prefix=/mingw64 --with-backend=windows` respectively, but even then building KeePassXC with YubiKey support fails because it tries to link to ykpers (statically?), but the SetupApi.dll symbols/imports are missing.

**Comment by phoerious** [comment]
The static linking should be fixed from our side.

**Comment by droidmonkey** [comment]
Like i mentioned above, just download the lib zip files from the yubikey site and unzip to your mingw64 directory. I do believe their configure is broken as well, also when trying to find -luuid which prevents shared libs from being generated.
