### ISSUE TITLE
Auto-output does not work by hotkey after the program is started

### ISSUE THREAD

**Issue by so1arin** [keepassxreboot/keepassxc#9727]
## Overview
"Auto input" only works until you exit the program. After logging into the program, opening the "Auto input" settings and clicking OK, "Auto input"works. I checked different keyboard shortcuts for their use by other applications - everywhere the result is the same.

## Steps to Reproduce
1. Launch the program;
2. Select auto-drive hotkeys;
3. Close the program;
4. Open the program again and try to use auto-drive hotkeys in any form.

## Expected Behavior
I expect that by selecting the auto-drive hotkey once, it will work automatically after each application launch.

## Actual Behavior
However, now after each launch of the application, along with the start of Windows, I have to re-enter the auto drive settings and click OK to make it work.

Keepassx - Version 2.7.5
Revision: 9d0537b

Operating System: Windows 11 Version 2009
CPU Architecture: x86_64
Core: winnt 10.0.22621

Included extensions:
- Autovod
- Integration with the browser
- SSH agent
- KeeShare
- YubiKey
- Quick unlock

**Comment by droidmonkey** [comment]
I'm assuming you are referring to the global Auto-Type shortcut. You likely have some other program interfering with our ability to obtain the shortcut. You could also have a problem with your settings file not saving. You should delete or rename your %APPDATA%/KeePassXC/keepassxc.ini file. Make sure you don't have any other programs managing keyboard shortcuts. 

Closing since this isn't likely a problem with our program as it works fine everywhere else.
