### ISSUE TITLE
Can't import 1Password opvault in KeePassXC 2.7.6

### ISSUE THREAD

**Issue by hmlea** [keepassxreboot/keepassxc#9771]
## Overview
I used to use 1Password a long time ago on my iPhone before they required an account (IIRC). I synced the vault to my Dropbox where it was saved as 1Password.opvault. I downloaded this file and unzipped it and it resulted in a folder named 1Password.opvault. Now when I go into KeePassXC and click "Import 1Password Database" it won't let me select this folder - instead, the open button is grayed out when the folder is selected. The file structure for the opvault folder is as follows:

```
1Password.opvault/
├─ default/
│  ├─ band_0.js
│  ├─ band_1.js
│  ├─ ...
│  ├─ band_E.js
│  ├─ band_F.js
│  ├─ profile.js

```

I read that this might be a result of 1Password 8 not being a macOS package anymore. Is there any way to fix/get around this? I just want to import old passwords into KeePassXC. I have tried changing the extension to and from .txt like mentioned in previous issues.

## Context
KeePassXC - Version 2.7.6 (also tried on KeePassXC 2.7.4)
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 13.3
CPU architecture: arm64
Kernel: darwin 22.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: macOS

**Comment by michaelk83** [comment]
Currently (as of #5341) you need to have 1password (7?) installed on the system so that the `.opvault` is seen as a file.
If you can't install 1password you can either export/import via CSV, or download [KeePassXC 2.6.1](https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.1) or older, and [rename the `.opvault` folder](https://github.com/keepassxreboot/keepassxc/issues/4069#issuecomment-593407427).
1pux support is still WIP, there is a test build available at https://github.com/keepassxreboot/keepassxc/issues/7545#issuecomment-1512258361, but YMMV.

**Comment by hmlea** [comment]
> download [KeePassXC 2.6.1](https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.1) or older

This solved my problem and allowed for the folder to be imported as long as it contained the extension `.opvault`. I imported it on KeePassXC 2.6.1, converted it to a `.kbdx` file, then was able to open it up in KeePassXC 2.7.6. Thanks for the quick and easy solution!
