### ISSUE TITLE
CLI Loading of multiple databases forgets key path unless previously unlocked

### ISSUE THREAD

**Issue by adbusey** [keepassxreboot/keepassxc#9833]
## Summary
Currently in KeePassXC 2.7.6 Linux, when opening and unlocking a database, the key path is remembered the next time you open it when launching with hard coded database paths from the CLI.  If, however, you do not unlock the database, but exit KeePassXC and relaunch it, the key path is lost.

Remembering the key path in any launch condition would greatly help with automatic startup behavior.  I'm using two databases, so a cli solution would require adding a second key path, which currently isn't supported.

The following items are checked in settings:
Remember previously used database (5 recent files)
Load previously open databases on startup
Remember database key files and security dongles

My current script to launch at boot is:
```
#!/bin/sh

keepassxc /path/to/db.kdbx /path/to/seconddb.kdbx
exit
```

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. keepassxc /path/to/db.kdbx /path/to/seconddb.kdbx
2. Don't unlock databases, but do exit keepassxc
3. keepassxc /path/to/db.kdbx /path/to/seconddb.kdbx

## Expected Behavior
When launching without parameters, the key file path is remembered as expected.  Passing the kdbx paths should produce the same behavior.

## Actual Behavior
Key file path is lost if databases were not unlocked in the previous session

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.4.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Desktop Env: MATE
Windowing System: X11

**Comment by droidmonkey** [comment]
I see this behavior if you open a database, add a key file, but _never unlock_ the database. When you open it again (CLI or otherwise) the key file path is not populated. **This is expected behavior and by design.**

If, however, you do unlock the database then the key file path is remembered and populated when opening from the CLI or using the Open Database dialog.

If you are finding that the key files are not being remembered after a reboot, then you have a totally different problem. That problem would be your ~/.cache folder is RAM mounted and/or gets wiped on reboot. You need to specify a different directory for your local config file (see user guide) or change your .cache folder mounting.
