### ISSUE TITLE
View: Maximize left column group/entries content (I.E. hide Searches and Tags)

### ISSUE THREAD

**Issue by kbulgrien** [keepassxreboot/keepassxc#9861]
## Summary
KeyPassXC is wasteful of vertical screen real estate compared to the original KeyPassX 0.4.4.  One way it is wasteful is that the tree of groups/entries is less compact.  Combined with the fact that the UI wastes space with "Searches and Tags", this makes for a much smaller number of groups/entries to be visible at one time.  When there are hundreds of entries in dozens of groups, this makes for  unnecessarily increased scrolling to traverse the list.  To allow a user to avoid wasting screen space with unused features, allow "Searches and Tags" to be hidden.  Furthermore, there is a blank/unused area under "Searches and Tags" that should not require manual resizing to remove waste.

## Examples
Menu Option: View | [X] Hide Searches and Tags
UI left column contains only the Group/Entries tree.  All space in the column is used.

## Context
I recently moved from KeyPassX to KeyPassXC because on Linux, KeyPassX was no longer available after updating my distribution version.  This drove a change on Windows from KeyPassX 0.4.4 (yes, I intentionally used the old version) to KeyPassXC so I could use the same file format on all platforms.  Now on my Windows (work) system, I find the KeyPassXC UI/UX annoying due to wasted screen real estate and the fact that my work usage is much more dynamic than my Linux desktop (personal) usage.  With hundreds of credentials to store for both work/personal, I have many groups with several levels of depth.  Fully expanded, the left column is about 150 groups high (up to 6 levels deep, and yes, groups have more than one entry each).  In KeyPassX it was easy to visually locate items of need even though some scrolling was required.  In KeyPassXC, the scrolling is dramatically increased due to wasted vertical space (more padding).  I.e. If KeyPassX and KeyPassXC windows are sized the same, KeyPassX shows 40 Group/Entries vertically whereas KeyPassXC shows only 22.

In the example of a vertical height of 150 groups, note that in KeyPassX When the window is sized to fix 40 items, it takes almost 4x vertical spaces scrolled to see the entire list, but in KeyPassXC it takes almost 7x vertical space to see the whole list.  This is unfortunate to a user that likes quick visual searches vs using the search dialog.

**Comment by droidmonkey** [comment]
If you want to hide the searches and tags view just drag the divider down to the bottom of the application

**Comment by Jaz-z** [comment]
KeePassXC - Version 2.7.6
Revision: dd21def

Operating system: Ubuntu 24.04.3 LTS
60 HZ Monitor

 Searches and tags view 

In 'dark mode' on this version of KeePassXC, the demarcation of the panel (divider) is not seen well; the left column appears as a single unified panel. So user can get confused and search in the menus how the search panel can be hidden. 
Strangely sometimes the demarcation can just be seen, that is when the window has been still (not used) for more then a minute.
How much of this is due to a person's eye sight or quality of monitors, God knows.

Just a thought, a thin grey line as those on the right of this page at the edge of the divider can help people having problem seeing it. 
Also an option to hide  searches and tags view  in the view menu can help, currently version 2.7.6 for Linux does not have this option.

**Comment by droidmonkey** [comment]
Update to 2.7.11
