### ISSUE TITLE
Interrupt timeout/clear the clipboard manually (cli)

### ISSUE THREAD

**Issue by malwikt** [keepassxreboot/keepassxc#9864]
Is there an option to interrupt the timeout when using clip in cli?

When i use clip I need to wait 10 seconds until I can do anything else in cli. I often first copy username (nick, email) then password. I know that I can change how long the timeout is, but there will always be a few seconds that I will need to wait out before clipping another attribute, so it would be cool to have an option to interrupt that timer.

**Comment by droidmonkey** [comment]
No, because then we can't actually clear the clipboard. Since you are just going from username to password, you can just issue an interrupt (Ctrl+C) then do the password clip command. Let the password one cleanup the clipboard.

**Comment by malwikt** [comment]
When I'm clipping multiple values I first open the database with "keepassxc-cli open" so that I only need to type my password once. Ctrl+C exits the interactive environment instead of interrupting the "notification" saying "Clearing the clipboard in x seconds". I can clip with "keepassxc-cli clip", but it requires me to type password everytime. 
Maybe instead of blocking user input with that notification, the message could be printed only once so the user wouldn't need to wait?

**Comment by droidmonkey** [comment]
*clip* [_options_] <__database__> <__entry__> [_timeout_]:: 
   Copies an attribute or the current TOTP (if the *-t* option is specified) of a database entry to the clipboard. 
   If no attribute name is specified using the *-a* option, the password is copied. 
   If multiple entries with the same name exist in different groups, only the attribute for the first one is copied. 
   For copying the attribute of an entry in a specific group, the group path to the entry should be specified as well, instead of just the name. 
   **Optionally, a timeout in seconds can be specified to automatically clear the clipboard, the default timeout is 10 seconds, set to 0 to disable.**

**Comment by malwikt** [comment]
In gui I can copy next attribute without waiting for the timeout duration or disabling it and not clearing the clipboard. In cli the problem is the notification that stays there for the whole duration of a timeout and just refreshes itself every second to tell how much time is left. During that time user can't type another command. In my opinion it's not very helpful and printing that message only once and letting the user use the cli would be better.
