### ISSUE TITLE
Differ between url and entry title for autotype

### ISSUE THREAD

**Issue by jonazc** [keepassxreboot/keepassxc#990]
## Expected Behavior
***Two checkboxes in settings/autotype***

```
Use to match Window for global Auto Type
[ ] Entry Title
[x] Entry URL
```

*It could be even possible to have the possibility of choosing this for each entry, but that might also be to much overkill*

## Current Behavior
There is only one checkbox 
`[x] use entry title and url to match windows for global auto type`

**Comment by TheZ3ro** [comment]
This is already implemented in `develop` branch and will be available in the next 2.2.1 version (releasing soon)

**Comment by quinncomendant** [comment]
Just to clarify this feature: in order to use the *"Use entry URL to match windows for global Auto-Type"* feature, it is required that the URL appears in the *title* of the browser window. Is that correct? 

That would be necessary because the OS only makes the *window title* available, not browser window's *URL location*. So for this (*"Use entry URL…"*) to be useful, we need to install an extension like [Url in title](https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb?hl=en) so the URL can be matched.

If I'm wrong, please can someone explain how to match *Entry URL* to browser window without using an extension?

**Comment by TheZ3ro** [comment]
You are right

**Comment by quinncomendant** [comment]
Feel free to copy-paste what I wrote into the docs/FAQ (with minor editing), if you think it explains the usage well.

**Comment by mrchief** [comment]
On version 2.3.4, it seems only Window title matching works. If I choose just URL, it gives me an error saying no matching title entries. Is this expected?
