### ISSUE TITLE
App crashes on load - Debian 12 - Flatpak

### ISSUE THREAD

**Issue by Gituser-3434** [keepassxreboot/keepassxc#9901]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I am using Debian 12 currently- which I just switched from Ubuntu a couple weeks ago; I am using the Gnome desktop environment. I installed keepassxc a few days after I got Debian running. It was working for the first few days. Suddenly now every time I open it, it crashes. It opens up, and then I notice a loading symbol come up a few seconds after, up on the activities bar. After maybe <3 seconds of this, it crashes a few seconds after.

It is only this program, and I also dont see any upticks in RAM usage, CPU usage, or anything of the sort. Also, I dont have a syslog in the /var/log/ directory, so I don't know what is going on. I assume it is a bug. Everything is up to date.

I installed Keepassxc with flatpak, and I tried purging it and reinstalling it again. Still have the same issue. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open the program

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The program runs and I can get access to my passwords.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The program crashes after a handful of seconds of running. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: GNU/Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Unfortunately this isn't enough information to do anything with. Try using our appimage to see if this is a flatpak problem.

**Comment by Gituser-3434** [comment]
> Unfortunately this isn't enough information to do anything with. Try using our appimage to see if this is a flatpak problem.

I believe the issue has been resolved.

I installed the appimage, using this guide, https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md- all the way up to the testing stage. Then, I uninstalled the flatpak version, after I followed the guide. I probably should have uninstalled the flatpak first, but I forget. Nonetheless, it works. So it does, indeed, seem to be the case that this was a flatpak problem. 

Now, when I start the program, the icon still has a loading symbol next to it on the activities bar a second after I see the GUI start, but the loading symbol eventually disappears and it doesn't seem like it will crash now. I had enough time to get what I needed now.

**Comment by droidmonkey** [comment]
FWIW, we have not received any other reports of flatpak version crashing

**Comment by Abdull** [comment]
I had the exact same issues with KeepassXC (i.e., unannounced, unceremonious, silent process exit), including with the latest release 2.7.7, when using the [flatpak version from flathub](https://flathub.org/apps/org.keepassxc.KeePassXC) (`org.keepassxc.KeePassXC`) under Debian 12 with GNOME Desktop Environment.

It is highly likely that this issue comes from flatpak's *Background Monitor* closing KeepassXC once the monitor notices that the application runs in background, **under the conddition** the app has been user-configured to not be allowed to run in the background. **Most users (like me) are not aware that they have (incorrectly) configured their disappearing flatpak application to be denied to run in background: There will be some cryptic GNOME popup appearing eventually when KeepassXC runs for the first time**:

![image](https://github.com/keepassxreboot/keepassxc/assets/529862/e18a1762-8af4-47e2-afc1-b0eb0d9dbb8e)

![image](https://github.com/keepassxreboot/keepassxc/assets/529862/6daf6fcf-d5d9-464a-8e6a-fb3f2256fb7d)

![image](https://github.com/keepassxreboot/keepassxc/assets/529862/d635e95c-02e7-4374-a06c-f4f1098c9c98)

Some password manager running "secretly" in the background may incorrectly sound suspicious, so clicking on "Force quit" sounds reasonable. But doing so will (additionally and unintentionally) permanently configure flatpak-KeePassXC's *flatpak configuration* in a way that flatpak-KeePassXC is denied to run in the background:

To see flatpak-KeePassXC's current background settings per command line:
```
$ flatpak permission-show org.keepassxc.KeePassXC
Table      Object     App                     Permissions Data
background background org.keepassxc.KeePassXC no          0x00
```

see settings per *flatseal* GUI:
![image](https://github.com/keepassxreboot/keepassxc/assets/529862/803199ba-6ce3-4f62-9bc5-8b0bc593b81a)

With `background` having `no` permission, once the flatpak runtime (?) notices KeePassXC runs in the background, the next "Background Monitor" watchdog trigger moment (triggered periodically every 10 seconds IMHO), will SIGTERM KeePassXC. Or so I guess.

## Workaround
Explicitly allow flatpak-KeePassXC to run in background:

```
flatpak permission-set background background org.keepassxc.KeePassXC yes
```

E.g. using *flatseal*:
![image](https://github.com/keepassxreboot/keepassxc/assets/529862/791133e2-dd2d-4475-9811-d1b89d9dffc3)

Starting flatpak-KeePassXC from then onwards should no longer force-exit the application 10 seconds after application startup.

## Root cause solution
I guess by now flatpak applications can be publisher-configured to be allowed to run in the background out-of-the-box.

@droidmonkey , maybe it is worth having a look how to make the flatpak-KeePassXC release to be released with background permissions.

There is a ridiculous amount of other flatpak applications whose users are wondering about their application suddenly exiting out of nowhere. Maybe some found a proper solution and are good inspirations for how to allow background activity:

* https://github.com/flathub/org.signal.Signal/issues/177
* https://github.com/flatpak/flatpak/issues/5222
* https://github.com/goatcorp/XIVLauncher.Core/issues/43
* https://github.com/flathub/com.valvesoftware.Steam/issues/1040#issuecomment-1517036452
* https://www.reddit.com/r/flatpak/comments/15tzx0w/flatpak_apps_close_a_few_seconds_after_opening/
* https://bugs.kde.org/show_bug.cgi?id=473881
* https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.16.0
* https://github.com/flatpak/flatpak/issues/5427

**Comment by droidmonkey** [comment]
> maybe it is worth having a look how to make the flatpak-KeePassXC release to be released with background permissions.

We don't need to release with these permissions, they are (supposed to be) granted automatically. The end user (as you mentioned) are actually unwittingly _revoking_ the permission. There is nothing we can do about that besides complain to GNOME for some terrible UI/UX.
