### ISSUE TITLE
Auto open URL and type login

### ISSUE THREAD

**Issue by jonazc** [keepassxreboot/keepassxc#991]
## Expected Behavior
Within keepassxc, one selects an entry and presses specific keyboard shortcut. Then URL of the entry is opened in webbrowser and and credentials are autotyped and logged in.

## Current Behavior
One needs to open the specific login page in webbrowser, use the global autotype shortcut and has to choose the specific entry

**Comment by adatum** [comment]
One problem is that websites vary in where they place the focus/cursor.

When I first set up Keepass/KeepassXC, I was trying to (inelegantly) specify the right number of {TAB}s before the username and passwords are entered for each site, so that AutoType would log in without needing me to click first in the username field on the web page. In the end I decided it would be simpler and more robust for me to do that one click before hitting AutoType. Perhaps eventually password managers will become smarter and automatically detect username/password fields.

**Comment by jonazc** [comment]
> One problem is that websites vary in where they place the focus/cursor.

but thats no problem since it's possible to make custom procedures like for example put a `{tab}` before entering the username, isn't it?

**Comment by droidmonkey** [comment]
This is far more complicated then you are giving it credit. Every website has a unique focus and tab order. The proper and least flaky way to solve this already exists.

1. Select entry and press CTRL+U
2. Select username field in opened website
3. Press global hotkey for autotype

**Comment by jonazc** [comment]
> Every website has a unique focus and tab order.

yes, but again: I can already solve this problem by using a custom auto type sequence
So why not just opening page and autotyping in one step if the user set it up correctly for this page?

**Comment by droidmonkey** [comment]
It's just not that simple. How does KeePassXC know when to start autotyping? The webpage needs to launch, load, and all javascript whatevers settled out (field focused, etc). There is no indication from the browser when that happens. What if the site chanhed their layout, now you're autotyping into the search field your password. 

I just do not agree with this amount of automation when too much can "go wrong". This would be a good ise case for generic chained actions though, then you can setup this sequence of events yourself.

**Comment by TheZ3ro** [comment]
I agree with @droidmonkey and also we are working on our custom browser plugin that can achieve this easily

**Comment by jonazc** [comment]
That are detailed reasons I can accept and agree to
