### ISSUE TITLE
Consider using keepasshttp-connector plugin for FireFox instead of PassIFox

### ISSUE THREAD

**Issue by ydf** [keepassxreboot/keepassxc#998]
at https://github.com/keepassxreboot/keepassxc/blob/develop/README.md

KeePassHTTP support for use with PassIFox in Mozilla Firefox, chromeIPass in Google Chrome or Chromium and passafari in Safari.
its better for firefox user.
[github](https://github.com/smorks/keepasshttp-connector)
[releases](https://github.com/smorks/keepasshttp-connector/releases)

**Comment by droidmonkey** [comment]
I don't understand what you are asking for

**Comment by sts10** [comment]
I'm guessing ydf is suggesting that the KeePassXC README recommend that Firefox users use [keepasshttp-connector](https://github.com/smorks/keepasshttp-connector) rather than (or in addition to) PassIFox. 

From the current KeePassXC [README](https://github.com/keepassxreboot/keepassxc/blob/develop/README.md): 

> KeePassHTTP support for use with PassIFox in Mozilla Firefox, chromeIPass in Google Chrome or Chromium and passafari in Safari.

I don't know much about keepasshttp-connector so I can't say whether this a good idea. I'm just attempting to clarify the issue/ request.

**Comment by TheZ3ro** [comment]
I think he mean to replace PassIFox/ChromeIPass in our website in favor of the new maintained fork [KeePassHTTP Connector](https://github.com/smorks/keepasshttp-connector).

This can be a good idea since the first aren't maintained actively anymore, but the latter isn't available in any store (Firefox/Chrome) so I don't feel to make any changes to the website

And note that we are working on our custom plugin KeePassXC-browser

**Comment by varjolintu** [comment]
The plugin is now available at [AMO](https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/) and [Chrome Web Store](https://chrome.google.com/webstore/detail/keepasshttp-connector/dafgdjggglmmknipkhngniifhplpcldb).

**Comment by TheZ3ro** [comment]
Do we plan to keep HTTP support? @droidmonkey

**Comment by droidmonkey** [comment]
Yes there should be a deprecation period before we shut it down completely.

**Comment by TheZ3ro** [comment]
This is fixed in the website now https://keepassxc.org/project

**Comment by TheZ3ro** [comment]
Fixed also in the readme

**Comment by TheZ3ro** [comment]
Currently KeePassHTTP-Connector is offline from Mozilla addon store. https://github.com/smorks/keepasshttp-connector/issues/34

Consider using [Keywi](https://github.com/LEDfan/keywi/)

**Comment by tl-pierre** [comment]
KeePassHTTP-Connector is back on AMO : https://addons.mozilla.org/fr/firefox/addon/keepasshttp-connector/

**Comment by TheZ3ro** [comment]
Nice!
